import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const allowedRoles=new Set(["super_admin","sales_team_manager","sales_marketing_admin","advertising_admin"]);
const allowedProfileHosts=new Set(["tiktok.com","linkedin.com","fiverr.com","upwork.com","youtube.com","youtu.be","instagram.com","facebook.com","x.com","twitter.com","github.com"]);
type SearchResult={title:string;link:string;snippet:string;source:string;query:string};

const platformFor=(raw:string)=>{try{const h=new URL(raw).hostname.toLowerCase().replace(/^www\./,"");if(h.includes("tiktok.com"))return"TikTok";if(h.includes("linkedin.com"))return"LinkedIn";if(h.includes("fiverr.com"))return"Fiverr";if(h.includes("upwork.com"))return"Upwork";if(h.includes("instagram.com"))return"Instagram";if(h.includes("youtube.com")||h==="youtu.be")return"YouTube";if(h.includes("facebook.com"))return"Facebook";if(h==="x.com"||h.includes("twitter.com"))return"X";if(h.includes("github.com"))return"GitHub";return"Other"}catch{return"Other"}};
const validSubmittedProfileUrl=(value:string)=>{try{const u=new URL(value);if(u.protocol!=="https:")return false;const h=u.hostname.toLowerCase().replace(/^www\./,"");return[...allowedProfileHosts].some(x=>h===x||h.endsWith(`.${x}`))}catch{return false}};
const validPublicResultUrl=(value:string)=>{try{const u=new URL(value);return/^https?:$/.test(u.protocol)&&!!u.hostname}catch{return false}};
const quote=(v:string)=>`"${v.replace(/["\n\r]/g," ").slice(0,160)}"`;

async function serperSearch(q:string){const key=Deno.env.get("SERPER_API_KEY");if(!key)return{results:[] as SearchResult[],error:{code:"SERPER_KEY_MISSING",message:"Web research is not configured."}};try{const r=await fetch("https://google.serper.dev/search",{method:"POST",headers:{"X-API-KEY":key,"Content-Type":"application/json"},body:JSON.stringify({q,num:10})});const text=await r.text();let p:any=null;try{p=JSON.parse(text)}catch{}if(r.status===429)return{results:[] as SearchResult[],error:{code:"SERPER_RATE_LIMIT",message:"Web search provider rate limit reached."}};if(!r.ok){console.error("[marketer-profile-deep-research] Serper HTTP failure",r.status);return{results:[] as SearchResult[],error:{code:"SERPER_API_ERROR",message:"Web search could not be completed."}}}const results=Array.isArray(p?.organic)?p.organic.map((x:any)=>({title:String(x.title||"").slice(0,220),link:String(x.link||""),snippet:String(x.snippet||"").slice(0,500),source:"Serper/Google",query:q})).filter((x:SearchResult)=>validPublicResultUrl(x.link)):[];return{results}}catch(e){console.error("[marketer-profile-deep-research] Serper exception",e instanceof Error?e.message:String(e));return{results:[] as SearchResult[],error:{code:"SERPER_API_ERROR",message:"Web search could not be completed."}}}}

function buildQueries(profileUrl:string,platform:string,applicant:{username?:string|null;full_name?:string|null;profession?:string|null}){const u=new URL(profileUrl);const host=u.hostname.toLowerCase().replace(/^www\./,"");const handle=u.pathname.split("/").filter(Boolean).pop()?.replace(/^@/,"")||applicant.username||"";const name=String(applicant.full_name||"").trim();const profession=String(applicant.profession||"").trim();if(platform==="TikTok"&&handle){return[quote(profileUrl),`site:tiktok.com/@${handle}`,`${quote(handle)} TikTok`,`${quote(handle)} ${name?quote(name):""} TikTok`.trim(),`${quote(handle)} social media`,quote(handle)]}const site=host==="youtu.be"?"youtube.com":host;return[quote(profileUrl),`site:${site}/${handle}`,`site:${site} ${quote(handle)}`,`${quote(handle)} ${quote(platform)}`,name?`${quote(handle)} ${quote(name)} ${quote(platform)}`:`${quote(handle)} social media`,quote(handle)]}

function safeParse(content:string){const clean=String(content||"").replace(/^\s*```(?:json)?\s*/i,"").replace(/\s*```\s*$/i,"").trim();try{return JSON.parse(clean)}catch{const start=clean.indexOf("{");const end=clean.lastIndexOf("}");if(start>=0&&end>start){try{return JSON.parse(clean.slice(start,end+1))}catch{}}return null}}
const score=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)&&v>=0&&v<=100?Math.round(v):null;
const allowed=(v:unknown,list:string[],fallback:string)=>list.includes(String(v))?String(v):fallback;
const arr=(v:unknown)=>Array.isArray(v)?v.map(x=>typeof x==="string"?x:JSON.stringify(x)).filter(Boolean).slice(0,30):[];
const classified=(v:unknown)=>Array.isArray(v)?v.map(x=>{if(typeof x==="object"&&x){const c=String((x as any).classification||"UNKNOWN");return{classification:["VERIFIED FACT","OBSERVED PUBLIC DATA","CALCULATED","ESTIMATE","UNKNOWN"].includes(c)?c:"UNKNOWN",detail:String((x as any).detail||"")}}return{classification:"UNKNOWN",detail:String(x)}}).filter(x=>x.detail).slice(0,30):[];

function normalizeReport(raw:any,evidence:any){const ph=score(raw?.profile_health?.score);const aa=score(raw?.audience_authenticity?.score);const br=score(raw?.bot_risk?.score);const ic=score(raw?.identity_consistency?.score);const ac=score(raw?.audience_authenticity?.confidence);const bc=score(raw?.bot_risk?.confidence);return{summary:String(raw?.summary||"").slice(0,2000)||"Insufficient evidence for a reliable summary.",profile_health:{score:ph,status:ph===null?"unknown":allowed(raw?.profile_health?.status,["excellent","good","fair","poor","unknown"],"unknown")},audience_authenticity:{score:aa,status:aa===null?"unknown":allowed(raw?.audience_authenticity?.status,["high","medium","low","unknown"],"unknown"),confidence:aa===null?null:ac},bot_risk:{score:br,status:br===null?"unknown":allowed(raw?.bot_risk?.status,["low","medium","high","unknown"],"unknown"),confidence:br===null?null:bc},identity_consistency:{status:allowed(raw?.identity_consistency?.status,["consistent","mixed","unclear"],"unclear"),score:ic,evidence:arr(raw?.identity_consistency?.evidence)},activity:{status:allowed(raw?.activity?.status,["active","inactive","unknown"],"unknown"),evidence:arr(raw?.activity?.evidence)},platform_consistency:{status:allowed(raw?.platform_consistency?.status,["consistent","mixed","unclear"],"unclear"),evidence:arr(raw?.platform_consistency?.evidence)},positive_signals:arr(raw?.positive_signals),risk_signals:arr(raw?.risk_signals),verified_facts:classified(raw?.verified_facts),observed_data:classified(raw?.observed_data),calculated_metrics:classified(raw?.calculated_metrics),unknowns:arr(raw?.unknowns),limitations:arr(raw?.limitations),sources:Array.isArray(raw?.sources)?raw.sources.slice(0,20):evidence.search_results.slice(0,12).map((x:SearchResult)=>({title:x.title,link:x.link,source:x.source,query:x.query})),recommendation:allowed(raw?.recommendation,["approve","request_additional_verification","manual_review","reject"],"manual_review"),recommendation_reason:String(raw?.recommendation_reason||"Insufficient evidence for an automatic determination.").slice(0,1500),_evidence_meta:{search_result_count:evidence.search_results.length,search_queries:evidence.search_queries,source_domains:[...new Set(evidence.search_results.map((x:SearchResult)=>{try{return new URL(x.link).hostname.replace(/^www\./,"")}catch{return"unknown"}}))].slice(0,20)}}}

Deno.serve(async req=>{if(req.method==="OPTIONS")return json(null);if(req.method!=="POST")return json({success:false,error:{code:"METHOD_NOT_ALLOWED",message:"Method not allowed."}},405);try{const authorization=req.headers.get("Authorization");if(!authorization?.startsWith("Bearer "))return json({success:false,error:{code:"UNAUTHORIZED",message:"Unauthorized."}},401);const client=db();const{data:{user},error:authError}=await client.auth.getUser(authorization.slice(7));if(authError||!user)return json({success:false,error:{code:"UNAUTHORIZED",message:"Unauthorized."}},401);const{data:admin,error:adminError}=await client.from("users").select("id,is_admin,admin_status,admin_role").eq("id",user.id).single();if(adminError||!admin?.is_admin||String(admin.admin_status||"").toLowerCase()!=="active"||!allowedRoles.has(String(admin.admin_role||"")))return json({success:false,error:{code:"FORBIDDEN",message:"Sales Team administration permission required."}},403);
const body=await req.json().catch(()=>({}));const applicantId=String(body?.applicant_id||"").trim();const requestedUrl=body?.profile_url?String(body.profile_url).trim():null;if(!/^[0-9a-f-]{36}$/i.test(applicantId))return json({success:false,error:{code:"INVALID_APPLICANT_ID",message:"A valid applicant ID is required."}},400);
const{data:applicant,error:applicantError}=await client.from("users").select("id,email,full_name,username,profession,social_media_links,marketer_social_analysis,marketer_deep_research").eq("id",applicantId).single();if(applicantError||!applicant)return json({success:false,error:{code:"APPLICANT_NOT_FOUND",message:"Applicant not found."}},404);
const submitted=Array.isArray(applicant.social_media_links)?applicant.social_media_links.map((v:unknown)=>String(v).trim()).filter(validSubmittedProfileUrl):[];const targets=[...new Set(requestedUrl?[requestedUrl]:submitted)];if(!targets.length)return json({success:false,error:{code:"MISSING_PROFILE_URL",message:"No valid submitted profile links were found."}},400);if(requestedUrl&&!submitted.includes(requestedUrl))return json({success:false,error:{code:"PROFILE_NOT_SUBMITTED",message:"The requested profile URL is not one of the applicant's submitted profiles."}},400);
const existing=Array.isArray(applicant.marketer_social_analysis)?applicant.marketer_social_analysis:[];const previous=Array.isArray(applicant.marketer_deep_research)?applicant.marketer_deep_research:[];const reports:any[]=[];const errors:any[]=[];
for(const profileUrl of targets.slice(0,10)){const platform=platformFor(profileUrl);const basic=existing.find((x:any)=>x?.profile_url===profileUrl)||{};const queries=buildQueries(profileUrl,platform,applicant);const all:SearchResult[]=[];let searchError:any;
for(const q of queries){const result=await serperSearch(q);if(result.error){searchError=result.error;if(result.error.code==="SERPER_KEY_MISSING"||result.error.code==="SERPER_RATE_LIMIT")break;continue}all.push(...result.results)}
const seen=new Set<string>();const normalized=all.filter(x=>{const key=x.link.replace(/[?#].*$/," ").replace(/\/$/,"").trim().toLowerCase();if(!key||seen.has(key))return false;seen.add(key);return true}).slice(0,12);
if(searchError)errors.push({profile_url:profileUrl,stage:"search",error:searchError});
const evidence={submitted_profile:{url:profileUrl,platform,status:"submitted by applicant"},existing_profile_analysis:{profile_title:basic.profile_title??null,profile_description:basic.profile_description??null,followers:basic.followers??null,following:basic.following??null,likes:basic.likes??null,content_count:basic.content_count??null,verified_indicator:basic.verified_indicator??null,authenticity_score:basic.authenticity_score??null,risk_level:basic.risk_level??"UNKNOWN",confidence_score:basic.confidence_score??null,signals:Array.isArray(basic.signals)?basic.signals.slice(0,15):[]},search_results:normalized,search_queries:queries,search_provider:"Serper/Google",search_error:searchError?.code||null};
const prompt=`You are DRIGHT's marketer application Deep Research analyst. Analyze ONLY the supplied evidence. Do not invent follower counts, following counts, likes, content counts, account age, engagement, identity information, verification status, or other metrics. Missing information MUST be UNKNOWN or null. Do not assume search results belong to the applicant merely because a username is similar. Do not state an account is definitely fake, definitely genuine, or definitely a bot. Provide an evidence-based risk assessment.

Classifications: VERIFIED FACT=directly supported by a reliable source. OBSERVED PUBLIC DATA=visible in a public search result/page but not independently verified. CALCULATED=mathematically derived only from supplied values. ESTIMATE=assessment based on evidence, never a fact. UNKNOWN=cannot safely be established.

Source quality priority: official platform profile/API, authoritative external source, multiple independent matching sources, search-result metadata, single unverified third-party page.

Profile health is distinct from audience authenticity. If usable audience metrics are absent, audience_authenticity.score MUST be null and status unknown. Bot risk must be evidence-based and must not rely on follower count alone. Confidence must reflect source quality, direct profile match, consistency, and measurable evidence; do not manufacture a percentage.

Return ONLY valid JSON in this exact structure:
{"summary":"","profile_health":{"score":null,"status":"unknown"},"audience_authenticity":{"score":null,"status":"unknown","confidence":null},"bot_risk":{"score":null,"status":"unknown","confidence":null},"identity_consistency":{"status":"unclear","score":null,"evidence":[]},"activity":{"status":"unknown","evidence":[]},"platform_consistency":{"status":"unclear","evidence":[]},"positive_signals":[],"risk_signals":[],"verified_facts":[],"observed_data":[],"calculated_metrics":[],"unknowns":[],"limitations":[],"sources":[],"recommendation":"manual_review","recommendation_reason":""}

Numeric scores are 0-100 ONLY when supported by supplied evidence; otherwise null. Confidence is 0-100 ONLY when there is enough evidence to justify it; otherwise null. Never convert null/UNKNOWN to zero.

Applicant public context: ${JSON.stringify({full_name:applicant.full_name,username:applicant.username,profession:applicant.profession})}
Supplied evidence: ${JSON.stringify(evidence)}`;
const boundedPrompt=prompt.slice(0,7600);
let status="completed";let research:any;let provider="ai-proxy";let model:string|null=null;
try{const aiUrl=`${Deno.env.get("SUPABASE_URL")}/functions/v1/ai-proxy`;const aiResponse=await fetch(aiUrl,{method:"POST",headers:{"Content-Type":"application/json","Authorization":authorization,"apikey":Deno.env.get("SUPABASE_ANON_KEY")||""},body:JSON.stringify({feature:"generate-text",prompt:boundedPrompt})});const text=await aiResponse.text();let payload:any=null;try{payload=JSON.parse(text)}catch{}if(!aiResponse.ok||!payload?.success){console.error("[marketer-profile-deep-research] AI proxy failure",aiResponse.status,payload?.error||"unknown");throw Object.assign(new Error("AI service failed"),{code:aiResponse.status===429?"AI_RATE_LIMIT":"AI_ERROR"})}provider=String(payload.provider||"ai-proxy");model=payload.model?String(payload.model):null;const parsed=safeParse(String(payload.content||""));if(!parsed)throw Object.assign(new Error("AI returned invalid research JSON"),{code:"AI_INVALID_JSON"});research=normalizeReport(parsed,evidence)}catch(e){status="failed";const code=(e as any)?.code||"AI_ERROR";const message=code==="AI_INVALID_JSON"?"DRIGHT AI returned an invalid research response.":code==="AI_RATE_LIMIT"?"DRIGHT AI is rate limited. Please retry.":"DRIGHT AI analysis failed.";errors.push({profile_url:profileUrl,stage:"ai",error:{code,message}});research=normalizeReport({summary:"Deep Research did not complete because the AI analysis failed.",profile_health:{score:null,status:"unknown"},audience_authenticity:{score:null,status:"unknown",confidence:null},bot_risk:{score:null,status:"unknown",confidence:null},identity_consistency:{status:"unclear",score:null,evidence:[]},activity:{status:"unknown",evidence:[]},platform_consistency:{status:"unclear",evidence:[]},positive_signals:[],risk_signals:[],verified_facts:[],observed_data:[],calculated_metrics:[],unknowns:[message],limitations:["Automated AI analysis did not complete."],sources:[],recommendation:"manual_review",recommendation_reason:"Manual review is required because the AI analysis did not complete."},evidence)}
const report={profile_url:profileUrl,platform,status,provider,model,research,search_evidence:normalized,search_queries:queries,requested_at:new Date().toISOString()};reports.push(report);
const{error:saveError}=await client.from("marketer_profile_deep_research").insert({applicant_id:applicantId,profile_url:profileUrl,platform,status,research:report,requested_by:user.id});if(saveError){console.error("[marketer-profile-deep-research] database save failure",saveError.message);errors.push({profile_url:profileUrl,stage:"database",error:{code:"DATABASE_SAVE_ERROR",message:"Research report could not be saved."}})}}
const merged=[...reports,...previous].slice(0,50);const{error:historyError}=await client.from("users").update({marketer_deep_research:merged,updated_at:new Date().toISOString()}).eq("id",applicantId);if(historyError){console.error("[marketer-profile-deep-research] history save failure",historyError.message);errors.push({stage:"database_history",error:{code:"DATABASE_SAVE_ERROR",message:"Research history could not be updated."}})}
const completed=reports.some(r=>r.status==="completed");return json({success:completed,reports,errors:errors.length?errors:undefined},completed?200:502);
}catch(e){console.error("[marketer-profile-deep-research] unhandled failure",e instanceof Error?e.message:String(e));return json({success:false,error:{code:"DEEP_RESEARCH_ERROR",message:"Deep Research could not be completed."}},500)}});
