import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const SECRETS={groq:Deno.env.get("GROQ_API_KEY")||"",gemini:Deno.env.get("GEMINI_API_KEY")||"",openai:Deno.env.get("OPENAI_API_KEY")||""};
const ADMIN_ROLES=["super_admin","ai_admin","system_admin","marketplace_admin","moderator"];
const supabase=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");
async function isAdmin(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return false;try{const{data:{user}}=await supabase.auth.getUser(h.slice(7));if(!user)return false;const{data:p}=await supabase.from("users").select("is_admin,admin_status,role").eq("id",user.id).maybeSingle();if(!p)return false;return p.is_admin===true&&String(p.admin_status).toLowerCase()==="active"||ADMIN_ROLES.includes(String(p.role||""))}catch{return false}}
interface ProviderMetrics{requests:number;tokens:number;avgLatencyMs:number;errors:number;fallbackUsed:number;estimatedCost:number}
async function getProviderMetrics(provider:string,days:number):Promise<ProviderMetrics>{const since=new Date(Date.now()-days*86400000).toISOString();const{data}=await supabase.from("ai_usage").select("tokens,latency_ms,success,estimated_cost").eq("provider",provider).gte("created_at",since);const rows=(data||[]) as any[];const total=rows.length;const errors=rows.filter(r=>r.success===false).length;const tokens=rows.reduce((s,r)=>s+(r.tokens||0),0);const latency=rows.reduce((s,r)=>s+(r.latency_ms||0),0);const cost=rows.reduce((s,r)=>s+Number(r.estimated_cost||0),0);return{requests:total,tokens,avgLatencyMs:total?Math.round(latency/total):0,errors,fallbackUsed:0,estimatedCost:cost}}
async function getGlobalMetrics(days:number){const since=new Date(Date.now()-days*86400000).toISOString();const{data}=await supabase.from("ai_usage").select("tokens,latency_ms,success,estimated_cost,provider,feature,created_at").gte("created_at",since);const rows=(data||[]) as any[];const total=rows.length;const errors=rows.filter(r=>r.success===false).length;const tokens=rows.reduce((s,r)=>s+(r.tokens||0),0);const latency=rows.reduce((s,r)=>s+(r.latency_ms||0),0);const cost=rows.reduce((s,r)=>s+Number(r.estimated_cost||0),0);const dailyMap=new Map<string,number>();for(const r of rows){const day=new Date(r.created_at).toISOString().slice(0,10);dailyMap.set(day,(dailyMap.get(day)||0)+1)}const dailyRequests=Array.from(dailyMap.entries()).sort((a,b)=>a[0].localeCompare(b[0])).slice(-30).map(([date,count])=>({date,count}));const featureMap=new Map<string,{requests:number;tokens:number}>();for(const r of rows){const f=r.feature||"unknown";const x=featureMap.get(f)||{requests:0,tokens:0};x.requests++;x.tokens+=r.tokens||0;featureMap.set(f,x)}const byFeature=Array.from(featureMap.entries()).map(([feature,stats])=>({feature,...stats})).sort((a,b)=>b.requests-a.requests);const users=new Set<string>();for(const r of rows)if(r.provider&&r.success!==false)users.add(r.provider);return{totalRequests:total,totalTokens:tokens,avgLatencyMs:total?Math.round(latency/total):0,errorRate:total?(errors/total)*100:0,estimatedCost:cost,dailyRequests,byFeature,activeUsers:users.size,errorCount:errors}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});if(req.method!=="GET")return new Response(JSON.stringify({success:false,error:"Method not allowed"}),{status:405,headers:{...corsHeaders,"Content-Type":"application/json"}});if(!(await isAdmin(req)))return new Response(JSON.stringify({success:false,error:"Unauthorized — admin access required"}),{status:403,headers:{...corsHeaders,"Content-Type":"application/json"}});const daysParam=new URL(req.url).searchParams.get("days");const days=daysParam?Math.min(90,Math.max(1,parseInt(daysParam,10)||7)):7;try{const[g,g2,o,global]=await Promise.all([getProviderMetrics("groq",days),getProviderMetrics("gemini",days),getProviderMetrics("openai",days),getGlobalMetrics(days)]);const providers={groq:{provider:"Groq",configured:!!SECRETS.groq,model:"llama-3.3-70b-versatile",fallbackModel:"llama-3.1-8b-instant",...g,...(g.errors>0&&{errorRate:(g.errors/g.requests)*100})},gemini:{provider:"Google Gemini",configured:!!SECRETS.gemini,model:"gemini-2.5-flash-lite",...g2,...(g2.errors>0&&{errorRate:(g2.errors/g2.requests)*100})},openai:{provider:"OpenAI",configured:!!SECRETS.openai,model:"gpt-4o-mini",...o,...(o.errors>0&&{errorRate:(o.errors/o.requests)*100})}};return new Response(JSON.stringify({success:Object.values(SECRETS).some(Boolean),primary:"groq",fallbackChain:["groq","gemini","openai"],anyAvailable:Object.values(SECRETS).some(Boolean),any_available:Object.values(SECRETS).some(Boolean),providers,metrics:global,period:`${days} days`}),{status:200,headers:{...corsHeaders,"Content-Type":"application/json"}})}catch(e){console.error("[ai-health] error");return new Response(JSON.stringify({success:false,error:"Failed to retrieve AI health metrics"}),{status:500,headers:{...corsHeaders,"Content-Type":"application/json"}})}});
