import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.110.0";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const supabase=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");
const KEYS={groq:Deno.env.get("GROQ_API_KEY")||"",gemini:Deno.env.get("GEMINI_API_KEY")||"",openai:Deno.env.get("OPENAI_API_KEY")||""};
const MODELS={groq:"llama-3.3-70b-versatile",gemini:"gemini-2.5-flash-lite",openai:"gpt-4o-mini"};
const ROLES=new Set(["super_admin","ai_admin","system_admin","marketplace_admin","moderator","sales_team_manager","sales_marketing_admin","advertising_admin"]);
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
async function admin(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const{data:{user}}=await supabase.auth.getUser(h.slice(7));if(!user)return null;const{data:p}=await supabase.from("users").select("id,is_admin,admin_status,role,admin_role").eq("id",user.id).maybeSingle();return p?.is_admin===true&&String(p.admin_status).toLowerCase()==="active"&&ROLES.has(String(p.admin_role||p.role||""))?user:null}
const reason=(s:unknown)=>String(s||"UNKNOWN").slice(0,300);
async function state(provider:string,days:number){const since=new Date(Date.now()-days*86400000).toISOString();const{data:rows}=await supabase.from("ai_usage").select("success,error_message,model,latency_ms,tokens,created_at,fallback_used").eq("provider",provider).gte("created_at",since).order("created_at",{ascending:false}).limit(200);const all=(rows||[]) as any[];const success=all.find(x=>x.success===true);const fail=all.find(x=>x.success===false);const req=all.length,errors=all.filter(x=>x.success===false).length;const avg=req?Math.round(all.reduce((n,x)=>n+Number(x.latency_ms||0),0)/req):0;return{requests:req,errors,errorRate:req?Number(((errors/req)*100).toFixed(2)):0,avgLatencyMs:avg,lastSuccessfulRequest:success?.created_at||null,lastFailedRequest:fail?.created_at||null,lastFailureReason:fail?reason(fail.error_message):null,lastSuccessfulModel:success?.model||null,connectionStatus:!KEYS[provider as keyof typeof KEYS]?"NOT_CONFIGURED":success&&(!fail||new Date(success.created_at)>=new Date(fail.created_at))?"HEALTHY":fail?"FAILING":"UNKNOWN"}}
async function globalMetrics(days:number){const since=new Date(Date.now()-days*86400000).toISOString();const{data}=await supabase.from("ai_usage").select("tokens,latency_ms,success,estimated_cost,provider,feature,created_at").gte("created_at",since);const rows=(data||[]) as any[];return{totalRequests:rows.length,totalTokens:rows.reduce((s,x)=>s+Number(x.tokens||0),0),errorCount:rows.filter(x=>x.success===false).length,avgLatencyMs:rows.length?Math.round(rows.reduce((s,x)=>s+Number(x.latency_ms||0),0)/rows.length):0,estimatedCost:rows.reduce((s,x)=>s+Number(x.estimated_cost||0),0)}}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});if(req.method!=="GET")return json({success:false,error:"Method not allowed"},405);if(!(await admin(req)))return json({success:false,error:"Admin access required"},403);const days=Math.min(90,Math.max(1,Number(new URL(req.url).searchParams.get("days")||7)));try{const[g,m,o,metrics]=await Promise.all([state("groq",days),state("gemini",days),state("openai",days),globalMetrics(days)]);return json({success:true,primary:"groq",fallbackChain:["groq","gemini","openai"],providers:{groq:{provider:"Groq",configured:!!KEYS.groq,model:MODELS.groq,...g},gemini:{provider:"Google Gemini",configured:!!KEYS.gemini,model:MODELS.gemini,...m},openai:{provider:"OpenAI",configured:!!KEYS.openai,model:MODELS.openai,...o}},metrics,period:`${days} days`,note:"Connection status is derived from sanitized provider attempts recorded by ai-proxy; no API keys or authorization headers are exposed."})}catch(e){console.error("[ai-health] diagnostics failure",e instanceof Error?e.message:String(e));return json({success:false,error:"Failed to retrieve AI provider diagnostics"},500)}});