import { createClient } from "npm:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const db=()=>createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
const platformFor=(url:URL)=>{const h=url.hostname.toLowerCase().replace(/^www\./,'');if(h.includes('tiktok.com'))return'TikTok';if(h.includes('linkedin.com'))return'LinkedIn';if(h.includes('fiverr.com'))return'Fiverr';if(h.includes('upwork.com'))return'Upwork';if(h.includes('instagram.com'))return'Instagram';if(h.includes('youtube.com')||h==='youtu.be')return'YouTube';if(h.includes('facebook.com'))return'Facebook';if(h==='x.com'||h.includes('twitter.com'))return'X';if(h.includes('github.com'))return'GitHub';return'Other'};
const strip=(s:string)=>s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();
const meta=(html:string,key:string)=>{const e=key.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:property|name)=["']${e}["'][^>]+content=["']([^"']*)["'][^>]*>`,'i');const b=new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${e}["'][^>]*>`,'i');return(html.match(a)?.[1]||html.match(b)?.[1]||'').trim()};
const first=(html:string,ps:RegExp[])=>{for(const p of ps){const m=html.match(p);if(m?.[1])return m[1]}return null};
const num=(raw:string|null)=>{if(!raw)return null;const m=raw.replace(/,/g,'').trim().match(/([0-9]+(?:\.[0-9]+)?)\s*([KMB])?/i);if(!m)return null;const n=Number(m[1]);const x=m[2]?.toUpperCase()==='K'?1e3:m[2]?.toUpperCase()==='M'?1e6:m[2]?.toUpperCase()==='B'?1e9:1;return Number.isFinite(n)?Math.round(n*x):null};
const metric=(text:string,words:string[])=>{const e=words.map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|');return num(first(text,[new RegExp(`(?:^|[^0-9])([0-9][0-9,.]*\\s*[KMB]?)\\s*(?:${e})\\b`,'i'),new RegExp(`(?:${e})\\s*[:=]?\\s*([0-9][0-9,.]*\\s*[KMB]?)`,'i')]))};
const usernameFor=(url:URL)=>{if(!url.hostname.toLowerCase().includes('tiktok.com'))return null;const m=url.pathname.match(/\/@([^/?#]+)/);return m?.[1]||null};

async function officialTikTokResearch(username:string){
 const token=Deno.env.get('TIKTOK_RESEARCH_ACCESS_TOKEN');
 if(!token)return null;
 const endpoint='https://open.tiktokapis.com/v2/research/user/info/?fields=display_name,bio_description,avatar_url,is_verified,follower_count,following_count,likes_count,video_count,bio_url';
 try{
  const r=await fetch(endpoint,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({username})});
  const j=await r.json().catch(()=>null);
  if(!r.ok||j?.error?.code&&j.error.code!=='ok')return null;
  const u=j?.data||j?.data?.user; if(!u)return null;
  return {display_name:u.display_name??null,bio_description:u.bio_description??null,avatar_url:u.avatar_url??null,is_verified:u.is_verified??false,follower_count:u.follower_count??null,following_count:u.following_count??null,likes_count:u.likes_count??null,video_count:u.video_count??null,bio_url:u.bio_url??null};
 }catch{return null}
}

async function analyzeUrl(rawUrl:string){
 let url:URL;try{url=new URL(rawUrl)}catch{return{profile_url:rawUrl,platform:'Other',status:'invalid_url',risk_level:'UNKNOWN',confidence_score:0,error:'Invalid URL'}}
 if(url.protocol!=='https:')return{profile_url:rawUrl,platform:platformFor(url),status:'invalid_url',risk_level:'UNKNOWN',confidence_score:0,error:'HTTPS is required'};
 const platform=platformFor(url);let official:any=null;
 if(platform==='TikTok'){const username=usernameFor(url);if(username)official=await officialTikTokResearch(username)}
 const headers={"User-Agent":"Mozilla/5.0 (compatible; DRIGHT-Marketer-Verification/1.0; +https://dright.com)",Accept:'text/html,application/xhtml+xml'};
 let response:Response;try{response=await fetch(url.toString(),{headers,redirect:'follow'})}catch(e){return{profile_url:rawUrl,platform,status:'fetch_failed',risk_level:'UNKNOWN',confidence_score:0,error:e instanceof Error?e.message:'Could not fetch profile'}}
 const finalUrl=response.url||url.toString();
 if(!response.ok)return{profile_url:rawUrl,final_url:finalUrl,platform,status:'blocked_or_unavailable',risk_level:'UNKNOWN',confidence_score:0,http_status:response.status,error:`Profile returned HTTP ${response.status}`};
 const html=(await response.text()).slice(0,1500000),text=strip(html);
 const title=meta(html,'og:title')||meta(html,'twitter:title')||first(html,[/<title[^>]*>([\s\S]*?)<\/title>/i]);
 const description=meta(html,'og:description')||meta(html,'description')||meta(html,'twitter:description');
 const canonical=first(html,[/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i,/<link[^>]+href=["']([^"']+)["'][^>]+rel=["']canonical["']/i]);
 let followers=metric(text,['followers','follower']),following=metric(text,['following']),likes=metric(text,['likes','like']),contentCount=metric(text,['videos','video','posts','post','gigs','jobs','projects']),verified=/verified|verification badge|verified account/i.test(text)&&!/unverified/i.test(text),profileTitle=title?strip(title):null,profileDescription=description||null,dataSource='public profile HTML';
 if(official){followers=official.follower_count;following=official.following_count;likes=official.likes_count;contentCount=official.video_count;verified=Boolean(official.is_verified);profileTitle=official.display_name||profileTitle;profileDescription=official.bio_description||profileDescription;dataSource='TikTok Research API';}
 const available=[followers,following,likes,contentCount].filter(v=>v!==null).length;
 const signals:string[]=[];if(profileTitle||profileDescription)signals.push('public profile metadata found');if(followers!==null)signals.push('follower count found');if(following!==null)signals.push('following count found');if(likes!==null)signals.push('likes count found');if(contentCount!==null)signals.push('content/activity count found');if(verified)signals.push('verified status reported by platform');
 if(available===0){signals.push('platform did not expose usable public metrics');return{profile_url:rawUrl,final_url:finalUrl,canonical_url:canonical,platform,status:'limited_data',profile_title:profileTitle,profile_description:profileDescription,followers:null,following:null,likes:null,content_count:null,verified_indicator:verified,authenticity_score:null,risk_level:'UNKNOWN',confidence_score:0,signals,data_source,data_access:'No authoritative profile statistics were available. Do not treat the result as a bot/non-bot decision.',analyzed_at:new Date().toISOString()}}
 let authenticity=50;if(followers!==null)authenticity+=10;if(contentCount!==null)authenticity+=8;if(verified)authenticity+=12;if(followers!==null&&following!==null){if(following>followers*3&&following>1000){authenticity-=15;signals.push('unusually high following-to-follower ratio')}else if(followers>following){authenticity+=5;signals.push('follower/following ratio is consistent with an established profile')}}
 authenticity=Math.max(0,Math.min(100,authenticity));const risk=authenticity>=75?'LOW':authenticity>=50?'MEDIUM':'HIGH';
 const confidence=Math.min(95,Math.round(available*20+(official?20:0)+(verified?10:0)));
 return{profile_url:rawUrl,final_url:finalUrl,canonical_url:canonical,platform,status:'analyzed',profile_title:profileTitle,profile_description:profileDescription,followers,following,likes,content_count:contentCount,verified_indicator:verified,authenticity_score:authenticity,risk_level:risk,confidence_score:confidence,signals,data_source,disclaimer:'Automated risk estimate only. It does not prove that followers are real or that an account is operated by a bot.',analyzed_at:new Date().toISOString()}
}

Deno.serve(async req=>{if(req.method==='OPTIONS')return json(null);if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({error:'Unauthorized'},401);const client=db();const{data:{user},error:authError}=await client.auth.getUser(auth.slice(7));if(authError||!user)return json({error:'Unauthorized'},401);const body=await req.json().catch(()=>({}));const applicantId=String(body.applicant_id||user.id);if(applicantId!==user.id){const{data:admin}=await client.from('users').select('is_admin,admin_status,admin_role').eq('id',user.id).single();const roles=new Set(['super_admin','sales_team_manager','sales_marketing_admin','advertising_admin']);if(!admin?.is_admin||String(admin.admin_status||'').toLowerCase()!=='active'||!roles.has(String(admin.admin_role||'')))return json({error:'Not allowed to analyze another applicant'},403)}const{data:applicant,error:applicantError}=await client.from('users').select('id,social_media_links').eq('id',applicantId).single();if(applicantError||!applicant)return json({error:'Applicant not found'},404);const links=Array.isArray(body.links)?body.links.map((v:unknown)=>String(v).trim()).filter(Boolean):Array.isArray(applicant.social_media_links)?applicant.social_media_links.map((v:unknown)=>String(v).trim()).filter(Boolean):[];if(!links.length)return json({error:'No profile links to analyze'},400);if(links.length>10)return json({error:'Maximum 10 profile links'},400);const analyses=[];for(const link of links)analyses.push(await analyzeUrl(link));const now=new Date().toISOString();const{error:updateError}=await client.from('users').update({marketer_social_analysis:analyses,updated_at:now}).eq('id',applicantId);if(updateError)throw updateError;const snapshots=analyses.map((a:any)=>({applicant_id:applicantId,profile_url:a.profile_url,platform:a.platform,analysis:a,analyzed_at:now}));const{error:snapshotError}=await client.from('marketer_social_analysis_snapshots').insert(snapshots);if(snapshotError)throw snapshotError;return json({success:true,applicant_id:applicantId,analyses})}catch(e){return json({error:e instanceof Error?e.message:'Profile analysis failed'},400)}});
