import { useCallback, useEffect, useState } from 'react';
import { AlertCircle, Eye, EyeOff, Loader2, MessageCircle, RotateCcw, Save, Trash2, X } from 'lucide-react';
import { supabase } from '../../lib/supabase';

interface ModerationComment { id:string; user_id:string; body:string; status:'visible'|'hidden'; created_at:string; moderated_at:string|null; moderation_reason:string|null; author_name:string; author_email:string|null; author_avatar:string|null; }
interface Props { contentId:string; title:string; onClose:()=>void; }

export default function AdminNewsCommentModerationModal({ contentId, title, onClose }:Props){
  const [comments,setComments]=useState<ModerationComment[]>([]);
  const [loading,setLoading]=useState(true); const [busyId,setBusyId]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  const [hideViews,setHideViews]=useState(false); const [hideReactions,setHideReactions]=useState(false); const [settingsBusy,setSettingsBusy]=useState(false); const [saved,setSaved]=useState(false);

  const load=useCallback(async()=>{
    setLoading(true); setError(null);
    const [commentsResult,settingsResult]=await Promise.all([
      supabase.rpc('admin_get_global_content_comments',{p_content_id:contentId}),
      supabase.from('global_announcements').select('hide_view_count,hide_reaction_count').eq('id',contentId).single(),
    ]);
    if(commentsResult.error){setError(commentsResult.error.message||'Unable to load comments.');setComments([]);} else setComments((commentsResult.data||[]) as ModerationComment[]);
    if(!settingsResult.error&&settingsResult.data){setHideViews(Boolean(settingsResult.data.hide_view_count));setHideReactions(Boolean(settingsResult.data.hide_reaction_count));}
    setLoading(false);
  },[contentId]);
  useEffect(()=>{void load();},[load]);

  const saveSettings=async()=>{setSettingsBusy(true);setSaved(false);setError(null);const {error:e}=await supabase.rpc('admin_set_global_content_display_settings',{p_content_id:contentId,p_hide_view_count:hideViews,p_hide_reaction_count:hideReactions});setSettingsBusy(false);if(e)return setError(e.message||'Unable to save display settings.');setSaved(true);window.setTimeout(()=>setSaved(false),2200);};
  const moderate=async(comment:ModerationComment,action:'hide'|'restore'|'delete')=>{if(action==='delete'&&!window.confirm('Permanently delete this comment?'))return;setBusyId(comment.id);setError(null);const {error:e}=await supabase.rpc('admin_moderate_global_content_comment',{p_comment_id:comment.id,p_action:action,p_reason:action==='hide'?'Hidden by DRIGHT content moderation':null});setBusyId(null);if(e)return setError(e.message||'Unable to moderate this comment.');await load();};

  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/65 p-3 sm:p-4" onClick={onClose}>
    <div className="max-h-[92vh] w-full max-w-3xl overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-gray-700 dark:bg-gray-900" onClick={e=>e.stopPropagation()}>
      <div className="flex items-start justify-between gap-3 border-b border-gray-200 p-4 dark:border-gray-700 sm:p-5"><div className="min-w-0"><div className="flex items-center gap-2"><MessageCircle className="h-5 w-5 text-primary-600"/><h2 className="text-lg font-bold text-gray-900 dark:text-white">Post settings & comment moderation</h2></div><p className="mt-1 truncate text-sm text-gray-500">{title}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-800" aria-label="Close"><X className="h-5 w-5"/></button></div>
      <div className="max-h-[76vh] overflow-y-auto p-4 sm:p-5">
        {error&&<div className="mb-4 flex gap-2 rounded-xl bg-error-muted p-3 text-sm text-error"><AlertCircle className="h-4 w-4 shrink-0"/><span>{error}</span></div>}
        <section className="mb-5 rounded-2xl border border-gray-200 p-4 dark:border-gray-700 dark:bg-gray-800/50"><div className="flex items-start justify-between gap-3"><div><h3 className="font-bold text-gray-900 dark:text-white">Public engagement counts</h3><p className="mt-1 text-xs text-gray-500">The metrics still count internally when hidden; only the public number is concealed.</p></div>{saved&&<span className="text-xs font-semibold text-emerald-600">Saved</span>}</div><div className="mt-4 grid gap-3 sm:grid-cols-2">
          <label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-gray-200 p-3 dark:border-gray-700"><span className="flex items-center gap-2 text-sm font-semibold text-gray-700 dark:text-gray-200">{hideViews?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>} Hide view count</span><input type="checkbox" checked={hideViews} onChange={e=>setHideViews(e.target.checked)} className="h-4 w-4"/></label>
          <label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-gray-200 p-3 dark:border-gray-700"><span className="flex items-center gap-2 text-sm font-semibold text-gray-700 dark:text-gray-200">{hideReactions?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>} Hide reaction count</span><input type="checkbox" checked={hideReactions} onChange={e=>setHideReactions(e.target.checked)} className="h-4 w-4"/></label>
        </div><button type="button" disabled={settingsBusy} onClick={()=>void saveSettings()} className="mt-3 inline-flex min-h-[40px] items-center gap-2 rounded-xl bg-primary-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{settingsBusy?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}Save display settings</button></section>
        <h3 className="mb-3 font-bold text-gray-900 dark:text-white">Comments</h3>
        {loading?<div className="flex min-h-[180px] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-primary-600"/></div>:comments.length===0?<div className="py-12 text-center"><MessageCircle className="mx-auto h-11 w-11 text-gray-300"/><p className="mt-3 font-semibold text-gray-700 dark:text-gray-200">No comments yet</p></div>:<div className="space-y-3">{comments.map(comment=><article key={comment.id} className={`rounded-2xl border p-4 ${comment.status==='hidden'?'border-amber-200 bg-amber-50/60 dark:border-amber-900/50 dark:bg-amber-950/20':'border-gray-200 dark:border-gray-700 dark:bg-gray-800'}`}><div className="flex items-start gap-3">{comment.author_avatar?<img src={comment.author_avatar} alt="" className="h-10 w-10 rounded-full object-cover"/>:<div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-100 text-sm font-bold text-primary-700">{(comment.author_name||'D').slice(0,1).toUpperCase()}</div>}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-gray-900 dark:text-white">{comment.author_name}</p><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${comment.status==='visible'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}`}>{comment.status}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-gray-700 dark:text-gray-200">{comment.body}</p><p className="mt-2 text-xs text-gray-400">{new Date(comment.created_at).toLocaleString()}</p>{comment.moderation_reason&&<p className="mt-1 text-xs text-amber-700">{comment.moderation_reason}</p>}</div></div><div className="mt-3 flex justify-end gap-2 border-t border-gray-100 pt-3 dark:border-gray-700">{comment.status==='visible'?<button type="button" disabled={busyId===comment.id} onClick={()=>void moderate(comment,'hide')} className="inline-flex items-center gap-1 rounded-xl border border-amber-200 px-3 py-2 text-xs font-semibold text-amber-700"><EyeOff className="h-3.5 w-3.5"/>Hide</button>:<button type="button" disabled={busyId===comment.id} onClick={()=>void moderate(comment,'restore')} className="inline-flex items-center gap-1 rounded-xl border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700"><RotateCcw className="h-3.5 w-3.5"/>Restore</button>}<button type="button" disabled={busyId===comment.id} onClick={()=>void moderate(comment,'delete')} className="inline-flex items-center gap-1 rounded-xl border border-red-200 px-3 py-2 text-xs font-semibold text-red-700"><Trash2 className="h-3.5 w-3.5"/>Delete</button></div></article>)}</div>}
      </div>
    </div>
  </div>;
}
