import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '006',
  slug: 'weight-loss-fitness-business-affiliate-mastery-2026',
  title: 'Weight Loss & Fitness Business/Affiliate Mastery 2026',
  subtitle: 'Evidence-Based Fitness • Content • Offers • Supplements • Affiliate Marketing',
  promise: 'Build a responsible fitness-content and affiliate business around evidence-based training, weight-management education, useful product recommendations and transparent marketing. This course does not provide individualized medical treatment and does not promote unsafe weight-loss products.',
  accent: 'whatsapp',
  modules: [
    {
      title: 'Fitness niche and business foundations',
      intro: 'Start by deciding who you serve, what problem you help them understand and how the business earns revenue without making unsafe or misleading health claims.',
      principles: ['Choose a specific audience and problem.', 'Separate education from medical diagnosis.', 'Use transparent monetization and affiliate disclosures.'],
      mistakes: ['Promising guaranteed weight loss.', 'Trying to serve every fitness audience at once.'],
      deliverable: 'Write your niche, audience, value proposition and monetization model.',
      lessons: [
        { title: 'Choose a defensible fitness niche', brief: 'Focus on a clear audience such as beginners, gym newcomers, busy adults or evidence-based supplement education rather than vague “fitness for everyone.”', action: 'Write one niche statement using audience + problem + outcome.' },
        { title: 'Business models in fitness', brief: 'Compare content, affiliate commissions, digital products, coaching, sponsorships and ecommerce while understanding the obligations of each.', action: 'Choose one primary and one secondary monetization model.' },
        { title: 'Health information boundaries', brief: 'Learn the difference between general educational information, personal coaching and medical advice.', action: 'Write a disclaimer and referral rule for situations that require a qualified health professional.' },
      ],
      question: { prompt: 'What is the safest business foundation?', choices: ['A clear niche with evidence-based education and transparent monetization', 'Guaranteed weight-loss promises', 'Selling every supplement available'], answer: 0, explanation: 'A focused, transparent model reduces confusion and health-claim risk.' },
    },
    {
      title: 'Evidence-based weight management',
      intro: 'Weight management is influenced by food intake, physical activity, sleep, stress, health conditions, medicines and other factors. Avoid simplistic miracle claims.',
      principles: ['Use gradual, sustainable behavior change.', 'Understand energy balance without reducing health to one number.', 'Recognize when medical factors may affect weight.'],
      mistakes: ['Promoting crash diets.', 'Treating one method as universally effective.'],
      deliverable: 'Create an evidence-based beginner weight-management education sheet.',
      lessons: [
        { title: 'Energy balance basics', brief: 'Understand how calorie intake and energy expenditure influence body weight while recognizing individual variation.', action: 'Create a simple educational diagram explaining energy balance.' },
        { title: 'Sustainable rate of change', brief: 'Use gradual change, practical meal habits, activity, sleep and stress management rather than extreme restriction.', action: 'Write five sustainable habit examples.' },
        { title: 'When to refer out', brief: 'Recognize medication, pregnancy, eating-disorder concerns, chronic disease and other situations where individualized care belongs with a qualified clinician.', action: 'Create a referral checklist for your content or business.' },
      ],
      question: { prompt: 'Which approach is most consistent with public-health guidance?', choices: ['Gradual, sustainable lifestyle change', 'Guaranteed rapid weight loss', 'Unverified detox products'], answer: 0, explanation: 'Public-health guidance emphasizes sustainable eating, activity, sleep and stress-management habits.' },
    },
    {
      title: 'Nutrition fundamentals for fitness content',
      intro: 'Teach useful nutrition concepts without pretending one eating style is mandatory for everyone.',
      principles: ['Prioritize overall dietary pattern.', 'Explain protein, carbohydrates and fats in context.', 'Avoid demonizing single foods.'],
      mistakes: ['Calling foods “toxic” without evidence.', 'Giving rigid meal plans to people with medical needs.'],
      deliverable: 'Build a beginner nutrition content guide.',
      lessons: [
        { title: 'Protein, carbohydrates and fats', brief: 'Explain how macronutrients contribute to recovery, training and energy in simple language.', action: 'Create three short educational posts, one for each macronutrient.' },
        { title: 'Meal structure and satiety', brief: 'Use practical concepts such as protein, fiber, minimally processed foods and portion awareness without creating a restrictive diet prescription.', action: 'Design three balanced-meal examples.' },
        { title: 'Reading labels and claims', brief: 'Teach customers to separate serving size, calories, protein and ingredient information from front-of-pack marketing claims.', action: 'Create a label-reading checklist.' },
      ],
      question: { prompt: 'What is a better nutrition teaching approach?', choices: ['Explain patterns and trade-offs', 'Label every carbohydrate as bad', 'Promise one food causes fat loss'], answer: 0, explanation: 'Balanced education is more accurate and useful than absolute claims.' },
    },
    {
      title: 'Strength training fundamentals',
      intro: 'Resistance training supports strength, muscle and general fitness when progressed appropriately.',
      principles: ['Use safe technique and progressive overload.', 'Match training volume to experience.', 'Allow recovery.'],
      mistakes: ['Copying advanced programs as a beginner.', 'Training through sharp or unusual pain.'],
      deliverable: 'Create a general beginner strength-training education plan.',
      lessons: [
        { title: 'Movement patterns', brief: 'Teach squat, hinge, push, pull, carry and core concepts without prescribing one mandatory exercise.', action: 'Create an exercise-category reference sheet.' },
        { title: 'Progressive overload', brief: 'Explain how training can progress through load, repetitions, range, technique and volume over time.', action: 'Write a simple four-week progression example.' },
        { title: 'Recovery and consistency', brief: 'Explain why sleep, recovery days and manageable program design matter for adherence.', action: 'Create a weekly training-and-recovery checklist.' },
      ],
      question: { prompt: 'What does progressive overload mean?', choices: ['Gradually increasing training challenge over time', 'Maxing out every workout', 'Avoiding recovery'], answer: 0, explanation: 'Progression can come from several variables and should remain appropriate to the trainee.' },
    },
    {
      title: 'Cardio, steps and activity',
      intro: 'Cardio and general activity support health, fitness and energy expenditure, but the right dose depends on goals and ability.',
      principles: ['Use walking and general activity as accessible tools.', 'Balance cardio with strength training and recovery.', 'Scale intensity gradually.'],
      mistakes: ['Treating cardio as punishment for eating.', 'Jumping immediately into excessive high-intensity training.'],
      deliverable: 'Create a beginner activity education framework.',
      lessons: [
        { title: 'Daily movement and steps', brief: 'Use daily walking and movement as practical, low-barrier activity rather than relying only on formal workouts.', action: 'Create a progressive walking challenge.' },
        { title: 'Moderate and vigorous cardio', brief: 'Explain intensity differences and how public-health recommendations combine aerobic and strength activity.', action: 'Create three cardio examples at different intensities.' },
        { title: 'Cardio for fat loss and fitness', brief: 'Explain that cardio can support an energy deficit and fitness but does not replace sustainable nutrition or strength work.', action: 'Write a myth-vs-fact post about cardio.' },
      ],
      question: { prompt: 'What is a useful role for cardio?', choices: ['Support health, fitness and energy expenditure', 'Punish food intake', 'Guarantee fat loss regardless of diet'], answer: 0, explanation: 'Cardio is one part of a broader health and weight-management system.' },
    },
    {
      title: 'Protein supplements and product literacy',
      intro: 'Protein powders can be convenient food supplements, but they are not magic fat-loss or muscle-building products.',
      principles: ['Food can meet protein needs.', 'Use supplements for convenience when appropriate.', 'Evaluate label quality and claims.'],
      mistakes: ['Claiming protein powder automatically causes weight loss.', 'Assuming more is always better.'],
      deliverable: 'Build a responsible protein-product review template.',
      lessons: [
        { title: 'When protein powder is useful', brief: 'Explain convenience, dietary preferences and total daily protein rather than selling powder as mandatory.', action: 'Write a balanced “who may benefit / who may not need it” guide.' },
        { title: 'Comparing protein products', brief: 'Compare serving protein, calories, ingredients, allergens, price per serving and third-party testing where relevant.', action: 'Build a five-column comparison table.' },
        { title: 'Affiliate review ethics', brief: 'Disclose commissions and separate personal preference from evidence-based claims.', action: 'Write your standard affiliate disclosure.' },
      ],
      question: { prompt: 'What should a protein-product review focus on?', choices: ['Useful label information, fit and transparent disclosure', 'Guaranteed transformation claims', 'Commission size only'], answer: 0, explanation: 'A responsible review helps the buyer evaluate the product rather than exaggerating outcomes.' },
    },
    {
      title: 'Creatine and evidence-based supplementation',
      intro: 'Creatine monohydrate is one of the most studied sports supplements, mainly for repeated high-intensity activity and strength/power training.',
      principles: ['Separate performance evidence from weight-loss claims.', 'Explain water-weight changes accurately.', 'Do not present supplements as substitutes for training and nutrition.'],
      mistakes: ['Selling creatine as a fat burner.', 'Ignoring contraindications or individual medical questions.'],
      deliverable: 'Create a responsible creatine education and product-review guide.',
      lessons: [
        { title: 'What creatine does', brief: 'Explain phosphocreatine, repeated high-intensity performance and strength-training support in beginner-friendly language.', action: 'Write a 60-second creatine explainer.' },
        { title: 'Common misconceptions', brief: 'Address water retention, cycling and “instant muscle” misconceptions without overstating certainty.', action: 'Create five myth-vs-fact cards.' },
        { title: 'Review and recommendation standards', brief: 'Compare form, serving size, price and quality while avoiding disease-treatment or guaranteed-body-composition claims.', action: 'Build a creatine-review checklist.' },
      ],
      question: { prompt: 'What is creatine best supported for?', choices: ['Repeated high-intensity performance and training support', 'Guaranteed fat loss', 'Treating medical conditions'], answer: 0, explanation: 'Evidence is strongest for high-intensity performance and strength/power contexts, not miracle weight loss.' },
    },
    {
      title: 'Unsafe weight-loss products and red flags',
      intro: 'The fitness market contains contaminated or misleading weight-loss products. A credible business must know what not to promote.',
      principles: ['Avoid unverified fat burners and detox claims.', 'Check regulator warnings.', 'Do not market hidden-drug or prescription-like effects as supplements.'],
      mistakes: ['Promoting “rapid fat melting” pills or teas.', 'Using before/after claims without context or substantiation.'],
      deliverable: 'Create a supplement red-flag and product-rejection policy.',
      lessons: [
        { title: 'Weight-loss supplement risk', brief: 'Understand why some weight-loss pills, teas and “natural” products have been found with hidden ingredients or unsupported claims.', action: 'Create a red-flag list for products you will never promote.' },
        { title: 'Claims and substantiation', brief: 'Learn why a metabolism study does not automatically substantiate a weight-loss claim.', action: 'Rewrite five exaggerated claims into accurate educational language.' },
        { title: 'Affiliate due diligence', brief: 'Check brand identity, product labeling, return policy, regulator warnings and evidence before accepting a partnership.', action: 'Build a product due-diligence checklist.' },
      ],
      question: { prompt: 'What should you do with a product promising extreme rapid weight loss with unclear ingredients?', choices: ['Reject it and verify regulator warnings', 'Promote it for a higher commission', 'Call it medically proven'], answer: 0, explanation: 'Health-risk products and unsupported claims can harm both customers and the business.' },
    },
    {
      title: 'Content strategy for the fitness niche',
      intro: 'Useful fitness content answers real beginner questions and demonstrates expertise without pretending to diagnose individuals.',
      principles: ['Create around audience questions.', 'Use demonstrations and visual explanations.', 'Build recurring content pillars.'],
      mistakes: ['Posting only motivational quotes.', 'Using shame-based transformation messaging.'],
      deliverable: 'Create four content pillars and a 30-day content calendar.',
      lessons: [
        { title: 'Fitness content pillars', brief: 'Use education, demonstrations, myth-busting, product literacy and progress-process content.', action: 'Choose four pillars for your brand.' },
        { title: 'Hooks without fear tactics', brief: 'Use specificity and relevance rather than body shame or medical scare tactics.', action: 'Write 25 ethical hooks.' },
        { title: 'Short-form visual teaching', brief: 'Use exercise demos, label comparisons, meal examples and simple diagrams for people who prefer visual learning.', action: 'Storyboard five short educational videos.' },
      ],
      question: { prompt: 'Which hook style is more sustainable?', choices: ['Specific, useful and respectful', 'Body-shaming fear tactics', 'Guaranteed transformation promises'], answer: 0, explanation: 'Useful content can attract attention without making people feel unsafe or deceived.' },
    },
    {
      title: 'Affiliate marketing fundamentals',
      intro: 'Affiliate marketing pays commission for referred purchases or actions, but trust depends on disclosure and useful product selection.',
      principles: ['Recommend products that fit the audience.', 'Disclose affiliate relationships.', 'Track clicks, conversions, refunds and customer feedback.'],
      mistakes: ['Choosing products only for high commission.', 'Hiding the affiliate relationship.'],
      deliverable: 'Create a fitness affiliate offer scorecard.',
      lessons: [
        { title: 'How affiliate marketing works', brief: 'Understand merchant, affiliate, customer, tracking link, commission and attribution window.', action: 'Draw the full affiliate transaction flow.' },
        { title: 'Choosing programs', brief: 'Evaluate commission, cookie/attribution window, payout reliability, product quality, refund rate and brand reputation.', action: 'Score five potential programs.' },
        { title: 'Disclosure and trust', brief: 'Use clear disclosures close to the recommendation instead of hiding them in a distant policy page.', action: 'Write disclosure versions for video, social caption and blog.' },
      ],
      question: { prompt: 'What should matter besides commission rate?', choices: ['Product fit, quality, payout reliability and customer outcomes', 'Nothing', 'Only follower count'], answer: 0, explanation: 'A high commission does not make a poor or risky product suitable for your audience.' },
    },
    {
      title: 'Product reviews and comparison content',
      intro: 'High-quality affiliate content helps customers make a decision rather than simply repeating sales copy.',
      principles: ['Use consistent evaluation criteria.', 'Explain who the product is and is not for.', 'Separate facts, evidence and opinion.'],
      mistakes: ['Copying the manufacturer description.', 'Pretending every reviewed product is “the best.”'],
      deliverable: 'Create one full review and one comparison piece.',
      lessons: [
        { title: 'Review framework', brief: 'Cover use case, features, evidence, price, downsides, alternatives and disclosure.', action: 'Create a reusable review template.' },
        { title: 'Comparison content', brief: 'Compare products on the same criteria and explain trade-offs instead of declaring arbitrary winners.', action: 'Build one side-by-side comparison.' },
        { title: 'Calls to action', brief: 'Use clear but non-manipulative CTAs that tell the reader what happens when they click.', action: 'Write five transparent CTAs.' },
      ],
      question: { prompt: 'What makes a comparison trustworthy?', choices: ['Consistent criteria and clear trade-offs', 'Changing criteria to favor the highest commission', 'Hiding downsides'], answer: 0, explanation: 'Consistent criteria help customers understand the decision rather than being steered by hidden incentives.' },
    },
    {
      title: 'Funnels, email and lead capture',
      intro: 'Do not rely on a single social platform. Build owned audience channels and useful follow-up.',
      principles: ['Offer a useful lead magnet.', 'Collect email with consent.', 'Segment follow-up by audience interest.'],
      mistakes: ['Buying email lists.', 'Sending unrelated promotions constantly.'],
      deliverable: 'Build a simple fitness lead magnet and five-email nurture sequence.',
      lessons: [
        { title: 'Lead magnet design', brief: 'Create a checklist, beginner guide or tracker that solves one small problem.', action: 'Outline a one-page lead magnet.' },
        { title: 'Email nurture', brief: 'Use education, proof, product literacy and occasional relevant offers.', action: 'Write a five-email sequence.' },
        { title: 'Landing-page continuity', brief: 'Make the lead magnet or affiliate page match the promise made in the social content.', action: 'Audit headline, proof and CTA consistency.' },
      ],
      question: { prompt: 'Why build an email list?', choices: ['It creates an owned communication channel with permission', 'It guarantees sales', 'It replaces useful content'], answer: 0, explanation: 'Owned channels reduce dependence on a single platform while still requiring useful communication.' },
    },
    {
      title: 'Analytics and unit economics',
      intro: 'Track both content metrics and the economics of clicks, conversions, refunds and commissions.',
      principles: ['Separate vanity metrics from revenue metrics.', 'Account for refunds and chargebacks.', 'Use conversion data to improve content and offers.'],
      mistakes: ['Celebrating clicks with no sales context.', 'Ignoring refund rate.'],
      deliverable: 'Create a monthly affiliate and content dashboard.',
      lessons: [
        { title: 'Content metrics', brief: 'Track reach, watch time, clicks and lead actions based on the purpose of the content.', action: 'Choose five metrics for each content type.' },
        { title: 'Affiliate economics', brief: 'Calculate EPC, conversion rate, average commission, refund impact and profit after content/ad costs.', action: 'Build a simple unit-economics sheet.' },
        { title: 'Decision rules', brief: 'Define when to keep, improve or remove a product recommendation based on evidence and customer outcomes.', action: 'Write your keep/improve/remove criteria.' },
      ],
      question: { prompt: 'Why include refund rate in affiliate analysis?', choices: ['It affects real earnings and may signal customer dissatisfaction', 'It has no effect', 'It only changes follower count'], answer: 0, explanation: 'High refunds can reduce earnings and indicate a weak product-audience fit.' },
    },
    {
      title: 'Brand trust, legal and claims compliance',
      intro: 'Fitness businesses operate in a sensitive category. Evidence, disclosures and careful claims are part of the product.',
      principles: ['Substantiate objective claims.', 'Disclose commercial relationships.', 'Avoid disease-treatment and guaranteed-body claims without appropriate legal/medical basis.'],
      mistakes: ['“Lose 10kg in 7 days guaranteed.”', 'Presenting testimonials as typical guaranteed results.'],
      deliverable: 'Create a claims-review checklist and content disclaimer system.',
      lessons: [
        { title: 'Health claims vs education', brief: 'Distinguish general educational discussion from claims that a product treats, cures or guarantees a health outcome.', action: 'Classify ten sample claims as acceptable, risky or requires specialist review.' },
        { title: 'Testimonials and before/after content', brief: 'Use context, permission and truthful presentation instead of implying one result is typical for everyone.', action: 'Create a testimonial-review checklist.' },
        { title: 'Affiliate disclosure placement', brief: 'Make commercial relationships obvious wherever the recommendation appears.', action: 'Audit disclosure placement across your channels.' },
      ],
      question: { prompt: 'What should happen before publishing a strong health/product claim?', choices: ['Confirm evidence and compliance requirements', 'Add more emojis', 'Hide the affiliate link'], answer: 0, explanation: 'Sensitive claims require substantiation and appropriate context.' },
    },
    {
      title: 'Capstone: 90-day fitness affiliate business',
      intro: 'Combine audience research, responsible health education, content, products, funnels and analytics into one repeatable system.',
      principles: ['Build trust before monetization pressure.', 'Use evidence and transparent product selection.', 'Review both customer outcomes and business economics.'],
      mistakes: ['Launching dozens of unrelated products.', 'Making revenue claims you cannot substantiate.'],
      deliverable: 'Complete a 90-day content, affiliate and analytics operating plan.',
      lessons: [
        { title: 'Product portfolio', brief: 'Select a small group of relevant products such as equipment, apparel, protein or evidence-based performance products with clear review criteria.', action: 'Choose three primary products and two alternatives.' },
        { title: 'Content and funnel calendar', brief: 'Schedule educational content, product comparisons, lead magnets, email nurture and campaign reviews.', action: 'Build a 12-week calendar.' },
        { title: 'Monthly business review', brief: 'Review content performance, clicks, conversion, refunds, disclosures, product quality and audience feedback.', action: 'Create your monthly review checklist.' },
      ],
      question: { prompt: 'What is the strongest long-term fitness affiliate strategy?', choices: ['Useful evidence-based content plus trustworthy product selection', 'Maximum claims and maximum products', 'Hiding commercial relationships'], answer: 0, explanation: 'Trust and useful decision support are durable business assets.' },
    },
  ],
  videos: [
    { module: 1, title: 'The Fool-Proof Way to Lose Fat', url: 'https://www.youtube.com/watch?v=qB74X92vCac', description: 'Renaissance Periodization explains calorie deficit, cardio, macronutrients, meal schedule, meal prep, simple foods and diet adherence in a detailed evidence-based format.', region: 'English • Evidence-based fat loss' },
    { module: 4, title: 'The Smartest Way to Do Cardio for Fat Loss and Health', url: 'https://www.youtube.com/watch?v=0r_AlKrc70c', description: 'Dr. Mike Israetel explains cardio variables for health, leanness, strength and endurance with practical dos and don’ts.', region: 'English • 2026 • Cardio' },
    { module: 3, title: 'How to Build Muscle: Explained in 5 Levels', url: 'https://www.youtube.com/watch?v=lu_BObG6dj8', description: 'Jeff Nippard explains beginner-to-advanced muscle-building concepts including protein, progressive overload, volume, intensity, exercise selection and frequency.', region: 'English • Evidence-based training' },
    { module: 6, title: 'Creatine: Everything You Need to Know', url: 'https://www.youtube.com/watch?v=Z9mlsyV7Hek', description: 'Jeff Nippard reviews the science behind creatine, common questions, performance effects, use and safety context.', region: 'English • Supplement literacy' },
    { module: 9, title: 'How to Use Affiliate Marketing to Drive Sales and Signups', url: 'https://www.youtube.com/watch?v=5P2_kpQEYqA', description: 'HubSpot Marketing explains affiliate marketing, common strategies and how affiliate programs can fit into a wider business system.', region: 'USA/International • English • Business' },
  ],
  visuals: [
    { title: 'Protein shaker after training', imageUrl: 'https://images.pexels.com/photos/5327559/pexels-photo-5327559.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/a-man-holding-a-protein-shaker-5327559/', sourceLabel: 'Pexels stock photo', caption: 'A neutral visual reference for supplement-literacy lessons. A shaker is a convenience tool, not a guarantee of muscle or fat loss.' },
    { title: 'Fitness supplements and shaker', imageUrl: 'https://images.pexels.com/photos/36429456/pexels-photo-36429456/free-photo-of-fitness-pre-workout-supplements-and-shaker.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/fitness-pre-workout-supplements-and-shaker-36429456/', sourceLabel: 'Pexels stock photo', caption: 'Use product imagery to teach label comparison, serving size, ingredient review and responsible affiliate disclosure.' },
    { title: 'Healthy food in a gym setting', imageUrl: 'https://images.pexels.com/videos/6740367/free-video-6740367.jpg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/video/eating-healthy-food-inside-a-fitness-gym-6740367/', sourceLabel: 'Pexels stock video', caption: 'Visual support for balanced nutrition and training discussions without promoting one restrictive diet.' },
    { title: 'Trainer discussing healthy food', imageUrl: 'https://images.pexels.com/videos/6547808/free-video-6547808.jpg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/video/a-personal-trainer-talking-to-his-client-about-healthy-food-and-junk-food-6547808/', sourceLabel: 'Pexels stock video', caption: 'A useful visual reference for coaching conversations, food choices and explaining trade-offs without moralizing food.' },
    { title: 'Gym strength-training routine', imageUrl: 'https://images.pexels.com/videos/29546657/pexels-photo-29546657.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/video/gym-workout-routine-with-weightlifting-machine-29546657/', sourceLabel: 'Pexels stock video', caption: 'Vertical training footage for exercise education, form discussion and social-content planning.' },
  ],
  references: [
    { label: 'CDC — Steps for Losing Weight', url: 'https://www.cdc.gov/healthy-weight-growth/losing-weight/index.html', summary: 'Public-health guidance emphasizing gradual, sustainable weight management with nutrition, activity, sleep and stress management.', points: ['Use specific plans.', 'Prefer gradual sustainable change.', 'Recognize medical and individual factors.'] },
    { label: 'CDC — Physical Activity and Weight', url: 'https://www.cdc.gov/healthy-weight-growth/physical-activity/', summary: 'Official CDC guidance on physical activity, calorie expenditure and adult activity recommendations.', points: ['Combine activity and nutrition.', 'Include aerobic activity.', 'Include muscle-strengthening activity.'] },
    { label: 'NIH ODS — Exercise & Athletic Performance Supplements', url: 'https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/', summary: 'Evidence-focused consumer information on performance supplements including creatine.', points: ['Understand evidence strength.', 'Separate performance from marketing claims.', 'Review safety information.'] },
    { label: 'FDA — Weight Loss Product Notifications', url: 'https://www.fda.gov/drugs/medication-health-fraud-notifications/weight-loss-product-notifications', summary: 'FDA warnings about contaminated and fraudulently marketed weight-loss products.', points: ['Avoid hidden-ingredient products.', 'Do not trust “natural” as proof of safety.', 'Check regulator warnings before promotion.'] },
  ],
  downloads: [],
};

export default function CourseFitnessAffiliatePage() {
  return <PremiumCourseLearningPage config={config} />;
}
