import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '002',
  slug: 'instagram-ads-mastery-2026',
  title: 'Instagram Ads Mastery 2026',
  subtitle: 'Campaigns • Reels • Stories • Targeting • Creative • Scaling',
  promise: 'Build Instagram advertising campaigns that are easy to understand, easy to test, and connected to a real business goal. This course focuses on Instagram placements, creative, audiences, tracking, optimization and practical mobile-first execution.',
  accent: 'instagram',
  modules: [
    {
      title: 'Instagram advertising foundations',
      intro: 'Start with the business outcome and the customer journey before touching campaign settings. Instagram ads work best when the offer, creative and destination tell one continuous story.',
      principles: ['Choose one measurable business goal per campaign.', 'Know the difference between attention metrics and business outcomes.', 'Treat Instagram as a visual sales channel, not only a follower-growth channel.'],
      mistakes: ['Boosting posts without knowing the objective.', 'Judging success only by likes or followers.'],
      deliverable: 'Write one campaign goal, one target customer, one offer and the action you want the customer to take.',
      lessons: [
        { title: 'How Instagram ads actually work', brief: 'Understand the relationship between Meta Ads Manager, Instagram placements, the ad auction and the action you optimize for.', action: 'Write the result you want from your next Instagram campaign in one sentence.' },
        { title: 'The Instagram customer journey', brief: 'Map discovery, interest, trust and conversion so each ad has a clear role.', action: 'Draw a four-stage Instagram funnel for one real product or service.' },
        { title: 'Metrics that matter', brief: 'Learn CPM, CTR, CPC, CVR, CPA and ROAS and how each one helps diagnose a different stage.', action: 'Calculate your maximum acceptable CPA before launch.' },
      ],
      question: { prompt: 'Which number connects ad spend most directly to the cost of acquiring a customer?', choices: ['CPA', 'Reach', 'Likes'], answer: 0, explanation: 'CPA measures the cost per acquired result or customer action. Reach and likes can be useful context but do not tell you acquisition cost.' },
    },
    {
      title: 'Professional account and business setup',
      intro: 'A clean business setup reduces account confusion and makes campaign management safer.',
      principles: ['Use a professional Instagram account for business activity.', 'Connect the correct Meta business assets before advertising.', 'Protect administrator access with strong security and least-privilege permissions.'],
      mistakes: ['Sharing one login across a team.', 'Running ads from the wrong Instagram identity.'],
      deliverable: 'Create an account-and-assets checklist covering Instagram, Facebook Page, ad account, billing and permissions.',
      lessons: [
        { title: 'Professional Instagram account setup', brief: 'Prepare the profile, category, contact information and business identity that customers will see after clicking an ad.', action: 'Audit your bio, profile photo, contact buttons and link destination.' },
        { title: 'Connect Meta business assets', brief: 'Understand the relationship between Instagram, Facebook Page, Business Portfolio and ad account.', action: 'Document which account owns each asset.' },
        { title: 'Security and billing readiness', brief: 'Set up two-factor authentication, billing access and recovery options before spending.', action: 'Enable 2FA and document who can edit billing.' },
      ],
      question: { prompt: 'What is the safest team-access approach?', choices: ['Share one password', 'Give everyone admin', 'Give each person only the permissions they need'], answer: 2, explanation: 'Least-privilege access limits damage from mistakes or compromised accounts.' },
    },
    {
      title: 'Offer and audience research',
      intro: 'Targeting cannot rescue an unclear offer. Research the customer first, then build the message.',
      principles: ['Use customer language from real conversations and reviews.', 'Turn features into outcomes and proof.', 'Use competitor research to find patterns, not copy ads.'],
      mistakes: ['Choosing interests before understanding the buyer.', 'Copying competitor creative word-for-word.'],
      deliverable: 'Create a one-page audience sheet with pains, desired outcomes, objections, proof and five competitor patterns.',
      lessons: [
        { title: 'Customer language research', brief: 'Collect exact phrases customers use when describing the problem, desired outcome and objections.', action: 'Collect 15 customer phrases from comments, chats, reviews or interviews.' },
        { title: 'Build the offer', brief: 'Combine product, promise, proof, price context and CTA into an offer a viewer understands quickly.', action: 'Rewrite your offer in one sentence and one 15-second pitch.' },
        { title: 'Instagram competitor research', brief: 'Study active ads, Reels and landing-page patterns without cloning another brand.', action: 'Save five creative patterns and explain the hypothesis behind each.' },
      ],
      question: { prompt: 'What should come before detailed targeting?', choices: ['Customer and offer research', 'Duplicating ad sets', 'Increasing the budget'], answer: 0, explanation: 'Research gives the campaign a relevant offer and message. Targeting settings come after that.' },
    },
    {
      title: 'Campaign objectives and structure',
      intro: 'A simple structure makes it easier to know what is working and what should change.',
      principles: ['Match the objective to the real business action.', 'Know what belongs at campaign, ad set and ad level.', 'Avoid unnecessary fragmentation.'],
      mistakes: ['Optimizing for traffic when the goal is purchase without a clear reason.', 'Creating many small ad sets with too little budget.'],
      deliverable: 'Draw one Instagram campaign with objective, audiences, placements and three creative concepts.',
      lessons: [
        { title: 'Choose the right objective', brief: 'Compare Awareness, Traffic, Engagement, Leads, App promotion and Sales against the outcome you need.', action: 'Choose the objective for one offer and explain why it matches the desired action.' },
        { title: 'Campaign, ad set and ad hierarchy', brief: 'Learn where budget, audience, placement and creative decisions belong.', action: 'Sketch the hierarchy of your next campaign.' },
        { title: 'When to consolidate', brief: 'Recognize when too many ad sets are starving learning and making results harder to interpret.', action: 'Remove one unnecessary split from your draft structure.' },
      ],
      question: { prompt: 'Where are placements normally controlled?', choices: ['At the ad set level', 'Only in the Instagram profile', 'Inside the product catalog'], answer: 0, explanation: 'Placements are generally configured at the ad set level in Meta Ads Manager.' },
    },
    {
      title: 'Instagram audiences',
      intro: 'Audience strategy should express a testable hypothesis rather than a random list of interests.',
      principles: ['Broad targeting can work when signals and creative are strong.', 'Interest targeting should remain coherent.', 'Custom and lookalike quality depends on source data quality.'],
      mistakes: ['Stacking unrelated interests.', 'Retargeting people who already purchased as if they were cold traffic.'],
      deliverable: 'Prepare one broad, one interest and one warm-audience hypothesis.',
      lessons: [
        { title: 'Broad targeting', brief: 'Understand when Instagram can rely more heavily on conversion signals and creative to find buyers.', action: 'Write the conditions that would make you test broad targeting.' },
        { title: 'Interest and demographic targeting', brief: 'Build focused audiences that reflect a clear customer hypothesis.', action: 'Create one focused interest audience and write why each interest belongs.' },
        { title: 'Custom and lookalike audiences', brief: 'Use site visitors, engagers, customer lists and quality source audiences responsibly.', action: 'List every first-party audience source you currently own.' },
      ],
      question: { prompt: 'What makes a lookalike source more useful?', choices: ['Quality and relevance of the source data', 'More random interests', 'A longer ad caption'], answer: 0, explanation: 'Lookalike audiences inherit signal from the source; poor source quality produces weaker similarity.' },
    },
    {
      title: 'Instagram placements: Feed, Stories and Reels',
      intro: 'The same offer needs different visual execution across Instagram surfaces.',
      principles: ['Feed rewards quick comprehension and strong hierarchy.', 'Stories and Reels need vertical mobile-first creative.', 'Placement decisions should follow evidence.'],
      mistakes: ['Using one horizontal asset everywhere.', 'Excluding placements only because you personally dislike them.'],
      deliverable: 'Adapt one offer into Feed, Story and Reel creative plans.',
      lessons: [
        { title: 'Instagram Feed ads', brief: 'Design for fast comprehension using 1:1 or 4:5 creative, clear product focus and readable copy.', action: 'Storyboard one 4:5 Feed ad with hook, proof and CTA.' },
        { title: 'Instagram Stories ads', brief: 'Use 9:16 framing, safe zones, fast pacing and a direct CTA for full-screen viewing.', action: 'Create a three-frame Story sequence.' },
        { title: 'Instagram Reels ads', brief: 'Use native-feeling 9:16 video, audio, captions and an immediate opening that earns attention.', action: 'Write a 15-second Reel ad script with a two-second hook.' },
      ],
      question: { prompt: 'What is a strong default creative format for Reels?', choices: ['9:16 vertical video', 'Wide desktop banner', 'Long PDF'], answer: 0, explanation: 'Reels is an immersive vertical placement. Meta recommends mobile-native vertical creative for the experience.' },
    },
    {
      title: 'Creative strategy and hooks',
      intro: 'Creative is the part of the campaign the customer actually experiences. Build concepts you can test, not just pretty graphics.',
      principles: ['Separate customer angle from execution.', 'Test meaningful concepts before tiny variations.', 'Make the first seconds visually and verbally clear.'],
      mistakes: ['Changing everything at once.', 'Assuming a polished ad will outperform a clear one.'],
      deliverable: 'Create six distinct Instagram ad concepts with angle, hook, proof and CTA.',
      lessons: [
        { title: 'Hooks that earn attention', brief: 'Use specificity, tension, relevance, novelty or demonstration to make the opening worth watching.', action: 'Write 20 hooks for one offer.' },
        { title: 'Angles and concepts', brief: 'Build ads around different customer motivations rather than only changing colors.', action: 'Create five concept directions for the same offer.' },
        { title: 'Instagram ad copy', brief: 'Write concise primary text, headlines and CTAs that match customer awareness.', action: 'Write short, medium and long copy versions.' },
      ],
      question: { prompt: 'Which test teaches you more?', choices: ['Five genuinely different concepts', 'Five identical ads with different button colors', 'No written hypothesis'], answer: 0, explanation: 'Meaningfully different concepts help identify which customer angle is creating the response.' },
    },
    {
      title: 'Reels advertising system',
      intro: 'Reels needs native pacing, safe-zone awareness and a reason to keep watching.',
      principles: ['Front-load the hook.', 'Use on-screen text and captions for comprehension.', 'Build native-feeling creative instead of simply resizing Feed ads.'],
      mistakes: ['Long introductions before the value appears.', 'Placing important text under interface controls.'],
      deliverable: 'Produce one 15-30 second Reel ad with hook, demonstration, proof and CTA.',
      lessons: [
        { title: 'Reel script structure', brief: 'Use hook, problem, demonstration, proof and CTA to maintain momentum.', action: 'Write a 20-second Reel script.' },
        { title: 'Phone-first production', brief: 'Improve lighting, framing, audio and editing with a smartphone.', action: 'Record one raw vertical take using your script.' },
        { title: 'Safe zones and captions', brief: 'Keep critical text away from Instagram interface areas and make the ad understandable without perfect audio.', action: 'Review your video and reposition any blocked text.' },
      ],
      question: { prompt: 'Why use captions on Reels ads?', choices: ['They help comprehension when audio is low or off', 'They increase the ad account limit', 'They replace tracking'], answer: 0, explanation: 'Captions improve message comprehension in sound-off or noisy viewing conditions.' },
    },
    {
      title: 'Story advertising system',
      intro: 'Stories are fast, full-screen and sequential. Use them to create momentum.',
      principles: ['Use one idea per frame.', 'Keep text large and readable.', 'Make the CTA obvious before the viewer taps away.'],
      mistakes: ['Overloading one frame with paragraphs.', 'Using tiny desktop-sized text.'],
      deliverable: 'Build a three-frame Story campaign sequence with a clear CTA.',
      lessons: [
        { title: 'Frame one: stop the tap', brief: 'Use a strong visual, question or outcome to earn the next second.', action: 'Create five first-frame concepts.' },
        { title: 'Frame two: prove the claim', brief: 'Use demonstration, testimonial, feature proof or process to build trust.', action: 'Choose one proof format and storyboard it.' },
        { title: 'Frame three: make the next step clear', brief: 'End with one CTA and destination aligned with the campaign objective.', action: 'Write the final CTA and landing/message transition.' },
      ],
      question: { prompt: 'What is the best reason to use multiple Story frames?', choices: ['To sequence attention, proof and action', 'To hide the CTA', 'To avoid a campaign objective'], answer: 0, explanation: 'Sequential frames can move the viewer through hook, proof and CTA while keeping each screen simple.' },
    },
    {
      title: 'Lead, message and sales funnels',
      intro: 'Instagram ads are only one step. The handoff to form, DM, WhatsApp or landing page must continue the same promise.',
      principles: ['Ad promise and destination should match.', 'Qualify leads without adding unnecessary friction.', 'Fast follow-up protects campaign economics.'],
      mistakes: ['Sending every click to a generic home page.', 'Ignoring lead response time.'],
      deliverable: 'Build one complete Instagram-to-lead or Instagram-to-message funnel.',
      lessons: [
        { title: 'Instant forms and lead quality', brief: 'Balance lead volume with useful qualification questions.', action: 'Write five questions that improve lead quality.' },
        { title: 'DM and WhatsApp handoff', brief: 'Design the opening message and next steps after a person clicks to chat.', action: 'Write the first four replies in your sales conversation.' },
        { title: 'Landing-page continuity', brief: 'Keep headline, proof, offer and CTA consistent from ad to page.', action: 'Compare your ad promise to your landing-page headline.' },
      ],
      question: { prompt: 'What can make cheap leads expensive?', choices: ['Poor follow-up and weak qualification', 'A clear CTA', 'Tracking the source'], answer: 0, explanation: 'Low CPL is not enough if the lead process fails after acquisition.' },
    },
    {
      title: 'Tracking and measurement',
      intro: 'Measurement helps you separate creative problems from funnel problems.',
      principles: ['Map events before launching.', 'Use business records as a revenue source of truth.', 'Understand attribution as useful evidence, not perfect certainty.'],
      mistakes: ['Installing tracking but never testing events.', 'Relying only on impressions to judge success.'],
      deliverable: 'Create an event map and reporting sheet for your campaign.',
      lessons: [
        { title: 'Pixel event concepts', brief: 'Understand events such as ViewContent, AddToCart, Lead and Purchase.', action: 'Map the events for a sample ecommerce funnel.' },
        { title: 'Conversions API concepts', brief: 'Understand why server-side signals and deduplication matter.', action: 'List the events your backend should send.' },
        { title: 'Attribution and reporting', brief: 'Compare Ads Manager results with your own sales or lead records.', action: 'Define your business source of truth.' },
      ],
      question: { prompt: 'What should you compare Meta reporting against?', choices: ['Your business records', 'Only follower count', 'Only comments'], answer: 0, explanation: 'Business records help validate whether attributed conversions represent real outcomes.' },
    },
    {
      title: 'Budgets and bidding',
      intro: 'A useful budget gives the campaign enough opportunity to test the hypothesis without ignoring your economics.',
      principles: ['Base test budgets on target CPA and learning needs.', 'Choose campaign or ad-set budget intentionally.', 'Use bid controls only when you understand the trade-off.'],
      mistakes: ['Choosing a random round number.', 'Restricting delivery with aggressive controls too early.'],
      deliverable: 'Create a seven-day Instagram test budget with target CPA and stop rules.',
      lessons: [
        { title: 'Test budget planning', brief: 'Estimate the spend needed to observe enough target actions for a useful decision.', action: 'Calculate a seven-day budget from target CPA.' },
        { title: 'Campaign vs ad-set budget', brief: 'Decide whether Meta or you should control spend allocation during the test.', action: 'Choose one budget structure and document why.' },
        { title: 'Bid and cost controls', brief: 'Understand when controls can help and when they reduce delivery.', action: 'Write the condition that would justify using a bid control.' },
      ],
      question: { prompt: 'What should influence a test budget?', choices: ['Target CPA and needed conversion opportunities', 'Competitor follower count', 'How many colors are in the ad'], answer: 0, explanation: 'Budget should relate to the action being measured and the economics of that action.' },
    },
    {
      title: 'Testing and optimization',
      intro: 'Optimization is a diagnosis process, not a sequence of random edits.',
      principles: ['Read delivery, attention, click, conversion and economics in order.', 'Define the hypothesis before the test.', 'Record results and the next decision.'],
      mistakes: ['Editing several variables at once.', 'Stopping ads after a few hours without enough evidence.'],
      deliverable: 'Create a testing log and decision rules for your next 12 creatives.',
      lessons: [
        { title: 'Diagnose the funnel', brief: 'Use CPM, CTR, CPC, CVR and CPA to identify where performance is breaking down.', action: 'Create a diagnosis checklist.' },
        { title: 'Creative test matrix', brief: 'Plan concept, hook, format and offer tests in a trackable matrix.', action: 'Build a 12-creative test matrix.' },
        { title: 'Decision windows and stop rules', brief: 'Predefine what evidence means stop, continue or scale.', action: 'Write your stop, continue and scale rules before launch.' },
      ],
      question: { prompt: 'Why write stop rules before launch?', choices: ['To reduce emotional decision-making', 'To guarantee profit', 'To remove the need for tracking'], answer: 0, explanation: 'Predefined rules help you make consistent decisions when money is being spent.' },
    },
    {
      title: 'Retargeting and scaling',
      intro: 'Retargeting responds to demonstrated intent; scaling expands what is already economically sound.',
      principles: ['Segment warm audiences by behavior.', 'Change the message as intent increases.', 'Scale contribution profit, not vanity metrics.'],
      mistakes: ['Showing the same ad forever.', 'Doubling budget repeatedly without watching marginal CPA.'],
      deliverable: 'Build a warm-audience ladder and four scale levers.',
      lessons: [
        { title: 'Instagram warm audiences', brief: 'Use video viewers, profile engagers, website visitors and customer lists with appropriate windows.', action: 'Create 7-day and 30-day warm-audience plans.' },
        { title: 'Message sequencing', brief: 'Move from education to proof to urgency as customer intent increases.', action: 'Write cold, warm and hot versions of one message.' },
        { title: 'Vertical and horizontal scaling', brief: 'Increase budget or expand concepts, audiences, offers and geographies while protecting economics.', action: 'Choose four scale levers and their stop conditions.' },
      ],
      question: { prompt: 'What should be protected while scaling?', choices: ['Contribution profit and acceptable CPA', 'Only total impressions', 'Only follower count'], answer: 0, explanation: 'Scaling is valuable when additional spend still produces acceptable business economics.' },
    },
    {
      title: 'Policy, capstone and 90-day operating plan',
      intro: 'Finish by turning the course into a repeatable operating system with policy review, a complete campaign and weekly execution rhythm.',
      principles: ['Review Meta advertising standards before launch.', 'Build the capstone from research through tracking and economics.', 'Schedule recurring creative production and review.'],
      mistakes: ['Making unsupported claims in ads.', 'Finishing the course without building a campaign plan.'],
      deliverable: 'Complete a full Instagram campaign plan and a 90-day research, production, launch and optimization schedule.',
      lessons: [
        { title: 'Advertising policy review', brief: 'Check claims, restricted categories, landing-page quality and account health before publishing.', action: 'Run a policy review on your strongest concept.' },
        { title: 'Capstone campaign', brief: 'Combine offer, audience, three placements, six creatives, budget, tracking and decision rules.', action: 'Complete the campaign planner and save the final version.' },
        { title: '90-day operating rhythm', brief: 'Turn research, creative production, testing and reporting into a weekly routine.', action: 'Schedule your next four creative drops and review dates.' },
      ],
      question: { prompt: 'What makes the capstone useful?', choices: ['It connects research, creative, tracking and economics', 'It guarantees sales', 'It removes the need to test'], answer: 0, explanation: 'The capstone proves you can connect the moving parts into a repeatable decision process.' },
    },
  ],
  videos: [
    {
      module: 0,
      title: 'Nigeria: Instagram Ads Step-by-Step',
      url: 'https://www.youtube.com/watch?v=haUZvNZWae0',
      description: 'Nigeria-focused English walkthrough dedicated to creating and running Instagram advertising for a local business context.',
      region: 'Nigeria • English • Instagram Ads',
    },
    {
      module: 1,
      title: 'How to Run Instagram Ads for Business in Nigeria',
      url: 'https://www.youtube.com/watch?v=jyyktM88Rb4',
      description: 'Chinedu Paul Nnamani demonstrates an Instagram-only campaign workflow for Nigerian businesses: account setup, objectives, audience, budget, Instagram placements, creative and performance review.',
      region: 'Nigeria • English • Instagram Business Ads',
    },
    {
      module: 3,
      title: 'The BEST Instagram Ads Tutorial for Beginners in 2026',
      url: 'https://www.youtube.com/watch?v=q7W4hgLb2mE',
      description: 'Ben Heath gives a current English Instagram Ads tutorial focused on campaign setup, creative, targeting and practical optimization for Instagram advertising.',
      region: 'UK/International • English • 2026',
    },
    {
      module: 5,
      title: 'Instagram Ads 2025: Complete Instagram Campaign Setup',
      url: 'https://www.youtube.com/watch?v=CL1w2o2BJsU',
      description: 'A step-by-step Instagram advertising walkthrough covering account connection, objectives, targeting, image/Reels creative, tracking and optimization.',
      region: 'English • Instagram Ads • Step-by-step',
    },
    {
      module: 5,
      title: 'Instagram Engagement Ads — Step-by-Step 2026',
      url: 'https://www.youtube.com/watch?v=3MO_BAoNIPM',
      description: 'Instagram-specific tutorial showing how to structure an engagement campaign, choose Instagram placements, control audience and budget, and avoid common setup mistakes.',
      region: 'English • 2026 • Instagram Engagement',
    },
  ],
  visuals: [
    {
      title: 'Instagram app on smartphone',
      imageUrl: 'https://images.pexels.com/photos/27552013/pexels-photo-27552013/free-photo-of-instagram-on-a-smartphone-with-the-instagram-app-open.jpeg?auto=compress&dpr=1&h=750&w=1260',
      sourceUrl: 'https://www.pexels.com/photo/instagram-on-a-smartphone-with-the-instagram-app-open-27552013/',
      sourceLabel: 'Pexels stock photo',
      caption: 'A real mobile Instagram screen reference for thinking about how ads, profiles and content appear in a customer’s hand.',
    },
    {
      title: 'Instagram profile on a phone',
      imageUrl: 'https://images.pexels.com/photos/15226554/pexels-photo-15226554/free-photo-of-instagram-on-smartphone.jpeg?auto=compress&dpr=1&h=750&w=1260',
      sourceUrl: 'https://www.pexels.com/photo/instagram-on-smartphone-15226554/',
      sourceLabel: 'Pexels stock photo',
      caption: 'Use this kind of phone-screen reference when auditing profile credibility after a customer clicks an ad.',
    },
    {
      title: 'Social media apps on smartphone',
      imageUrl: 'https://images.pexels.com/photos/15406294/pexels-photo-15406294/free-photo-of-close-up-of-a-smartphone-screen-displaying-social-media-app-folder.jpeg?auto=compress&dpr=1&h=750&w=1260',
      sourceUrl: 'https://www.pexels.com/photo/close-up-of-a-smartphone-screen-displaying-social-media-app-folder-15406294/',
      sourceLabel: 'Pexels stock photo',
      caption: 'A practical visual reminder that Instagram competes for attention among many apps on the same mobile screen.',
    },
    {
      title: 'Instagram feed browsing demonstration',
      imageUrl: 'https://images.pexels.com/photos/27552013/pexels-photo-27552013/free-photo-of-instagram-on-a-smartphone-with-the-instagram-app-open.jpeg?auto=compress&dpr=1&h=750&w=1260',
      videoUrl: 'https://videos.pexels.com/video-files/4199353/4199353-uhd_3840_2160_25fps.mp4',
      sourceUrl: 'https://www.pexels.com/video/close-up-shot-of-a-smartphone-4199353/',
      sourceLabel: 'Pexels stock video',
      caption: 'Stock demonstration of a person browsing an Instagram feed. Use it to study thumb-stop behavior and the small amount of time an ad gets to communicate.',
    },
    {
      title: 'Instagram sales-post browsing demonstration',
      imageUrl: 'https://images.pexels.com/photos/27552013/pexels-photo-27552013/free-photo-of-instagram-on-a-smartphone-with-the-instagram-app-open.jpeg?auto=compress&dpr=1&h=750&w=1260',
      videoUrl: 'https://videos.pexels.com/video-files/6115070/6115070-uhd_2160_4096_25fps.mp4',
      sourceUrl: 'https://www.pexels.com/video/sales-posting-on-instagram-6115070/',
      sourceLabel: 'Pexels stock video',
      caption: 'Vertical stock footage of social-media shopping/browsing, useful when planning mobile sales creative and Reels/Story framing.',
    },
  ],
  references: [
    {
      label: 'Meta for Business — Reels Ads',
      url: 'https://www.facebook.com/business/ads/facebook-instagram-reels-ads',
      summary: 'Official Meta guidance for Facebook and Instagram Reels ads, placements, creative and A/B testing.',
      points: ['Use vertical creative.', 'Keep important elements in safe zones.', 'Test and learn.'],
    },
    {
      label: 'Meta Ad Library',
      url: 'https://www.facebook.com/ads/library/',
      summary: 'Official ad-transparency library for studying active advertising patterns.',
      points: ['Search advertisers.', 'Record hooks and formats.', 'Turn observations into hypotheses.'],
    },
    {
      label: 'Pexels — Instagram Story stock video',
      url: 'https://www.pexels.com/video/posting-the-business-products-on-instagram-story-7308040/',
      summary: 'Free stock video showing a product being prepared for an Instagram Story.',
      points: ['Visual reference for Story creative.', 'Useful production inspiration.', 'Check Pexels license before redistribution.'],
    },
  ],
  downloads: [],
};

export default function CourseInstagramAdsPage() {
  return <PremiumCourseLearningPage config={config} />;
}
