import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '003',
  slug: 'whatsapp-marketing-sales-mastery-2026',
  title: 'WhatsApp Marketing & Sales Mastery 2026',
  subtitle: 'Business Setup • Catalog • Status • Broadcasts • Follow-ups • Closing',
  promise: 'Turn WhatsApp Business into a structured sales channel for a Nigerian or international small business. Learn how to set up the account, build a catalog, attract leads, organize conversations, follow up responsibly, close sales and retain customers without turning your business into spam.',
  accent: 'whatsapp',
  modules: [
    {
      title: 'WhatsApp Business foundations',
      intro: 'WhatsApp becomes useful for business when conversations are organized around a customer journey instead of random replies.',
      principles: ['Use WhatsApp Business for a defined sales or service process.', 'Make the next customer action obvious.', 'Treat trust and response quality as part of marketing.'],
      mistakes: ['Using a personal account with no business information.', 'Sending messages without a clear purpose or customer context.'],
      deliverable: 'Write the role WhatsApp will play in your business: lead capture, sales, support, retention or a combination.',
      lessons: [
        { title: 'What WhatsApp marketing is', brief: 'Understand WhatsApp as a conversational sales channel rather than a place to blast messages.', action: 'Write the three most common customer conversations your business needs to handle.' },
        { title: 'Customer journey on WhatsApp', brief: 'Map discovery, first message, qualification, offer, objection, payment and follow-up.', action: 'Draw the journey from first contact to repeat purchase.' },
        { title: 'Metrics that matter', brief: 'Track response time, qualified conversations, close rate, average order value and repeat sales.', action: 'Choose five metrics you can record every week.' },
      ],
      question: { prompt: 'What makes WhatsApp useful as a sales channel?', choices: ['Structured conversations tied to customer intent', 'Sending the same message to everyone', 'Ignoring response time'], answer: 0, explanation: 'WhatsApp works best when conversations are organized around what the customer needs and the next business action.' },
    },
    {
      title: 'Professional business profile setup',
      intro: 'Your business profile is the trust layer customers see before they decide whether to continue a conversation.',
      principles: ['Use a recognizable business name and profile image.', 'Add accurate contact and business information.', 'Keep support details and operating expectations clear.'],
      mistakes: ['Using incomplete or misleading business information.', 'Mixing several unrelated businesses into one profile.'],
      deliverable: 'Complete a professional WhatsApp Business profile audit.',
      lessons: [
        { title: 'Create the business profile', brief: 'Set business name, category, description, hours and contact details.', action: 'Complete every relevant profile field.' },
        { title: 'Profile photo and brand consistency', brief: 'Use the same recognizable brand identity customers see on your website and social media.', action: 'Compare your WhatsApp profile with your Instagram/Facebook identity.' },
        { title: 'Trust and support information', brief: 'Make it easy for customers to know who they are talking to and where to get help.', action: 'Write a concise business description and support statement.' },
      ],
      question: { prompt: 'Why should business contact information be complete?', choices: ['It helps customers verify and trust the business', 'It increases phone battery life', 'It replaces follow-up'], answer: 0, explanation: 'Complete business information reduces uncertainty and supports a more credible customer experience.' },
    },
    {
      title: 'Catalogs and product presentation',
      intro: 'A catalog reduces repetitive selling and gives customers a cleaner way to understand products before asking questions.',
      principles: ['Use clear product names and current prices.', 'Use good product images and simple descriptions.', 'Organize catalog items around how customers shop.'],
      mistakes: ['Posting blurry images with no price.', 'Leaving unavailable products active for long periods.'],
      deliverable: 'Build or clean up a WhatsApp catalog with at least five properly presented items.',
      lessons: [
        { title: 'Create catalog items', brief: 'Add product image, title, price, description and useful links where available.', action: 'Create one complete catalog item as a quality standard.' },
        { title: 'Collections and organization', brief: 'Group products in ways customers naturally browse, such as category, use case or season.', action: 'Design three useful catalog collections.' },
        { title: 'Product image quality', brief: 'Use consistent lighting, backgrounds and angles so the catalog feels trustworthy.', action: 'Create a simple phone-photo checklist for every new product.' },
      ],
      question: { prompt: 'What makes a catalog easier to buy from?', choices: ['Clear images, price and concise description', 'No price and long voice notes', 'Unrelated products mixed together'], answer: 0, explanation: 'Clear product information reduces unnecessary questions and helps the buyer make a faster decision.' },
    },
    {
      title: 'Lead capture and entry points',
      intro: 'A WhatsApp sales system needs predictable ways for the right people to start conversations.',
      principles: ['Use click-to-chat links and QR codes intentionally.', 'Match the opening message to the source of the lead.', 'Track where conversations came from.'],
      mistakes: ['Sending every traffic source to a generic “Hi”.', 'Running traffic without knowing how leads will be handled.'],
      deliverable: 'Create three lead-entry paths and a different opening message for each.',
      lessons: [
        { title: 'Click-to-chat links', brief: 'Create links that open WhatsApp with useful pre-filled context.', action: 'Create one link for a product, one for support and one for a campaign.' },
        { title: 'QR codes and offline traffic', brief: 'Use QR codes on packaging, flyers, events and physical locations to start useful conversations.', action: 'Choose one offline touchpoint and define the message it should open.' },
        { title: 'Social-to-WhatsApp flow', brief: 'Connect Instagram, Facebook, TikTok or website traffic to a clear WhatsApp conversation.', action: 'Write the CTA and first reply for one social campaign.' },
      ],
      question: { prompt: 'Why use a pre-filled WhatsApp message?', choices: ['It gives context about what the lead wants', 'It guarantees a sale', 'It replaces customer service'], answer: 0, explanation: 'Pre-filled messages help the business know the campaign or intent behind the conversation.' },
    },
    {
      title: 'Labels and lightweight CRM',
      intro: 'Labels turn a crowded inbox into a simple sales pipeline.',
      principles: ['Label conversations by stage, not by random memory.', 'Keep the number of stages understandable.', 'Review the pipeline every day.'],
      mistakes: ['Using dozens of labels nobody understands.', 'Never moving customers between stages.'],
      deliverable: 'Create a five-to-seven-stage WhatsApp sales pipeline.',
      lessons: [
        { title: 'Design the label system', brief: 'Use stages such as New Lead, Qualified, Proposal Sent, Awaiting Payment, Customer and Follow-up.', action: 'Create your label list and define what each one means.' },
        { title: 'Daily pipeline routine', brief: 'Review conversations that need action instead of relying on unread messages.', action: 'Create a 15-minute daily follow-up routine.' },
        { title: 'Customer notes and context', brief: 'Store useful context without collecting information you do not need.', action: 'Define the minimum notes your sales process should keep.' },
      ],
      question: { prompt: 'What should a useful label represent?', choices: ['A clear customer or sales stage', 'A random emoji', 'The salesperson’s mood'], answer: 0, explanation: 'Labels work best when everyone understands what action belongs to each stage.' },
    },
    {
      title: 'Quick replies and service automation',
      intro: 'Automation should make responses faster without making customers feel ignored.',
      principles: ['Automate repetitive information, not empathy.', 'Keep quick replies short and editable.', 'Use greeting and away messages to set expectations.'],
      mistakes: ['Sending robotic walls of text.', 'Using automation to avoid answering real questions.'],
      deliverable: 'Create a library of 15 quick replies plus greeting and away messages.',
      lessons: [
        { title: 'Greeting and away messages', brief: 'Set a professional first response and a clear expectation when the team is unavailable.', action: 'Write one greeting and one away message in your brand voice.' },
        { title: 'Quick replies library', brief: 'Create reusable answers for price, delivery, payment, availability and FAQs.', action: 'Write 15 quick replies and organize them by shortcut.' },
        { title: 'When to hand over to a human', brief: 'Recognize questions, complaints and objections that require a real conversation.', action: 'List five situations that should never receive only an automated answer.' },
      ],
      question: { prompt: 'What is the best use of a quick reply?', choices: ['Repeated factual questions that still allow personalization', 'Every complaint', 'Every negotiation'], answer: 0, explanation: 'Quick replies save time on repeated information while leaving room to adapt to the customer.' },
    },
    {
      title: 'Broadcast marketing and consent',
      intro: 'Broadcasts can be useful for opted-in audiences, but careless mass messaging damages trust and may violate platform rules.',
      principles: ['Message people who have a legitimate reason to hear from the business.', 'Segment broadcasts by relevance.', 'Make it easy to stop receiving promotional messages.'],
      mistakes: ['Buying contact lists.', 'Sending the same promotion too frequently.'],
      deliverable: 'Create an opt-in plan, two broadcast segments and a four-week message calendar.',
      lessons: [
        { title: 'Build an opted-in audience', brief: 'Collect permission through customers, lead forms, events or explicit requests instead of scraping numbers.', action: 'Write the opt-in language you will use.' },
        { title: 'Segment before sending', brief: 'Group customers by interest, purchase history or stage so broadcasts remain relevant.', action: 'Create three practical broadcast segments.' },
        { title: 'Broadcast message structure', brief: 'Use context, value, one offer and one CTA instead of spammy message dumps.', action: 'Write one useful promotional broadcast and one educational broadcast.' },
      ],
      question: { prompt: 'What is the strongest foundation for promotional broadcasts?', choices: ['Relevant opt-in and segmentation', 'A purchased phone-number list', 'Sending as often as possible'], answer: 0, explanation: 'Permission and relevance protect customer trust and reduce spam complaints.' },
    },
    {
      title: 'WhatsApp Status marketing',
      intro: 'Status can keep the business visible without interrupting customers in direct chat.',
      principles: ['Mix proof, product, education and personality.', 'Use clear visual hierarchy and short text.', 'Create a consistent posting rhythm.'],
      mistakes: ['Posting only prices every day.', 'Using unreadable screenshots with too much text.'],
      deliverable: 'Create a seven-day Status content plan with four content types.',
      lessons: [
        { title: 'Status content pillars', brief: 'Use education, proof, behind-the-scenes, product and urgency in a balanced mix.', action: 'Choose four recurring Status pillars.' },
        { title: 'Status visual quality', brief: 'Use clear photos, simple layouts and readable text built for a phone screen.', action: 'Create three Status templates.' },
        { title: 'Status-to-chat CTA', brief: 'Turn passive views into conversation with a simple next step.', action: 'Write five CTAs that invite a relevant reply.' },
      ],
      question: { prompt: 'Why mix content types in Status?', choices: ['To build trust and interest instead of posting only promotions', 'To make text smaller', 'To avoid customer questions'], answer: 0, explanation: 'A balanced mix keeps the business useful and visible without every post feeling like a sales push.' },
    },
    {
      title: 'Sales scripts and qualification',
      intro: 'A sales script is a flexible conversation map, not a copy-paste speech.',
      principles: ['Ask useful questions before recommending.', 'Confirm the customer’s goal and constraint.', 'Keep the conversation moving toward one next step.'],
      mistakes: ['Sending the entire price list before understanding the request.', 'Arguing with objections.'],
      deliverable: 'Create one sales conversation script from opening to close.',
      lessons: [
        { title: 'Opening the conversation', brief: 'Acknowledge the customer’s message and ask the first useful qualifying question.', action: 'Write three opening replies for different lead sources.' },
        { title: 'Qualification questions', brief: 'Learn what to ask about budget, need, timing, size, quantity or use case without interrogating the buyer.', action: 'Write five qualification questions for your business.' },
        { title: 'Recommend instead of overwhelm', brief: 'Use the customer’s answers to suggest a small number of relevant options.', action: 'Create a recommendation script for three common customer types.' },
      ],
      question: { prompt: 'What should happen before a strong recommendation?', choices: ['Useful qualification', 'Sending every product', 'Ignoring the customer’s goal'], answer: 0, explanation: 'Qualification helps you recommend based on the customer rather than pushing a generic offer.' },
    },
    {
      title: 'Objection handling and closing',
      intro: 'Objections are information. Handle them calmly, clarify the real concern and make the next step easy.',
      principles: ['Acknowledge before answering.', 'Use evidence and alternatives instead of pressure.', 'Clarify payment, delivery and next steps.'],
      mistakes: ['Arguing about price.', 'Using fake scarcity or unsupported promises.'],
      deliverable: 'Create responses for your five most common objections and a clean closing sequence.',
      lessons: [
        { title: 'Price objections', brief: 'Separate price from value, budget fit and product choice.', action: 'Write three responses to “too expensive” without discounting immediately.' },
        { title: 'Trust and proof objections', brief: 'Use real policies, testimonials, process and product information to reduce uncertainty.', action: 'List the proof assets you can send legitimately.' },
        { title: 'Ask for the order', brief: 'Make payment and fulfillment steps simple once the customer is ready.', action: 'Write your exact closing message and payment instructions.' },
      ],
      question: { prompt: 'What is a better first response to an objection?', choices: ['Clarify the concern and answer it', 'Argue immediately', 'Create fake urgency'], answer: 0, explanation: 'Clarifying the objection helps you solve the real concern instead of guessing.' },
    },
    {
      title: 'Follow-up without becoming spam',
      intro: 'Many sales need more than one conversation. Follow-up should add context or value instead of repeating “are you buying?”',
      principles: ['Follow up because there is a reason.', 'Use timing that matches the purchase decision.', 'Stop when the customer opts out or the conversation is no longer relevant.'],
      mistakes: ['Following up every few hours.', 'Repeating the same message with no new value.'],
      deliverable: 'Create a seven-day follow-up sequence for one offer.',
      lessons: [
        { title: 'Follow-up timing', brief: 'Choose intervals based on urgency, product type and the customer’s stated timeline.', action: 'Define your follow-up schedule for hot, warm and long-term leads.' },
        { title: 'Value-based follow-up', brief: 'Add answers, proof, reminders or relevant alternatives instead of pressure.', action: 'Write four follow-up messages that each add something new.' },
        { title: 'When to stop', brief: 'Respect opt-outs and recognize when continued contact damages trust.', action: 'Write a polite final follow-up and opt-out acknowledgement.' },
      ],
      question: { prompt: 'What makes a follow-up useful?', choices: ['It adds relevant value or context', 'It repeats the same pressure message', 'It ignores opt-out requests'], answer: 0, explanation: 'A good follow-up gives the customer a reason to re-engage and respects their choice.' },
    },
    {
      title: 'Retention, referrals and repeat sales',
      intro: 'The cheapest next sale often comes from customers who already trust the business.',
      principles: ['Follow up after delivery.', 'Use purchase history to make relevant repeat offers.', 'Ask for reviews or referrals at the right moment.'],
      mistakes: ['Disappearing after payment.', 'Sending unrelated promotions to every past customer.'],
      deliverable: 'Build a 30-day customer retention and referral flow.',
      lessons: [
        { title: 'Post-purchase follow-up', brief: 'Confirm delivery, satisfaction and any support needed after the sale.', action: 'Write a three-step post-purchase sequence.' },
        { title: 'Repeat-purchase campaigns', brief: 'Use timing and purchase history to create relevant reorder or cross-sell messages.', action: 'Choose one repeat offer and define the right timing.' },
        { title: 'Reviews and referrals', brief: 'Ask satisfied customers for feedback or introductions without making the request awkward.', action: 'Write your review and referral requests.' },
      ],
      question: { prompt: 'When is a good time to ask for a review?', choices: ['After the customer has received value', 'Before delivering anything', 'During a complaint'], answer: 0, explanation: 'A review request is strongest after the customer has had a fair chance to experience the product or service.' },
    },
    {
      title: 'Click-to-WhatsApp ads and traffic',
      intro: 'Ads can create conversations, but the chat experience determines whether those conversations become useful leads.',
      principles: ['Match the ad promise to the first chat message.', 'Use campaign context to qualify quickly.', 'Measure lead quality and close rate, not only cost per message.'],
      mistakes: ['Using a generic opening for every campaign.', 'Optimizing for cheap chats with no sales process.'],
      deliverable: 'Build one click-to-WhatsApp funnel from ad to conversation to follow-up.',
      lessons: [
        { title: 'Ad-to-chat continuity', brief: 'Keep the same offer, proof and next step from the ad into the WhatsApp conversation.', action: 'Write the ad CTA and first automated/manual reply as one sequence.' },
        { title: 'Campaign-specific opening messages', brief: 'Use pre-filled context so the team knows what the lead saw and wants.', action: 'Create three campaign-specific opening messages.' },
        { title: 'Measure lead quality', brief: 'Track qualified chats, close rate, revenue and response time alongside cost per conversation.', action: 'Create a weekly click-to-WhatsApp scorecard.' },
      ],
      question: { prompt: 'What should you measure beyond cost per message?', choices: ['Lead quality and close rate', 'Only emoji reactions', 'Only profile views'], answer: 0, explanation: 'Cheap conversations are not valuable if they never become qualified leads or customers.' },
    },
    {
      title: 'Team workflows, scale and automation',
      intro: 'As message volume grows, ownership and process matter more than clever scripts.',
      principles: ['Define who owns each conversation stage.', 'Use templates and automation without losing human judgment.', 'Escalate complex cases clearly.'],
      mistakes: ['Two team members replying to the same customer with conflicting answers.', 'Automating complaints or sensitive issues blindly.'],
      deliverable: 'Create a team response SOP and escalation map.',
      lessons: [
        { title: 'Conversation ownership', brief: 'Assign leads, define handoffs and prevent duplicate replies.', action: 'Write a simple ownership rule for new, active and escalated chats.' },
        { title: 'Standard operating procedures', brief: 'Document pricing, refunds, delivery, tone and approval rules so the team stays consistent.', action: 'Create a one-page WhatsApp sales SOP.' },
        { title: 'Business Platform and API concepts', brief: 'Understand when growing teams may need the WhatsApp Business Platform or approved tools instead of relying only on the app.', action: 'List the scale signals that would justify evaluating a more advanced setup.' },
      ],
      question: { prompt: 'What should happen before adding more automation?', choices: ['Define the process and ownership clearly', 'Remove all human review', 'Send more messages'], answer: 0, explanation: 'Automation works best when it supports a process that is already understood.' },
    },
    {
      title: 'Policy, capstone and 90-day sales system',
      intro: 'Finish by combining profile, catalog, leads, broadcasts, scripts, follow-up and measurement into a responsible operating system.',
      principles: ['Follow WhatsApp Business messaging and commerce policies.', 'Respect customer choice and privacy.', 'Review the system weekly and improve weak stages.'],
      mistakes: ['Using scraped contact lists.', 'Selling prohibited products through commerce features.'],
      deliverable: 'Complete a full WhatsApp sales system and a 90-day operating calendar.',
      lessons: [
        { title: 'Messaging and commerce policy', brief: 'Understand quality expectations, customer support information, prohibited content and commerce restrictions.', action: 'Review your messages, catalog and opt-in process against policy.' },
        { title: 'Capstone sales system', brief: 'Combine profile, catalog, labels, scripts, broadcasts, Status, follow-up and metrics.', action: 'Complete the WhatsApp Sales Planner and save your final workflow.' },
        { title: '90-day operating rhythm', brief: 'Create weekly routines for Status, broadcast planning, pipeline review, follow-up and retention.', action: 'Schedule the next four weeks and define what you will review every Friday.' },
      ],
      question: { prompt: 'What protects a long-term WhatsApp sales channel?', choices: ['Relevant messaging, consent and policy compliance', 'Scraped contact lists', 'Constant promotional blasts'], answer: 0, explanation: 'Trust, relevance and policy compliance support a healthier customer channel over time.' },
    },
  ],
  videos: [
    {
      module: 0,
      title: 'Nigeria: Complete WhatsApp Marketing for Business Training',
      url: 'https://www.youtube.com/watch?v=pD5aXXTfTF4',
      description: 'A Nigeria-focused WhatsApp marketing training reference for local business context.',
      region: 'Nigeria • English',
    },
    {
      module: 1,
      title: 'WhatsApp Business Complete Guide for Entrepreneurs',
      url: 'https://www.youtube.com/watch?v=XboSEL5o05A',
      description: 'A step-by-step English tutorial covering profile setup, catalogs, automated messages, quick replies and labels.',
      region: 'International • English',
    },
    {
      module: 8,
      title: 'Nigeria: WhatsApp Marketing Strategy',
      url: 'https://www.youtube.com/watch?v=sz54BzLNdPs',
      description: 'A Nigerian creator explains lead generation, follow-up, customer experience, relevant offers and WhatsApp sales strategy. Treat earnings claims as personal examples, not guarantees.',
      region: 'Nigeria • English',
    },
  ],
  visuals: [
    {
      title: 'WhatsApp on a smartphone',
      imageUrl: 'https://images.pexels.com/photos/21792116/pexels-photo-21792116/free-photo-of-whatsapp-on-a-smartphone.jpeg?auto=compress&dpr=1&h=750&w=1260',
      sourceUrl: 'https://www.pexels.com/photo/whatsapp-on-a-smartphone-21792116/',
      sourceLabel: 'Pexels stock photo',
      caption: 'A direct visual reference for the mobile-first customer experience the course is designed around.',
    },
    {
      title: 'Small business owner handling customer communication',
      imageUrl: 'https://images.pexels.com/photos/10375889/pexels-photo-10375889.jpeg?auto=compress&dpr=1&h=750&w=1260',
      sourceUrl: 'https://www.pexels.com/photo/woman-working-on-laptop-on-window-sill-and-talking-on-phone-10375889/',
      sourceLabel: 'Pexels stock photo',
      caption: 'Customer conversations, laptop records and mobile communication often happen together in a small-business workflow.',
    },
  ],
  references: [
    {
      label: 'WhatsApp Business Messaging Policy',
      url: 'https://business.whatsapp.com/policy',
      summary: 'Official WhatsApp Business rules for creating quality customer experiences, messaging and commerce.',
      points: ['Keep support information accurate.', 'Respect policy and customer choice.', 'Follow commerce restrictions.'],
    },
    {
      label: 'Meta — Ads that click to WhatsApp',
      url: 'https://www.facebook.com/business/success/categories/ads-that-click-to-whatsapp',
      summary: 'Meta resource category for ads that start WhatsApp conversations.',
      points: ['Connect campaign promise to chat.', 'Measure conversation quality.', 'Use an intentional follow-up process.'],
    },
    {
      label: 'Pexels — small business product video',
      url: 'https://www.pexels.com/video/woman-taking-picture-of-the-cake-while-using-smartphone-7551831/',
      summary: 'Free stock video of an entrepreneur creating product content with a smartphone.',
      points: ['Useful product-content inspiration.', 'Shows phone-first selling workflow.', 'Check Pexels license before redistribution.'],
    },
  ],
  downloads: [
    { label: 'WhatsApp Sales Handbook', href: '/course-003-whatsapp-sales/WhatsApp_Marketing_Sales_Mastery_2026_Handbook.html', type: 'Offline handbook' },
    { label: 'Broadcast & Sales Planner', href: '/course-003-whatsapp-sales/WhatsApp_Sales_Broadcast_Planner_2026.csv', type: 'CSV workbook' },
    { label: 'WhatsApp Sales Checklist', href: '/course-003-whatsapp-sales/WhatsApp_Sales_Checklist.html', type: 'Checklist' },
    { label: 'Sales Scripts & Follow-up Matrix', href: '/course-003-whatsapp-sales/WhatsApp_Sales_Scripts_Matrix.csv', type: 'CSV template' },
  ],
};

export default function CourseWhatsAppMarketingPage() {
  return <PremiumCourseLearningPage config={config} />;
}
