import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '004',
  slug: 'tiktok-ads-organic-sales-mastery-2026',
  title: 'TikTok Ads & Organic Sales Mastery 2026',
  subtitle: 'Ads Manager • Creative • Organic Growth • TikTok Shop • Pixel • Scaling',
  promise: 'Build a complete TikTok customer-acquisition system using both paid ads and organic content. Learn account setup, billing, Pixel, campaign structure, creative research, hooks, Spark Ads, TikTok Shop, affiliate content, analytics and responsible scaling.',
  accent: 'instagram',
  modules: [
    {
      title: 'TikTok marketing foundations',
      intro: 'Start by separating the business goal from views. TikTok can create awareness, leads and sales, but the content and funnel must be built around a measurable outcome.',
      principles: ['Choose one primary business outcome.', 'Understand paid and organic as connected systems.', 'Treat attention as the beginning of the funnel, not the final result.'],
      mistakes: ['Chasing views with no commercial path.', 'Copying trends without knowing why they fit the offer.'],
      deliverable: 'Write one TikTok business goal, customer profile, offer and conversion action.',
      lessons: [
        { title: 'How TikTok creates demand', brief: 'Understand recommendation-driven discovery, native content behavior and why the strongest ads often resemble useful or entertaining TikToks.', action: 'Describe the exact action you want a viewer to take after watching your content.' },
        { title: 'Paid vs organic roles', brief: 'Use organic content to research angles and build trust while using Ads Manager to control distribution, targeting and measurement.', action: 'Map one offer into an organic discovery path and a paid acquisition path.' },
        { title: 'The TikTok customer journey', brief: 'Connect discovery, interest, profile/product research, click or Shop interaction, purchase and follow-up.', action: 'Draw your five-stage TikTok funnel.' },
      ],
      question: { prompt: 'What should come before choosing a campaign setting?', choices: ['A measurable business outcome', 'A random trending sound', 'A higher follower count'], answer: 0, explanation: 'The objective, content and measurement should all connect back to the business outcome.' },
    },
    {
      title: 'Business Center, Ads Manager and billing',
      intro: 'A clean business setup makes campaign management safer and easier to scale.',
      principles: ['Create the correct TikTok for Business and Ads Manager accounts.', 'Use Business Center when multiple people or assets need controlled access.', 'Understand the billing option assigned to the account before launch.'],
      mistakes: ['Sharing one login with a whole team.', 'Adding spend before confirming account ownership and payment settings.'],
      deliverable: 'Create an account map covering Business Center, Ads Manager, TikTok identity, website and billing owner.',
      lessons: [
        { title: 'Create Ads Manager correctly', brief: 'Set up the advertiser account, business information, timezone, currency and verification details carefully because some settings are difficult to change later.', action: 'Audit your advertiser profile and document the selected currency/timezone.' },
        { title: 'Business Center permissions', brief: 'Assign people and assets based on role rather than giving everyone full admin access.', action: 'Create a simple permission matrix for owner, marketer and analyst.' },
        { title: 'Billing and payment options', brief: 'Understand manual payment, automatic payment and monthly invoicing where available, plus how deposits and billing thresholds work.', action: 'Write which billing option your account uses and the person responsible for it.' },
      ],
      question: { prompt: 'Why confirm account currency and timezone during setup?', choices: ['They affect reporting and billing and may be difficult to change', 'They increase video quality', 'They replace the Pixel'], answer: 0, explanation: 'These are foundational account settings that affect financial and reporting workflows.' },
    },
    {
      title: 'Offer, niche and audience research',
      intro: 'TikTok creative works best when the offer and customer problem are obvious before production starts.',
      principles: ['Research customer language and objections.', 'Use Creative Center and competitor examples to identify patterns.', 'Build multiple creative angles for the same offer.'],
      mistakes: ['Starting with editing before knowing the customer.', 'Copying a viral video without adapting the message.'],
      deliverable: 'Create an audience sheet with pains, desired outcomes, objections, proof and five creative angles.',
      lessons: [
        { title: 'Customer language research', brief: 'Collect phrases from comments, reviews, support chats and creator content to understand how customers describe the problem.', action: 'Collect 20 customer phrases.' },
        { title: 'Creative Center research', brief: 'Use TikTok Creative Center to inspect top ads, formats, hooks and industry patterns without cloning another advertiser.', action: 'Save five creative patterns and write the hypothesis behind each.' },
        { title: 'Build the offer', brief: 'Turn the product into a clear promise supported by proof, price context and one next action.', action: 'Write a one-sentence offer and three reasons to believe it.' },
      ],
      question: { prompt: 'What is the best use of competitor research?', choices: ['Find patterns and generate hypotheses', 'Copy the ad exactly', 'Ignore your own customer'], answer: 0, explanation: 'Research is useful when it informs your own experiments rather than producing copies.' },
    },
    {
      title: 'TikTok content strategy',
      intro: 'Organic content gives you a fast testing environment for hooks, angles, formats and audience response.',
      principles: ['Build repeatable content pillars.', 'Create for the viewer, not the algorithm myth of the week.', 'Track meaningful signals such as watch behavior, comments and downstream actions.'],
      mistakes: ['Posting unrelated trends every day.', 'Deleting useful tests too quickly because they did not go viral.'],
      deliverable: 'Create four content pillars and a 30-day organic posting calendar.',
      lessons: [
        { title: 'Content pillars', brief: 'Organize content around education, demonstration, proof, entertainment, objection handling and behind-the-scenes themes.', action: 'Choose four content pillars for your business.' },
        { title: 'Hook library', brief: 'Build opening lines and visual patterns that earn the next second of attention.', action: 'Write 30 hooks across your four content pillars.' },
        { title: 'Posting and learning rhythm', brief: 'Use consistent production and review cycles to learn what the audience actually responds to.', action: 'Schedule the next 14 posts and one weekly review session.' },
      ],
      question: { prompt: 'What makes an organic content system easier to sustain?', choices: ['Repeatable content pillars', 'A new niche every day', 'Only copying trends'], answer: 0, explanation: 'Content pillars create structure while still leaving room for creative variation.' },
    },
    {
      title: 'TikTok-native creative production',
      intro: 'Strong TikTok advertising often feels like useful creator content rather than a traditional polished commercial.',
      principles: ['Front-load the idea.', 'Use vertical 9:16 composition.', 'Show, demonstrate or prove instead of only claiming.'],
      mistakes: ['Long logo animations before the hook.', 'Using landscape creative designed for another platform.'],
      deliverable: 'Produce six vertical concepts using different hooks and proof styles.',
      lessons: [
        { title: 'UGC-style structure', brief: 'Use hook, problem, demonstration, proof and CTA in a natural creator-style sequence.', action: 'Write a 20-second UGC-style script.' },
        { title: 'Phone-first filming', brief: 'Use simple lighting, clear audio, stable framing and close product demonstrations.', action: 'Record three raw vertical clips for one concept.' },
        { title: 'Editing for retention', brief: 'Use captions, visual changes and pacing to remove dead time while keeping the message understandable.', action: 'Edit one concept into 15-second and 30-second versions.' },
      ],
      question: { prompt: 'What is the strongest default aspect ratio for TikTok creative?', choices: ['9:16 vertical', '16:9 landscape', 'A4 portrait PDF'], answer: 0, explanation: 'TikTok is primarily a full-screen vertical mobile experience.' },
    },
    {
      title: 'Pixel and web measurement',
      intro: 'TikTok Pixel and Events API help connect ad exposure to website behavior and conversion measurement.',
      principles: ['Define event names before implementation.', 'Verify events before spending.', 'Use business records as an independent source of truth.'],
      mistakes: ['Installing the Pixel but never testing it.', 'Optimizing for an event that does not represent business value.'],
      deliverable: 'Create an event map from page view to purchase or lead.',
      lessons: [
        { title: 'TikTok Pixel basics', brief: 'Understand how the Pixel sends web events back to TikTok for reporting and optimization.', action: 'List the website events your funnel needs.' },
        { title: 'Events API concepts', brief: 'Understand the role of server-side data connections and why duplicate event handling matters.', action: 'Mark which events could be sent from browser, server or both.' },
        { title: 'Verification and source of truth', brief: 'Test events and compare TikTok reporting with your ecommerce or CRM records.', action: 'Document the system that determines real revenue or qualified leads.' },
      ],
      question: { prompt: 'What should happen before optimizing for Purchase?', choices: ['Verify the Purchase event works correctly', 'Change the logo', 'Increase followers'], answer: 0, explanation: 'Optimization depends on a reliable conversion signal.' },
    },
    {
      title: 'Campaign objectives and structure',
      intro: 'Ads Manager organizes decisions across campaign, ad group and ad levels.',
      principles: ['Match objective to business outcome.', 'Keep tests readable.', 'Avoid unnecessary fragmentation.'],
      mistakes: ['Choosing Traffic when the real goal is a tracked sale without a reason.', 'Creating too many tiny ad groups.'],
      deliverable: 'Draw your first paid campaign structure with objective, ad groups, audience and creative tests.',
      lessons: [
        { title: 'Choose the objective', brief: 'Understand awareness, consideration and conversion-oriented objectives and when each is useful.', action: 'Choose the objective for one real offer and explain the reason.' },
        { title: 'Campaign and ad group logic', brief: 'Place budget, audience, placements and optimization decisions at the correct level.', action: 'Sketch the hierarchy of your campaign.' },
        { title: 'Test design', brief: 'Keep creative and audience tests structured enough that you can learn from results.', action: 'Write the exact question your first campaign should answer.' },
      ],
      question: { prompt: 'What makes a test interpretable?', choices: ['A clear hypothesis and controlled changes', 'Changing everything at once', 'No primary metric'], answer: 0, explanation: 'A clear hypothesis makes the result useful for the next decision.' },
    },
    {
      title: 'Audiences, placements and budgets',
      intro: 'Targeting and spend should express a hypothesis and give the campaign enough opportunity to learn.',
      principles: ['Use broad targeting when appropriate.', 'Build custom audiences from useful signals.', 'Base test budget on target CPA and learning needs.'],
      mistakes: ['Over-narrowing the audience.', 'Choosing budget only because the number feels comfortable.'],
      deliverable: 'Create broad, interest and retargeting audience plans plus a seven-day test budget.',
      lessons: [
        { title: 'Audience hypotheses', brief: 'Compare broad, demographic/interest and custom audiences based on your offer and data quality.', action: 'Write three audience hypotheses.' },
        { title: 'Placements and identity', brief: 'Understand placements and the TikTok identity associated with the ad experience.', action: 'Document the placement and identity choices for your test.' },
        { title: 'Budget and bidding', brief: 'Plan daily or lifetime spend using target CPA and enough conversion opportunities to evaluate the test.', action: 'Calculate a seven-day test budget.' },
      ],
      question: { prompt: 'What should influence a paid test budget?', choices: ['Target CPA and required learning opportunities', 'How many followers the competitor has', 'The color of the CTA'], answer: 0, explanation: 'Budget should connect to the action being measured and its economics.' },
    },
    {
      title: 'First campaign: In-Feed Ads',
      intro: 'Build the full campaign from business goal to ad-level creative and preview.',
      principles: ['Check destination and tracking before publish.', 'Use TikTok-native vertical creative.', 'Preview every ad before launch.'],
      mistakes: ['Publishing before testing the landing page.', 'Uploading a creative with unreadable text.'],
      deliverable: 'Build one complete In-Feed campaign ready for review.',
      lessons: [
        { title: 'Campaign setup', brief: 'Choose objective, naming convention, budget framework and primary conversion event.', action: 'Create the campaign shell using your planning sheet.' },
        { title: 'Ad group setup', brief: 'Configure audience, placement, optimization, schedule and bidding based on the test hypothesis.', action: 'Complete one ad group and save the settings.' },
        { title: 'Ad setup and preview', brief: 'Connect identity, upload creative, write copy, set CTA and confirm destination.', action: 'Preview the ad on mobile before publishing.' },
      ],
      question: { prompt: 'What is the last step before publishing an ad?', choices: ['Preview and verify destination/tracking', 'Delete the Pixel', 'Change the business name'], answer: 0, explanation: 'A final preview catches broken links, layout problems and tracking mistakes.' },
    },
    {
      title: 'Spark Ads and organic-to-paid',
      intro: 'Spark Ads let advertisers amplify eligible TikTok posts while retaining the native post identity and engagement context.',
      principles: ['Use organic performance as one input, not the only criterion.', 'Get proper authorization for creator posts.', 'Match the boosted content to a business objective.'],
      mistakes: ['Boosting a viral post that has no relevance to the offer.', 'Using creator content without proper authorization.'],
      deliverable: 'Choose three organic posts that could logically become paid tests.',
      lessons: [
        { title: 'Spark Ads concept', brief: 'Understand how Spark Ads use existing TikTok posts as ad creative.', action: 'Identify three posts with strong commercial relevance.' },
        { title: 'Creator authorization workflow', brief: 'Use approved authorization methods and clear collaboration agreements when amplifying creator content.', action: 'Write the permissions checklist for creator collaborations.' },
        { title: 'Organic test to paid scale', brief: 'Turn strong organic angles into structured paid tests with defined KPIs.', action: 'Create one organic-to-paid testing plan.' },
      ],
      question: { prompt: 'What makes an organic post a useful paid candidate?', choices: ['Commercial relevance plus evidence of audience response', 'Views alone', 'A famous sound only'], answer: 0, explanation: 'Paid media still needs to support a business objective.' },
    },
    {
      title: 'TikTok Shop, identity verification and legitimate regional access',
      intro: 'TikTok Shop is not available in every country. This module shows the legitimate Seller Center path for supported markets, the current US identity/business requirements, and what a Nigeria/Africa-based business can do when native Shop onboarding is not available.',
      principles: ['Confirm the supported-market list before collecting documents.', 'Use your real residence/business identity, banking and tax information.', 'Use TikTok Ads to a website, WhatsApp or another compliant checkout when Shop is unavailable locally.'],
      mistakes: ['Changing location or submitting borrowed/fake identity documents to bypass eligibility.', 'Assuming a US Shop can be opened without genuine US eligibility.', 'Making exaggerated product claims for commissions.'],
      deliverable: 'Create a market-specific commerce plan: native TikTok Shop if genuinely eligible, or a compliant TikTok-to-website/WhatsApp sales funnel if not.',
      lessons: [
        { title: 'Seller Center and supported markets', brief: 'TikTok lists Seller Center availability by country. As of the 2026 course edition, the official list includes markets such as the US and UK but not Nigeria. Check the current official list because availability can expand.', action: 'Check the official Seller Center availability page and write down whether your actual country is currently supported.' },
        { title: 'US Shop identity and business verification', brief: 'For the US, learn the real onboarding requirements: adult applicant, US residence/business eligibility, matching government ID, contact details, address, tax/business information and banking details depending on seller type. Never fabricate or borrow these.', action: 'Create a document checklist for the seller type you genuinely qualify for.' },
        { title: 'Nigeria and other unsupported-market alternatives', brief: 'If native TikTok Shop is unavailable in your actual market, build a legitimate funnel using organic TikTok and TikTok Ads to your website, DRIGHT listing, WhatsApp Business or another available checkout. Do not use VPN/location spoofing or false identity documents.', action: 'Build one TikTok-to-checkout funnel using a destination that is genuinely available to your business.' },
      ],
      question: { prompt: 'What should a Nigeria-based seller do if TikTok Shop is not officially available to their market?', choices: ['Use a compliant external checkout/website/WhatsApp funnel until legitimately eligible', 'Use fake US identity documents', 'Spoof location and borrow a bank account'], answer: 0, explanation: 'Regional eligibility and verification rules must be respected. TikTok Ads and organic content can still send customers to legitimate external sales channels.' },
    },
    {
      title: 'Organic sales content system',
      intro: 'A sustainable organic selling system uses repeated testing rather than one viral-video gamble.',
      principles: ['Create multiple angles per product.', 'Use comments as research.', 'Build clear profile and product-page continuity.'],
      mistakes: ['Posting only direct sales pitches.', 'Ignoring questions in comments.'],
      deliverable: 'Build a 30-video organic sales testing plan.',
      lessons: [
        { title: 'Content-to-sale formats', brief: 'Use demonstrations, before/after process, comparison, problem-solution, FAQ and story formats appropriately.', action: 'Choose six formats for one product.' },
        { title: 'Comments as research', brief: 'Turn recurring questions and objections into new content.', action: 'Create ten videos from real or expected customer questions.' },
        { title: 'Profile and destination optimization', brief: 'Make the profile, link destination or Shop product page consistent with what the video promised.', action: 'Audit bio, pinned content and destination page.' },
      ],
      question: { prompt: 'What is a useful source of future content ideas?', choices: ['Customer questions and objections', 'Random unrelated trends', 'Deleting all comments'], answer: 0, explanation: 'Questions reveal what the audience needs explained before they buy.' },
    },
    {
      title: 'Analytics and optimization',
      intro: 'Read the path from delivery to attention to click to conversion instead of reacting to one metric.',
      principles: ['Use a primary KPI tied to the objective.', 'Review creative and funnel metrics together.', 'Keep a test log.'],
      mistakes: ['Optimizing only for cheap CPM.', 'Editing campaigns constantly without a decision window.'],
      deliverable: 'Create a weekly TikTok performance dashboard and test log.',
      lessons: [
        { title: 'Organic analytics', brief: 'Review retention, watch time, completion, shares, comments and profile/product actions.', action: 'Choose the five organic metrics that matter for your goal.' },
        { title: 'Paid analytics', brief: 'Connect CPM, CTR, CPC, CVR, CPA and ROAS into a diagnostic chain.', action: 'Create a troubleshooting map for each metric.' },
        { title: 'Decision rules', brief: 'Define evidence for stop, continue, iterate and scale before the campaign starts.', action: 'Write your four decision rules.' },
      ],
      question: { prompt: 'Why use several funnel metrics together?', choices: ['They help locate where performance is breaking', 'One metric is always enough', 'They guarantee profitability'], answer: 0, explanation: 'Different metrics describe different stages of the customer journey.' },
    },
    {
      title: 'Retargeting and scaling',
      intro: 'Scale what has demonstrated acceptable economics and use retargeting to respond to higher-intent behavior.',
      principles: ['Segment warm audiences by action.', 'Refresh creative before fatigue becomes severe.', 'Protect marginal CPA while increasing spend.'],
      mistakes: ['Showing the same ad forever.', 'Doubling budget repeatedly without checking economics.'],
      deliverable: 'Create a retargeting ladder and four scaling levers.',
      lessons: [
        { title: 'Warm audience strategy', brief: 'Use video viewers, site visitors, add-to-cart users and customers with appropriate messages.', action: 'Create a warm-audience ladder.' },
        { title: 'Creative refresh system', brief: 'Replace fatigued creative using new hooks, creators, formats and proof while keeping the winning angle.', action: 'Plan three refreshes for your best concept.' },
        { title: 'Vertical and horizontal scaling', brief: 'Increase spend or expand creative, audiences, offers and geographies with guardrails.', action: 'Write four scale levers and their stop conditions.' },
      ],
      question: { prompt: 'What should remain protected while scaling?', choices: ['Acceptable business economics', 'Only view count', 'Only follower growth'], answer: 0, explanation: 'Growth is useful only when incremental spend remains economically acceptable.' },
    },
    {
      title: 'Policy, capstone and 90-day plan',
      intro: 'Finish with a policy-aware operating system combining organic production, paid campaigns, measurement and commerce.',
      principles: ['Review advertising and commerce rules.', 'Keep content authentic and claims supportable.', 'Schedule production, tests and reporting.'],
      mistakes: ['Unsupported product or earnings claims.', 'Finishing the course without a complete campaign system.'],
      deliverable: 'Complete a 90-day TikTok growth and sales operating plan.',
      lessons: [
        { title: 'Policy and claim review', brief: 'Check ad policy, commerce eligibility, creator disclosures and product claims before publishing.', action: 'Run your strongest concept through a compliance checklist.' },
        { title: 'Capstone campaign', brief: 'Combine audience research, six creatives, one organic plan, one paid campaign, Pixel events, budget and KPIs.', action: 'Complete the full capstone planner.' },
        { title: '90-day operating rhythm', brief: 'Schedule content production, organic review, paid launches, creative refreshes and weekly reporting.', action: 'Put the next 12 weeks on a calendar.' },
      ],
      question: { prompt: 'What makes the capstone complete?', choices: ['It connects organic, paid, creative, tracking and economics', 'It guarantees a viral video', 'It removes the need for testing'], answer: 0, explanation: 'A durable system connects all the pieces and preserves learning.' },
    },
  ],
  videos: [
    {
      module: 1,
      title: 'Nigeria: Create a TikTok Ads Manager Account — 2026 Step-by-Step',
      url: 'https://www.youtube.com/watch?v=OsvIPiMFATc',
      description: 'Innocent Popka gives an English, Nigeria-based walkthrough of TikTok Ads Manager signup, advertiser-account setup, verification and preparing the account to run paid campaigns.',
      region: 'Nigeria • English • Ads Manager setup',
    },
    {
      module: 1,
      title: 'Nigeria: How to Pay for TikTok Ads — Step-by-Step',
      url: 'https://www.youtube.com/watch?v=n-gnd2CoEUQ',
      description: 'English Nigeria-focused payment walkthrough covering TikTok Ads payment-method setup, account funding, common card/payment errors and practical checks before launching campaigns.',
      region: 'Nigeria • English • Billing & payment',
    },
    {
      module: 6,
      title: 'The Full TikTok Ads Course 2026',
      url: 'https://www.youtube.com/watch?v=T1xOxbGUB-A',
      description: 'A long-form English TikTok advertising course covering Business Center, Pixel, creative psychology, competitor research, campaign creation, Search Ads, Spark Ads, Seller Center, GMV Max and retargeting.',
      region: 'English • 2026 • Full paid-ads course',
    },
    {
      module: 2,
      title: 'TikTok Creative Center Tutorial 2026',
      url: 'https://www.youtube.com/watch?v=2LTJ2YA9fsk',
      description: 'Step-by-step English walkthrough for finding top TikTok ads, filtering by industry/country/format and turning creative patterns into your own testing hypotheses.',
      region: 'English • Creative research',
    },
    {
      module: 10,
      title: 'TikTok Shop Affiliate Marketing Tutorial 2026',
      url: 'https://www.youtube.com/watch?v=hYGIlU8vwsU',
      description: 'English walkthrough of TikTok Shop affiliate workflow, eligibility, product research, samples and conversion-focused creator content. Use only where TikTok Shop is legitimately available to the learner.',
      region: 'English • 2026 • TikTok Shop',
    },
  ],
  visuals: [
    { title: 'TikTok on smartphone', imageUrl: 'https://images.pexels.com/photos/7480536/pexels-photo-7480536.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/people-holding-smartphone-7480536/', sourceLabel: 'Pexels stock photo', caption: 'Mobile-first reference for how TikTok content competes for attention on a phone screen.' },
    { title: 'Short-form video content workflow', imageUrl: 'https://images.pexels.com/photos/6016365/pexels-photo-6016365.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/women-planning-their-small-business-6016365/', sourceLabel: 'Pexels stock photo', caption: 'Use mobile content references to plan framing, hooks, captions and creator-style production.' },
    { title: 'Creator filming vertical content', imageUrl: 'https://images.pexels.com/photos/8360447/pexels-photo-8360447.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/close-up-shot-of-a-smartphone-8360447/', sourceLabel: 'Pexels stock photo', caption: 'A visual reference for phone-first UGC-style creative production.' },
    { title: 'Social media analytics review', imageUrl: 'https://images.pexels.com/photos/5744245/pexels-photo-5744245.jpeg?auto=compress&dpr=1&h=750&w=1260', sourceUrl: 'https://www.pexels.com/photo/smart-phone-displaying-tiktok-profile-5744245/', sourceLabel: 'Pexels stock photo', caption: 'Creative and analytics should be reviewed together rather than as separate activities.' },
  ],
  references: [
    { label: 'TikTok for Business — Ads Manager 101', url: 'https://ads.tiktok.com/business/en-US/blog/how-to-get-started-with-tiktok-ads-manager-your-step-by-step-guide', summary: 'Official TikTok step-by-step guide to Ads Manager setup and first campaign.', points: ['Create the account correctly.', 'Choose a business objective.', 'Build, launch and improve campaigns.'] },
    { label: 'TikTok Business Center setup', url: 'https://ads.tiktok.com/help/article/create-tiktok-business-center?lang=en', summary: 'Official TikTok guide to Business Center setup, team access and asset management.', points: ['Use controlled permissions.', 'Centralize assets.', 'Keep ownership clear.'] },
    { label: 'TikTok Pixel & Events setup', url: 'https://ads.tiktok.com/help/article/get-started-pixel?lang=en', summary: 'Official TikTok guidance for Pixel and web data connections.', points: ['Define events.', 'Verify setup.', 'Use measurement responsibly.'] },
    { label: 'TikTok billing options', url: 'https://ads.tiktok.com/resources/help/article/tiktok-billing-options?lang=en-GB', summary: 'Official explanation of manual payment, automatic payment and monthly invoicing where available.', points: ['Know your billing model.', 'Confirm payment method availability.', 'Monitor account balance and thresholds.'] },
    { label: 'TikTok Shop — Seller Center setup & supported markets', url: 'https://ads.tiktok.com/resources/help/article/set-up-tiktok-shop-using-tiktok-seller-center?lang=en-GB', summary: 'Official TikTok Seller Center setup guide and current supported-country list.', points: ['Confirm your real market is supported.', 'Prepare genuine business verification documents.', 'Provide legitimate banking/contact information.'] },
    { label: 'TikTok Shop US — seller registration documents', url: 'https://seller-us.tiktok.com/university/essay?knowledge_id=3460256793413390', summary: 'Current US Seller Center documentation requirements for eligible sellers.', points: ['Use valid matching ID.', 'Meet actual US residence/business requirements.', 'Never use fabricated or borrowed identity documents.'] },
  ],
  downloads: [],
};

export default function CourseTikTokAdsPage() {
  return <PremiumCourseLearningPage config={config} />;
}
