import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '007',
  slug: 'youtube-ads-mastery-2026',
  title: 'YouTube Ads Mastery 2026',
  subtitle: 'Google Ads • Video Campaigns • Demand Gen • Shorts Ads • Creative • Conversion Tracking • Scaling',
  promise: 'Build YouTube advertising campaigns from first setup to profitable optimization. Learn Google Ads account structure, YouTube channel linking, video formats, Shorts ads, Demand Gen, conversion tracking, bidding, budgets, creative testing, remarketing and responsible scaling using the current 2026 workflow.',
  accent: 'youtube',
  modules: [
    {
      title: 'YouTube advertising foundations',
      intro: 'YouTube ads are bought through Google Ads or through the simpler Promote workflow in YouTube Studio. Start with the business outcome, not a format.',
      principles: ['Choose one measurable outcome before campaign setup.', 'Separate paid advertising from creator monetization.', 'Use Google Ads when you need full targeting, bidding and measurement control.'],
      mistakes: ['Buying views without a next step.', 'Confusing YouTube Partner Program revenue with buying YouTube ads.'],
      deliverable: 'Write one offer, target customer, primary campaign goal and conversion action.',
      lessons: [
        { title: 'How YouTube advertising works', brief: 'Understand the relationship between YouTube, Google Ads, video assets, audiences, auctions and conversion goals.', action: 'Draw the path from ad impression to business result.' },
        { title: 'Google Ads versus YouTube Promote', brief: 'Use Promote for simplified channel/video promotion and Google Ads when you need deeper campaign, audience, bidding and reporting control.', action: 'Choose the workflow that fits your next campaign and explain why.' },
        { title: 'Paid views versus business results', brief: 'Views and engagement can be useful, but sales, leads, qualified traffic or brand lift must match the objective you selected.', action: 'Choose one primary KPI and three diagnostic metrics.' },
      ],
      question: { prompt: 'What should determine the YouTube campaign type you choose?', choices: ['The business objective', 'The longest video you own', 'The number of subscribers'], answer: 0, explanation: 'Campaign types and bidding should follow the outcome you are trying to produce.' },
    },
    {
      title: 'Account, channel, billing and permissions',
      intro: 'A clean setup prevents reporting, ownership and billing problems later.',
      principles: ['Use the correct Google Ads account, currency and timezone.', 'Link the correct YouTube channel.', 'Give collaborators only the access they need.'],
      mistakes: ['Sharing one password across a team.', 'Launching before confirming payment profile and conversion ownership.'],
      deliverable: 'Complete an account-and-assets map before spending.',
      lessons: [
        { title: 'Google Ads account setup', brief: 'Create or audit the advertiser account, business information, billing profile, currency and timezone.', action: 'Record your account ID, billing owner, currency and timezone.' },
        { title: 'Link the YouTube channel', brief: 'Connect the channel to Google Ads so ad workflows and eligible engagement audiences can work correctly.', action: 'Verify the intended channel is linked to the correct Ads account.' },
        { title: 'Security and team permissions', brief: 'Use individual access, two-step verification and least-privilege permissions for agencies or staff.', action: 'Create an owner, marketer and analyst permission matrix.' },
      ],
      question: { prompt: 'Why should account currency and timezone be checked before launch?', choices: ['They affect billing and reporting', 'They change video resolution', 'They automatically create audiences'], answer: 0, explanation: 'Foundational account settings affect reporting and financial operations.' },
    },
    {
      title: 'Offer, funnel and campaign economics',
      intro: 'The video cannot rescue a weak offer or a broken post-click experience.',
      principles: ['Know the value of the conversion you are buying.', 'Make the ad promise and landing page match.', 'Calculate acceptable acquisition cost before scaling.'],
      mistakes: ['Optimizing cheap views when the goal is sales.', 'Sending every audience to the homepage.'],
      deliverable: 'Build a one-page funnel and break-even acquisition model.',
      lessons: [
        { title: 'Offer clarity', brief: 'Turn product features into a clear customer outcome, proof, price context and next action.', action: 'Write your offer in one sentence.' },
        { title: 'Post-click continuity', brief: 'Keep message, visual, proof and CTA consistent from video to landing page or lead form.', action: 'Compare your ad promise with your destination headline.' },
        { title: 'Break-even math', brief: 'Use margin, conversion rate, average order value and lifetime value to define an acceptable CPA or ROAS target.', action: 'Calculate a conservative break-even CPA.' },
      ],
      question: { prompt: 'What should be known before aggressive scaling?', choices: ['Acceptable acquisition economics', 'Only total views', 'Only subscriber count'], answer: 0, explanation: 'Scaling without business economics can amplify losses.' },
    },
    {
      title: 'Audience and intent research',
      intro: 'YouTube combines video consumption, search behavior and Google audience signals. Research should guide creative and targeting together.',
      principles: ['Start with customer problems and intent.', 'Use first-party audiences where appropriate.', 'Treat targeting as a hypothesis to validate.'],
      mistakes: ['Creating tiny audiences with many stacked filters.', 'Ignoring what the creative itself communicates.'],
      deliverable: 'Create three audience hypotheses and a customer-language sheet.',
      lessons: [
        { title: 'Customer language research', brief: 'Collect objections, questions, reviews, search phrases and comments that reveal customer intent.', action: 'Collect 20 real phrases from your market.' },
        { title: 'Audience segments', brief: 'Understand demographics, interests, custom segments, first-party data and remarketing eligibility without assuming one signal guarantees a buyer.', action: 'Map three audience groups to three messages.' },
        { title: 'Creative as targeting', brief: 'Specific hooks, demonstrations and offers can self-select the right viewers even when audience controls are broader.', action: 'Write three hooks that explicitly call out the intended buyer.' },
      ],
      question: { prompt: 'What makes targeting more useful?', choices: ['Connecting audience hypotheses to specific creative', 'Adding every possible interest', 'Avoiding measurement'], answer: 0, explanation: 'Audience and creative should work together as a testable hypothesis.' },
    },
    {
      title: 'YouTube-native creative strategy',
      intro: 'People can skip or scroll. The opening seconds must earn attention and communicate relevance quickly.',
      principles: ['Lead with the problem, result, proof or compelling visual.', 'Show instead of only claiming.', 'Create several genuinely different concepts.'],
      mistakes: ['Long logo animations.', 'Producing one ad and expecting targeting to solve everything.'],
      deliverable: 'Create six distinct video-ad concepts.',
      lessons: [
        { title: 'Hook, body, proof, CTA', brief: 'Build a simple structure that earns attention, develops the idea, proves it and gives one next action.', action: 'Write a 30-second script in four sections.' },
        { title: 'Creator-style versus polished creative', brief: 'Choose production style based on audience and offer rather than assuming expensive production performs better.', action: 'Storyboard one creator-style and one polished concept.' },
        { title: 'Creative testing matrix', brief: 'Test different angles, hooks, presenters, proof types and lengths instead of changing only colors.', action: 'Plan a 12-creative matrix.' },
      ],
      question: { prompt: 'What is a stronger creative test?', choices: ['Different concepts and angles', 'Twelve different button colors', 'One video forever'], answer: 0, explanation: 'Concept-level variation creates more meaningful learning.' },
    },
    {
      title: 'YouTube ad formats and placements',
      intro: 'Different campaign goals unlock different inventory and formats across YouTube, Google TV and eligible video partners.',
      principles: ['Know what each format is designed to accomplish.', 'Design the asset for the placement.', 'Check network settings and reporting before judging performance.'],
      mistakes: ['Using the same crop everywhere.', 'Assuming every campaign supports every format.'],
      deliverable: 'Create a format-to-objective decision sheet.',
      lessons: [
        { title: 'Skippable in-stream and in-feed', brief: 'Understand where skippable in-stream and in-feed video ads appear and how viewing behavior differs.', action: 'Create one concept for each format.' },
        { title: 'Bumper and non-skippable reach', brief: 'Use short or non-skippable formats when the objective and buying method support awareness/reach.', action: 'Write a six-second bumper message with one idea only.' },
        { title: 'Shorts and multi-format delivery', brief: 'Use vertical creative for Shorts and understand how campaign subtype determines where the asset can serve.', action: 'Convert one campaign idea into horizontal and vertical versions.' },
      ],
      question: { prompt: 'Should one creative crop automatically be used for every placement?', choices: ['No, adapt assets to the placement', 'Yes, always use landscape', 'Yes, always use square'], answer: 0, explanation: 'Placement-native assets usually communicate more effectively.' },
    },
    {
      title: 'Reach, views and engagement campaigns',
      intro: 'Video campaigns can optimize for reach, views and engagement when those are the true marketing objectives.',
      principles: ['Use the campaign subtype that matches the KPI.', 'Measure quality of attention, not just cheap delivery.', 'Control frequency when repeated exposure matters.'],
      mistakes: ['Using an awareness campaign and evaluating it only on immediate purchases.', 'Buying the cheapest views regardless of audience quality.'],
      deliverable: 'Build one awareness or consideration campaign plan.',
      lessons: [
        { title: 'Video views campaigns', brief: 'Use video views when consideration and TrueView view volume are the core objective, with eligible in-stream, in-feed and Shorts inventory.', action: 'Define a view-quality review checklist.' },
        { title: 'Video reach campaigns', brief: 'Use reach-focused subtypes when the goal is efficient reach, non-skippable reach or controlled frequency.', action: 'Choose a reach subtype for a sample launch.' },
        { title: 'Engagement objectives', brief: 'Use YouTube engagement goals only when channel subscriptions or interactions are a meaningful business outcome.', action: 'Write the business reason for seeking engagement.' },
      ],
      question: { prompt: 'When is a Video Views campaign appropriate?', choices: ['When qualified video views are the intended outcome', 'When you need guaranteed purchases', 'When you have no video asset'], answer: 0, explanation: 'The optimization goal should match the desired result.' },
    },
    {
      title: 'Demand Gen for YouTube conversions',
      intro: 'Google upgraded Video Action Campaigns to Demand Gen by May 2026. Conversion-focused YouTube planning must reflect the current Demand Gen workflow rather than outdated VAC tutorials.',
      principles: ['Use Demand Gen when the goal is engagement/action across visual Google surfaces.', 'Use channel controls deliberately when available.', 'Provide strong video, image and text assets.'],
      mistakes: ['Following old Video Action Campaign setup screens.', 'Assuming Demand Gen means YouTube only.'],
      deliverable: 'Build a 2026 Demand Gen conversion campaign plan.',
      lessons: [
        { title: 'Why VAC tutorials are outdated', brief: 'All Video Action Campaigns were upgraded to Demand Gen by May 2026, so current learners should use the Demand Gen setup and reporting model.', action: 'Remove VAC-only steps from your old campaign checklist.' },
        { title: 'Demand Gen channels and formats', brief: 'Understand YouTube in-stream, in-feed, Shorts and the additional visual surfaces available to Demand Gen.', action: 'Choose whether to use broad channel automation or manual channel controls for a test.' },
        { title: 'Bidding for action', brief: 'Connect the campaign to trustworthy conversion goals before using conversion-focused bidding.', action: 'Name the conversion action and economic target for the campaign.' },
      ],
      question: { prompt: 'What replaced Video Action Campaigns by May 2026?', choices: ['Demand Gen', 'Email campaigns', 'Organic Shorts'], answer: 0, explanation: 'Google upgraded all Video Action Campaigns to Demand Gen.' },
    },
    {
      title: 'YouTube Shorts advertising',
      intro: 'Shorts ads sit inside a fast, swipeable feed, so vertical composition and immediate relevance are essential.',
      principles: ['Prefer 9:16 vertical creative.', 'Communicate the idea immediately.', 'Use campaign types that explicitly support Shorts.'],
      mistakes: ['Uploading only a horizontal TV commercial.', 'Hiding the product or idea until the end.'],
      deliverable: 'Produce three Shorts ad scripts and one vertical storyboard.',
      lessons: [
        { title: 'Shorts-supported campaign types', brief: 'Learn how Demand Gen, Video Views, efficient-reach Video campaigns, Performance Max, app campaigns and eligible reservation campaigns can use Shorts inventory.', action: 'Choose the campaign family that matches your Shorts objective.' },
        { title: 'Shorts asset specifications', brief: 'Use a YouTube-hosted video, preferably vertical, and design the headline/description/CTA to support the mobile overlay experience.', action: 'Audit one creative for vertical safe areas and immediate comprehension.' },
        { title: 'Creative that belongs in the feed', brief: 'Use movement, voice, captions, demonstration and social-native pacing while keeping advertising claims accurate.', action: 'Record a 15-second vertical test.' },
      ],
      question: { prompt: 'What aspect ratio is the strongest default for Shorts creative?', choices: ['9:16 vertical', '16:9 landscape only', 'A4 document'], answer: 0, explanation: 'Vertical creative is recommended for the Shorts experience.' },
    },
    {
      title: 'Conversion tracking and the Google tag',
      intro: 'Conversion-focused YouTube campaigns need trustworthy signals. Optimize only for actions that represent real value.',
      principles: ['Define primary and secondary conversions deliberately.', 'Install and verify the Google tag or supported implementation.', 'Compare ad-platform data with business records.'],
      mistakes: ['Optimizing to page views as if they were purchases.', 'Launching Smart Bidding with broken tracking.'],
      deliverable: 'Create and test a conversion-event map.',
      lessons: [
        { title: 'Conversion actions', brief: 'Choose purchases, qualified leads, sign-ups or other valuable actions and decide which are primary optimization goals.', action: 'List your primary and secondary conversions.' },
        { title: 'Google tag and click events', brief: 'Implement the Google tag and event tracking for confirmation pages, buttons or other meaningful actions.', action: 'Verify one conversion in your site and Ads diagnostics.' },
        { title: 'Enhanced conversions', brief: 'Understand how hashed first-party data can improve measurement where appropriate and compliant.', action: 'Decide whether your business has the consent and implementation path needed.' },
      ],
      question: { prompt: 'What should Smart Bidding optimize toward?', choices: ['A trustworthy valuable conversion', 'Any page view', 'A random video metric'], answer: 0, explanation: 'Automation is only as useful as the goal signal it receives.' },
    },
    {
      title: 'Bidding, budgets and learning',
      intro: 'Budget and bidding must give the campaign enough opportunity to learn while respecting business risk.',
      principles: ['Choose bidding based on objective.', 'Avoid constant large changes during learning.', 'Use a test budget tied to expected conversion economics.'],
      mistakes: ['Changing bids every few hours.', 'Setting targets disconnected from historical performance.'],
      deliverable: 'Create a seven-day budget and bid-strategy plan.',
      lessons: [
        { title: 'CPV, CPM and conversion bidding', brief: 'Understand when view, reach or conversion-focused bidding aligns with the campaign goal.', action: 'Choose one bid strategy and explain its KPI.' },
        { title: 'Smart Bidding', brief: 'Use Maximize Conversions, Target CPA, Maximize Conversion Value or Target ROAS only with appropriate measurement and enough useful signal.', action: 'Select the strategy that fits your conversion economics.' },
        { title: 'Budget changes', brief: 'Use measured changes and document them so you can distinguish learning from noise.', action: 'Define a budget-change rule before launch.' },
      ],
      question: { prompt: 'What is a poor optimization habit?', choices: ['Changing major settings constantly', 'Documenting tests', 'Matching bidding to the objective'], answer: 0, explanation: 'Frequent changes can make learning and diagnosis harder.' },
    },
    {
      title: 'Reporting and diagnosis',
      intro: 'Diagnose delivery, attention, clicks, conversion and economics in order.',
      principles: ['Read the funnel sequentially.', 'Segment by format/channel when useful.', 'Separate creative problems from landing-page problems.'],
      mistakes: ['Declaring success from CPM alone.', 'Blaming targeting before checking creative and conversion tracking.'],
      deliverable: 'Create a weekly YouTube Ads dashboard.',
      lessons: [
        { title: 'Attention metrics', brief: 'Review reach, impressions, TrueView views, view rate, watch behavior and engagement in the context of the objective.', action: 'Choose four attention metrics for your dashboard.' },
        { title: 'Action metrics', brief: 'Review CTR, conversion rate, CPA, conversion value and ROAS for conversion-focused campaigns.', action: 'Build a metric-to-diagnosis table.' },
        { title: 'Channel and format reporting', brief: 'Use available segmentation to understand Shorts, in-stream, in-feed and other delivery patterns without overreacting to tiny samples.', action: 'Create one weekly segmentation routine.' },
      ],
      question: { prompt: 'Why read the funnel in order?', choices: ['It helps locate where performance is breaking', 'It guarantees low CPM', 'It removes the need for tests'], answer: 0, explanation: 'Different metrics describe different parts of the customer journey.' },
    },
    {
      title: 'Remarketing and first-party audiences',
      intro: 'Warm audiences can receive a message appropriate to their prior interaction rather than seeing the same cold ad.',
      principles: ['Segment by meaningful behavior.', 'Respect consent and audience eligibility rules.', 'Change the message as intent increases.'],
      mistakes: ['Showing one ad forever.', 'Treating every site visitor as equally valuable.'],
      deliverable: 'Build a four-stage warm-audience ladder.',
      lessons: [
        { title: 'Engagement and site audiences', brief: 'Plan eligible viewer, site visitor, lead and customer groups based on available first-party signals.', action: 'List your warm audience sources.' },
        { title: 'Sequence the message', brief: 'Move from education to proof to objection handling to offer based on prior behavior.', action: 'Write one message for each warm stage.' },
        { title: 'Exclusions and customer treatment', brief: 'Exclude existing buyers from inappropriate acquisition messages where practical and create relevant retention offers.', action: 'Document buyer exclusion and retention rules.' },
      ],
      question: { prompt: 'Should every warm audience see exactly the same message?', choices: ['No, align message with prior behavior', 'Yes, always', 'Only if the ad is long'], answer: 0, explanation: 'Intent differs across warm audience stages.' },
    },
    {
      title: 'Experiments, creative refresh and scaling',
      intro: 'Scale what has demonstrated acceptable economics, then keep feeding the system new creative and controlled experiments.',
      principles: ['Change one major hypothesis at a time when possible.', 'Refresh concepts before severe fatigue.', 'Protect marginal CPA/ROAS while increasing spend.'],
      mistakes: ['Doubling budget repeatedly without review.', 'Calling a tiny sample a winner.'],
      deliverable: 'Create a 12-week testing and scaling calendar.',
      lessons: [
        { title: 'Experiment design', brief: 'Define hypothesis, control, variable, decision metric, duration and minimum useful sample before launch.', action: 'Write three test cards.' },
        { title: 'Creative refresh', brief: 'Keep the proven angle while introducing new hooks, presenters, demonstrations and proof.', action: 'Plan three refreshes for your strongest concept.' },
        { title: 'Scale with guardrails', brief: 'Increase budget or expand creative/audience/geography only while incremental economics stay acceptable.', action: 'Write your scale and rollback rules.' },
      ],
      question: { prompt: 'What should remain protected during scaling?', choices: ['Business economics', 'Only total views', 'Only frequency'], answer: 0, explanation: 'More spend is useful only if incremental results remain acceptable.' },
    },
    {
      title: 'Policy, capstone and 90-day operating plan',
      intro: 'Finish with a campaign system that respects Google Ads policy, local law and truthful advertising.',
      principles: ['Review claims before launch.', 'Use accurate landing pages and disclosures.', 'Schedule measurement and creative maintenance.'],
      mistakes: ['Unsupported earnings or health claims.', 'Finishing the course without launching a measurable system.'],
      deliverable: 'Complete a full YouTube Ads capstone and 90-day operating plan.',
      lessons: [
        { title: 'Policy and claim review', brief: 'Check Google Ads and YouTube requirements before publishing, especially for regulated products, personal attributes and misleading claims.', action: 'Run one proposed ad through a policy checklist.' },
        { title: 'Capstone campaign', brief: 'Combine objective, audience, six creatives, conversion measurement, bid strategy, budget, landing page and reporting plan.', action: 'Build the complete campaign blueprint.' },
        { title: '90-day rhythm', brief: 'Schedule weekly reporting, creative production, tests, landing-page work and scale decisions.', action: 'Put the next 12 weeks on a calendar.' },
      ],
      question: { prompt: 'What makes the capstone complete?', choices: ['Creative, media, measurement and economics are connected', 'It guarantees virality', 'It removes the need for policy review'], answer: 0, explanation: 'A durable advertising system connects all parts and remains measurable.' },
    },
  ],
  videos: [
    { module: 1, title: 'Google Ads Tutorial for Beginners — Updated for 2026', url: 'https://www.youtube.com/watch?v=h7xOSw1i7Jw', description: 'A current 2026 Google Ads walkthrough covering account strategy and campaign setup fundamentals that support YouTube advertising.', region: 'English • 2026 • Full walkthrough' },
    { module: 8, title: 'When & How to Use Demand Gen in 2026', url: 'https://www.youtube.com/watch?v=CkF-Hh_6yPE', description: 'Step-by-step 2026 Demand Gen campaign walkthrough covering when the campaign type fits and how to structure it.', region: 'English • 2026 • Demand Gen' },
    { module: 8, title: 'Demand Gen Ads Tutorial 2026', url: 'https://www.youtube.com/watch?v=9XENSN-yFu4', description: 'A practical setup walkthrough for current Demand Gen campaigns across YouTube, Gmail and Discover, useful alongside Google’s official documentation.', region: 'English • 2026 • Step-by-step' },
  ],
  visuals: [
    { title: 'YouTube advertising workspace', imageUrl: '/course-007-youtube-ads/banner.svg', sourceUrl: 'https://support.google.com/youtube/answer/2375497', sourceLabel: 'DRIGHT course artwork + official reference', caption: 'Use the campaign objective to choose the correct video campaign workflow.' },
    { title: 'YouTube Shorts advertising', imageUrl: '/course-007-youtube-ads/shorts.svg', sourceUrl: 'https://support.google.com/google-ads/answer/16041697', sourceLabel: 'DRIGHT course artwork + Google Ads Help', caption: 'Shorts ads require mobile-first creative and campaign types that support Shorts inventory.' },
  ],
  references: [
    { label: 'Google Ads Help — Create a Video campaign', url: 'https://support.google.com/youtube/answer/2375497', summary: 'Official workflow for objectives, budgets, audiences, ad groups and video creatives.', points: ['Choose the objective first.', 'Set budget and audience deliberately.', 'Use relevant YouTube-hosted creative.'] },
    { label: 'Google Ads Help — Video campaign objectives', url: 'https://support.google.com/google-ads/answer/10197127', summary: 'Official breakdown of current reach, views, engagement and conversion-oriented video campaign options.', points: ['Campaign subtype controls formats.', 'Match bidding to the goal.', 'Check eligible networks.'] },
    { label: 'Google Ads Help — Demand Gen', url: 'https://support.google.com/google-ads/answer/13695777', summary: 'Current Demand Gen capabilities across YouTube, Shorts and Google visual surfaces.', points: ['Video Action Campaigns were upgraded to Demand Gen.', 'Use strong multi-format assets.', 'Use channel controls when they fit the strategy.'] },
    { label: 'Google Ads Help — YouTube Shorts ad specifications', url: 'https://support.google.com/google-ads/answer/16041697', summary: 'Official Shorts asset specifications and creative guidance.', points: ['Prefer vertical 9:16.', 'Use clear mobile CTA assets.', 'Host the video on YouTube.'] },
    { label: 'Google Ads Help — Google tag', url: 'https://support.google.com/google-ads/answer/6331314', summary: 'Official website conversion measurement setup with the Google tag.', points: ['Create a conversion action.', 'Install the tag correctly.', 'Verify the event before optimizing.'] },
    { label: 'Google Ads Help — Smart Bidding', url: 'https://support.google.com/google-ads/answer/7065882', summary: 'Current conversion and value-focused bidding strategies and 2026 naming updates.', points: ['Use trustworthy conversion data.', 'Pick CPA or value goals based on economics.', 'Avoid unrealistic targets.'] },
  ],
  downloads: [],
};

export default function CourseYouTubeAdsPage() {
  return <PremiumCourseLearningPage config={config} />;
}
