import PremiumCourseLearningPage, { type PremiumCourseConfig } from '../components/PremiumCourseLearningPage';

const config: PremiumCourseConfig = {
  courseNumber: '008',
  slug: 'google-ads-mastery-2026',
  title: 'Google Ads Mastery 2026',
  subtitle: 'Search • Keywords • Responsive Search Ads • Conversion Tracking • Smart Bidding • Performance Max • Demand Gen',
  promise: 'Learn the current Google Ads system from measurement and Search campaigns to Smart Bidding, Performance Max and Demand Gen. Build campaigns around real customer intent, trustworthy conversion data and controlled economics instead of blindly following automation.',
  accent: 'google',
  modules: [
    {
      title: 'Google Ads foundations and the auction',
      intro: 'Google Ads reaches people across Search and other Google inventory. The right campaign starts with customer intent, business economics and a measurable conversion.',
      principles: ['Start with the business outcome.', 'Understand that campaign types solve different problems.', 'Treat Google automation as a tool that needs good inputs.'],
      mistakes: ['Opening a campaign before defining conversions.', 'Assuming the highest bid automatically wins every auction.'],
      deliverable: 'Write your offer, primary conversion, target customer and acceptable acquisition cost.',
      lessons: [
        { title: 'How the Google Ads auction works', brief: 'Understand eligibility, bid strategy, quality/relevance and auction-time signals at a practical level.', action: 'Describe what Google must know to decide whether your ad is useful for a search.' },
        { title: 'Campaign-type map', brief: 'Separate Search, Performance Max, Demand Gen, Video, Shopping/App and other workflows by objective rather than novelty.', action: 'Choose the two campaign types most relevant to your business.' },
        { title: 'Business economics before clicks', brief: 'Define value, margin, lead value, close rate and break-even CPA/ROAS before buying traffic.', action: 'Calculate one conservative break-even target.' },
      ],
      question: { prompt: 'What should come before campaign automation?', choices: ['A clear conversion and business target', 'Random keywords', 'A very high daily budget'], answer: 0, explanation: 'Automation needs a meaningful objective and economic boundary.' },
    },
    {
      title: 'Account setup, billing and access',
      intro: 'Account architecture and permissions should remain clean enough to audit months later.',
      principles: ['Use the correct currency and timezone.', 'Keep billing ownership explicit.', 'Use individual access instead of shared passwords.'],
      mistakes: ['Creating duplicate advertiser accounts without a reason.', 'Giving every collaborator admin access.'],
      deliverable: 'Create an account, billing and access map.',
      lessons: [
        { title: 'Advertiser account setup', brief: 'Confirm business identity, timezone, currency and basic account configuration before campaign creation.', action: 'Document your account ID and permanent settings.' },
        { title: 'Billing and payment methods', brief: 'Understand your account’s available billing method, payment profile and responsibility for spend.', action: 'Set a documented spend approval process.' },
        { title: 'Manager accounts and permissions', brief: 'Use appropriate user roles or manager-account access for agencies and teams.', action: 'Create a least-privilege access matrix.' },
      ],
      question: { prompt: 'Why avoid one shared login?', choices: ['Individual access improves security and accountability', 'It improves CTR', 'It lowers CPC automatically'], answer: 0, explanation: 'Access controls are an operational security issue, not a bidding tactic.' },
    },
    {
      title: 'Conversion tracking and 2026 measurement',
      intro: 'Google Ads cannot optimize intelligently if the conversion data is wrong. In 2026 Google also unified enhanced-conversion settings and shifted parts of lead import toward Data Manager.',
      principles: ['Track valuable actions, not vanity events.', 'Verify tags before trusting automated bidding.', 'Respect consent and customer-data requirements.'],
      mistakes: ['Counting every page view as a lead.', 'Importing duplicated conversions from multiple sources.'],
      deliverable: 'Build and verify a conversion-event map.',
      lessons: [
        { title: 'Google tag and conversion actions', brief: 'Create website conversion actions and implement the Google tag or supported tag-manager setup for purchases, qualified leads and other valuable actions.', action: 'Test one conversion end to end.' },
        { title: 'Enhanced conversions', brief: 'Understand the unified 2026 enhanced-conversions setting and how hashed first-party data can improve measurement where appropriate.', action: 'Document what first-party fields you collect and the consent basis for using them.' },
        { title: 'Lead and offline conversion data', brief: 'Use Data Manager or current supported import workflows for qualified/closed leads so bidding can learn from business outcomes rather than form fills alone.', action: 'Map lead created → qualified → closed sale.' },
      ],
      question: { prompt: 'What is the first requirement for useful Smart Bidding?', choices: ['Reliable conversion data', 'A huge keyword list', 'Daily manual bid changes'], answer: 0, explanation: 'Bidding quality depends on the quality of the outcome signal.' },
    },
    {
      title: 'Search intent and keyword research',
      intro: 'Search campaigns work when keywords, search intent, ad copy and landing page all solve the same customer problem.',
      principles: ['Group keywords by intent and offer.', 'Use actual search language.', 'Prioritize commercial relevance over raw volume.'],
      mistakes: ['Mixing unrelated intents in one ad group.', 'Choosing keywords only because volume is high.'],
      deliverable: 'Create an intent-based keyword map.',
      lessons: [
        { title: 'Intent categories', brief: 'Separate informational, commercial, local, brand and transactional search behavior so bidding and copy match the likely need.', action: 'Classify 30 seed queries by intent.' },
        { title: 'Keyword research workflow', brief: 'Use product language, Search terms, Keyword Planner and customer questions to build a focused list.', action: 'Build five tightly related keyword themes.' },
        { title: 'Forecast with economics', brief: 'Use estimated volume and CPC as planning inputs, then compare them with your real conversion rate and CPA target.', action: 'Estimate clicks and conversions for one test budget.' },
      ],
      question: { prompt: 'What is more important than keyword volume alone?', choices: ['Intent and business relevance', 'The longest keyword possible', 'Using only one-word keywords'], answer: 0, explanation: 'Relevant commercial intent matters more than raw traffic volume.' },
    },
    {
      title: 'Match types, search terms and negative keywords',
      intro: 'Broad, phrase and exact match control how related a query can be to a keyword, while negatives help prevent irrelevant traffic.',
      principles: ['Understand match-type reach.', 'Review actual Search terms.', 'Use negatives to protect relevance without blocking good demand.'],
      mistakes: ['Assuming exact match means character-for-character matching.', 'Never checking Search terms.'],
      deliverable: 'Build a match-type and negative-keyword strategy.',
      lessons: [
        { title: 'Broad, phrase and exact', brief: 'Broad reaches the widest related queries, phrase includes narrower matching, and exact is the narrowest; modern matching considers meaning and close variants.', action: 'Choose match types for ten commercial keywords and explain the choice.' },
        { title: 'Search-term review', brief: 'Use the Search terms report to discover good queries, wasted spend and new negatives.', action: 'Create a weekly Search terms review routine.' },
        { title: 'Negative keywords', brief: 'Build account/campaign/ad-group negatives carefully, understanding that negative matching behaves differently from positive keywords.', action: 'Create a starter negative list for one business.' },
      ],
      question: { prompt: 'What report shows the actual queries that triggered ads?', choices: ['Search terms report', 'Billing summary', 'Asset library only'], answer: 0, explanation: 'Search terms reveal what users actually typed or searched.' },
    },
    {
      title: 'Search campaign structure',
      intro: 'Good structure makes relevance, budgets, ads and optimization readable without fragmenting data unnecessarily.',
      principles: ['Group closely related intent.', 'Keep brand and non-brand decisions explicit.', 'Name campaigns and ad groups consistently.'],
      mistakes: ['One ad group for an entire website.', 'Hundreds of tiny ad groups with no data.'],
      deliverable: 'Design one complete Search campaign architecture.',
      lessons: [
        { title: 'Campaign and ad-group roles', brief: 'Use campaigns for major budget/location/goal distinctions and ad groups for tightly related search themes.', action: 'Build one campaign with four intent-based ad groups.' },
        { title: 'Brand versus non-brand', brief: 'Separate reporting when brand traffic has materially different intent and economics.', action: 'Define how you will report brand and non-brand performance.' },
        { title: 'Location, language and schedule', brief: 'Set geography and other campaign controls based on where you can genuinely serve customers.', action: 'Audit your serviceable locations and business hours.' },
      ],
      question: { prompt: 'What makes an ad group useful?', choices: ['Closely related search intent', 'Random keywords', 'A different budget for every keyword'], answer: 0, explanation: 'Intent-based groups improve message relevance and analysis.' },
    },
    {
      title: 'Responsive Search Ads and assets',
      intro: 'Responsive Search Ads combine multiple headlines and descriptions. Each asset must work alone and in combinations.',
      principles: ['Write distinct, useful headlines.', 'Match copy to keyword intent and landing page.', 'Use ad assets that add real information.'],
      mistakes: ['Repeating the same headline 15 times.', 'Pinning everything without a strong reason.'],
      deliverable: 'Create two complete Responsive Search Ads for one ad group.',
      lessons: [
        { title: 'RSA asset writing', brief: 'Provide multiple headlines and descriptions that cover keyword relevance, value, proof, differentiation and CTA.', action: 'Write 12 distinct headlines and four descriptions.' },
        { title: 'Ad Strength versus business results', brief: 'Use Ad Strength as a creative completeness signal while still judging conversions and economics.', action: 'Improve an RSA without changing the offer promise.' },
        { title: 'Sitelinks and other assets', brief: 'Add useful sitelinks, callouts, structured snippets, prices, locations or other eligible assets that help the searcher decide.', action: 'Create at least four relevant sitelinks.' },
      ],
      question: { prompt: 'How many headlines can an RSA contain?', choices: ['Up to 15', 'Only one', 'Unlimited'], answer: 0, explanation: 'Google currently allows up to 15 headlines in a responsive search ad.' },
    },
    {
      title: 'Smart Bidding and budget strategy',
      intro: 'Smart Bidding uses Google AI at auction time to optimize for conversions or conversion value.',
      principles: ['Use bidding that matches the conversion goal.', 'Give automation clean measurement.', 'Set targets that reflect actual economics.'],
      mistakes: ['Changing targets constantly.', 'Using Target ROAS without meaningful conversion values.'],
      deliverable: 'Choose a bidding strategy and budget rule for three business scenarios.',
      lessons: [
        { title: 'Maximize Conversions and Target CPA', brief: 'Use conversion-focused bidding when each conversion has roughly comparable value or when CPA is the primary constraint.', action: 'Write a scenario where Target CPA is appropriate.' },
        { title: 'Maximize Conversion Value and Target ROAS', brief: 'Use value-based bidding when conversion values are meaningful and reliable.', action: 'Define how your site passes purchase or lead value.' },
        { title: '2026 bidding-label changes', brief: 'Google updated how Target CPA and Target ROAS strategies are labeled from June 2026 without changing their underlying bidding behavior.', action: 'Update any internal SOP that still uses obsolete labels.' },
      ],
      question: { prompt: 'Which bidding family uses auction-time AI for conversion/value goals?', choices: ['Smart Bidding', 'Manual invoice billing', 'Negative keyword matching'], answer: 0, explanation: 'Smart Bidding adjusts bids using auction-time signals.' },
    },
    {
      title: 'Landing pages and conversion rate',
      intro: 'Search ads create intent-rich visits; the landing page must complete the promise.',
      principles: ['Match search intent to headline.', 'Make proof and CTA obvious.', 'Design for mobile speed and clarity.'],
      mistakes: ['Sending every keyword to the homepage.', 'Hiding price or next step when the buyer needs it.'],
      deliverable: 'Audit and improve one landing page.',
      lessons: [
        { title: 'Message match', brief: 'Carry the search intent and ad promise directly into the page headline, offer and CTA.', action: 'Compare one keyword, ad and landing-page headline side by side.' },
        { title: 'Trust and proof', brief: 'Use relevant evidence such as reviews, guarantees, demonstrations, credentials or transparent policies without fabricating proof.', action: 'Add three truthful proof elements.' },
        { title: 'Mobile conversion path', brief: 'Remove unnecessary friction, improve speed and keep forms/checkouts appropriate to the customer decision.', action: 'Complete your own funnel from a phone and list five friction points.' },
      ],
      question: { prompt: 'What is message match?', choices: ['Keeping keyword, ad promise and landing page aligned', 'Using identical colors everywhere', 'Adding more keywords to the page footer'], answer: 0, explanation: 'Continuity helps users see that they reached the right destination.' },
    },
    {
      title: 'Performance Max',
      intro: 'Performance Max can serve across Google channels and uses automated bidding, audiences and creative. It should supplement a sound measurement system, not replace strategy.',
      principles: ['Feed it trustworthy conversions.', 'Organize asset groups around meaningful themes.', 'Use audience signals and Search Themes as guidance, not hard targeting.'],
      mistakes: ['Launching with poor assets and no conversion quality control.', 'Treating audience signals as strict audience restrictions.'],
      deliverable: 'Build a Performance Max asset-group and signal plan.',
      lessons: [
        { title: 'Where Performance Max serves', brief: 'Understand cross-channel inventory and why Performance Max is different from keyword-led Search.', action: 'List which business goals make PMax worth testing.' },
        { title: 'Asset groups and creative', brief: 'Provide diverse high-quality headlines, descriptions, images, logos and videos organized around coherent themes.', action: 'Plan one complete asset group.' },
        { title: 'Audience signals and Search Themes', brief: 'Use first-party lists, custom intent and Search Themes to help guide automation while understanding it can expand beyond those signals.', action: 'Create one audience-signal pack and ten Search Themes.' },
      ],
      question: { prompt: 'Are Performance Max audience signals strict targeting?', choices: ['No, they guide automation', 'Yes, always', 'Only for desktop users'], answer: 0, explanation: 'Google may reach relevant people beyond the supplied signals.' },
    },
    {
      title: 'Demand Gen and the 2026 visual-ad transition',
      intro: 'Demand Gen now carries more of Google’s visual advertising workflow. Video Action Campaigns were upgraded by May 2026, and eligible Display campaigns began moving toward Demand Gen in 2026.',
      principles: ['Use Demand Gen for visual demand creation and action.', 'Choose channels deliberately where controls are available.', 'Use strong video and image assets.'],
      mistakes: ['Building 2026 training around obsolete VAC screens.', 'Assuming Demand Gen is only YouTube.'],
      deliverable: 'Create one Demand Gen test plan separate from Search.',
      lessons: [
        { title: 'Demand Gen inventory', brief: 'Understand YouTube including Shorts, Discover, Gmail and other supported visual surfaces in the current product.', action: 'Map one customer journey where visual discovery matters.' },
        { title: '2026 migration changes', brief: 'Recognize that older Video Action and Display tutorials may no longer match current campaign creation because Google has been consolidating visual inventory into Demand Gen.', action: 'Mark outdated steps in any older SOP you use.' },
        { title: 'Channel controls and creative', brief: 'Use current channel controls when a placement-specific experience is part of your experiment, and prepare assets for each chosen format.', action: 'Design one YouTube-specific and one broader visual test.' },
      ],
      question: { prompt: 'Which current campaign family replaced Video Action Campaigns?', choices: ['Demand Gen', 'Search', 'Local Services Ads'], answer: 0, explanation: 'Video Action Campaigns were upgraded to Demand Gen.' },
    },
    {
      title: 'Shopping and product-feed fundamentals',
      intro: 'Ecommerce advertisers need clean product data and conversion value, whether using Shopping inventory or Performance Max.',
      principles: ['Keep Merchant Center data accurate.', 'Use product titles/images that reflect real products.', 'Track purchase value and feed health.'],
      mistakes: ['Using misleading product data.', 'Ignoring disapprovals or feed diagnostics.'],
      deliverable: 'Create an ecommerce feed-quality checklist.',
      lessons: [
        { title: 'Merchant Center connection', brief: 'Understand how product data, eligibility and linked accounts support Shopping-related advertising.', action: 'Audit account linking and feed diagnostics.' },
        { title: 'Product data quality', brief: 'Improve titles, descriptions, images, price, availability and identifiers truthfully.', action: 'Rewrite five product titles for clarity rather than keyword stuffing.' },
        { title: 'Product-level economics', brief: 'Use margin and conversion value to understand which products can support paid acquisition.', action: 'Calculate target ROAS for three margin levels.' },
      ],
      question: { prompt: 'What should product feeds prioritize?', choices: ['Accurate useful product data', 'Keyword stuffing', 'Hidden price changes'], answer: 0, explanation: 'Clean product data supports eligibility, relevance and customer trust.' },
    },
    {
      title: 'Optimization and search-term diagnosis',
      intro: 'Optimization should move from query quality to ad relevance to landing-page conversion to economics.',
      principles: ['Review Search terms and conversion quality.', 'Segment by useful dimensions.', 'Document changes and outcomes.'],
      mistakes: ['Optimizing only CTR.', 'Making ten changes at once.'],
      deliverable: 'Create a weekly optimization checklist and dashboard.',
      lessons: [
        { title: 'Query and keyword diagnosis', brief: 'Review waste, new demand, match behavior, impression share and conversion quality.', action: 'Create keep, expand, negative and investigate buckets.' },
        { title: 'Ad and landing-page diagnosis', brief: 'Use CTR with conversion rate and downstream quality to distinguish copy problems from offer/page problems.', action: 'Build a metric diagnosis tree.' },
        { title: 'Change log', brief: 'Record date, change, hypothesis and result so performance history remains understandable.', action: 'Create a simple campaign change log.' },
      ],
      question: { prompt: 'Why keep a change log?', choices: ['To connect changes with outcomes', 'To make campaigns spend faster', 'To avoid all experiments'], answer: 0, explanation: 'Documentation protects learning and makes diagnosis more reliable.' },
    },
    {
      title: 'Experiments, scaling and portfolio control',
      intro: 'Scale only after a campaign demonstrates useful economics, then expand with controlled tests.',
      principles: ['Use experiments for meaningful hypotheses.', 'Protect marginal CPA or ROAS.', 'Expand budget, keywords, creative or campaign types deliberately.'],
      mistakes: ['Scaling because of one good day.', 'Changing budget, ads, landing page and bidding simultaneously.'],
      deliverable: 'Create a 90-day experiment and scaling roadmap.',
      lessons: [
        { title: 'Experiment design', brief: 'Define control, variable, decision metric and evaluation window before launching.', action: 'Write three experiment cards.' },
        { title: 'Budget scaling', brief: 'Increase spend while watching incremental conversion quality and auction changes rather than assuming historical averages remain constant.', action: 'Write a scale-up and rollback rule.' },
        { title: 'Portfolio expansion', brief: 'Add new keyword themes, regions, Search campaigns, PMax or Demand Gen only when they solve a specific growth constraint.', action: 'Choose the next expansion lever and justify it.' },
      ],
      question: { prompt: 'What should justify adding a new campaign type?', choices: ['A specific business or funnel need', 'Because it is new', 'Because a competitor mentioned it'], answer: 0, explanation: 'Campaign complexity should solve a real problem.' },
    },
    {
      title: 'Policy, capstone and operating system',
      intro: 'Google Ads performance must coexist with truthful claims, landing-page quality, policy compliance and repeatable operations.',
      principles: ['Review restricted/prohibited content rules.', 'Keep claims supportable.', 'Schedule measurement, search-term and creative reviews.'],
      mistakes: ['Trying to evade policy review.', 'Using fake urgency or unsupported guarantees.'],
      deliverable: 'Complete a Google Ads capstone and 90-day operating calendar.',
      lessons: [
        { title: 'Policy review', brief: 'Check advertising policies and local legal requirements before launching, especially for regulated industries or sensitive claims.', action: 'Run one campaign through a policy checklist.' },
        { title: 'Capstone account plan', brief: 'Build Search campaign structure, conversions, ads, negatives, bidding, budget, landing page and reporting, plus one expansion hypothesis.', action: 'Complete the full account blueprint.' },
        { title: '90-day rhythm', brief: 'Schedule Search terms, budget, conversion-quality, landing-page, asset and experiment reviews.', action: 'Put the next 12 weeks on a calendar.' },
      ],
      question: { prompt: 'What makes a durable Google Ads system?', choices: ['Measurement, intent, creative, landing pages and economics working together', 'More campaigns regardless of quality', 'Manual changes every hour'], answer: 0, explanation: 'Sustainable performance comes from a connected operating system.' },
    },
  ],
  videos: [
    { module: 1, title: 'Google Ads Tutorial for Beginners — Updated for 2026', url: 'https://www.youtube.com/watch?v=h7xOSw1i7Jw', description: 'Current 2026 walkthrough covering account fundamentals and campaign setup with a practical screen-share approach.', region: 'English • 2026 • Beginner to intermediate' },
    { module: 10, title: 'Performance Max Campaign Setup in 2026', url: 'https://www.youtube.com/watch?v=N9XNZCyAIrM', description: 'Step-by-step 2026 Performance Max setup covering current asset and campaign workflows.', region: 'English • 2026 • Performance Max' },
    { module: 11, title: 'When & How to Use Demand Gen in 2026', url: 'https://www.youtube.com/watch?v=CkF-Hh_6yPE', description: 'Current Demand Gen walkthrough explaining when the campaign fits and how to create it.', region: 'English • 2026 • Demand Gen' },
  ],
  visuals: [
    { title: 'Google Ads campaign control center', imageUrl: '/course-008-google-ads/banner.svg', sourceUrl: 'https://support.google.com/google-ads/', sourceLabel: 'DRIGHT course artwork + Google Ads Help', caption: 'Search, bidding, measurement and campaign structure work as one system.' },
    { title: 'Search intent to conversion', imageUrl: '/course-008-google-ads/search-system.svg', sourceUrl: 'https://support.google.com/google-ads/answer/14996023', sourceLabel: 'DRIGHT course artwork + Google Ads Help', caption: 'Match customer search intent with the right keyword, ad, landing page and conversion goal.' },
  ],
  references: [
    { label: 'Google Ads Help — Keyword matching', url: 'https://support.google.com/google-ads/answer/14996023', summary: 'Official explanation of broad, phrase and exact keyword matching.', points: ['Match types overlap.', 'Modern matching considers meaning.', 'Review actual Search terms.'] },
    { label: 'Google Ads Help — Negative keywords', url: 'https://support.google.com/google-ads/answer/2453972', summary: 'Official guidance for excluding irrelevant search demand.', points: ['Use negatives intentionally.', 'Negative matching behaves differently.', 'Account-level lists can apply broadly.'] },
    { label: 'Google Ads Help — Responsive Search Ads', url: 'https://support.google.com/google-ads/answer/7684791', summary: 'Official RSA setup and asset guidance.', points: ['Use multiple distinct headlines.', 'Write assets that work in combinations.', 'Connect copy to keyword intent.'] },
    { label: 'Google Ads Help — Google tag', url: 'https://support.google.com/google-ads/answer/6331314', summary: 'Official website conversion tracking setup.', points: ['Create the conversion action.', 'Install the Google tag.', 'Verify events before bidding on them.'] },
    { label: 'Google Ads Help — Enhanced conversions', url: 'https://support.google.com/google-ads/answer/15712870', summary: 'Current 2026 enhanced-conversion guidance and unified settings.', points: ['Use consented first-party data.', 'Data is hashed for matching.', 'Implementation changed in 2026.'] },
    { label: 'Google Ads Help — Smart Bidding', url: 'https://support.google.com/google-ads/answer/7065882', summary: 'Official description of Target CPA, Target ROAS, Maximize Conversions and Maximize Conversion Value.', points: ['Uses auction-time bidding.', 'Requires quality conversion signals.', '2026 label changes did not change underlying behavior.'] },
    { label: 'Google Ads Help — Performance Max optimization', url: 'https://support.google.com/google-ads/answer/14104997', summary: 'Official best practices for assets, audience signals, Search Themes and campaign quality.', points: ['Provide varied high-quality assets.', 'Use audience signals to guide AI.', 'Connect goals to value.'] },
    { label: 'Google Ads Help — Demand Gen', url: 'https://support.google.com/google-ads/answer/13695777', summary: 'Current visual advertising workflow across YouTube and other Google surfaces.', points: ['Demand Gen absorbed Video Action Campaigns.', 'Display inventory is moving into Demand Gen.', 'Use channel controls and asset quality intentionally.'] },
  ],
  downloads: [],
};

export default function CourseGoogleAdsPage() {
  return <PremiumCourseLearningPage config={config} />;
}
