import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { AtSign, Bookmark, ExternalLink, Loader2, MessageCircle, Newspaper, Pin, Send, Share2, Sparkles, ThumbsUp, Trash2, TrendingUp, X } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import SeoHead from '../components/SeoHead';
import { supabase } from '../lib/supabase';

type ReactionType='like'|'love'|'care'|'haha'|'wow'|'sad'|'angry';
type Item={id:string;title:string;message:string;type:string;content_kind:'news'|'announcement';show_in_news:boolean;show_in_notifications:boolean;is_active:boolean;is_pinned:boolean;is_trending:boolean;mention_all:boolean;comments_enabled:boolean;allowed_reactions:ReactionType[];view_count:number;hide_view_count:boolean;hide_reaction_count:boolean;media_url:string|null;media_type:'image'|'video'|null;external_url:string|null;cta_label:string|null;published_at:string;};
type Engagement={reaction_count:number;comment_count:number;save_count:number;reaction_breakdown:Record<string,number>;current_reaction:ReactionType|null;is_saved:boolean};
type Comment={id:string;body:string;created_at:string;author_name:string;author_avatar:string|null;can_delete:boolean};
const EMPTY:Engagement={reaction_count:0,comment_count:0,save_count:0,reaction_breakdown:{},current_reaction:null,is_saved:false};
const META:Record<ReactionType,{emoji:string;label:string}>={like:{emoji:'👍',label:'Like'},love:{emoji:'❤️',label:'Love'},care:{emoji:'🤗',label:'Care'},haha:{emoji:'😂',label:'Haha'},wow:{emoji:'😮',label:'Wow'},sad:{emoji:'😢',label:'Sad'},angry:{emoji:'😡',label:'Angry'}};
const FILTERS=['all','news','update','market','affiliate','announcement','promo','referral'];
function compact(n:number){return n>=1_000_000?`${(n/1_000_000).toFixed(1)}M`:n>=1_000?`${(n/1_000).toFixed(1)}K`:String(n);}
function ReactionButton({item,e,onReact}:{item:Item;e:Engagement;onReact:(r:ReactionType)=>void}){const [open,setOpen]=useState(false);const timer=useRef<number|null>(null);const allowed=item.allowed_reactions||[];const fallback=allowed.includes('like')?'like':allowed[0];if(!allowed.length)return <span className="flex min-h-[44px] items-center justify-center text-xs text-neutral-600">Reactions off</span>;const down=()=>{timer.current=window.setTimeout(()=>setOpen(true),430)};const clear=()=>{if(timer.current)window.clearTimeout(timer.current);timer.current=null};return <div className="relative flex justify-center">{open&&<div className="absolute bottom-full z-40 mb-2 flex gap-1 rounded-full border border-white/10 bg-[#202531] p-1.5 shadow-2xl">{allowed.map(r=><button key={r} type="button" onClick={()=>{setOpen(false);onReact(r)}} className="h-10 w-10 rounded-full text-2xl hover:bg-white/10" title={META[r].label}>{META[r].emoji}</button>)}</div>}<button type="button" onPointerDown={down} onPointerUp={clear} onPointerCancel={clear} onDoubleClick={()=>setOpen(true)} onClick={()=>fallback&&onReact(fallback)} className={`inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl px-3 text-sm font-semibold ${e.current_reaction?'text-[#7180ff]':'text-neutral-300 hover:bg-white/5'}`}>{e.current_reaction?<span className="text-xl">{META[e.current_reaction].emoji}</span>:<ThumbsUp className="h-5 w-5"/>}<span>{e.current_reaction?META[e.current_reaction].label:'Like'}</span>{!item.hide_reaction_count&&e.reaction_count>0&&<span className="text-xs text-neutral-500">{compact(e.reaction_count)}</span>}</button></div>}
export default function NewsPage(){
 const navigate=useNavigate();const [params,setParams]=useSearchParams();const target=params.get('item');const focusComments=params.get('comments')==='1';const [items,setItems]=useState<Item[]>([]);const [engagement,setEngagement]=useState<Record<string,Engagement>>({});const [comments,setComments]=useState<Comment[]>([]);const [draft,setDraft]=useState('');const [loading,setLoading]=useState(true);const [commentsLoading,setCommentsLoading]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [filter,setFilter]=useState('all');const viewed=useRef<string|null>(null);const commentInput=useRef<HTMLInputElement|null>(null);
 const refresh=useCallback(async(ids:string[])=>{if(!ids.length)return;const {data}=await supabase.rpc('get_global_content_engagement',{p_content_ids:ids});const next:Record<string,Engagement>={};for(const raw of data||[]){const x=raw as Record<string,unknown>;next[String(x.content_id)]={reaction_count:Number(x.reaction_count||0),comment_count:Number(x.comment_count||0),save_count:Number(x.save_count||0),reaction_breakdown:(x.reaction_breakdown||{}) as Record<string,number>,current_reaction:(x.current_reaction||null) as ReactionType|null,is_saved:Boolean(x.is_saved)};}setEngagement(cur=>({...cur,...next}));},[]);
 const loadComments=useCallback(async(id:string)=>{setCommentsLoading(true);const {data,error:e}=await supabase.rpc('get_global_content_comments',{p_content_id:id});if(e)setError(e.message);else setComments((data||[]) as Comment[]);setCommentsLoading(false);},[]);
 useEffect(()=>{let active=true;void(async()=>{setLoading(true);const {data,error:e}=await supabase.from('global_announcements').select('id,title,message,type,content_kind,show_in_news,show_in_notifications,is_active,is_pinned,is_trending,mention_all,comments_enabled,allowed_reactions,view_count,hide_view_count,hide_reaction_count,media_url,media_type,external_url,cta_label,published_at').eq('is_active',true).or('content_kind.eq.news,show_in_news.eq.true').order('published_at',{ascending:false});if(!active)return;if(e){setError(e.message);setItems([])}else{const list=(data||[]) as Item[];setItems(list);void refresh(list.map(x=>x.id));}setLoading(false);})();return()=>{active=false};},[refresh]);
 useEffect(()=>{if(!target||loading||!items.some(x=>x.id===target))return;requestAnimationFrame(()=>document.getElementById(`news-${target}`)?.scrollIntoView({behavior:'smooth',block:'center'}));if(viewed.current!==target){viewed.current=target;void supabase.rpc('record_global_content_view',{p_content_id:target}).then(({data,error:e})=>{if(e){setError(e.message);return;}const n=Number(data||0);setItems(cur=>cur.map(x=>x.id===target?{...x,view_count:n}:x));});}void loadComments(target);void refresh([target]);},[items.length,loading,target,loadComments,refresh]);
 useEffect(()=>{if(target&&focusComments&&!commentsLoading)window.setTimeout(()=>commentInput.current?.focus(),150)},[target,focusComments,commentsLoading]);
 const shown=useMemo(()=>items.filter(x=>filter==='all'||(filter==='announcement'?x.content_kind==='announcement':x.type===filter)),[items,filter]);
 const open=(id:string,commentsOpen=false)=>setParams(commentsOpen?{item:id,comments:'1'}:{item:id});
 const react=async(item:Item,r:ReactionType)=>{if(busy)return;setBusy(item.id);const {data,error:e}=await supabase.rpc('set_global_content_reaction',{p_content_id:item.id,p_reaction:r});setBusy(null);if(e)return setError(e.message);const x=(data||{}) as Record<string,unknown>;setEngagement(cur=>({...cur,[item.id]:{...(cur[item.id]||EMPTY),reaction_count:Number(x.reaction_count||0),reaction_breakdown:(x.reaction_breakdown||{}) as Record<string,number>,current_reaction:(x.reaction||null) as ReactionType|null}}));};
 const save=async(item:Item)=>{const {data,error:e}=await supabase.rpc('toggle_global_content_save',{p_content_id:item.id});if(e)return setError(e.message);const x=(data||{}) as Record<string,unknown>;setEngagement(cur=>({...cur,[item.id]:{...(cur[item.id]||EMPTY),is_saved:Boolean(x.saved),save_count:Number(x.save_count||0)}}));};
 const addComment=async(item:Item)=>{const body=draft.trim();if(!body||!item.comments_enabled)return;setBusy(item.id);const {data,error:e}=await supabase.rpc('add_global_content_comment',{p_content_id:item.id,p_body:body});setBusy(null);if(e)return setError(e.message);setDraft('');const x=(data||{}) as Record<string,unknown>;setEngagement(cur=>({...cur,[item.id]:{...(cur[item.id]||EMPTY),comment_count:Number(x.comment_count||0)}}));await loadComments(item.id);};
 const delComment=async(item:Item,id:string)=>{const {error:e}=await supabase.rpc('delete_own_global_content_comment',{p_comment_id:id});if(e)return setError(e.message);await loadComments(item.id);await refresh([item.id]);};
 const share=async(item:Item)=>{const url=`${location.origin}/news?item=${item.id}`;if(navigator.share){try{await navigator.share({title:item.title,text:item.message.slice(0,150),url});return}catch{}}await navigator.clipboard?.writeText(url)};
 return <main className="min-h-screen bg-[#0d1017] text-white"><SeoHead title="News" description="DRIGHT News, updates and announcements." canonical="/news"/><header className="border-b border-white/5 bg-gradient-to-b from-[#151a25] to-[#0d1017] px-4 py-7"><div className="mx-auto max-w-4xl"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#4353ff]/15 text-[#7180ff]"><Newspaper className="h-6 w-6"/></div><div><h1 className="text-3xl font-black">News</h1><p className="text-sm text-neutral-400">Official stories, announcements and updates from DRIGHT.</p></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{FILTERS.map(f=><button key={f} type="button" onClick={()=>setFilter(f)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-bold capitalize ${filter===f?'bg-[#4353ff] text-white':'border border-white/10 bg-white/[.03] text-neutral-400'}`}>{f}</button>)}</div></div></header><div className="mx-auto max-w-4xl px-3 py-5 sm:px-5">{error&&<div className="mb-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-sm text-red-200">{error}</div>}{loading?<div className="flex min-h-[300px] items-center justify-center"><Loader2 className="h-7 w-7 animate-spin text-[#7180ff]"/></div>:shown.length===0?<div className="py-20 text-center text-neutral-600"><Sparkles className="mx-auto h-10 w-10"/><p className="mt-3">No posts here yet.</p></div>:<div className="space-y-5">{shown.map((item,index)=>{const isOpen=target===item.id;const e=engagement[item.id]||EMPTY;return <motion.article id={`news-${item.id}`} key={item.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:Math.min(index*.03,.18)}} onClick={ev=>{const el=ev.target as HTMLElement;if(el.closest('button,a,input,video'))return;if(!isOpen)open(item.id)}} className={`overflow-hidden rounded-2xl border bg-[#141822] ${isOpen?'border-[#7180ff] ring-2 ring-[#4353ff]/20':'border-white/[.07] hover:border-white/15'} ${!isOpen?'cursor-pointer':''}`}>
 {item.media_url&&<div className="flex max-h-[560px] items-center justify-center bg-black">{item.media_type==='video'?<button type="button" onClick={()=>navigate(`/social?news=${item.id}`)} className="block w-full cursor-pointer" aria-label="Open video in Social"><video src={item.media_url} muted playsInline preload="metadata" className="pointer-events-none max-h-[560px] w-full object-contain"/></button>:<img src={item.media_url} alt="" loading="lazy" className="max-h-[560px] w-full object-contain"/>}</div>}
 <div className="p-4 sm:p-5"><div className="flex flex-wrap items-center gap-2 text-[10px] font-bold uppercase tracking-wide text-neutral-500"><span className="rounded-full border border-blue-400/20 bg-blue-500/10 px-2 py-1 text-blue-300">{item.content_kind==='announcement'?'Announcement':item.type}</span>{item.is_pinned&&<span className="inline-flex items-center gap-1"><Pin className="h-3 w-3"/>Pinned</span>}{item.is_trending&&<span className="inline-flex items-center gap-1 text-orange-300"><TrendingUp className="h-3 w-3"/>Trending</span>}{item.mention_all&&<span className="inline-flex items-center gap-1 text-violet-300"><AtSign className="h-3 w-3"/>All DRIGHT</span>}<span>{new Date(item.published_at).toLocaleDateString()}</span>{isOpen&&<button type="button" onClick={()=>setParams({})} className="ml-auto rounded-full p-1.5 hover:bg-white/5"><X className="h-4 w-4"/></button>}</div><h2 className="mt-3 text-lg font-bold sm:text-xl">{item.title}</h2><p className={`mt-2 whitespace-pre-wrap text-sm leading-relaxed text-neutral-300 ${isOpen?'':'line-clamp-2'}`}>{item.message}</p>{!isOpen&&item.message.length>90&&<button type="button" onClick={()=>open(item.id)} className="mt-1 text-sm font-bold text-neutral-300">… more</button>}
 {isOpen&&<div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>navigate(`/social?news=${item.id}`)} className="inline-flex min-h-[40px] items-center gap-2 rounded-xl bg-[#4353ff] px-4 py-2 text-sm font-bold">View in Social Field <ExternalLink className="h-4 w-4"/></button>{item.external_url&&<a href={item.external_url} target={item.external_url.startsWith('/')?undefined:'_blank'} rel="noreferrer" className="inline-flex min-h-[40px] items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold">{item.cta_label||'Learn more'}<ExternalLink className="h-4 w-4"/></a>}</div>}
 <div className="mt-4 flex items-center gap-2 text-xs text-neutral-600">{!item.hide_view_count&&<span>{compact(item.view_count||0)} views</span>}{!item.hide_view_count&&<span>·</span>}<span>{compact(e.comment_count)} comments</span>{!item.hide_reaction_count&&<><span>·</span><span>{compact(e.reaction_count)} reactions</span></>}</div></div>
 <div className="grid grid-cols-4 border-t border-white/[.06] px-2 py-1" onClick={ev=>ev.stopPropagation()}><ReactionButton item={item} e={e} onReact={r=>void react(item,r)}/><button type="button" onClick={()=>open(item.id,true)} disabled={!item.comments_enabled} className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl text-sm font-semibold text-neutral-300 disabled:text-neutral-700"><MessageCircle className="h-5 w-5"/><span className="hidden sm:inline">Comment</span></button><button type="button" onClick={()=>void share(item)} className="inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl text-sm font-semibold text-neutral-300"><Share2 className="h-5 w-5"/><span className="hidden sm:inline">Share</span></button><button type="button" onClick={()=>void save(item)} className={`inline-flex min-h-[44px] items-center justify-center gap-2 rounded-xl text-sm font-semibold ${e.is_saved?'text-[#7180ff]':'text-neutral-300'}`}><Bookmark className={`h-5 w-5 ${e.is_saved?'fill-current':''}`}/><span className="hidden sm:inline">Save</span></button></div>
 {isOpen&&<section className="border-t border-white/[.06] bg-[#11151e] p-4" onClick={ev=>ev.stopPropagation()}><h3 className="font-bold">Comments</h3>{item.comments_enabled?<div className="mt-3 flex gap-2"><input ref={commentInput} value={draft} onChange={ev=>setDraft(ev.target.value)} onKeyDown={ev=>{if(ev.key==='Enter'&&!ev.shiftKey){ev.preventDefault();void addComment(item)}}} maxLength={2000} placeholder="Write a comment…" className="min-h-[44px] flex-1 rounded-full border border-white/10 bg-[#1b202b] px-4 text-sm outline-none focus:border-[#7180ff]"/><button type="button" disabled={!draft.trim()||busy===item.id} onClick={()=>void addComment(item)} className="flex h-11 w-11 items-center justify-center rounded-full bg-[#4353ff] disabled:opacity-40"><Send className="h-4 w-4"/></button></div>:<p className="mt-3 rounded-xl bg-white/[.03] p-3 text-sm text-neutral-500">Comments are turned off for this post.</p>}<div className="mt-4 space-y-3">{commentsLoading?<Loader2 className="mx-auto h-5 w-5 animate-spin"/>:comments.length===0?<p className="py-5 text-center text-sm text-neutral-600">No comments yet.</p>:comments.map(c=><div key={c.id} className="flex gap-3">{c.author_avatar?<img src={c.author_avatar} alt="" className="h-9 w-9 rounded-full object-cover"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#252b38] text-xs font-bold">{(c.author_name||'D').slice(0,1).toUpperCase()}</div>}<div className="min-w-0 flex-1 rounded-2xl bg-[#1b202b] px-3.5 py-2.5"><div className="flex justify-between gap-2"><div><p className="text-xs font-bold">{c.author_name}</p><p className="mt-1 whitespace-pre-wrap text-sm text-neutral-300">{c.body}</p></div>{c.can_delete&&<button type="button" onClick={()=>void delComment(item,c.id)} className="text-neutral-600 hover:text-red-300"><Trash2 className="h-4 w-4"/></button>}</div><p className="mt-1 text-[10px] text-neutral-600">{new Date(c.created_at).toLocaleString()}</p></div></div>)}</div></section>}
 </motion.article>})}</div>}</div></main>;
}