import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Bookmark, ChevronLeft, Expand, MessageCircle, MoreHorizontal, RotateCw, Share2, ThumbsUp, Volume2, VolumeX } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';

type ReactionType='like'|'love'|'care'|'haha'|'wow'|'sad'|'angry';
type Item={id:string;title:string;message:string;media_url:string|null;media_type:'image'|'video'|null;view_count:number;hide_view_count:boolean;hide_reaction_count:boolean;comments_enabled:boolean;allowed_reactions:ReactionType[];published_at:string;created_by:string|null;};
type Engagement={reaction_count:number;comment_count:number;save_count:number;current_reaction:ReactionType|null;is_saved:boolean;reaction_breakdown:Record<string,number>};
const EMPTY:Engagement={reaction_count:0,comment_count:0,save_count:0,current_reaction:null,is_saved:false,reaction_breakdown:{}};
const REACTIONS:Record<ReactionType,{emoji:string;label:string}>={like:{emoji:'👍',label:'Like'},love:{emoji:'❤️',label:'Love'},care:{emoji:'🤗',label:'Care'},haha:{emoji:'😂',label:'Haha'},wow:{emoji:'😮',label:'Wow'},sad:{emoji:'😢',label:'Sad'},angry:{emoji:'😡',label:'Angry'}};

function compact(n:number){return n>=1_000_000?`${(n/1_000_000).toFixed(n>=10_000_000?0:1)}M`:n>=1_000?`${(n/1_000).toFixed(n>=10_000?0:1)}K`:String(n);}

function SocialReaction({item,value,count,onReact}:{item:Item;value:ReactionType|null;count:number;onReact:(r:ReactionType)=>void}){
 const [open,setOpen]=useState(false); const timer=useRef<number|null>(null); const allowed=item.allowed_reactions||[]; const fallback=allowed.includes('like')?'like':allowed[0];
 const press=()=>{if(!allowed.length)return;timer.current=window.setTimeout(()=>setOpen(true),430)}; const clear=()=>{if(timer.current)window.clearTimeout(timer.current);timer.current=null};
 if(!allowed.length)return null;
 return <div className="relative flex flex-col items-center"><div className="relative">{open&&<div className="absolute bottom-14 right-0 flex gap-1 rounded-full bg-black/80 p-1.5 shadow-2xl backdrop-blur">{allowed.map(r=><button key={r} type="button" onClick={()=>{setOpen(false);onReact(r)}} className="h-10 w-10 rounded-full text-2xl hover:bg-white/10">{REACTIONS[r].emoji}</button>)}</div>}<button type="button" onPointerDown={press} onPointerUp={clear} onPointerCancel={clear} onDoubleClick={()=>setOpen(true)} onClick={()=>fallback&&onReact(fallback)} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur">{value?<span className="text-2xl">{REACTIONS[value].emoji}</span>:<ThumbsUp className="h-7 w-7"/>}</button></div>{!item.hide_reaction_count&&count>0&&<span className="mt-1 text-xs font-bold text-white drop-shadow">{compact(count)}</span>}</div>;
}

function SocialCard({item,engagement,onEngagement}:{item:Item;engagement:Engagement;onEngagement:(id:string,e:Partial<Engagement>)=>void}){
 const navigate=useNavigate(); const root=useRef<HTMLDivElement|null>(null); const video=useRef<HTMLVideoElement|null>(null); const viewed=useRef(false); const [muted,setMuted]=useState(false); const [landscape,setLandscape]=useState(false); const [reactionBusy,setReactionBusy]=useState(false);
 useEffect(()=>{const node=root.current;if(!node)return;const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.intersectionRatio>=.65){video.current?.play().catch(()=>{});if(!viewed.current){viewed.current=true;void supabase.rpc('record_global_content_view',{p_content_id:item.id}).then(({data})=>{const n=Number(data||0);if(n>=0)onEngagement(item.id,{})});}}else video.current?.pause();}},{threshold:[.2,.65,.9]});observer.observe(node);return()=>observer.disconnect();},[item.id,onEngagement]);
 const react=async(r:ReactionType)=>{if(reactionBusy)return;setReactionBusy(true);const {data}=await supabase.rpc('set_global_content_reaction',{p_content_id:item.id,p_reaction:r});setReactionBusy(false);if(data){const x=data as Record<string,unknown>;onEngagement(item.id,{reaction_count:Number(x.reaction_count||0),current_reaction:(x.reaction||null) as ReactionType|null,reaction_breakdown:(x.reaction_breakdown||{}) as Record<string,number>});}};
 const save=async()=>{const {data}=await supabase.rpc('toggle_global_content_save',{p_content_id:item.id});if(data){const x=data as Record<string,unknown>;onEngagement(item.id,{is_saved:Boolean(x.saved),save_count:Number(x.save_count||0)});}};
 const share=async()=>{const url=`${location.origin}/news?item=${item.id}`;if(navigator.share){try{await navigator.share({title:item.title,text:item.message.slice(0,140),url});return;}catch{}}await navigator.clipboard?.writeText(url);};
 const fullscreen=async()=>{const el=video.current||root.current;if(el?.requestFullscreen)await el.requestFullscreen();};
 const rotate=async()=>{const el=video.current;if(!el)return;try{await el.requestFullscreen?.();const orientation=(screen as Screen&{orientation?:ScreenOrientation&{lock?:(o:string)=>Promise<void>}}).orientation;await orientation?.lock?.('landscape');}catch{void 0;}};
 const openNormal=(comments=false)=>navigate(`/news?item=${item.id}${comments?'&comments=1':''}`);
 return <section ref={root} className="relative h-[calc(100dvh-5rem)] min-h-[560px] w-full snap-start overflow-hidden bg-black sm:h-[calc(100dvh-4rem)]">
   <div className="absolute inset-0 flex items-center justify-center bg-black">
    {item.media_type==='video'&&item.media_url?<video ref={video} src={item.media_url} playsInline loop muted={muted} preload="metadata" onLoadedMetadata={e=>setLandscape(e.currentTarget.videoWidth>e.currentTarget.videoHeight)} onClick={e=>e.currentTarget.paused?void e.currentTarget.play():e.currentTarget.pause()} className="h-full w-full object-contain"/>:item.media_type==='image'&&item.media_url?<img src={item.media_url} alt="" className="h-full w-full object-contain"/>:<div className="absolute inset-0 bg-gradient-to-b from-[#111827] via-[#0f172a] to-black"/>}
   </div>
   <div className="pointer-events-none absolute inset-0 bg-gradient-to-b from-black/30 via-transparent to-black/80"/>
   <div className="absolute left-3 right-3 top-3 z-20 flex items-center justify-between"><button type="button" onClick={()=>navigate('/news')} className="flex h-11 w-11 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur" aria-label="Back to News"><ChevronLeft className="h-7 w-7"/></button><div className="rounded-full bg-black/35 px-4 py-2 text-sm font-bold text-white backdrop-blur">Social Field</div><button type="button" onClick={()=>openNormal()} className="flex h-11 w-11 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur" aria-label="Open post"><MoreHorizontal className="h-6 w-6"/></button></div>
   {item.media_type==='video'&&<div className="absolute right-3 top-20 z-20 flex gap-2"><button type="button" onClick={()=>setMuted(v=>!v)} className="flex h-10 w-10 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur">{muted?<VolumeX className="h-5 w-5"/>:<Volume2 className="h-5 w-5"/>}</button><button type="button" onClick={()=>void fullscreen()} className="flex h-10 w-10 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur" title="Full screen"><Expand className="h-5 w-5"/></button>{landscape&&<button type="button" onClick={()=>void rotate()} className="flex h-10 w-10 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur" title="Flip landscape video"><RotateCw className="h-5 w-5"/></button>}</div>}
   <div className="absolute bottom-5 left-4 right-20 z-20 text-white"><button type="button" onClick={()=>openNormal()} className="text-left"><p className="text-base font-extrabold">DRIGHT News</p><p className="mt-1 text-xs text-white/70">{new Date(item.published_at).toLocaleDateString()}</p><h2 className="mt-3 text-lg font-bold leading-snug">{item.title}</h2><p className="mt-1 line-clamp-2 text-sm leading-relaxed text-white/90">{item.message} <span className="font-bold">… more</span></p></button>{!item.hide_view_count&&<p className="mt-2 text-xs font-semibold text-white/65">{compact(item.view_count||0)} views</p>}</div>
   <div className="absolute bottom-5 right-3 z-30 flex flex-col items-center gap-4"><SocialReaction item={item} value={engagement.current_reaction} count={engagement.reaction_count} onReact={r=>void react(r)}/>{item.comments_enabled&&<button type="button" onClick={()=>openNormal(true)} className="flex flex-col items-center text-white"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-black/35 backdrop-blur"><MessageCircle className="h-7 w-7"/></span>{engagement.comment_count>0&&<span className="mt-1 text-xs font-bold">{compact(engagement.comment_count)}</span>}</button>}<button type="button" onClick={()=>void share()} className="flex h-12 w-12 items-center justify-center rounded-full bg-black/35 text-white backdrop-blur"><Share2 className="h-7 w-7"/></button><button type="button" onClick={()=>void save()} className={`flex h-12 w-12 items-center justify-center rounded-full bg-black/35 backdrop-blur ${engagement.is_saved?'text-[#7180ff]':'text-white'}`}><Bookmark className={`h-7 w-7 ${engagement.is_saved?'fill-current':''}`}/></button></div>
 </section>;
}

export default function SocialFieldPage(){
 const [params]=useSearchParams(); const target=params.get('item'); const [items,setItems]=useState<Item[]>([]); const [engagement,setEngagement]=useState<Record<string,Engagement>>({}); const [loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;void(async()=>{const {data}=await supabase.from('global_announcements').select('id,title,message,media_url,media_type,view_count,hide_view_count,hide_reaction_count,comments_enabled,allowed_reactions,published_at,created_by').eq('is_active',true).or('content_kind.eq.news,show_in_news.eq.true').order('published_at',{ascending:false});if(!active)return;let list=(data||[]) as Item[];if(target){const i=list.findIndex(x=>x.id===target);if(i>0)list=[list[i],...list.slice(0,i),...list.slice(i+1)];}setItems(list);if(list.length){const {data:e}=await supabase.rpc('get_global_content_engagement',{p_content_ids:list.map(x=>x.id)});const map:Record<string,Engagement>={};for(const raw of e||[]){const x=raw as Record<string,unknown>;map[String(x.content_id)]={reaction_count:Number(x.reaction_count||0),comment_count:Number(x.comment_count||0),save_count:Number(x.save_count||0),current_reaction:(x.current_reaction||null) as ReactionType|null,is_saved:Boolean(x.is_saved),reaction_breakdown:(x.reaction_breakdown||{}) as Record<string,number>};}setEngagement(map);}setLoading(false);})();return()=>{active=false};},[target]);
 const update=useCallback((id:string,patch:Partial<Engagement>)=>setEngagement(cur=>({...cur,[id]:{...(cur[id]||EMPTY),...patch}})),[]);
 const ordered=useMemo(()=>items,[items]);
 if(loading)return <div className="flex h-[70vh] items-center justify-center bg-black text-white">Loading Social Field…</div>;
 return <main className="h-[calc(100dvh-5rem)] snap-y snap-mandatory overflow-y-auto bg-black [scrollbar-width:none] [&::-webkit-scrollbar]:hidden sm:h-[calc(100dvh-4rem)]">{ordered.map(item=><SocialCard key={item.id} item={item} engagement={engagement[item.id]||EMPTY} onEngagement={update}/>)}</main>;
}
