import { createClient } from "npm:@supabase/supabase-js@2.110.0";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const SERVICE_ROLE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const supabase=createClient(SUPABASE_URL,SERVICE_ROLE_KEY);

const AI_CONFIG={
  providers:{
    groq:{models:["llama-3.3-70b-versatile","llama-3.1-8b-instant"],maxTokens:2200,costPerToken:0.00000059,timeoutMs:30000},
    gemini:{models:["gemini-2.5-flash-lite"],maxTokens:2200,costPerToken:0.000000075,timeoutMs:30000},
    openai:{models:["gpt-4o-mini"],maxTokens:2200,costPerToken:0.0000015,timeoutMs:30000},
  },
  providerPriority:["groq","gemini","openai"] as const,
  maxRetries:2,
  maxPromptLength:8000,
  rateLimit:{windowMs:60000,maxRequests:{user:20,guest:5,admin:60}},
  cache:{enabled:true,ttlMs:5*60*1000,maxSize:200},
} as const;

const SECRETS={groq:Deno.env.get("GROQ_API_KEY")||"",gemini:Deno.env.get("GEMINI_API_KEY")||"",openai:Deno.env.get("OPENAI_API_KEY")||""};

type Role="system"|"user"|"assistant";
interface AIMessage{role:Role;content:string}
interface AIRequest{feature:string;prompt:string;context?:string;messages?:AIMessage[];userId?:string;conversationId?:string;locale?:string;stream?:boolean}
interface ProviderResult{content:string;tokens:number;model:string;provider:string;fallbackUsed:boolean}

const VALID_FEATURES=["chat","search","product-description","rewrite","summarize","moderate","translate","recommend","generate-text","test","product-qa","faq","marketplace-assistant"];
const SYSTEM_PROMPTS:Record<string,string>={
  chat:"You are DRIGHT AI, a marketplace intelligence assistant. Be concise, helpful and specific. Do not invent facts.",
  search:"You are DRIGHT Smart Search. Return only valid JSON describing search keywords and intent.",
  "product-description":"You are DRIGHT Product Description Generator. Create clear, engaging marketplace copy.",
  rewrite:"You are DRIGHT Content Rewriter. Preserve meaning while improving clarity and tone.",
  summarize:"You are DRIGHT Content Summarizer. Capture the important points concisely.",
  moderate:"You are DRIGHT Content Moderator. Return only valid JSON for moderation decisions.",
  translate:"You are DRIGHT Translator. Preserve meaning and formatting.",
  recommend:"You are DRIGHT Product Recommender. Return only valid JSON recommendations based on supplied context.",
  "generate-text":"You are DRIGHT AI Assistant. Generate helpful, professional and concise content based only on the supplied request and evidence.",
  test:"You are DRIGHT AI. Respond briefly to confirm the connection is working.",
  "product-qa":"You are DRIGHT AI Product Assistant. Answer only from supplied product context and say when information is unavailable.",
  faq:"You are DRIGHT FAQ Assistant. Answer DRIGHT marketplace questions concisely and accurately.",
  "marketplace-assistant":"You are DRIGHT Marketplace Assistant. Help buyers, sellers, affiliates and admins with marketplace tasks using supplied context.",
};
const TEMPERATURE_MAP:Record<string,number>={moderate:0.1,search:0.2,summarize:0.3,translate:0.3,recommend:0.3,"product-description":0.6,rewrite:0.6,chat:0.6,"generate-text":0.2,test:0.2,"product-qa":0.2,faq:0.2,"marketplace-assistant":0.4};

function sanitizePrompt(input:string){return String(input||"").replace(/\0/g,"").replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g,"").trim().slice(0,AI_CONFIG.maxPromptLength)}
function antiInject(input:string){return input.replace(/ignore\s+(all\s+)?(previous|above|prior)\s+instructions?/gi,"").replace(/disregard\s+(all\s+)?(previous|above)\s+/gi,"").replace(/system\s*:\s*/gi,"").replace(/<\/?system>/gi,"").trim()}
function jsonResponse(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}})}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))}
function hashKey(input:string){let h=0;for(let i=0;i<input.length;i++){h=((h<<5)-h)+input.charCodeAt(i);h|=0}return h.toString(36)}

interface CacheEntry{content:string;tokens:number;model:string;provider:string;insertedAt:number}
const cache=new Map<string,CacheEntry>();
function cacheKey(body:AIRequest){if(!AI_CONFIG.cache.enabled||body.feature==="chat"||body.feature==="test")return null;const p=body.messages?.map(m=>`${m.role}:${m.content}`).join("|")||body.prompt;return hashKey(`${body.feature}|${body.context||""}|${p}`)}
function getCached(key:string){const x=cache.get(key);if(!x)return null;if(Date.now()-x.insertedAt>AI_CONFIG.cache.ttlMs){cache.delete(key);return null}return x}
function putCached(key:string,x:CacheEntry){if(cache.size>=AI_CONFIG.cache.maxSize){const oldest=cache.keys().next().value;if(oldest)cache.delete(oldest)}cache.set(key,x)}

const rateMap=new Map<string,{count:number;start:number}>();
function checkRate(id:string,tier:"user"|"guest"|"admin"){const now=Date.now(),max=AI_CONFIG.rateLimit.maxRequests[tier],x=rateMap.get(id);if(!x||now-x.start>AI_CONFIG.rateLimit.windowMs){rateMap.set(id,{count:1,start:now});return true}x.count++;return x.count<=max}
setInterval(()=>{const now=Date.now();for(const[k,v]of rateMap)if(now-v.start>120000)rateMap.delete(k)},120000);

class ProviderError extends Error{provider:string;status:number;code:string;retryable:boolean;constructor(provider:string,status:number,code:string,retryable=false){super(`${provider}:${code}`);this.provider=provider;this.status=status;this.code=code;this.retryable=retryable}}
function classifyStatus(status:number){if(status===401||status===403)return"PROVIDER_AUTH_ERROR";if(status===404)return"PROVIDER_NOT_FOUND";if(status===408||status===504)return"PROVIDER_TIMEOUT";if(status===429)return"PROVIDER_RATE_LIMITED";if(status>=500)return"PROVIDER_SERVER_ERROR";return"PROVIDER_INVALID_RESPONSE"}
async function readProviderJson(res:Response,provider:string){const text=await res.text();let data:any=null;try{data=JSON.parse(text)}catch{throw new ProviderError(provider,res.status,"PROVIDER_INVALID_RESPONSE")};return data}

async function requestWithRetry(provider:string,model:string,init:RequestInit,timeoutMs:number){let last:ProviderError|undefined;for(let attempt=0;attempt<=AI_CONFIG.maxRetries;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);try{const res=await fetch(init.url as string,{...init,signal:controller.signal});clearTimeout(timer);if(res.ok)return res;if(res.status===429||res.status>=500||res.status===408||res.status===504){last=new ProviderError(provider,res.status,classifyStatus(res.status),true);if(attempt<AI_CONFIG.maxRetries){await sleep(Math.min(4000,1000*(attempt+1)));continue}}throw new ProviderError(provider,res.status,classifyStatus(res.status))}catch(e){clearTimeout(timer);if(e instanceof ProviderError){last=e;if(e.retryable&&attempt<AI_CONFIG.maxRetries){await sleep(Math.min(4000,1000*(attempt+1)));continue}throw e}if(e instanceof DOMException&&e.name==="AbortError"){last=new ProviderError(provider,408,"PROVIDER_TIMEOUT",true);if(attempt<AI_CONFIG.maxRetries)continue;throw last}last=new ProviderError(provider,0,"PROVIDER_CONFIGURATION_ERROR");if(attempt<AI_CONFIG.maxRetries){await sleep(500*(attempt+1));continue}throw last}}throw last||new ProviderError(provider,0,"PROVIDER_CONFIGURATION_ERROR")}

async function callGroq(messages:AIMessage[],temperature:number){const cfg=AI_CONFIG.providers.groq;let last:ProviderError|undefined;for(const model of cfg.models){try{const res=await requestWithRetry("groq",model,{url:"https://api.groq.com/openai/v1/chat/completions",method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${SECRETS.groq}`},body:JSON.stringify({model,messages,max_tokens:cfg.maxTokens,temperature,top_p:0.9})},cfg.timeoutMs);const data=await readProviderJson(res,"groq");const content=String(data?.choices?.[0]?.message?.content||"").trim();if(!content)throw new ProviderError("groq",200,"PROVIDER_INVALID_RESPONSE");return{content,tokens:Number(data?.usage?.total_tokens||0),model}}catch(e){last=e instanceof ProviderError?e:new ProviderError("groq",0,"PROVIDER_CONFIGURATION_ERROR");if(last.status===404)continue;throw last}}throw last||new ProviderError("groq",404,"PROVIDER_NOT_FOUND")}

async function callGemini(systemPrompt:string,userPrompt:string,history:AIMessage[],temperature:number){const cfg=AI_CONFIG.providers.gemini;const model=cfg.models[0];const contents=history.filter(m=>m.role!=="system").slice(-8).map(m=>({role:m.role==="assistant"?"model":"user",parts:[{text:m.content}]}));contents.push({role:"user",parts:[{text:userPrompt}]});const body={systemInstruction:{parts:[{text:systemPrompt}]},contents,generationConfig:{maxOutputTokens:cfg.maxTokens,temperature,topP:0.9}};const res=await requestWithRetry("gemini",model,{url:`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":SECRETS.gemini},body:JSON.stringify(body)},cfg.timeoutMs);const data=await readProviderJson(res,"gemini");const content=String(data?.candidates?.[0]?.content?.parts?.map((p:any)=>p?.text||"").join("")||"").trim();if(!content)throw new ProviderError("gemini",200,"PROVIDER_INVALID_RESPONSE");return{content,tokens:Number(data?.usageMetadata?.totalTokenCount||0),model}}

async function callOpenAI(messages:AIMessage[],temperature:number){const cfg=AI_CONFIG.providers.openai;const model=cfg.models[0];const res=await requestWithRetry("openai",model,{url:"https://api.openai.com/v1/chat/completions",method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${SECRETS.openai}`},body:JSON.stringify({model,messages,max_tokens:cfg.maxTokens,temperature})},cfg.timeoutMs);const data=await readProviderJson(res,"openai");const content=String(data?.choices?.[0]?.message?.content||"").trim();if(!content)throw new ProviderError("openai",200,"PROVIDER_INVALID_RESPONSE");return{content,tokens:Number(data?.usage?.total_tokens||0),model}}

async function callWithFallback(systemPrompt:string,prompt:string,messages:AIMessage[],temperature:number):Promise<ProviderResult>{const errors:string[]=[];let fallback=false;for(const provider of AI_CONFIG.providerPriority){if(!SECRETS[provider]){errors.push(`${provider}:PROVIDER_CONFIGURATION_ERROR`);continue}try{const result=provider==="groq"?await callGroq(messages,temperature):provider==="gemini"?await callGemini(systemPrompt,prompt,messages,temperature):await callOpenAI(messages,temperature);return{...result,provider,fallbackUsed:fallback}}catch(e){const pe=e instanceof ProviderError?e:new ProviderError(provider,0,"PROVIDER_CONFIGURATION_ERROR");errors.push(`${provider}:${pe.code}:${pe.status||0}`);console.warn(`[ai-proxy] ${provider} failed (${pe.code}), continuing`);fallback=true}}throw new Error(`ALL_PROVIDERS_FAILED:${errors.join(";")}`)}

async function logUsage(p:{userId:string;feature:string;prompt:string;response:string|null;tokens:number;model:string;provider:string;latencyMs:number;success:boolean;fallbackUsed:boolean;errorMessage?:string;cacheHit?:boolean;conversationId?:string}){try{const cost=Number(p.tokens||0)*(AI_CONFIG.providers[p.provider as keyof typeof AI_CONFIG.providers]?.costPerToken||0);await supabase.from("ai_usage").insert({user_id:p.userId,feature:p.feature,prompt:p.prompt.slice(0,5000),response:p.response?.slice(0,5000)||null,tokens:p.tokens,model:p.model,provider:p.provider,estimated_cost:cost,latency_ms:p.latencyMs,success:p.success,error_message:p.errorMessage||null,cache_hit:p.cacheHit||false,fallback_used:p.fallbackUsed||false,conversation_id:p.conversationId||null})}catch(e){console.error("[ai-proxy] usage logging failed")}}
async function logMessage(p:{conversationId?:string;userId:string;role:Role;content:string;tokens:number;model:string;provider:string;feature:string;latencyMs:number}){try{await supabase.from("ai_messages").insert({conversation_id:p.conversationId||null,user_id:p.userId,role:p.role,content:p.content.slice(0,5000),tokens:p.tokens,model:p.model,provider:p.provider,feature:p.feature,latency_ms:p.latencyMs})}catch{console.error("[ai-proxy] message logging failed")}}

async function getUserId(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;try{const{data:{user}}=await supabase.auth.getUser(h.slice(7));return user?.id||null}catch{return null}}
async function getUserRole(id:string){try{const{data}=await supabase.from("users").select("role,admin_role,is_admin,admin_status").eq("id",id).maybeSingle();if(!data)return null;if(data.is_admin&&String(data.admin_status).toLowerCase()==="active")return String(data.admin_role||data.role||"admin");return String(data.role||"")}catch{return null}}

async function handle(body:AIRequest,userId:string):Promise<AIResult>{const start=Date.now();const prompt=antiInject(sanitizePrompt(body.prompt||""));const system=SYSTEM_PROMPTS[body.feature]||SYSTEM_PROMPTS["generate-text"];const temperature=TEMPERATURE_MAP[body.feature]??0.2;const messages:AIMessage[]=[{role:"system",content:system},...(body.messages||[]).filter(m=>m.role==="user"||m.role==="assistant").slice(-8).map(m=>({role:m.role,content:antiInject(sanitizePrompt(m.content))})),{role:"user",content:body.context?`Context:\n${sanitizePrompt(body.context)}\n\nRequest:\n${prompt}`:prompt}];const key=cacheKey(body);if(key){const hit=getCached(key);if(hit){const latency=Date.now()-start;await logUsage({userId,feature:body.feature,prompt,response:hit.content,tokens:hit.tokens,model:hit.model,provider:hit.provider,latencyMs:latency,success:true,fallbackUsed:false,cacheHit:true,conversationId:body.conversationId});return{success:true,content:hit.content,tokens:hit.tokens,model:hit.model,provider:hit.provider,latencyMs:latency,cached:true}}}const result=await callWithFallback(system,prompt,messages,temperature);const latency=Date.now()-start;if(key&&result.content)putCached(key,{content:result.content,tokens:result.tokens,model:result.model,provider:result.provider,insertedAt:Date.now()});await logUsage({userId,feature:body.feature,prompt,response:result.content,tokens:result.tokens,model:result.model,provider:result.provider,latencyMs:latency,success:true,fallbackUsed:result.fallbackUsed,conversationId:body.conversationId});if(["chat","marketplace-assistant","product-qa"].includes(body.feature)&&userId!=="anonymous"){await logMessage({conversationId:body.conversationId,userId,role:"user",content:prompt,tokens:0,model:result.model,provider:result.provider,feature:body.feature,latencyMs:0});await logMessage({conversationId:body.conversationId,userId,role:"assistant",content:result.content,tokens:result.tokens,model:result.model,provider:result.provider,feature:body.feature,latencyMs:latency})}return{success:true,content:result.content,tokens:result.tokens,model:result.model,provider:result.provider,latencyMs,fallbackUsed:result.fallbackUsed}}

async function streamGroq(messages:AIMessage[],temperature:number){const model=AI_CONFIG.providers.groq.models[0];const res=await fetch("https://api.groq.com/openai/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${SECRETS.groq}`},body:JSON.stringify({model,messages,max_tokens:AI_CONFIG.providers.groq.maxTokens,temperature,stream:true})});if(!res.ok||!res.body)throw new ProviderError("groq",res.status,"PROVIDER_INVALID_RESPONSE");return new ReadableStream<Uint8Array>({async start(controller){const reader=res.body!.getReader();const decoder=new TextDecoder();const encoder=new TextEncoder();let buffer="";try{for(;;){const{done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()||"";for(const line of lines){if(!line.startsWith("data: "))continue;const data=line.slice(6);if(data==="[DONE]"){controller.enqueue(encoder.encode("data: [DONE]\n\n"));controller.close();return}try{const parsed=JSON.parse(data);const content=parsed?.choices?.[0]?.delta?.content;if(content)controller.enqueue(encoder.encode(`data: ${JSON.stringify({content})}\n\n`))}catch{}}}}catch(e){controller.error(e)}}})}

Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});if(req.method==="GET"){return jsonResponse({success:Object.values(SECRETS).some(Boolean),providers:Object.fromEntries(AI_CONFIG.providerPriority.map(p=>[p,{configured:!!SECRETS[p],model:AI_CONFIG.providers[p].models[0],fallbackModels:AI_CONFIG.providers[p].models.slice(1)}])),primary:"groq",fallbackChain:["groq","gemini","openai"],cacheEnabled:AI_CONFIG.cache.enabled})}if(req.method!=="POST")return jsonResponse({success:false,error:"Method not allowed"},405);let body:AIRequest;try{body=await req.json()}catch{return jsonResponse({success:false,error:"Invalid request body"},400)}if(!body.feature||!VALID_FEATURES.includes(body.feature))return jsonResponse({success:false,error:"Invalid or missing feature"},400);if(!body.prompt&&!body.messages)return jsonResponse({success:false,error:"Missing prompt or messages"},400);const userId=await getUserId(req);if(!userId)return jsonResponse({success:false,error:"Authentication required. Please sign in to use AI features."},401);const tier=(await getUserRole(userId))?.includes("admin")?"admin":"user";if(body.feature!=="test"&&!checkRate(userId,tier))return jsonResponse({success:false,error:"Rate limit reached. Please wait a minute and try again."},429);if(body.stream&&body.feature==="chat"&&SECRETS.groq){try{const prompt=antiInject(sanitizePrompt(body.prompt||""));const messages:AIMessage[]=[{role:"system",content:SYSTEM_PROMPTS.chat},...(body.messages||[]).slice(-8).map(m=>({role:m.role,content:antiInject(sanitizePrompt(m.content))})),{role:"user",content:prompt}];return new Response(await streamGroq(messages,0.6),{headers:{...corsHeaders,"Content-Type":"text/event-stream","Cache-Control":"no-cache"}})}catch{console.warn("[ai-proxy] streaming failed; using non-streaming path")}}
try{return jsonResponse(await handle(body,userId),200)}catch(e){const message=e instanceof Error?e.message:"ALL_PROVIDERS_FAILED";console.error("[ai-proxy] request failed",message);const safe=message.startsWith("ALL_PROVIDERS_FAILED")?"AI research could not be completed because all configured AI providers failed.":"AI service is temporarily unavailable. Please try again.";await logUsage({userId,feature:body.feature,prompt:sanitizePrompt(body.prompt||""),response:null,tokens:0,model:"unknown",provider:"gateway",latencyMs:0,success:false,fallbackUsed:true,errorMessage:message});return jsonResponse({success:false,error:safe},502)}});
