import { createClient } from "npm:@supabase/supabase-js@2.110.0";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Access-Control-Allow-Headers":"Content-Type, Authorization, X-Client-Info, Apikey"};
const SUPABASE_URL=Deno.env.get("SUPABASE_URL")||"";
const supabase=createClient(SUPABASE_URL,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");
const CONFIG={
  groq:{models:["llama-3.3-70b-versatile","llama-3.1-8b-instant"],url:"https://api.groq.com/openai/v1/chat/completions",timeout:30000,cost:0.00000059},
  gemini:{models:["gemini-2.5-flash-lite"],url:"https://generativelanguage.googleapis.com/v1beta/models",timeout:30000,cost:0.000000075},
  openai:{models:["gpt-4o-mini"],url:"https://api.openai.com/v1/chat/completions",timeout:30000,cost:0.0000015}
} as const;
const KEYS={groq:Deno.env.get("GROQ_API_KEY")||"",gemini:Deno.env.get("GEMINI_API_KEY")||"",openai:Deno.env.get("OPENAI_API_KEY")||""};
const PRIORITY=["groq","gemini","openai"] as const;
type Provider=typeof PRIORITY[number];
type Role="system"|"user"|"assistant";
type Msg={role:Role;content:string};
type Req={feature:string;prompt?:string;context?:string;messages?:Msg[];conversationId?:string;stream?:boolean};
type PResult={content:string;tokens:number;model:string;provider:Provider};
const FEATURES=new Set(["chat","search","product-description","rewrite","summarize","moderate","translate","recommend","generate-text","test","product-qa","faq","marketplace-assistant"]);
const SYSTEM:Record<string,string>={chat:"You are DRIGHT AI, a marketplace intelligence assistant. Be concise, helpful and specific. Do not invent facts.",search:"You are DRIGHT Smart Search. Return only valid JSON describing search keywords and intent.","product-description":"You are DRIGHT Product Description Generator. Create clear, engaging marketplace copy.",rewrite:"You are DRIGHT Content Rewriter. Preserve meaning while improving clarity and tone.",summarize:"You are DRIGHT Content Summarizer. Capture important points concisely.",moderate:"You are DRIGHT Content Moderator. Return only valid JSON.",translate:"You are DRIGHT Translator. Preserve meaning and formatting.",recommend:"You are DRIGHT Product Recommender. Use only supplied context.","generate-text":"You are DRIGHT AI Assistant. Generate professional content based only on supplied request and evidence.",test:"Reply with a brief connection confirmation.","product-qa":"Answer only from supplied product context and say when information is unavailable.",faq:"Answer DRIGHT marketplace questions accurately and concisely.","marketplace-assistant":"Help DRIGHT buyers, sellers, affiliates and admins using supplied context."};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});
const clean=(v:unknown)=>String(v||"").replace(/\0/g,"").replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g,"").trim().slice(0,8000);
const classify=(s:number)=>s===401||s===403?"PROVIDER_AUTH_ERROR":s===404?"PROVIDER_NOT_FOUND":s===429?"PROVIDER_RATE_LIMITED":s===408||s===504?"PROVIDER_TIMEOUT":s>=500?"PROVIDER_SERVER_ERROR":"PROVIDER_INVALID_RESPONSE";
const safeReason=(provider:Provider,status:number,text:string)=>{let msg="";try{const j=JSON.parse(text);msg=String(j?.error?.message||j?.message||j?.error?.status||"")}catch{}msg=msg.replace(/[A-Za-z0-9_-]{24,}/g,"[redacted]").replace(/Bearer\s+\S+/gi,"Bearer [redacted]").slice(0,240);return `${provider}:${classify(status)}:${status}${msg?`:${msg}`:""}`};
class ProviderError extends Error{constructor(public provider:Provider,public status:number,public code:string,public reason:string){super(`${provider}:${code}`)}}
async function authUser(req:Request){const h=req.headers.get("Authorization");if(!h?.startsWith("Bearer "))return null;const{data:{user}}=await supabase.auth.getUser(h.slice(7));return user||null}
async function roleFor(id:string){const{data}=await supabase.from("users").select("role,admin_role,is_admin,admin_status").eq("id",id).maybeSingle();return data?.is_admin&&String(data.admin_status).toLowerCase()==="active"?String(data.admin_role||"admin"):String(data?.role||"")}
async function logUsage(p:{userId:string;feature:string;prompt:string;response?:string|null;tokens?:number;model:string;provider:string;latency:number;success:boolean;error?:string;fallback?:boolean}){try{const cost=CONFIG[p.provider as Provider]?.cost||0;await supabase.from("ai_usage").insert({user_id:p.userId,feature:p.feature,prompt:p.prompt.slice(0,5000),response:p.response?.slice(0,5000)||null,tokens:p.tokens||0,model:p.model||"unknown",provider:p.provider,estimated_cost:(p.tokens||0)*cost,latency_ms:p.latency,success:p.success,error_message:p.error||null,cache_hit:false,fallback_used:!!p.fallback,conversation_id:null})}catch{console.error("[ai-proxy] usage logging failed")}}
async function fetchBounded(provider:Provider,url:string,init:RequestInit,timeout:number){let last:ProviderError|undefined;for(let i=0;i<3;i++){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),timeout);try{const r=await fetch(url,{...init,signal:ctl.signal});clearTimeout(timer);if(r.ok)return r;const text=await r.text();const e=new ProviderError(provider,r.status,classify(r.status),safeReason(provider,r.status,text));if((r.status===429||r.status>=500||r.status===408||r.status===504)&&i<2){last=e;await new Promise(x=>setTimeout(x,500*(i+1)));continue}throw e}catch(e){clearTimeout(timer);if(e instanceof ProviderError)throw e;if(e instanceof DOMException&&e.name==="AbortError"){last=new ProviderError(provider,408,"PROVIDER_TIMEOUT",`${provider}:PROVIDER_TIMEOUT:408`);if(i<2)continue;throw last}last=new ProviderError(provider,0,"PROVIDER_CONFIGURATION_ERROR",`${provider}:PROVIDER_CONFIGURATION_ERROR:0`);if(i<2)continue;throw last}}throw last!}
async function groq(messages:Msg[]){let last:ProviderError|undefined;for(const model of CONFIG.groq.models){try{const r=await fetchBounded("groq",CONFIG.groq.url,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${KEYS.groq}`},body:JSON.stringify({model,messages,max_completion_tokens:2200,temperature:0.2,top_p:0.9})},CONFIG.groq.timeout);const j=await r.json();const content=String(j?.choices?.[0]?.message?.content||"").trim();if(!content)throw new ProviderError("groq",200,"PROVIDER_INVALID_RESPONSE","groq:PROVIDER_INVALID_RESPONSE:200:empty content");return{content,tokens:Number(j?.usage?.total_tokens||0),model,provider:"groq" as const}}catch(e){last=e instanceof ProviderError?e:new ProviderError("groq",0,"PROVIDER_CONFIGURATION_ERROR","groq:PROVIDER_CONFIGURATION_ERROR:0");if(last.status===404)continue;throw last}}throw last!}
async function gemini(system:string,prompt:string,history:Msg[]){const model=CONFIG.gemini.models[0];const contents=history.filter(x=>x.role!=="system").slice(-8).map(x=>({role:x.role==="assistant"?"model":"user",parts:[{text:x.content}]}));contents.push({role:"user",parts:[{text:prompt}]});const r=await fetchBounded("gemini",`${CONFIG.gemini.url}/${model}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":KEYS.gemini},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{maxOutputTokens:2200,temperature:0.2}})},CONFIG.gemini.timeout);const j=await r.json();const content=String(j?.candidates?.[0]?.content?.parts?.map((x:any)=>x?.text||"").join("")||"").trim();if(!content)throw new ProviderError("gemini",200,"PROVIDER_INVALID_RESPONSE","gemini:PROVIDER_INVALID_RESPONSE:200:empty content");return{content,tokens:Number(j?.usageMetadata?.totalTokenCount||0),model,provider:"gemini" as const}}
async function openai(messages:Msg[]){const model=CONFIG.openai.models[0];const r=await fetchBounded("openai",CONFIG.openai.url,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${KEYS.openai}`},body:JSON.stringify({model,messages,max_tokens:2200,temperature:0.2})},CONFIG.openai.timeout);const j=await r.json();const content=String(j?.choices?.[0]?.message?.content||"").trim();if(!content)throw new ProviderError("openai",200,"PROVIDER_INVALID_RESPONSE","openai:PROVIDER_INVALID_RESPONSE:200:empty content");return{content,tokens:Number(j?.usage?.total_tokens||0),model,provider:"openai" as const}}
async function fallback(userId:string,feature:string,prompt:string,system:string,messages:Msg[]){const errors:string[]=[];let usedFallback=false;for(const provider of PRIORITY){const model=CONFIG[provider].models[0];if(!KEYS[provider]){const err=`${provider}:PROVIDER_CONFIGURATION_ERROR:0:key missing`;errors.push(err);await logUsage({userId,feature,prompt,model,provider,latency:0,success:false,error:err,fallback:usedFallback});usedFallback=true;continue}const start=Date.now();try{const result:PResult=provider==="groq"?await groq(messages):provider==="gemini"?await gemini(system,prompt,messages):await openai(messages);await logUsage({userId,feature,prompt,response:result.content,tokens:result.tokens,model:result.model,provider,latency:Date.now()-start,success:true,fallback:usedFallback});return{...result,fallbackUsed:usedFallback}}catch(e){const pe=e instanceof ProviderError?e:new ProviderError(provider,0,"PROVIDER_CONFIGURATION_ERROR",`${provider}:PROVIDER_CONFIGURATION_ERROR:0`);errors.push(pe.reason);console.error(`[ai-proxy] provider failure ${pe.reason}`);await logUsage({userId,feature,prompt,model,provider,latency:Date.now()-start,success:false,error:pe.reason,fallback:usedFallback});usedFallback=true}}throw new Error(`ALL_PROVIDERS_FAILED:${errors.join(";")}`)}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response(null,{status:200,headers:corsHeaders});if(req.method==="GET")return json({success:Object.values(KEYS).some(Boolean),providers:Object.fromEntries(PRIORITY.map(p=>[p,{configured:!!KEYS[p],model:CONFIG[p].models[0],fallbackModels:CONFIG[p].models.slice(1)}])),primary:"groq",fallbackChain:PRIORITY});if(req.method!=="POST")return json({success:false,error:"Method not allowed"},405);const user=await authUser(req);if(!user)return json({success:false,error:"Authentication required."},401);let body:Req;try{body=await req.json()}catch{return json({success:false,error:"Invalid request body"},400)}if(!FEATURES.has(String(body.feature||"")))return json({success:false,error:"Invalid or missing feature"},400);const prompt=clean(body.prompt||"");if(!prompt&&!body.messages?.length)return json({success:false,error:"Missing prompt or messages"},400);const system=SYSTEM[body.feature]||SYSTEM["generate-text"];const finalPrompt=body.context?`Context:\n${clean(body.context)}\n\nRequest:\n${prompt}`:prompt;const messages:Msg[]=[{role:"system",content:system},...(body.messages||[]).filter(x=>x.role==="user"||x.role==="assistant").slice(-8).map(x=>({role:x.role,content:clean(x.content)})),{role:"user",content:finalPrompt}];try{const result=await fallback(user.id,body.feature,prompt,system,messages);return json({success:true,content:result.content,tokens:result.tokens,model:result.model,provider:result.provider,fallbackUsed:result.fallbackUsed})}catch(e){const internal=e instanceof Error?e.message:"ALL_PROVIDERS_FAILED";console.error(`[ai-proxy] ${internal}`);await logUsage({userId:user.id,feature:body.feature,prompt,model:"unknown",provider:"gateway",latency:0,success:false,error:internal,fallback:true});return json({success:false,error:{code:"AI_PROVIDER_FAILURE",message:"DRIGHT AI is temporarily unavailable. Provider diagnostics are available to authorized administrators."}},502)}});