begin;
create temporary table tmp_taxonomy_paths_v2(listing_type_code text not null,path_names text[] not null) on commit drop;
insert into tmp_taxonomy_paths_v2 values
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Standard Smartphones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Foldable Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Flip Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Gaming Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Rugged Smartphones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones','Compact Smartphones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Feature Phones','Basic Feature Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Feature Phones','Rugged Feature Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Feature Phones','Easy-Use & Senior Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','Android Tablets']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','Apple iPad']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','Windows Tablets']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','Kids Tablets']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','Rugged Tablets']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets','E-Readers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Cases & Covers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Screen Protectors']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Camera Lens Protectors']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Wall Chargers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Car Chargers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Wireless Chargers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Charging Cables']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Power Banks']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Phone Mounts']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Phone Stands']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Selfie Sticks & Tripods']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Styluses']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Mobile Game Controllers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Replacement Batteries']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Replacement Screens']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Repair Parts']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','SIM & eSIM Accessories']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Adapters & Dongles']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Phone Camera Lenses']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Cleaning Kits']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Grip Holders & Rings']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Waterproof Pouches']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories','Mobile Microphones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables','Smartwatches']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables','Fitness Trackers']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables','Smart Rings']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables','Kids Smartwatches']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables','Wearable Accessories']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Mobile Hotspots & MiFi']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Satellite Phones']::text[]),
('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Walkie Talkies & Two-Way Radios']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Laptops','Ultrabooks']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Laptops','Gaming Laptops']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Laptops','Business Laptops']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Laptops','2-in-1 Laptops']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Laptops','Mobile Workstations']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers','All-in-One PCs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers','Gaming Desktops']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers','Business Desktops']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers','Mini PCs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers','Workstations']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Monitors','Office Monitors']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Monitors','Gaming Monitors']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Monitors','Ultrawide Monitors']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Monitors','Portable Monitors']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Monitors','Professional Color Monitors']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice','Keyboards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice','Mice']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice','Keyboard & Mouse Combos']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice','Gaming Keyboards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice','Gaming Mice']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Processors / CPUs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Graphics Cards / GPUs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Motherboards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Desktop RAM']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Laptop RAM']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Internal SSDs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Internal Hard Drives']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Power Supplies']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','PC Cases']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','CPU Coolers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Case Fans']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Sound Cards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Capture Cards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Components','Expansion Cards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','External SSDs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','External Hard Drives']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','USB Flash Drives']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','Memory Cards']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','NAS Storage']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices','RAID Enclosures']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Wi-Fi Routers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Mesh Wi-Fi Systems']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Modems']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Network Switches']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Access Points']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Network Adapters']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment','Ethernet Cables']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Printers & Scanners','Inkjet Printers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Printers & Scanners','Laser Printers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Printers & Scanners','Photo Printers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Printers & Scanners','3D Printers']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Printers & Scanners','Document Scanners']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','Laptop Bags & Sleeves']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','Laptop Stands']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','Docking Stations']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','USB Hubs']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','Webcams']::text[]),
('PHYSICAL', ARRAY['Electronics','Computers','Computer Accessories','Cooling Pads']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions','LED TVs']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions','OLED TVs']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions','Mini-LED TVs']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions','QLED TVs']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions','Smart TVs']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Projectors','Home Projectors']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Projectors','Portable Projectors']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Projectors','Business Projectors']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Speakers','Bluetooth Speakers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Speakers','Bookshelf Speakers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Speakers','Floorstanding Speakers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Speakers','Smart Speakers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Headphones & Earbuds','Wireless Earbuds']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Headphones & Earbuds','Over-Ear Headphones']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Headphones & Earbuds','On-Ear Headphones']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Headphones & Earbuds','Wired Earphones']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Home Theater','Soundbars']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Home Theater','AV Receivers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Home Theater','Subwoofers']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Streaming Devices']::text[]),
('PHYSICAL', ARRAY['Electronics','TV & Audio','Media Players']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras','Mirrorless Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras','DSLR Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras','Compact Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras','Instant Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras','Action Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Lenses','Prime Lenses']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Lenses','Zoom Lenses']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Lenses','Cinema Lenses']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Drones','Camera Drones']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Drones','FPV Drones']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Drones','Professional Drones']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories','Tripods']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories','Gimbals']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories','Camera Bags']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories','Camera Batteries']::text[]),
('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories','Flashes & Lighting']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Game Consoles','Home Consoles']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Game Consoles','Handheld Consoles']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Video Games','PlayStation Games']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Video Games','Xbox Games']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Video Games','Nintendo Games']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Video Games','PC Games']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories','Controllers']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories','Gaming Headsets']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories','Steering Wheels']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories','Arcade Sticks']::text[]),
('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories','VR Headsets']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Security Cameras','Indoor Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Security Cameras','Outdoor Cameras']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Security Cameras','Video Doorbells']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Lighting','Smart Bulbs']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Lighting','Smart Light Strips']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Plugs']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Locks']::text[]),
('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Sensors']::text[]),
('PHYSICAL', ARRAY['Fashion','Men','Formal Shirts']::text[]),
('PHYSICAL', ARRAY['Fashion','Men','Casual Shirts']::text[]),
('PHYSICAL', ARRAY['Fashion','Men','Jeans']::text[]),
('PHYSICAL', ARRAY['Fashion','Men','Shorts']::text[]),
('PHYSICAL', ARRAY['Fashion','Men','Jackets & Coats']::text[]),
('PHYSICAL', ARRAY['Fashion','Women','Evening Dresses']::text[]),
('PHYSICAL', ARRAY['Fashion','Women','Casual Dresses']::text[]),
('PHYSICAL', ARRAY['Fashion','Women','Jeans']::text[]),
('PHYSICAL', ARRAY['Fashion','Women','Jumpsuits']::text[]),
('PHYSICAL', ARRAY['Fashion','Women','Jackets & Coats']::text[]),
('PHYSICAL', ARRAY['Fashion','Shoes','Running Shoes']::text[]),
('PHYSICAL', ARRAY['Fashion','Shoes','Formal Shoes']::text[]),
('PHYSICAL', ARRAY['Fashion','Shoes','Heels']::text[]),
('PHYSICAL', ARRAY['Fashion','Shoes','Loafers']::text[]),
('PHYSICAL', ARRAY['Fashion','Shoes','Sports Shoes']::text[]),
('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Laptop Bags']::text[]),
('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Travel Bags']::text[]),
('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Sunglasses']::text[]),
('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Hats & Caps']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Skin Care','Face Cleansers']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Skin Care','Moisturizers']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Skin Care','Serums']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Skin Care','Sunscreen']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Hair Care','Shampoo']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Hair Care','Conditioner']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Hair Care','Hair Oils']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Makeup & Cosmetics','Foundation']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Makeup & Cosmetics','Lip Makeup']::text[]),
('PHYSICAL', ARRAY['Health & Beauty','Makeup & Cosmetics','Eye Makeup']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Furniture','Sofas']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Furniture','Beds']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Furniture','Dining Tables']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Furniture','Office Chairs']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Cookware','Pots & Pans']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Cookware','Bakeware']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Kitchen Tools','Knives']::text[]),
('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Kitchen Tools','Utensils']::text[]),
('PHYSICAL', ARRAY['Home Appliances','Small Appliances','Blenders']::text[]),
('PHYSICAL', ARRAY['Home Appliances','Small Appliances','Air Fryers']::text[]),
('PHYSICAL', ARRAY['Home Appliances','Small Appliances','Coffee Makers']::text[]),
('PHYSICAL', ARRAY['Home Appliances','Small Appliances','Electric Kettles']::text[]),
('PHYSICAL', ARRAY['Automotive','Auto Parts','Engine Parts']::text[]),
('PHYSICAL', ARRAY['Automotive','Auto Parts','Brake Parts']::text[]),
('PHYSICAL', ARRAY['Automotive','Auto Parts','Suspension Parts']::text[]),
('PHYSICAL', ARRAY['Automotive','Auto Parts','Electrical Parts']::text[]),
('PHYSICAL', ARRAY['Automotive','Car Electronics','Car Stereos']::text[]),
('PHYSICAL', ARRAY['Automotive','Car Electronics','Dash Cameras']::text[]),
('PHYSICAL', ARRAY['Automotive','Car Electronics','GPS Navigation']::text[]),
('PHYSICAL', ARRAY['Medical Supplies','Diagnostic Equipment','Blood Pressure Monitors']::text[]),
('PHYSICAL', ARRAY['Medical Supplies','Diagnostic Equipment','Thermometers']::text[]),
('PHYSICAL', ARRAY['Medical Supplies','Diagnostic Equipment','Pulse Oximeters']::text[]),
('PHYSICAL', ARRAY['Medical Supplies','Mobility Aids','Wheelchairs']::text[]),
('PHYSICAL', ARRAY['Medical Supplies','Mobility Aids','Walking Aids']::text[]),
('DIGITAL', ARRAY['Software & Digital','Software','Operating Systems']::text[]),
('DIGITAL', ARRAY['Software & Digital','Software','Security Software']::text[]),
('DIGITAL', ARRAY['Software & Digital','Software','Office & Productivity']::text[]),
('DIGITAL', ARRAY['Software & Digital','Software','Creative Software']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Website Templates','HTML Templates']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Website Templates','WordPress Themes']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Website Templates','Shopify Themes']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Canva Templates','Social Media Templates']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Canva Templates','Business Templates']::text[]),
('DIGITAL', ARRAY['Software & Digital','Templates','Presentation Templates','Pitch Deck Templates']::text[]),
('DIGITAL', ARRAY['Development','Source Code','Web App Source Code']::text[]),
('DIGITAL', ARRAY['Development','Source Code','Mobile App Source Code']::text[]),
('DIGITAL', ARRAY['Development','Source Code','Game Source Code']::text[]),
('DIGITAL', ARRAY['Development','Themes','WordPress Themes']::text[]),
('DIGITAL', ARRAY['Development','Themes','Shopify Themes']::text[]),
('DIGITAL', ARRAY['Design','Stock Graphics','Vectors']::text[]),
('DIGITAL', ARRAY['Design','Stock Graphics','Textures']::text[]),
('DIGITAL', ARRAY['Design','Stock Graphics','Patterns']::text[]),
('DIGITAL', ARRAY['Design','Fonts','Serif Fonts']::text[]),
('DIGITAL', ARRAY['Design','Fonts','Sans Serif Fonts']::text[]),
('DIGITAL', ARRAY['AI Assets','AI Prompt Packs','ChatGPT Prompts']::text[]),
('DIGITAL', ARRAY['AI Assets','AI Prompt Packs','Image Generation Prompts']::text[]),
('DIGITAL', ARRAY['AI Assets','AI Workflows','Automation Workflows']::text[]),
('DIGITAL', ARRAY['AI Assets','AI Workflows','Agent Workflows']::text[]),
('DIGITAL', ARRAY['Photography & Video','Video Templates','After Effects Templates']::text[]),
('DIGITAL', ARRAY['Photography & Video','Video Templates','Premiere Pro Templates']::text[]),
('DIGITAL', ARRAY['Photography & Video','LUTs & Presets','Lightroom Presets']::text[]),
('DIGITAL', ARRAY['Photography & Video','LUTs & Presets','Video LUTs']::text[]),
('DIGITAL', ARRAY['Data & Spreadsheets','Dashboards','Excel Dashboards']::text[]),
('DIGITAL', ARRAY['Data & Spreadsheets','Dashboards','Google Sheets Dashboards']::text[]),
('DIGITAL', ARRAY['Data & Spreadsheets','Dashboards','Power BI Templates']::text[]),
('SERVICE', ARRAY['Development','Web Development','Frontend Development']::text[]),
('SERVICE', ARRAY['Development','Web Development','Backend Development']::text[]),
('SERVICE', ARRAY['Development','Web Development','Full Stack Development']::text[]),
('SERVICE', ARRAY['Development','Web Development','Landing Pages']::text[]),
('SERVICE', ARRAY['Development','Mobile App Development','iOS Development']::text[]),
('SERVICE', ARRAY['Development','Mobile App Development','Android Development']::text[]),
('SERVICE', ARRAY['Development','Mobile App Development','Cross-Platform Apps']::text[]),
('SERVICE', ARRAY['Development','E-commerce Development','Shopify Development']::text[]),
('SERVICE', ARRAY['Development','E-commerce Development','WooCommerce Development']::text[]),
('SERVICE', ARRAY['Design','Graphic Design','Logo Design']::text[]),
('SERVICE', ARRAY['Design','Graphic Design','Social Media Design']::text[]),
('SERVICE', ARRAY['Design','Graphic Design','Print Design']::text[]),
('SERVICE', ARRAY['Design','UI & UX Design','Mobile App UI']::text[]),
('SERVICE', ARRAY['Design','UI & UX Design','Website UI']::text[]),
('SERVICE', ARRAY['Design','UI & UX Design','UX Research']::text[]),
('SERVICE', ARRAY['Marketing','Social Media Marketing','Instagram Marketing']::text[]),
('SERVICE', ARRAY['Marketing','Social Media Marketing','TikTok Marketing']::text[]),
('SERVICE', ARRAY['Marketing','Social Media Marketing','Facebook Marketing']::text[]),
('SERVICE', ARRAY['Marketing','Social Media Marketing','LinkedIn Marketing']::text[]),
('SERVICE', ARRAY['Marketing','SEO','Technical SEO']::text[]),
('SERVICE', ARRAY['Marketing','SEO','Local SEO']::text[]),
('SERVICE', ARRAY['Marketing','SEO','E-commerce SEO']::text[]),
('SERVICE', ARRAY['Marketing','SEO','Keyword Research']::text[]),
('SERVICE', ARRAY['Business','Virtual Assistant','Executive Virtual Assistant']::text[]),
('SERVICE', ARRAY['Business','Virtual Assistant','E-commerce Virtual Assistant']::text[]),
('SERVICE', ARRAY['Business','Virtual Assistant','Real Estate Virtual Assistant']::text[]),
('SERVICE', ARRAY['Data & Analytics','Data Analysis','Excel Analysis']::text[]),
('SERVICE', ARRAY['Data & Analytics','Data Analysis','Python Data Analysis']::text[]),
('SERVICE', ARRAY['Data & Analytics','Data Visualization','Power BI']::text[]),
('SERVICE', ARRAY['Data & Analytics','Data Visualization','Tableau']::text[]),
('SERVICE', ARRAY['AI Services','AI Automation','Business Automation']::text[]),
('SERVICE', ARRAY['AI Services','AI Automation','Workflow Automation']::text[]),
('SERVICE', ARRAY['AI Services','Chatbot Development','Customer Support Chatbots']::text[]),
('SERVICE', ARRAY['AI Services','AI Agent Development','Sales Agents']::text[]),
('SERVICE', ARRAY['AI Services','AI Agent Development','Research Agents']::text[]),
('SERVICE', ARRAY['Video & Animation','Video Editing','YouTube Video Editing']::text[]),
('SERVICE', ARRAY['Video & Animation','Video Editing','Short-Form Video Editing']::text[]),
('SERVICE', ARRAY['Video & Animation','Animation','2D Animation']::text[]),
('SERVICE', ARRAY['Video & Animation','Animation','3D Animation']::text[]),
('SERVICE', ARRAY['Home Services','Cleaning','Home Cleaning']::text[]),
('SERVICE', ARRAY['Home Services','Cleaning','Office Cleaning']::text[]),
('SERVICE', ARRAY['Home Services','Plumbing','Pipe Repair']::text[]),
('SERVICE', ARRAY['Home Services','Electrical Repair','Wiring & Installation']::text[]),
('SERVICE', ARRAY['Home Services','Appliance Repair','Refrigerator Repair']::text[]),
('SERVICE', ARRAY['Home Services','Appliance Repair','Washing Machine Repair']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Frontend Engineering','React Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Frontend Engineering','Vue Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Frontend Engineering','Angular Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Backend Engineering','Node.js Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Backend Engineering','Python Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Backend Engineering','Java Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Backend Engineering','.NET Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Software Engineering','Full Stack Engineering','MERN Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Mobile Development','iOS Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Mobile Development','Android Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Mobile Development','Flutter Developer']::text[]),
('JOB', ARRAY['Technology & Engineering','Data Science','Data Scientist']::text[]),
('JOB', ARRAY['Technology & Engineering','Machine Learning & AI','Machine Learning Engineer']::text[]),
('JOB', ARRAY['Technology & Engineering','Machine Learning & AI','AI Engineer']::text[]),
('JOB', ARRAY['Advertising & Marketing','Digital Marketing','Digital Marketing Manager']::text[]),
('JOB', ARRAY['Advertising & Marketing','Social Media Management','Social Media Manager']::text[]),
('JOB', ARRAY['Advertising & Marketing','SEO','SEO Specialist']::text[]),
('JOB', ARRAY['Advertising & Marketing','Paid Media','PPC Specialist']::text[]),
('JOB', ARRAY['Design & Creative','Graphic Design','Graphic Designer']::text[]),
('JOB', ARRAY['Design & Creative','UI & UX Design','UI Designer']::text[]),
('JOB', ARRAY['Design & Creative','UI & UX Design','UX Designer']::text[]),
('JOB', ARRAY['Design & Creative','Video Editing','Video Editor']::text[]),
('JOB', ARRAY['YouTube Automation','YouTube Video Editor','Long-Form Editor']::text[]),
('JOB', ARRAY['YouTube Automation','YouTube Video Editor','Shorts Editor']::text[]),
('JOB', ARRAY['YouTube Automation','Thumbnail Designer','YouTube Thumbnail Designer']::text[]),
('JOB', ARRAY['YouTube Automation','YouTube Scriptwriter','Long-Form Scriptwriter']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','Web Development','Frontend Web Development']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','Web Development','Backend Web Development']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','Web Development','Full Stack Web Development']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','Python','Python Fundamentals']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','Python','Python Automation']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','JavaScript','JavaScript Fundamentals']::text[]),
('COURSE', ARRAY['Technology & Engineering','Programming','JavaScript','React']::text[]),
('COURSE', ARRAY['Technology & Engineering','Data & AI','Data Science','Python for Data Science']::text[]),
('COURSE', ARRAY['Technology & Engineering','Data & AI','Machine Learning','Machine Learning Fundamentals']::text[]),
('COURSE', ARRAY['Technology & Engineering','Data & AI','Generative AI','Prompt Engineering']::text[]),
('COURSE', ARRAY['Technology & Engineering','Data & AI','Generative AI','AI Agents']::text[]),
('COURSE', ARRAY['Business','Project Management','Agile & Scrum']::text[]),
('COURSE', ARRAY['Business','Sales','B2B Sales']::text[]),
('COURSE', ARRAY['Marketing','Paid Advertising','Google Ads']::text[]),
('COURSE', ARRAY['Marketing','Paid Advertising','Meta Ads']::text[]),
('COURSE', ARRAY['Design & Creative','UI & UX Design','Figma']::text[]),
('COURSE', ARRAY['Finance & Accounting','Financial Analysis','Financial Modeling']::text[]),
('COURSE', ARRAY['Languages','English','Business English']::text[]),
('COURSE', ARRAY['Trades & Vocational','Automotive Repair','Auto Repair Basics']::text[]),
('TASK', ARRAY['Digital Task','Data Entry','Spreadsheet Data Entry']::text[]),
('TASK', ARRAY['Digital Task','Data Entry','CRM Data Entry']::text[]),
('TASK', ARRAY['Digital Task','Web Research','Product Research']::text[]),
('TASK', ARRAY['Digital Task','Web Research','Company Research']::text[]),
('TASK', ARRAY['Digital Task','App Testing','Android App Testing']::text[]),
('TASK', ARRAY['Digital Task','App Testing','iOS App Testing']::text[]),
('TASK', ARRAY['Digital Task','Website Testing','Usability Testing']::text[]),
('TASK', ARRAY['Digital Task','Social Media Engagement','Like & Follow Tasks']::text[]),
('TASK', ARRAY['Digital Task','Social Media Engagement','Comment Tasks']::text[]),
('TASK', ARRAY['Digital Task','Lead Collection','Business Leads']::text[]),
('TASK', ARRAY['Digital Task','File Conversion','PDF Conversion']::text[]),
('TASK', ARRAY['Local Task','Delivery & Errands','Food Delivery']::text[]),
('TASK', ARRAY['Local Task','Delivery & Errands','Parcel Delivery']::text[]),
('TASK', ARRAY['Local Task','Shopping & Pickup','Grocery Pickup']::text[]),
('TASK', ARRAY['Local Task','Cleaning & Home Help','Home Cleaning']::text[]),
('TASK', ARRAY['Local Task','Moving Help','Loading & Unloading']::text[]),
('TASK', ARRAY['Local Task','Pet Care','Dog Walking']::text[]),
('TASK', ARRAY['Local Task','Handyman Task','Furniture Assembly']::text[]);

do $$
declare r record; v_parent uuid; v_id uuid; v_name text; v_slug text; v_depth integer; v_last integer;
begin
  for r in select * from tmp_taxonomy_paths_v2 order by listing_type_code,cardinality(path_names),path_names loop
    v_parent:=null; v_last:=cardinality(r.path_names);
    for v_depth in 1..v_last loop
      v_name:=trim(r.path_names[v_depth]);
      v_slug:=trim(both '-' from regexp_replace(lower(v_name),'[^a-z0-9]+','-','g'));
      select c.id into v_id from public.marketplace_taxonomy_categories c
       where c.listing_type_code=r.listing_type_code
         and ((v_parent is null and c.parent_id is null) or c.parent_id=v_parent)
         and lower(c.slug)=lower(v_slug) order by c.created_at limit 1;
      if v_id is null then
        insert into public.marketplace_taxonomy_categories(listing_type_code,parent_id,name,slug,sort_order,is_leaf,is_active,metadata)
        values(r.listing_type_code,v_parent,v_name,v_slug,100,v_depth=v_last,true,'{"seed_kind":"taxonomy_spec_expansion_v2"}'::jsonb)
        returning id into v_id;
      else
        update public.marketplace_taxonomy_categories set is_active=true,is_leaf=case when v_depth<v_last then false else is_leaf end,updated_at=now() where id=v_id;
      end if;
      if v_parent is not null then update public.marketplace_taxonomy_categories set is_leaf=false,updated_at=now() where id=v_parent and is_leaf=true; end if;
      v_parent:=v_id;
    end loop;
  end loop;
end $$;

update public.marketplace_attribute_definitions d set options='["8 GB","16 GB","32 GB","64 GB","128 GB","256 GB","512 GB","1 TB","2 TB","3 TB","4 TB","Other / Custom"]'::jsonb,validation='{"market_reference":"2026-current-plus-future-proof","verified_current_high":"2 TB","future_values":["3 TB","4 TB"]}'::jsonb,updated_at=now()
from public.marketplace_taxonomy_categories c where d.category_id=c.id and c.listing_type_code='PHYSICAL' and c.slug='smartphones' and d.attribute_key='storage_gb' and d.is_active=true;
update public.marketplace_attribute_definitions d set options='["1 GB","2 GB","3 GB","4 GB","6 GB","8 GB","12 GB","16 GB","18 GB","20 GB","24 GB","32 GB","36 GB","48 GB","64 GB","Other / Custom"]'::jsonb,validation='{"market_reference":"2026-current-plus-future-proof","verified_current_high":"24 GB","future_values":["32 GB","36 GB","48 GB","64 GB"]}'::jsonb,updated_at=now()
from public.marketplace_taxonomy_categories c where d.category_id=c.id and c.listing_type_code='PHYSICAL' and c.slug='smartphones' and d.attribute_key='ram_gb' and d.is_active=true;
update public.marketplace_attribute_definitions d set options='["128 GB","256 GB","512 GB","1 TB","2 TB","4 TB","8 TB","16 TB","Other / Custom"]'::jsonb,validation='{"market_reference":"2026-current-plus-future-proof","verified_current_high":"8 TB"}'::jsonb,updated_at=now()
from public.marketplace_taxonomy_categories c where d.category_id=c.id and c.listing_type_code='PHYSICAL' and c.slug='laptops' and d.attribute_key='storage_size_gb' and d.is_active=true;
update public.marketplace_attribute_definitions d set options='["4 GB","8 GB","12 GB","16 GB","18 GB","24 GB","32 GB","36 GB","48 GB","64 GB","96 GB","128 GB","192 GB","256 GB","Other / Custom"]'::jsonb,validation='{"market_reference":"2026-current-plus-future-proof","verified_current_high":"128 GB"}'::jsonb,updated_at=now()
from public.marketplace_taxonomy_categories c where d.category_id=c.id and c.listing_type_code='PHYSICAL' and c.slug='laptops' and d.attribute_key='ram_gb' and d.is_active=true;

create temporary table tmp_attribute_specs(category_slug text,attribute_key text,label text,input_type text,options jsonb,validation jsonb,sort_order integer,is_filterable boolean,is_searchable boolean,is_sortable boolean,is_comparable boolean,show_on_card boolean) on commit drop;
insert into tmp_attribute_specs values
('smartphones','form_factor','Phone Type','select','["Standard","Foldable","Flip","Gaming","Rugged","Compact"]','{}',170,true,true,false,true,true),
('smartphones','operating_system','Operating System','select','["Android","iOS","HarmonyOS","Other"]','{}',180,true,true,false,true,true),
('smartphones','screen_size','Screen Size','select','["Under 5.5 inch","5.5-5.9 inch","6.0-6.4 inch","6.5-6.9 inch","7.0 inch and above"]','{}',190,true,false,false,true,false),
('smartphones','refresh_rate_hz','Refresh Rate','select','["60 Hz","90 Hz","120 Hz","144 Hz","165 Hz","185 Hz","Other"]','{}',200,true,false,true,true,false),
('smartphones','chipset','Chipset / Processor','text','[]','{"maxLength":120}',210,true,true,false,true,false),
('smartphones','battery_capacity_mah','Battery Capacity (mAh)','number','[]','{"min":500,"max":20000}',220,true,false,true,true,false),
('smartphones','wired_charging_w','Wired Charging (W)','number','[]','{"min":0,"max":500}',230,true,false,true,true,false),
('smartphones','wireless_charging','Wireless Charging','toggle','[]','{}',240,true,false,false,true,false),
('smartphones','esim_support','eSIM Support','toggle','[]','{}',250,true,false,false,true,false),
('smartphones','water_resistance','Water / Dust Resistance','select','["None / Not Rated","IP52","IP54","IP55","IP65","IP67","IP68","IP69","Other"]','{}',260,true,false,false,true,false),

('tablets','storage_gb','Storage','select','["16 GB","32 GB","64 GB","128 GB","256 GB","512 GB","1 TB","2 TB","3 TB","4 TB","Other / Custom"]'::jsonb,'{"market_reference":"2026-current-plus-future-proof"}',110,true,true,true,true,true),
('tablets','ram_gb','RAM','select','["1 GB","2 GB","3 GB","4 GB","6 GB","8 GB","12 GB","16 GB","18 GB","24 GB","32 GB","48 GB","64 GB","Other / Custom"]'::jsonb,'{"market_reference":"2026-current-plus-future-proof"}',120,true,true,true,true,true),
('tablets','operating_system','Operating System','select','["Android","iPadOS","Windows","ChromeOS","Other"]','{}',130,true,true,false,true,true),
('tablets','screen_size','Screen Size','select','["Under 8 inch","8-9.9 inch","10-10.9 inch","11-11.9 inch","12-12.9 inch","13-13.9 inch","14 inch and above"]','{}',140,true,false,false,true,false),
('tablets','cellular_support','Cellular Connectivity','select','["Wi-Fi Only","4G LTE","5G"]','{}',150,true,false,false,true,false),
('tablets','stylus_support','Stylus Support','toggle','[]','{}',160,true,false,false,true,false),
('tablets','keyboard_support','Keyboard Support','toggle','[]','{}',170,true,false,false,true,false),

('phone-accessories','accessory_type','Accessory Type','select','["Case / Cover","Screen Protector","Lens Protector","Wall Charger","Car Charger","Wireless Charger","Charging Cable","Power Bank","Mount","Stand","Selfie Stick / Tripod","Stylus","Game Controller","Replacement Battery","Replacement Screen","Repair Part","SIM Accessory","Adapter / Dongle","Camera Lens","Cleaning Kit","Grip / Ring","Waterproof Pouch","Mobile Microphone","Other"]','{}',110,true,true,false,true,true),
('phone-accessories','compatible_brand','Compatible Brand','text','[]','{"maxLength":100}',120,true,true,false,true,true),
('phone-accessories','compatible_models','Compatible Models','tags','[]','{}',130,true,true,false,true,false),
('phone-accessories','connector_type','Connector Type','select','["USB-C","Lightning","Micro-USB","USB-A","3.5 mm","MagSafe","Qi / Qi2","Proprietary","None","Other"]','{}',140,true,false,false,true,false),
('phone-accessories','max_power_w','Maximum Power (W)','number','[]','{"min":0,"max":1000}',150,true,false,true,true,false),
('phone-accessories','cable_length_m','Cable Length (m)','number','[]','{"min":0,"max":100}',160,true,false,true,false,false),
('phone-accessories','power_bank_capacity_mah','Power Bank Capacity (mAh)','number','[]','{"min":0,"max":1000000}',170,true,false,true,true,false),
('phone-accessories','wireless_standard','Wireless Standard','select','["None","Qi","Qi2","MagSafe Compatible","Other"]','{}',180,true,false,false,true,false),
('phone-accessories','material','Material','text','[]','{"maxLength":100}',190,true,false,false,false,false),

('smartwatches-wearables','wearable_type','Wearable Type','select','["Smartwatch","Fitness Tracker","Smart Ring","Kids Smartwatch","Other"]','{}',110,true,true,false,true,true),
('smartwatches-wearables','storage','Storage','select','["4 GB","8 GB","16 GB","32 GB","64 GB","128 GB","256 GB","Other / Custom"]','{}',120,true,false,true,true,false),
('smartwatches-wearables','ram','RAM','select','["512 MB","1 GB","2 GB","3 GB","4 GB","6 GB","8 GB","12 GB","16 GB","Other / Custom"]','{}',130,true,false,true,true,false),
('smartwatches-wearables','gps','Built-in GPS','toggle','[]','{}',140,true,false,false,true,false),
('smartwatches-wearables','cellular','Cellular / LTE','toggle','[]','{}',150,true,false,false,true,false),

('desktop-computers','ram_gb','RAM','select','["8 GB","16 GB","32 GB","48 GB","64 GB","96 GB","128 GB","192 GB","256 GB","512 GB","1 TB","Other / Custom"]','{}',110,true,true,true,true,true),
('desktop-computers','storage','Storage','select','["256 GB","512 GB","1 TB","2 TB","4 TB","8 TB","16 TB","32 TB","64 TB","Other / Custom"]','{}',120,true,true,true,true,true),
('desktop-computers','processor','Processor','text','[]','{"maxLength":120}',130,true,true,false,true,false),
('desktop-computers','gpu','Graphics','text','[]','{"maxLength":120}',140,true,true,false,true,false),

('computer-components','component_type','Component Type','select','["CPU","GPU","Motherboard","RAM","SSD","HDD","Power Supply","PC Case","CPU Cooler","Case Fan","Sound Card","Capture Card","Expansion Card","Other"]','{}',110,true,true,false,true,true),
('computer-components','capacity','Capacity / Size','text','[]','{"maxLength":100}',120,true,true,false,true,false),
('computer-components','interface','Interface / Socket','text','[]','{"maxLength":100}',130,true,true,false,true,false),

('game-consoles','storage','Storage','select','["64 GB","128 GB","256 GB","512 GB","1 TB","2 TB","4 TB","8 TB","Other / Custom"]','{}',110,true,true,true,true,true);

insert into public.marketplace_attribute_definitions(listing_type_code,category_id,attribute_key,label,input_type,is_required,is_searchable,is_filterable,is_sortable,is_comparable,show_on_card,show_on_details,options,validation,sort_order,schema_version,is_active)
select 'PHYSICAL',c.id,s.attribute_key,s.label,s.input_type,false,s.is_searchable,s.is_filterable,s.is_sortable,s.is_comparable,s.show_on_card,true,s.options,s.validation,s.sort_order,1,true
from tmp_attribute_specs s join public.marketplace_taxonomy_categories c on c.listing_type_code='PHYSICAL' and c.slug=s.category_slug and c.is_active=true
where not exists(select 1 from public.marketplace_attribute_definitions d where d.listing_type_code='PHYSICAL' and d.category_id=c.id and d.attribute_key=s.attribute_key and d.schema_version=1);

update public.marketplace_attribute_definitions d
set label=s.label,input_type=s.input_type,options=s.options,validation=s.validation,sort_order=s.sort_order,is_filterable=s.is_filterable,is_searchable=s.is_searchable,is_sortable=s.is_sortable,is_comparable=s.is_comparable,show_on_card=s.show_on_card,show_on_details=true,is_active=true,updated_at=now()
from tmp_attribute_specs s join public.marketplace_taxonomy_categories c on c.listing_type_code='PHYSICAL' and c.slug=s.category_slug and c.is_active=true
where d.listing_type_code='PHYSICAL' and d.category_id=c.id and d.attribute_key=s.attribute_key and d.schema_version=1;
commit;