/* DRIGHT2 verified achievement evidence + explainable growth ranking. */
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('achievement-evidence','achievement-evidence',false,20971520,ARRAY['application/pdf','image/jpeg','image/png','image/webp']::text[])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=EXCLUDED.file_size_limit,allowed_mime_types=EXCLUDED.allowed_mime_types;

ALTER TABLE public.user_achievements ADD COLUMN IF NOT EXISTS verification_status text NOT NULL DEFAULT 'unverified';
ALTER TABLE public.user_achievements ADD COLUMN IF NOT EXISTS verified_by uuid REFERENCES public.users(id);
ALTER TABLE public.user_achievements ADD COLUMN IF NOT EXISTS verified_at timestamptz;
ALTER TABLE public.user_achievements ADD COLUMN IF NOT EXISTS verification_source text NOT NULL DEFAULT 'user_claim';
ALTER TABLE public.user_achievements ADD COLUMN IF NOT EXISTS verification_note text;
DO $$ BEGIN ALTER TABLE public.user_achievements ADD CONSTRAINT user_achievements_verification_status_check CHECK(verification_status IN('unverified','submitted','under_review','verified','rejected','needs_more_evidence','system_verified')); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DROP POLICY IF EXISTS insert_own_achievement ON public.user_achievements;
CREATE POLICY insert_own_achievement ON public.user_achievements FOR INSERT TO authenticated WITH CHECK(auth.uid()=user_id AND verification_status='unverified' AND verified_by IS NULL AND verified_at IS NULL);
DROP POLICY IF EXISTS user_achievements_admin_update ON public.user_achievements;
CREATE POLICY user_achievements_admin_update ON public.user_achievements FOR UPDATE TO authenticated USING(public.has_dright_permission('badges','review_evidence')) WITH CHECK(public.has_dright_permission('badges','review_evidence'));

CREATE TABLE IF NOT EXISTS public.achievement_evidence(
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,user_achievement_id uuid REFERENCES public.user_achievements(id) ON DELETE SET NULL,achievement_id uuid REFERENCES public.achievements(id) ON DELETE SET NULL,title text NOT NULL,description text,evidence_type text NOT NULL DEFAULT 'document' CHECK(evidence_type IN('document','image','certificate','portfolio','external_link','platform_record','other')),external_url text,storage_bucket text,storage_path text,original_file_name text,mime_type text,size_bytes bigint,status text NOT NULL DEFAULT 'submitted' CHECK(status IN('submitted','under_review','verified','rejected','needs_more_evidence')),reviewer_id uuid REFERENCES public.users(id),reviewed_at timestamptz,user_visible_reason text,is_deleted boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT achievement_evidence_location CHECK((evidence_type='external_link' AND external_url IS NOT NULL) OR evidence_type='platform_record' OR (storage_bucket='achievement-evidence' AND storage_path IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_achievement_evidence_user ON public.achievement_evidence(user_id,created_at DESC); CREATE INDEX IF NOT EXISTS idx_achievement_evidence_status ON public.achievement_evidence(status,created_at DESC); ALTER TABLE public.achievement_evidence ENABLE ROW LEVEL SECURITY;
CREATE TABLE IF NOT EXISTS public.achievement_evidence_reviews(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),evidence_id uuid NOT NULL REFERENCES public.achievement_evidence(id) ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,reviewer_id uuid NOT NULL REFERENCES public.users(id),previous_status text,decision text NOT NULL CHECK(decision IN('under_review','verified','rejected','needs_more_evidence')),new_status text NOT NULL,user_visible_reason text,internal_note text,authenticity_checks jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now()); CREATE INDEX IF NOT EXISTS idx_achievement_evidence_reviews_evidence ON public.achievement_evidence_reviews(evidence_id,created_at DESC); ALTER TABLE public.achievement_evidence_reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS achievement_evidence_own_read ON public.achievement_evidence; CREATE POLICY achievement_evidence_own_read ON public.achievement_evidence FOR SELECT TO authenticated USING(user_id=auth.uid() AND is_deleted=false);
DROP POLICY IF EXISTS achievement_evidence_own_insert ON public.achievement_evidence; CREATE POLICY achievement_evidence_own_insert ON public.achievement_evidence FOR INSERT TO authenticated WITH CHECK(user_id=auth.uid() AND status='submitted' AND reviewer_id IS NULL AND reviewed_at IS NULL AND (storage_bucket IS NULL OR storage_bucket='achievement-evidence'));
DROP POLICY IF EXISTS achievement_evidence_admin_read ON public.achievement_evidence; CREATE POLICY achievement_evidence_admin_read ON public.achievement_evidence FOR SELECT TO authenticated USING(public.has_dright_permission('badges','view_evidence'));
DROP POLICY IF EXISTS achievement_evidence_admin_update ON public.achievement_evidence; CREATE POLICY achievement_evidence_admin_update ON public.achievement_evidence FOR UPDATE TO authenticated USING(public.has_dright_permission('badges','review_evidence')) WITH CHECK(public.has_dright_permission('badges','review_evidence'));
DROP POLICY IF EXISTS achievement_evidence_reviews_own_read ON public.achievement_evidence_reviews; CREATE POLICY achievement_evidence_reviews_own_read ON public.achievement_evidence_reviews FOR SELECT TO authenticated USING(user_id=auth.uid());
DROP POLICY IF EXISTS achievement_evidence_reviews_admin_read ON public.achievement_evidence_reviews; CREATE POLICY achievement_evidence_reviews_admin_read ON public.achievement_evidence_reviews FOR SELECT TO authenticated USING(public.has_dright_permission('badges','view_evidence'));
DROP POLICY IF EXISTS users_upload_own_achievement_evidence ON storage.objects; CREATE POLICY users_upload_own_achievement_evidence ON storage.objects FOR INSERT TO authenticated WITH CHECK(bucket_id='achievement-evidence' AND owner=auth.uid() AND (storage.foldername(name))[1]=auth.uid()::text);
DROP POLICY IF EXISTS users_read_own_achievement_evidence ON storage.objects; CREATE POLICY users_read_own_achievement_evidence ON storage.objects FOR SELECT TO authenticated USING(bucket_id='achievement-evidence' AND owner=auth.uid() AND (storage.foldername(name))[1]=auth.uid()::text);
DROP POLICY IF EXISTS reviewers_read_achievement_evidence ON storage.objects; CREATE POLICY reviewers_read_achievement_evidence ON storage.objects FOR SELECT TO authenticated USING(bucket_id='achievement-evidence' AND public.has_dright_permission('badges','view_evidence'));
DROP POLICY IF EXISTS badge_assignments_manage_admin ON public.badge_assignments;
DROP POLICY IF EXISTS badge_assignments_manage_authorized ON public.badge_assignments;
CREATE POLICY badge_assignments_manage_authorized ON public.badge_assignments FOR ALL TO authenticated USING(public.has_dright_permission('badges','assign')) WITH CHECK(public.has_dright_permission('badges','assign'));

CREATE OR REPLACE FUNCTION public.review_achievement_evidence(p_evidence_id uuid,p_decision text,p_user_visible_reason text DEFAULT NULL,p_internal_note text DEFAULT NULL,p_authenticity_checks jsonb DEFAULT '{}'::jsonb)
RETURNS public.achievement_evidence LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_row public.achievement_evidence%ROWTYPE;v_old text;
BEGIN
 IF NOT public.has_dright_permission('badges','review_evidence') THEN RAISE EXCEPTION 'permission denied'; END IF;
 IF p_decision NOT IN('under_review','verified','rejected','needs_more_evidence') THEN RAISE EXCEPTION 'invalid decision'; END IF;
 IF p_decision IN('rejected','needs_more_evidence') AND nullif(trim(coalesce(p_user_visible_reason,'')),'') IS NULL THEN RAISE EXCEPTION 'user-visible reason is required'; END IF;
 SELECT * INTO v_row FROM public.achievement_evidence WHERE id=p_evidence_id AND is_deleted=false FOR UPDATE; IF v_row.id IS NULL THEN RAISE EXCEPTION 'evidence not found'; END IF; v_old:=v_row.status;
 UPDATE public.achievement_evidence SET status=p_decision,reviewer_id=auth.uid(),reviewed_at=now(),user_visible_reason=p_user_visible_reason,updated_at=now() WHERE id=p_evidence_id RETURNING * INTO v_row;
 INSERT INTO public.achievement_evidence_reviews(evidence_id,user_id,reviewer_id,previous_status,decision,new_status,user_visible_reason,internal_note,authenticity_checks) VALUES(v_row.id,v_row.user_id,auth.uid(),v_old,p_decision,p_decision,p_user_visible_reason,p_internal_note,coalesce(p_authenticity_checks,'{}'::jsonb));
 IF v_row.user_achievement_id IS NOT NULL THEN UPDATE public.user_achievements SET verification_status=CASE WHEN p_decision='verified' THEN 'verified' ELSE p_decision END,verified_by=CASE WHEN p_decision='verified' THEN auth.uid() ELSE verified_by END,verified_at=CASE WHEN p_decision='verified' THEN now() ELSE verified_at END,verification_source='manual',verification_note=p_user_visible_reason WHERE id=v_row.user_achievement_id AND user_id=v_row.user_id; END IF;
 INSERT INTO public.admin_activity_logs(admin_id,action,resource_type,resource_id,details) VALUES(auth.uid(),'achievement_evidence_'||p_decision,'achievement_evidence',v_row.id,jsonb_build_object('user_id',v_row.user_id,'previous_status',v_old,'checks',coalesce(p_authenticity_checks,'{}'::jsonb)));
 INSERT INTO public.notifications(user_id,title,message,notification_type,related_id,category,priority,metadata) VALUES(v_row.user_id,'Achievement verification update',CASE WHEN p_decision='verified' THEN 'Your submitted achievement evidence was verified.' WHEN p_decision='needs_more_evidence' THEN 'More evidence is required for your achievement. '||coalesce(p_user_visible_reason,'') WHEN p_decision='rejected' THEN 'Your achievement evidence was not verified. '||coalesce(p_user_visible_reason,'') ELSE 'Your achievement evidence is under review.' END,'achievement_verification',v_row.id,'account',CASE WHEN p_decision IN('rejected','needs_more_evidence') THEN 'high' ELSE 'normal' END,jsonb_build_object('status',p_decision));
 RETURN v_row;
END;$$;
REVOKE ALL ON FUNCTION public.review_achievement_evidence(uuid,text,text,text,jsonb) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.review_achievement_evidence(uuid,text,text,text,jsonb) TO authenticated;

CREATE TABLE IF NOT EXISTS public.growth_ranking_rules(metric_key text PRIMARY KEY,label text NOT NULL,weight numeric(10,4) NOT NULL DEFAULT 1,cap numeric(12,2),is_active boolean NOT NULL DEFAULT true,description text,updated_by uuid REFERENCES public.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now()); ALTER TABLE public.growth_ranking_rules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS growth_ranking_rules_read ON public.growth_ranking_rules; CREATE POLICY growth_ranking_rules_read ON public.growth_ranking_rules FOR SELECT TO authenticated USING(is_active=true OR public.has_dright_permission('badges','manage_ranking'));
DROP POLICY IF EXISTS growth_ranking_rules_manage ON public.growth_ranking_rules; CREATE POLICY growth_ranking_rules_manage ON public.growth_ranking_rules FOR ALL TO authenticated USING(public.has_dright_permission('badges','manage_ranking')) WITH CHECK(public.has_dright_permission('badges','manage_ranking'));
INSERT INTO public.growth_ranking_rules(metric_key,label,weight,cap,description) VALUES('verified_achievements','Verified achievements',8,120,'Only manually verified or system-verified achievements'),('active_badges','Active verified/admin-issued badges',10,100,'Active badge assignments'),('trust_score','Trust score',0.5,50,'Existing DRIGHT trust score contribution'),('completed_sales','Completed sales',1,100,'Existing platform sales history'),('rating_quality','Average rating quality',10,50,'Existing average rating scaled to five stars') ON CONFLICT(metric_key) DO NOTHING;
CREATE TABLE IF NOT EXISTS public.user_growth_scores(user_id uuid PRIMARY KEY REFERENCES public.users(id) ON DELETE CASCADE,score numeric(12,2) NOT NULL DEFAULT 0,growth_level text NOT NULL DEFAULT 'emerging',components jsonb NOT NULL DEFAULT '{}'::jsonb,rank_position integer,calculated_at timestamptz NOT NULL DEFAULT now(),calculation_version integer NOT NULL DEFAULT 1); CREATE INDEX IF NOT EXISTS idx_user_growth_scores_score ON public.user_growth_scores(score DESC,calculated_at DESC); ALTER TABLE public.user_growth_scores ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS user_growth_scores_public_read ON public.user_growth_scores; CREATE POLICY user_growth_scores_public_read ON public.user_growth_scores FOR SELECT TO authenticated USING(true);

CREATE OR REPLACE FUNCTION public.recalculate_user_growth_score(p_user_id uuid)
RETURNS public.user_growth_scores LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$
DECLARE v_verified numeric:=0;v_badges numeric:=0;v_trust numeric:=0;v_sales numeric:=0;v_rating numeric:=0;v_score numeric:=0;v_components jsonb;v_row public.user_growth_scores%ROWTYPE;v_weight numeric;v_cap numeric;
BEGIN
 IF auth.uid() IS DISTINCT FROM p_user_id AND NOT public.has_dright_permission('badges','manage_ranking') AND NOT public.has_dright_permission('users','view') THEN RAISE EXCEPTION 'permission denied'; END IF;
 SELECT count(*) INTO v_verified FROM public.user_achievements WHERE user_id=p_user_id AND verification_status IN('verified','system_verified');
 SELECT count(*) INTO v_badges FROM public.badge_assignments WHERE user_id=p_user_id AND is_active=true AND is_deleted=false AND (expires_at IS NULL OR expires_at>now());
 SELECT coalesce(score,0) INTO v_trust FROM public.trust_scores WHERE user_id=p_user_id;
 SELECT coalesce(total_sales_count,0),coalesce(average_rating,0) INTO v_sales,v_rating FROM public.users WHERE id=p_user_id;
 SELECT weight,cap INTO v_weight,v_cap FROM public.growth_ranking_rules WHERE metric_key='verified_achievements' AND is_active=true; v_score:=v_score+least(v_verified*coalesce(v_weight,0),coalesce(v_cap,999999));
 SELECT weight,cap INTO v_weight,v_cap FROM public.growth_ranking_rules WHERE metric_key='active_badges' AND is_active=true; v_score:=v_score+least(v_badges*coalesce(v_weight,0),coalesce(v_cap,999999));
 SELECT weight,cap INTO v_weight,v_cap FROM public.growth_ranking_rules WHERE metric_key='trust_score' AND is_active=true; v_score:=v_score+least(v_trust*coalesce(v_weight,0),coalesce(v_cap,999999));
 SELECT weight,cap INTO v_weight,v_cap FROM public.growth_ranking_rules WHERE metric_key='completed_sales' AND is_active=true; v_score:=v_score+least(v_sales*coalesce(v_weight,0),coalesce(v_cap,999999));
 SELECT weight,cap INTO v_weight,v_cap FROM public.growth_ranking_rules WHERE metric_key='rating_quality' AND is_active=true; v_score:=v_score+least(v_rating*coalesce(v_weight,0),coalesce(v_cap,999999));
 v_components:=jsonb_build_object('verified_achievements',v_verified,'active_badges',v_badges,'trust_score',v_trust,'completed_sales',v_sales,'average_rating',v_rating,'explanation','Score uses DRIGHT platform facts and verified evidence; no AI-only approval signal is used.');
 INSERT INTO public.user_growth_scores(user_id,score,growth_level,components,calculated_at) VALUES(p_user_id,v_score,CASE WHEN v_score>=250 THEN 'established' WHEN v_score>=120 THEN 'growing' WHEN v_score>=40 THEN 'developing' ELSE 'emerging' END,v_components,now()) ON CONFLICT(user_id) DO UPDATE SET score=EXCLUDED.score,growth_level=EXCLUDED.growth_level,components=EXCLUDED.components,calculated_at=now() RETURNING * INTO v_row;
 RETURN v_row;
END;$$;
REVOKE ALL ON FUNCTION public.recalculate_user_growth_score(uuid) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.recalculate_user_growth_score(uuid) TO authenticated;
CREATE OR REPLACE FUNCTION public.refresh_growth_rank_positions() RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public,pg_temp AS $$ DECLARE v_count integer; BEGIN IF NOT public.has_dright_permission('badges','manage_ranking') THEN RAISE EXCEPTION 'permission denied'; END IF; WITH ranked AS(SELECT user_id,row_number() OVER(ORDER BY score DESC,calculated_at ASC,user_id) AS pos FROM public.user_growth_scores) UPDATE public.user_growth_scores s SET rank_position=r.pos FROM ranked r WHERE r.user_id=s.user_id; GET DIAGNOSTICS v_count=ROW_COUNT; RETURN v_count; END;$$;
REVOKE ALL ON FUNCTION public.refresh_growth_rank_positions() FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.refresh_growth_rank_positions() TO authenticated;