-- DRIGHT2 broad taxonomy expansion v1
-- Idempotent and additive: existing category ids are preserved.
-- No legacy listing, Sales Team, promotion, fee, checkout, wallet, order,
-- payout, or accounting tables are modified.

begin;

create temporary table tmp_taxonomy_paths(
  listing_type_code text not null,
  path_names text[] not null
) on commit drop;

insert into tmp_taxonomy_paths(listing_type_code,path_names)
values
    ('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartphones' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Feature Phones' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Tablets' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Phone Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Phones & Tablets','Smartwatches & Wearables' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Laptops' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Desktop Computers' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Monitors' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Keyboards & Mice' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Computer Components' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Storage Devices' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Computers','Networking Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','TV & Audio','Televisions' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','TV & Audio','Speakers' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','TV & Audio','Headphones & Earbuds' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','TV & Audio','Home Theater' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Cameras','Digital Cameras' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Cameras','Lenses' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Cameras','Drones' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Cameras','Camera Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Gaming','Game Consoles' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Gaming','Video Games' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Gaming','Gaming Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Smart Home','Security Cameras' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Lighting' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Smart Home','Smart Speakers' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Power & Charging','Power Banks' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Power & Charging','Chargers & Cables' ]::text[]),
    ('PHYSICAL', ARRAY['Electronics','Power & Charging','Batteries & UPS' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Men','Shirts' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Men','T-Shirts' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Men','Trousers' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Men','Suits' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Men','Underwear' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Women','Dresses' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Women','Tops' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Women','Trousers & Jeans' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Women','Skirts' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Women','Lingerie' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Shoes','Men''s Shoes' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Shoes','Women''s Shoes' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Shoes','Sneakers' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Shoes','Sandals & Slippers' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Shoes','Boots' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Handbags' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Backpacks' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Wallets' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Bags & Accessories','Belts' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Traditional & Cultural Wear','African Wear' ]::text[]),
    ('PHYSICAL', ARRAY['Fashion','Traditional & Cultural Wear','Religious Clothing' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Skin Care' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Hair Care' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Makeup & Cosmetics' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Fragrances' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Personal Care' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Oral Care' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Men''s Grooming' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Bath & Body' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Beauty Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Wigs & Hair Extensions' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','Wellness Devices' ]::text[]),
    ('PHYSICAL', ARRAY['Health & Beauty','First Aid' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Furniture','Living Room Furniture' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Furniture','Bedroom Furniture' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Furniture','Office Furniture' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Furniture','Outdoor Furniture' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Cookware' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Dinnerware' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Kitchen Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Kitchen & Dining','Food Storage' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Home Decor','Lighting' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Home Decor','Curtains & Blinds' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Home Decor','Rugs & Carpets' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Home Decor','Wall Decor' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Bedding & Bath','Bedding' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Bedding & Bath','Towels' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Bedding & Bath','Bathroom Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Garden & Outdoor','Gardening Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Garden & Outdoor','Plants & Seeds' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Garden & Outdoor','Outdoor Decor' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Cleaning Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Home & Garden','Storage & Organization' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Fresh Food' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Packaged Food' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Snacks' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Beverages' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Coffee & Tea' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Bakery' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Dairy & Eggs' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Meat & Seafood' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Spices & Seasonings' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Cooking Ingredients' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Health Foods' ]::text[]),
    ('PHYSICAL', ARRAY['Food & Beverage','Baby Food' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Exercise Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Gym Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Football' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Basketball' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Running' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Cycling' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Swimming' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Combat Sports' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Outdoor Recreation' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Team Sports' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Sportswear' ]::text[]),
    ('PHYSICAL', ARRAY['Sports & Fitness','Fitness Trackers' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Books' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Textbooks' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Children''s Books' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Comics & Manga' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Magazines' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Music CDs & Vinyl' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Movies & TV' ]::text[]),
    ('PHYSICAL', ARRAY['Books & Media','Educational Media' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Action Figures' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Dolls' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Educational Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Board Games' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Puzzles' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Remote Control Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Outdoor Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Building Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Toys & Games','Collectible Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Cars' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Motorcycles' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Auto Parts' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Motorcycle Parts' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Tires & Wheels' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Car Electronics' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Car Care' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Interior Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Exterior Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Tools & Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Automotive','Helmets & Riding Gear' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Baby Clothing' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Kids Clothing' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Baby Gear' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Strollers' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Car Seats' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Feeding' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Diapers & Potty' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Nursery' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Baby Care' ]::text[]),
    ('PHYSICAL', ARRAY['Baby & Kids','Kids Shoes' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Dog Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Cat Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Bird Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Fish & Aquarium' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Pet Food' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Pet Beds' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Pet Toys' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Pet Grooming' ]::text[]),
    ('PHYSICAL', ARRAY['Pet Supplies','Pet Health' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Stationery' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Office Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','School Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Printers & Ink' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Desks & Chairs' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Filing & Storage' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Calculators' ]::text[]),
    ('PHYSICAL', ARRAY['Office & School','Art Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Industrial Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Lab Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Measurement Instruments' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Electrical Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Safety Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Manufacturing Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Packaging Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Industrial & Scientific','Commercial Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Watches' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Necklaces' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Rings' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Earrings' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Bracelets' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Fine Jewelry' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Fashion Jewelry' ]::text[]),
    ('PHYSICAL', ARRAY['Jewelry & Watches','Jewelry Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Painting Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Drawing Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Sewing & Fabric' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Knitting & Crochet' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Craft Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Beads & Jewelry Making' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','Scrapbooking' ]::text[]),
    ('PHYSICAL', ARRAY['Arts & Crafts','DIY Kits' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Guitars' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Keyboards & Pianos' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Drums & Percussion' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Wind Instruments' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','String Instruments' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','DJ Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Studio Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Musical Instruments','Instrument Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Hand Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Power Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Hardware' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Plumbing' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Electrical' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Paint Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Building Materials' ]::text[]),
    ('PHYSICAL', ARRAY['Tools & Hardware','Tool Storage' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Refrigerators' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Freezers' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Washing Machines' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Air Conditioners' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Fans' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Microwaves' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Cookers & Ovens' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Small Appliances' ]::text[]),
    ('PHYSICAL', ARRAY['Home Appliances','Water Heaters' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Farm Tools' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Seeds' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Fertilizers' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Irrigation' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Livestock Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Poultry Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Animal Feed' ]::text[]),
    ('PHYSICAL', ARRAY['Agriculture & Farming','Farm Machinery' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Diagnostic Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Mobility Aids' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Hospital Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Protective Equipment' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Home Care Supplies' ]::text[]),
    ('PHYSICAL', ARRAY['Medical Supplies','Medical Consumables' ]::text[]),
    ('PHYSICAL', ARRAY['Travel & Luggage','Suitcases' ]::text[]),
    ('PHYSICAL', ARRAY['Travel & Luggage','Travel Bags' ]::text[]),
    ('PHYSICAL', ARRAY['Travel & Luggage','Travel Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Travel & Luggage','Passport Holders' ]::text[]),
    ('PHYSICAL', ARRAY['Travel & Luggage','Travel Organizers' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Antiques' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Coins & Currency' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Stamps' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Sports Collectibles' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Trading Cards' ]::text[]),
    ('PHYSICAL', ARRAY['Collectibles & Antiques','Memorabilia' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','Locks' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','Alarms' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','CCTV Accessories' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','Fire Safety' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','Protective Gear' ]::text[]),
    ('PHYSICAL', ARRAY['Safety & Security','Access Control' ]::text[]),
    ('PHYSICAL', ARRAY['Religious & Cultural','Religious Books' ]::text[]),
    ('PHYSICAL', ARRAY['Religious & Cultural','Prayer Items' ]::text[]),
    ('PHYSICAL', ARRAY['Religious & Cultural','Religious Clothing' ]::text[]),
    ('PHYSICAL', ARRAY['Religious & Cultural','Cultural Artifacts' ]::text[]),
    ('PHYSICAL', ARRAY['Religious & Cultural','Ceremonial Items' ]::text[]),
    ('PHYSICAL', ARRAY['Other & Miscellaneous','Other Physical Goods' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Software','Desktop Software' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Software','Mobile Apps' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Software','Plugins & Extensions' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Software','SaaS Access' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Website Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Canva Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Presentation Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Spreadsheet Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Notion Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Templates','Resume Templates' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','E-books','Fiction E-books' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','E-books','Nonfiction E-books' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','E-books','Guides & Manuals' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Audio & Music','Music Tracks' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Audio & Music','Sound Effects' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Audio & Music','Beats & Instrumentals' ]::text[]),
    ('DIGITAL', ARRAY['Software & Digital','Audio & Music','Podcasts & Audio Programs' ]::text[]),
    ('DIGITAL', ARRAY['Design','Logos & Branding Kits' ]::text[]),
    ('DIGITAL', ARRAY['Design','Social Media Graphics' ]::text[]),
    ('DIGITAL', ARRAY['Design','Icons' ]::text[]),
    ('DIGITAL', ARRAY['Design','Illustrations' ]::text[]),
    ('DIGITAL', ARRAY['Design','Fonts' ]::text[]),
    ('DIGITAL', ARRAY['Design','UI Kits' ]::text[]),
    ('DIGITAL', ARRAY['Design','Mockups' ]::text[]),
    ('DIGITAL', ARRAY['Design','Print Templates' ]::text[]),
    ('DIGITAL', ARRAY['Design','3D Models' ]::text[]),
    ('DIGITAL', ARRAY['Design','Stock Graphics' ]::text[]),
    ('DIGITAL', ARRAY['Design','Infographics' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Articles & Blog Content' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Copywriting Packs' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Scripts' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Email Templates' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Business Writing' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Academic Materials' ]::text[]),
    ('DIGITAL', ARRAY['Writing','Prompt Packs' ]::text[]),
    ('DIGITAL', ARRAY['Development','Source Code' ]::text[]),
    ('DIGITAL', ARRAY['Development','Website Scripts' ]::text[]),
    ('DIGITAL', ARRAY['Development','APIs & Integrations' ]::text[]),
    ('DIGITAL', ARRAY['Development','Automation Scripts' ]::text[]),
    ('DIGITAL', ARRAY['Development','Themes' ]::text[]),
    ('DIGITAL', ARRAY['Development','Game Assets' ]::text[]),
    ('DIGITAL', ARRAY['Development','Code Templates' ]::text[]),
    ('DIGITAL', ARRAY['Development','Developer Tools' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Marketing Plans' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Ad Creatives' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Social Media Content Packs' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','SEO Resources' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Email Marketing Assets' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Sales Funnels' ]::text[]),
    ('DIGITAL', ARRAY['Marketing','Lead Magnets' ]::text[]),
    ('DIGITAL', ARRAY['Education','Study Notes' ]::text[]),
    ('DIGITAL', ARRAY['Education','Worksheets' ]::text[]),
    ('DIGITAL', ARRAY['Education','Lesson Plans' ]::text[]),
    ('DIGITAL', ARRAY['Education','Exam Prep Materials' ]::text[]),
    ('DIGITAL', ARRAY['Education','Flashcards' ]::text[]),
    ('DIGITAL', ARRAY['Education','Educational Printables' ]::text[]),
    ('DIGITAL', ARRAY['Education','Research Papers' ]::text[]),
    ('DIGITAL', ARRAY['Business','Business Plans' ]::text[]),
    ('DIGITAL', ARRAY['Business','Contracts & Forms' ]::text[]),
    ('DIGITAL', ARRAY['Business','Invoices & Finance Templates' ]::text[]),
    ('DIGITAL', ARRAY['Business','HR Templates' ]::text[]),
    ('DIGITAL', ARRAY['Business','Project Management Templates' ]::text[]),
    ('DIGITAL', ARRAY['Business','Pitch Decks' ]::text[]),
    ('DIGITAL', ARRAY['Business','SOP Templates' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','Stock Photos' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','Stock Video' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','LUTs & Presets' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','Video Templates' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','Motion Graphics' ]::text[]),
    ('DIGITAL', ARRAY['Photography & Video','Photo Presets' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Datasets' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Dashboards' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Financial Models' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Trackers' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Calculators' ]::text[]),
    ('DIGITAL', ARRAY['Data & Spreadsheets','Data Templates' ]::text[]),
    ('DIGITAL', ARRAY['AI Assets','AI Prompt Packs' ]::text[]),
    ('DIGITAL', ARRAY['AI Assets','AI Workflows' ]::text[]),
    ('DIGITAL', ARRAY['AI Assets','Custom GPT Instructions' ]::text[]),
    ('DIGITAL', ARRAY['AI Assets','AI Image Prompt Packs' ]::text[]),
    ('DIGITAL', ARRAY['AI Assets','Automation Blueprints' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Planners' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Calendars' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Invitations' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Coloring Pages' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Labels & Stickers' ]::text[]),
    ('DIGITAL', ARRAY['Printables','Wall Art' ]::text[]),
    ('DIGITAL', ARRAY['Other & Miscellaneous','Other Digital Goods' ]::text[]),
    ('SERVICE', ARRAY['Writing','Article Writing' ]::text[]),
    ('SERVICE', ARRAY['Writing','Copywriting' ]::text[]),
    ('SERVICE', ARRAY['Writing','Technical Writing' ]::text[]),
    ('SERVICE', ARRAY['Writing','Ghostwriting' ]::text[]),
    ('SERVICE', ARRAY['Writing','Resume & CV Writing' ]::text[]),
    ('SERVICE', ARRAY['Writing','Scriptwriting' ]::text[]),
    ('SERVICE', ARRAY['Writing','Grant Writing' ]::text[]),
    ('SERVICE', ARRAY['Writing','Translation' ]::text[]),
    ('SERVICE', ARRAY['Writing','Transcription' ]::text[]),
    ('SERVICE', ARRAY['Design','Logo Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Brand Identity' ]::text[]),
    ('SERVICE', ARRAY['Design','Graphic Design' ]::text[]),
    ('SERVICE', ARRAY['Design','UI & UX Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Web Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Presentation Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Packaging Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Illustration' ]::text[]),
    ('SERVICE', ARRAY['Design','3D Design' ]::text[]),
    ('SERVICE', ARRAY['Design','Motion Design' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Business Consulting' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Strategy Consulting' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Management Consulting' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Startup Consulting' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Operations Consulting' ]::text[]),
    ('SERVICE', ARRAY['Consulting','Career Consulting' ]::text[]),
    ('SERVICE', ARRAY['Development','Web Development' ]::text[]),
    ('SERVICE', ARRAY['Development','Mobile App Development' ]::text[]),
    ('SERVICE', ARRAY['Development','E-commerce Development' ]::text[]),
    ('SERVICE', ARRAY['Development','WordPress' ]::text[]),
    ('SERVICE', ARRAY['Development','Shopify' ]::text[]),
    ('SERVICE', ARRAY['Development','Backend Development' ]::text[]),
    ('SERVICE', ARRAY['Development','Frontend Development' ]::text[]),
    ('SERVICE', ARRAY['Development','Full Stack Development' ]::text[]),
    ('SERVICE', ARRAY['Development','Automation & Integrations' ]::text[]),
    ('SERVICE', ARRAY['Development','API Development' ]::text[]),
    ('SERVICE', ARRAY['Development','Database Development' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Social Media Marketing' ]::text[]),
    ('SERVICE', ARRAY['Marketing','SEO' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Search Ads' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Social Ads' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Email Marketing' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Content Marketing' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Influencer Marketing' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Affiliate Marketing' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Marketing Strategy' ]::text[]),
    ('SERVICE', ARRAY['Marketing','Community Management' ]::text[]),
    ('SERVICE', ARRAY['Education','Tutoring' ]::text[]),
    ('SERVICE', ARRAY['Education','Language Lessons' ]::text[]),
    ('SERVICE', ARRAY['Education','Coding Lessons' ]::text[]),
    ('SERVICE', ARRAY['Education','Music Lessons' ]::text[]),
    ('SERVICE', ARRAY['Education','Academic Coaching' ]::text[]),
    ('SERVICE', ARRAY['Education','Test Preparation' ]::text[]),
    ('SERVICE', ARRAY['Education','Homework Help' ]::text[]),
    ('SERVICE', ARRAY['Business','Virtual Assistant' ]::text[]),
    ('SERVICE', ARRAY['Business','Data Entry' ]::text[]),
    ('SERVICE', ARRAY['Business','Market Research' ]::text[]),
    ('SERVICE', ARRAY['Business','Lead Generation' ]::text[]),
    ('SERVICE', ARRAY['Business','Project Management' ]::text[]),
    ('SERVICE', ARRAY['Business','Customer Support' ]::text[]),
    ('SERVICE', ARRAY['Business','CRM Management' ]::text[]),
    ('SERVICE', ARRAY['Business','E-commerce Management' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Video Editing' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Short-form Video Editing' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Animation' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Explainer Videos' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','YouTube Editing' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Color Grading' ]::text[]),
    ('SERVICE', ARRAY['Video & Animation','Subtitles & Captions' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Voice Over' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Audio Editing' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Mixing & Mastering' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Music Production' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Podcast Editing' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Sound Design' ]::text[]),
    ('SERVICE', ARRAY['Music & Audio','Jingles' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Data Analysis' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Data Visualization' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Dashboard Creation' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Excel Services' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Power BI' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Tableau' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Data Cleaning' ]::text[]),
    ('SERVICE', ARRAY['Data & Analytics','Web Scraping' ]::text[]),
    ('SERVICE', ARRAY['AI Services','AI Automation' ]::text[]),
    ('SERVICE', ARRAY['AI Services','Chatbot Development' ]::text[]),
    ('SERVICE', ARRAY['AI Services','AI Consulting' ]::text[]),
    ('SERVICE', ARRAY['AI Services','Prompt Engineering' ]::text[]),
    ('SERVICE', ARRAY['AI Services','AI Content Systems' ]::text[]),
    ('SERVICE', ARRAY['AI Services','AI Agent Development' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Bookkeeping' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Accounting' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Tax Preparation' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Financial Modeling' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Payroll' ]::text[]),
    ('SERVICE', ARRAY['Finance & Accounting','Financial Consulting' ]::text[]),
    ('SERVICE', ARRAY['Legal Services','Contract Review' ]::text[]),
    ('SERVICE', ARRAY['Legal Services','Legal Research' ]::text[]),
    ('SERVICE', ARRAY['Legal Services','Business Registration Support' ]::text[]),
    ('SERVICE', ARRAY['Legal Services','Policy Drafting' ]::text[]),
    ('SERVICE', ARRAY['Legal Services','Trademark Support' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','Recruiting' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','Candidate Sourcing' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','Interview Support' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','HR Consulting' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','Job Description Writing' ]::text[]),
    ('SERVICE', ARRAY['HR & Recruitment','Onboarding Support' ]::text[]),
    ('SERVICE', ARRAY['Cybersecurity','Security Audit' ]::text[]),
    ('SERVICE', ARRAY['Cybersecurity','Penetration Testing' ]::text[]),
    ('SERVICE', ARRAY['Cybersecurity','Vulnerability Assessment' ]::text[]),
    ('SERVICE', ARRAY['Cybersecurity','Security Consulting' ]::text[]),
    ('SERVICE', ARRAY['Cybersecurity','Incident Response' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','Architectural Design' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','CAD Drafting' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','Interior Design' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','Structural Engineering' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','Electrical Engineering' ]::text[]),
    ('SERVICE', ARRAY['Architecture & Engineering','Mechanical Engineering' ]::text[]),
    ('SERVICE', ARRAY['Photography','Portrait Photography' ]::text[]),
    ('SERVICE', ARRAY['Photography','Product Photography' ]::text[]),
    ('SERVICE', ARRAY['Photography','Event Photography' ]::text[]),
    ('SERVICE', ARRAY['Photography','Photo Editing' ]::text[]),
    ('SERVICE', ARRAY['Photography','Retouching' ]::text[]),
    ('SERVICE', ARRAY['Events','Event Planning' ]::text[]),
    ('SERVICE', ARRAY['Events','Wedding Planning' ]::text[]),
    ('SERVICE', ARRAY['Events','Event Decoration' ]::text[]),
    ('SERVICE', ARRAY['Events','MC & Hosting' ]::text[]),
    ('SERVICE', ARRAY['Events','Catering Coordination' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Cleaning' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Plumbing' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Electrical Repair' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Carpentry' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Painting' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Home Repair' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Appliance Repair' ]::text[]),
    ('SERVICE', ARRAY['Home Services','Gardening' ]::text[]),
    ('SERVICE', ARRAY['Automotive Services','Vehicle Repair' ]::text[]),
    ('SERVICE', ARRAY['Automotive Services','Vehicle Inspection' ]::text[]),
    ('SERVICE', ARRAY['Automotive Services','Car Wash & Detailing' ]::text[]),
    ('SERVICE', ARRAY['Automotive Services','Tire Services' ]::text[]),
    ('SERVICE', ARRAY['Automotive Services','Auto Electrical' ]::text[]),
    ('SERVICE', ARRAY['Logistics & Delivery','Courier Service' ]::text[]),
    ('SERVICE', ARRAY['Logistics & Delivery','Local Delivery' ]::text[]),
    ('SERVICE', ARRAY['Logistics & Delivery','Moving Services' ]::text[]),
    ('SERVICE', ARRAY['Logistics & Delivery','Freight Support' ]::text[]),
    ('SERVICE', ARRAY['Logistics & Delivery','Errand Service' ]::text[]),
    ('SERVICE', ARRAY['Health & Wellness','Fitness Coaching' ]::text[]),
    ('SERVICE', ARRAY['Health & Wellness','Nutrition Coaching' ]::text[]),
    ('SERVICE', ARRAY['Health & Wellness','Wellness Coaching' ]::text[]),
    ('SERVICE', ARRAY['Health & Wellness','Mental Wellness Support' ]::text[]),
    ('SERVICE', ARRAY['Health & Wellness','Yoga Instruction' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Personal Styling' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Beauty Services' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Hair Services' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Makeup Services' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Personal Shopping' ]::text[]),
    ('SERVICE', ARRAY['Lifestyle & Personal','Travel Planning' ]::text[]),
    ('SERVICE', ARRAY['Research & Testing','User Testing' ]::text[]),
    ('SERVICE', ARRAY['Research & Testing','Product Testing' ]::text[]),
    ('SERVICE', ARRAY['Research & Testing','Academic Research' ]::text[]),
    ('SERVICE', ARRAY['Research & Testing','Internet Research' ]::text[]),
    ('SERVICE', ARRAY['Research & Testing','Survey Research' ]::text[]),
    ('SERVICE', ARRAY['Other','Other Professional Service' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','Web Development' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','Mobile Development' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','Game Development' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','Python' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','JavaScript' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','Java' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Programming','C & C++' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Data & AI','Data Science' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Data & AI','Machine Learning' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Data & AI','Generative AI' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Data & AI','Data Analytics' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Cybersecurity','Ethical Hacking' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Cybersecurity','Network Security' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Cybersecurity','Cloud Security' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Cloud Computing' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','DevOps' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Networking' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Electronics' ]::text[]),
    ('COURSE', ARRAY['Technology & Engineering','Engineering Fundamentals' ]::text[]),
    ('COURSE', ARRAY['Business','Entrepreneurship' ]::text[]),
    ('COURSE', ARRAY['Business','Business Strategy' ]::text[]),
    ('COURSE', ARRAY['Business','Management' ]::text[]),
    ('COURSE', ARRAY['Business','Leadership' ]::text[]),
    ('COURSE', ARRAY['Business','Project Management' ]::text[]),
    ('COURSE', ARRAY['Business','Operations' ]::text[]),
    ('COURSE', ARRAY['Business','Human Resources' ]::text[]),
    ('COURSE', ARRAY['Business','Sales' ]::text[]),
    ('COURSE', ARRAY['Business','Customer Service' ]::text[]),
    ('COURSE', ARRAY['Marketing','Digital Marketing' ]::text[]),
    ('COURSE', ARRAY['Marketing','Social Media Marketing' ]::text[]),
    ('COURSE', ARRAY['Marketing','SEO' ]::text[]),
    ('COURSE', ARRAY['Marketing','Paid Advertising' ]::text[]),
    ('COURSE', ARRAY['Marketing','Email Marketing' ]::text[]),
    ('COURSE', ARRAY['Marketing','Content Marketing' ]::text[]),
    ('COURSE', ARRAY['Marketing','Affiliate Marketing' ]::text[]),
    ('COURSE', ARRAY['Marketing','Branding' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Graphic Design' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','UI & UX Design' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Web Design' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Illustration' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','3D Design' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Animation' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Fashion Design' ]::text[]),
    ('COURSE', ARRAY['Design & Creative','Interior Design' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Accounting' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Bookkeeping' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Investing Basics' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Financial Analysis' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Personal Finance' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Tax Fundamentals' ]::text[]),
    ('COURSE', ARRAY['Finance & Accounting','Excel for Finance' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Productivity' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Communication' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Public Speaking' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Career Development' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Time Management' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Confidence' ]::text[]),
    ('COURSE', ARRAY['Personal Development','Critical Thinking' ]::text[]),
    ('COURSE', ARRAY['Languages','English' ]::text[]),
    ('COURSE', ARRAY['Languages','French' ]::text[]),
    ('COURSE', ARRAY['Languages','Spanish' ]::text[]),
    ('COURSE', ARRAY['Languages','German' ]::text[]),
    ('COURSE', ARRAY['Languages','Arabic' ]::text[]),
    ('COURSE', ARRAY['Languages','Chinese' ]::text[]),
    ('COURSE', ARRAY['Languages','Japanese' ]::text[]),
    ('COURSE', ARRAY['Languages','Portuguese' ]::text[]),
    ('COURSE', ARRAY['Languages','Yoruba' ]::text[]),
    ('COURSE', ARRAY['Languages','Igbo' ]::text[]),
    ('COURSE', ARRAY['Languages','Hausa' ]::text[]),
    ('COURSE', ARRAY['Academic','Mathematics' ]::text[]),
    ('COURSE', ARRAY['Academic','Physics' ]::text[]),
    ('COURSE', ARRAY['Academic','Chemistry' ]::text[]),
    ('COURSE', ARRAY['Academic','Biology' ]::text[]),
    ('COURSE', ARRAY['Academic','Economics' ]::text[]),
    ('COURSE', ARRAY['Academic','Geography' ]::text[]),
    ('COURSE', ARRAY['Academic','History' ]::text[]),
    ('COURSE', ARRAY['Academic','Literature' ]::text[]),
    ('COURSE', ARRAY['Academic','Exam Preparation' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','Fitness' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','Nutrition' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','Yoga' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','Meditation' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','First Aid' ]::text[]),
    ('COURSE', ARRAY['Health & Fitness','Sports Training' ]::text[]),
    ('COURSE', ARRAY['Music','Guitar' ]::text[]),
    ('COURSE', ARRAY['Music','Piano' ]::text[]),
    ('COURSE', ARRAY['Music','Singing' ]::text[]),
    ('COURSE', ARRAY['Music','Music Production' ]::text[]),
    ('COURSE', ARRAY['Music','Music Theory' ]::text[]),
    ('COURSE', ARRAY['Music','DJing' ]::text[]),
    ('COURSE', ARRAY['Photography & Video','Photography' ]::text[]),
    ('COURSE', ARRAY['Photography & Video','Videography' ]::text[]),
    ('COURSE', ARRAY['Photography & Video','Video Editing' ]::text[]),
    ('COURSE', ARRAY['Photography & Video','Photo Editing' ]::text[]),
    ('COURSE', ARRAY['Photography & Video','Content Creation' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Cooking' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Baking' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Fashion' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Beauty' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Parenting' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Gardening' ]::text[]),
    ('COURSE', ARRAY['Lifestyle','Travel Skills' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Electrical' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Plumbing' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Carpentry' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Welding' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Automotive Repair' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Tailoring' ]::text[]),
    ('COURSE', ARRAY['Trades & Vocational','Hairdressing' ]::text[]),
    ('COURSE', ARRAY['Other & Miscellaneous','Other Course' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Software Engineering','Frontend Engineering' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Software Engineering','Backend Engineering' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Software Engineering','Full Stack Engineering' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Mobile Development' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','DevOps & Cloud' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Data Engineering' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Data Science' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Machine Learning & AI' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Cybersecurity' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','IT Support' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Network Engineering' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','QA & Testing' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Product Management' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Technical Project Management' ]::text[]),
    ('JOB', ARRAY['Technology & Engineering','Hardware Engineering' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Digital Marketing' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Social Media Management' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','SEO' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Paid Media' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Content Marketing' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Email Marketing' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Brand Marketing' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Marketing Analytics' ]::text[]),
    ('JOB', ARRAY['Advertising & Marketing','Influencer Marketing' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Graphic Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','UI & UX Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Product Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Web Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Motion Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Video Editing' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Illustration' ]::text[]),
    ('JOB', ARRAY['Design & Creative','3D Design' ]::text[]),
    ('JOB', ARRAY['Design & Creative','Creative Direction' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Sales Representative' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Account Executive' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Business Development' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Account Management' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Sales Operations' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Partnerships' ]::text[]),
    ('JOB', ARRAY['Sales & Business Development','Telesales' ]::text[]),
    ('JOB', ARRAY['Customer Support','Customer Service' ]::text[]),
    ('JOB', ARRAY['Customer Support','Customer Success' ]::text[]),
    ('JOB', ARRAY['Customer Support','Technical Support' ]::text[]),
    ('JOB', ARRAY['Customer Support','Call Center' ]::text[]),
    ('JOB', ARRAY['Customer Support','Chat Support' ]::text[]),
    ('JOB', ARRAY['Customer Support','Community Support' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Accountant' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Bookkeeper' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Financial Analyst' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Auditor' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Tax Specialist' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Payroll' ]::text[]),
    ('JOB', ARRAY['Finance & Accounting','Finance Manager' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Content Writer' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Copywriter' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Technical Writer' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Editor' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Journalist' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Scriptwriter' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Translator' ]::text[]),
    ('JOB', ARRAY['Content & Writing','Proofreader' ]::text[]),
    ('JOB', ARRAY['Education & Training','Teacher' ]::text[]),
    ('JOB', ARRAY['Education & Training','Tutor' ]::text[]),
    ('JOB', ARRAY['Education & Training','Lecturer' ]::text[]),
    ('JOB', ARRAY['Education & Training','Instructional Designer' ]::text[]),
    ('JOB', ARRAY['Education & Training','Trainer' ]::text[]),
    ('JOB', ARRAY['Education & Training','Education Administrator' ]::text[]),
    ('JOB', ARRAY['Healthcare','Nursing' ]::text[]),
    ('JOB', ARRAY['Healthcare','Medical Doctor' ]::text[]),
    ('JOB', ARRAY['Healthcare','Pharmacy' ]::text[]),
    ('JOB', ARRAY['Healthcare','Laboratory' ]::text[]),
    ('JOB', ARRAY['Healthcare','Healthcare Administration' ]::text[]),
    ('JOB', ARRAY['Healthcare','Caregiver' ]::text[]),
    ('JOB', ARRAY['Healthcare','Therapy & Counseling' ]::text[]),
    ('JOB', ARRAY['Legal','Lawyer' ]::text[]),
    ('JOB', ARRAY['Legal','Paralegal' ]::text[]),
    ('JOB', ARRAY['Legal','Legal Research' ]::text[]),
    ('JOB', ARRAY['Legal','Compliance' ]::text[]),
    ('JOB', ARRAY['Legal','Contract Management' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Administrative Assistant' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Executive Assistant' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Office Manager' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Operations Manager' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Data Entry' ]::text[]),
    ('JOB', ARRAY['Operations & Administration','Virtual Assistant' ]::text[]),
    ('JOB', ARRAY['Human Resources','Recruiter' ]::text[]),
    ('JOB', ARRAY['Human Resources','HR Generalist' ]::text[]),
    ('JOB', ARRAY['Human Resources','HR Manager' ]::text[]),
    ('JOB', ARRAY['Human Resources','Talent Acquisition' ]::text[]),
    ('JOB', ARRAY['Human Resources','People Operations' ]::text[]),
    ('JOB', ARRAY['Human Resources','Training & Development' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Logistics Coordinator' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Warehouse' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Procurement' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Supply Chain' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Delivery Driver' ]::text[]),
    ('JOB', ARRAY['Logistics & Supply Chain','Dispatcher' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Hotel' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Restaurant' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Chef' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Waiter' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Travel Agent' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Tour Guide' ]::text[]),
    ('JOB', ARRAY['Hospitality & Tourism','Event Staff' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Construction' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Electrician' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Plumber' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Carpenter' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Welder' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Mechanic' ]::text[]),
    ('JOB', ARRAY['Construction & Skilled Trades','Technician' ]::text[]),
    ('JOB', ARRAY['Manufacturing','Production' ]::text[]),
    ('JOB', ARRAY['Manufacturing','Machine Operator' ]::text[]),
    ('JOB', ARRAY['Manufacturing','Quality Control' ]::text[]),
    ('JOB', ARRAY['Manufacturing','Maintenance' ]::text[]),
    ('JOB', ARRAY['Manufacturing','Factory Supervisor' ]::text[]),
    ('JOB', ARRAY['Retail','Retail Sales' ]::text[]),
    ('JOB', ARRAY['Retail','Cashier' ]::text[]),
    ('JOB', ARRAY['Retail','Store Manager' ]::text[]),
    ('JOB', ARRAY['Retail','Merchandising' ]::text[]),
    ('JOB', ARRAY['Retail','Inventory' ]::text[]),
    ('JOB', ARRAY['Security & Public Safety','Security Guard' ]::text[]),
    ('JOB', ARRAY['Security & Public Safety','Safety Officer' ]::text[]),
    ('JOB', ARRAY['Security & Public Safety','Emergency Services' ]::text[]),
    ('JOB', ARRAY['Security & Public Safety','Loss Prevention' ]::text[]),
    ('JOB', ARRAY['Agriculture','Farm Worker' ]::text[]),
    ('JOB', ARRAY['Agriculture','Agronomist' ]::text[]),
    ('JOB', ARRAY['Agriculture','Livestock' ]::text[]),
    ('JOB', ARRAY['Agriculture','Agricultural Technician' ]::text[]),
    ('JOB', ARRAY['Agriculture','Farm Manager' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Actor' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Presenter' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Producer' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Camera Operator' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Audio Engineer' ]::text[]),
    ('JOB', ARRAY['Media & Entertainment','Content Creator' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','YouTube Scriptwriter' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','YouTube Video Editor' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','Thumbnail Designer' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','Channel Manager' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','Voice Over Artist' ]::text[]),
    ('JOB', ARRAY['YouTube Automation','YouTube Researcher' ]::text[]),
    ('JOB', ARRAY['Other','Other Job' ]::text[]),
    ('TASK', ARRAY['Digital Task','Data Entry' ]::text[]),
    ('TASK', ARRAY['Digital Task','Web Research' ]::text[]),
    ('TASK', ARRAY['Digital Task','Survey Participation' ]::text[]),
    ('TASK', ARRAY['Digital Task','App Testing' ]::text[]),
    ('TASK', ARRAY['Digital Task','Website Testing' ]::text[]),
    ('TASK', ARRAY['Digital Task','Content Moderation' ]::text[]),
    ('TASK', ARRAY['Digital Task','Image Labeling' ]::text[]),
    ('TASK', ARRAY['Digital Task','Audio Transcription' ]::text[]),
    ('TASK', ARRAY['Digital Task','Short Writing Task' ]::text[]),
    ('TASK', ARRAY['Digital Task','Social Media Engagement' ]::text[]),
    ('TASK', ARRAY['Digital Task','Lead Collection' ]::text[]),
    ('TASK', ARRAY['Digital Task','Product Research' ]::text[]),
    ('TASK', ARRAY['Digital Task','File Conversion' ]::text[]),
    ('TASK', ARRAY['Digital Task','Document Formatting' ]::text[]),
    ('TASK', ARRAY['Digital Task','Simple Design Task' ]::text[]),
    ('TASK', ARRAY['Local Task','Delivery & Errands' ]::text[]),
    ('TASK', ARRAY['Local Task','Cleaning & Home Help' ]::text[]),
    ('TASK', ARRAY['Local Task','Local Assistance' ]::text[]),
    ('TASK', ARRAY['Local Task','Shopping & Pickup' ]::text[]),
    ('TASK', ARRAY['Local Task','Moving Help' ]::text[]),
    ('TASK', ARRAY['Local Task','Furniture Assembly' ]::text[]),
    ('TASK', ARRAY['Local Task','Pet Care' ]::text[]),
    ('TASK', ARRAY['Local Task','Yard Work' ]::text[]),
    ('TASK', ARRAY['Local Task','Queue & Waiting' ]::text[]),
    ('TASK', ARRAY['Local Task','Event Help' ]::text[]),
    ('TASK', ARRAY['Local Task','Photography Task' ]::text[]),
    ('TASK', ARRAY['Local Task','Vehicle Help' ]::text[]),
    ('TASK', ARRAY['Local Task','Handyman Task' ]::text[]),
    ('TASK', ARRAY['Other & Miscellaneous','Other Task' ]::text[]);

do $$
declare
  r record;
  v_parent uuid;
  v_id uuid;
  v_name text;
  v_slug text;
  v_depth integer;
  v_last integer;
begin
  for r in
    select listing_type_code, path_names
    from tmp_taxonomy_paths
    order by listing_type_code, cardinality(path_names), path_names
  loop
    v_parent := null;
    v_last := cardinality(r.path_names);

    for v_depth in 1..v_last loop
      v_name := trim(r.path_names[v_depth]);
      v_slug := trim(both '-' from regexp_replace(lower(v_name),'[^a-z0-9]+','-','g'));

      select c.id into v_id
      from public.marketplace_taxonomy_categories c
      where c.listing_type_code=r.listing_type_code
        and (
          (v_parent is null and c.parent_id is null)
          or c.parent_id=v_parent
        )
        and lower(c.slug)=lower(v_slug)
      order by c.created_at
      limit 1;

      if v_id is null then
        insert into public.marketplace_taxonomy_categories(
          listing_type_code,parent_id,name,slug,sort_order,is_leaf,is_active,metadata
        )
        values(
          r.listing_type_code,
          v_parent,
          v_name,
          v_slug,
          100,
          v_depth=v_last,
          true,
          jsonb_build_object('seed_kind','taxonomy_expansion_v1')
        )
        returning id into v_id;
      else
        update public.marketplace_taxonomy_categories
        set is_active=true,
            is_leaf=case when v_depth<v_last then false else is_leaf end,
            updated_at=now()
        where id=v_id;
      end if;

      if v_parent is not null then
        update public.marketplace_taxonomy_categories
        set is_leaf=false, updated_at=now()
        where id=v_parent and is_leaf=true;
      end if;

      v_parent := v_id;
    end loop;
  end loop;
end;
$$;

-- Ensure every listing type has an escape path.
with required(code,name,slug) as (
  values
    ('PHYSICAL','Other & Miscellaneous','other-miscellaneous'),
    ('DIGITAL','Other & Miscellaneous','other-miscellaneous'),
    ('SERVICE','Other','other'),
    ('COURSE','Other & Miscellaneous','other-miscellaneous'),
    ('JOB','Other','other'),
    ('TASK','Other & Miscellaneous','other-miscellaneous')
)
insert into public.marketplace_taxonomy_categories(
  listing_type_code,parent_id,name,slug,sort_order,is_leaf,is_active,metadata
)
select r.code,null,r.name,r.slug,9999,true,true,'{"seed_kind":"taxonomy_expansion_v1"}'::jsonb
from required r
where not exists (
  select 1
  from public.marketplace_taxonomy_categories c
  where c.listing_type_code=r.code
    and c.parent_id is null
    and lower(c.slug)=lower(r.slug)
);

commit;
