-- ST-4D: Finish signup referral authority without creating a second referral system.
--
-- The permanent sponsor and referral code are already resolved/generated by
-- guard_user_referral_identity(). This migration makes the existing generic
-- affiliate referral link deterministic as part of profile creation, so the
-- browser no longer needs to create referral identity/state after signup.

CREATE OR REPLACE FUNCTION public.ensure_canonical_generic_referral_link()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
BEGIN
  IF coalesce(NEW.is_admin, false)
     AND coalesce(NEW.admin_status, '') = 'active' THEN
    RETURN NEW;
  END IF;

  IF NEW.referral_code IS NULL OR btrim(NEW.referral_code) = '' THEN
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.referral_links rl
    WHERE rl.user_id = NEW.id
      AND rl.product_id IS NULL
      AND coalesce(rl.source_type, 'affiliate') = 'affiliate'
      AND rl.campaign_id IS NULL
      AND rl.sales_team_id IS NULL
  ) THEN
    INSERT INTO public.referral_links(
      user_id,
      unique_code,
      source_type
    )
    VALUES(
      NEW.id,
      NEW.referral_code,
      'affiliate'
    )
    ON CONFLICT DO NOTHING;
  END IF;

  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_ensure_canonical_generic_referral_link ON public.users;
CREATE TRIGGER trg_ensure_canonical_generic_referral_link
AFTER INSERT ON public.users
FOR EACH ROW
EXECUTE FUNCTION public.ensure_canonical_generic_referral_link();

REVOKE ALL ON FUNCTION public.ensure_canonical_generic_referral_link()
FROM PUBLIC, anon, authenticated;

INSERT INTO public.referral_links(
  user_id,
  unique_code,
  source_type
)
SELECT
  u.id,
  u.referral_code,
  'affiliate'
FROM public.users u
WHERE u.referral_code IS NOT NULL
  AND btrim(u.referral_code) <> ''
  AND NOT (coalesce(u.is_admin, false) AND coalesce(u.admin_status, '') = 'active')
  AND NOT EXISTS (
    SELECT 1
    FROM public.referral_links rl
    WHERE rl.user_id = u.id
      AND rl.product_id IS NULL
      AND coalesce(rl.source_type, 'affiliate') = 'affiliate'
      AND rl.campaign_id IS NULL
      AND rl.sales_team_id IS NULL
  )
ON CONFLICT DO NOTHING;

DO $block$
BEGIN
  IF to_regclass('public.referrals') IS NOT NULL THEN
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE ON TABLE public.referrals FROM PUBLIC';
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE ON TABLE public.referrals FROM anon';
    EXECUTE 'REVOKE INSERT, UPDATE, DELETE ON TABLE public.referrals FROM authenticated';
  END IF;
END;
$block$;