import { useCallback, useEffect, useMemo, useState } from 'react';
import { AlertTriangle, Archive, BarChart3, Database, HardDrive, Image, RefreshCw, Save, Settings2, Shield, Video } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { useAuth } from '../../contexts/AuthContext';

type BucketRow={bucket:string;public:boolean;file_size_limit:number|null;allowed_mime_types:string[]|null;object_count:number;total_bytes:number;average_bytes:number;largest_file_bytes:number;percent_of_total:number};
type FeatureRow={feature:string;asset_count:number;total_bytes:number};
type LargestAsset={bucket:string;path:string;bytes:number;mime_type:string|null};
type HistoryRow={snapshot_date:string;total_bytes:number;object_count:number;video_bytes:number;image_bytes:number};
type MonitorSettings={singleton:boolean;included_storage_bytes:number|null;warning_thresholds:number[];unusual_daily_growth_percent:number;orphan_grace_days:number;estimated_storage_price_per_gb:number|null;estimated_cached_egress_price_per_gb:number|null;estimated_image_transform_price:number|null;estimated_video_provider_price_per_gb:number|null};
type Analytics={total_bytes:number;object_count:number;media_asset_count:number;growth_7d_bytes:number|null;growth_30d_bytes:number|null;average_daily_growth_bytes:number|null;estimated_30d_bytes:number|null;included_storage_bytes:number|null;included_percent_used:number|null;estimated_days_until_quota:number|null;estimated_monthly_storage_cost:number|null;buckets:BucketRow[];by_media_type:{images:number;video:number;audio:number;documents:number};by_feature:FeatureRow[];history:HistoryRow[];largest_assets:LargestAsset[];settings:MonitorSettings|null;orphan_candidates:number;policy_count:number;generated_at:string};
type Policy={feature:string;bucket:string|null;provider:string;max_file_size_bytes:number|null;allowed_mime_types:string[]|null;quality_preset:string|null;visibility:string;retention_days:number|null;per_user_quota_bytes:number|null;upload_rate_limit_per_hour:number|null;enabled:boolean};
type Orphan={bucket_id:string;object_path:string;bytes:number;mime_type:string|null;detected_at:string;state:string;protected:boolean;reason:string|null};

const fmtBytes=(value:number|null|undefined)=>{const n=Number(value||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;if(n<1024**3)return `${(n/1024**2).toFixed(1)} MB`;if(n<1024**4)return `${(n/1024**3).toFixed(2)} GB`;return `${(n/1024**4).toFixed(2)} TB`;};
const num=(value:number|null|undefined,fallback='—')=>value===null||value===undefined?fallback:Number(value).toLocaleString();

export default function AdminStorageMediaPage(){
 const {adminRole}=useAuth();
 const canEdit=['super_admin','technical_admin','system_config_admin'].includes(String(adminRole||''));
 const [analytics,setAnalytics]=useState<Analytics|null>(null);const [policies,setPolicies]=useState<Policy[]>([]);const [orphans,setOrphans]=useState<Orphan[]>([]);const [settings,setSettings]=useState<MonitorSettings|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);setMessage(null);try{const [{data:a,error:ae},{data:p,error:pe},{data:o,error:oe}]=await Promise.all([supabase.rpc('get_storage_media_analytics'),supabase.from('media_storage_policies').select('feature,bucket,provider,max_file_size_bytes,allowed_mime_types,quality_preset,visibility,retention_days,per_user_quota_bytes,upload_rate_limit_per_hour,enabled').order('feature'),supabase.from('storage_orphan_candidates').select('bucket_id,object_path,bytes,mime_type,detected_at,state,protected,reason').in('state',['detected','review','safe_to_delete']).order('bytes',{ascending:false}).limit(50)]);if(ae)throw ae;if(pe)throw pe;if(oe)throw oe;setAnalytics(a as Analytics);setPolicies((p||[]) as Policy[]);setOrphans((o||[]) as Orphan[]);setSettings((a as Analytics)?.settings||null);}catch(e){setMessage(e instanceof Error?e.message:'Unable to load storage analytics');}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const updateSetting=(key:keyof MonitorSettings,value:number|null|number[])=>setSettings(s=>s?{...s,[key]:value}:s);
 const saveSettings=async()=>{if(!settings||!canEdit)return;setSaving(true);setMessage(null);try{const {error}=await supabase.from('storage_monitor_settings').update({included_storage_bytes:settings.included_storage_bytes,warning_thresholds:settings.warning_thresholds,unusual_daily_growth_percent:settings.unusual_daily_growth_percent,orphan_grace_days:settings.orphan_grace_days,estimated_storage_price_per_gb:settings.estimated_storage_price_per_gb,estimated_cached_egress_price_per_gb:settings.estimated_cached_egress_price_per_gb,estimated_image_transform_price:settings.estimated_image_transform_price,estimated_video_provider_price_per_gb:settings.estimated_video_provider_price_per_gb,updated_at:new Date().toISOString()}).eq('singleton',true);if(error)throw error;setMessage('Storage monitoring settings saved.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to save settings');}finally{setSaving(false);}};
 const typeCards=useMemo(()=>analytics?[['Images',analytics.by_media_type?.images||0,Image],['Video',analytics.by_media_type?.video||0,Video],['Audio',analytics.by_media_type?.audio||0,BarChart3],['Documents',analytics.by_media_type?.documents||0,Archive]] as const:[],[analytics]);
 if(loading)return <div className="flex justify-center py-24"><div className="h-9 w-9 animate-spin rounded-full border-4 border-primary-200 border-t-primary-600"/></div>;
 return <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
  <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><HardDrive className="h-7 w-7 text-primary-500"/><h1 className="text-2xl font-bold">Storage & Media</h1></div><p className="mt-1 text-sm text-gray-500">Capacity, per-file upload policy, media providers, growth forecasting and orphan review are separate controls.</p></div><button onClick={()=>void load()} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-gray-200 px-4 dark:border-gray-700"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
  {message&&<div className="rounded-xl bg-primary-500/10 px-4 py-3 text-sm text-primary-600 dark:text-primary-300">{message}</div>}
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
   <Metric label="Stored" value={fmtBytes(analytics?.total_bytes)} sub={`${num(analytics?.object_count)} objects`}/><Metric label="30-day growth" value={analytics?.growth_30d_bytes==null?'Awaiting history':fmtBytes(analytics.growth_30d_bytes)} sub={`7d: ${analytics?.growth_7d_bytes==null?'—':fmtBytes(analytics.growth_7d_bytes)}`}/><Metric label="30-day estimate" value={analytics?.estimated_30d_bytes==null?'Awaiting history':fmtBytes(analytics.estimated_30d_bytes)} sub={`Daily: ${analytics?.average_daily_growth_bytes==null?'—':fmtBytes(analytics.average_daily_growth_bytes)}`}/><Metric label="Configured quota" value={analytics?.included_storage_bytes?fmtBytes(analytics.included_storage_bytes):'Not configured'} sub={analytics?.included_percent_used==null?'Set included GB below':`${analytics.included_percent_used}% used · ${analytics.estimated_days_until_quota??'—'} days est.`}/>
  </div>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{typeCards.map(([label,bytes,Icon])=><div key={label} className="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><Icon className="h-5 w-5 text-primary-500"/><div className="mt-2 text-xs text-gray-500">{label}</div><div className="text-xl font-bold">{fmtBytes(bytes)}</div></div>)}</div>

  <Section title="Buckets" description="Bucket capacity and each bucket's individual-object limit. A 100 MB file limit is not a 100 MB storage quota." icon={Database}><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-left text-xs text-gray-500"><tr><th className="p-2">Bucket</th><th>Access</th><th>Files</th><th>Stored</th><th>Avg</th><th>Largest</th><th>Per-file limit</th><th>Share</th></tr></thead><tbody>{(analytics?.buckets||[]).map(b=><tr key={b.bucket} className="border-t border-gray-100 dark:border-gray-700"><td className="p-2 font-semibold">{b.bucket}</td><td>{b.public?'Public':'Private'}</td><td>{b.object_count}</td><td>{fmtBytes(b.total_bytes)}</td><td>{fmtBytes(b.average_bytes)}</td><td>{fmtBytes(b.largest_file_bytes)}</td><td>{b.file_size_limit?fmtBytes(b.file_size_limit):'Global default'}</td><td>{Number(b.percent_of_total||0).toFixed(1)}%</td></tr>)}</tbody></table></div></Section>

  <Section title="Feature media policies" description={`${analytics?.policy_count||0} enabled policies. Provider selection, MIME allowlists and quotas are centralized here.`} icon={Shield}><div className="grid gap-3 lg:grid-cols-2">{policies.map(p=><div key={p.feature} className="rounded-xl border border-gray-100 p-3 dark:border-gray-700"><div className="flex items-center justify-between gap-2"><div className="font-semibold">{p.feature}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${p.enabled?'bg-emerald-500/10 text-emerald-500':'bg-gray-500/10 text-gray-500'}`}>{p.provider}</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs text-gray-500"><span>Bucket: <b className="text-gray-700 dark:text-gray-300">{p.bucket||'provider-managed'}</b></span><span>Visibility: <b className="text-gray-700 dark:text-gray-300">{p.visibility}</b></span><span>Max file: <b className="text-gray-700 dark:text-gray-300">{p.max_file_size_bytes?fmtBytes(p.max_file_size_bytes):'—'}</b></span><span>User quota: <b className="text-gray-700 dark:text-gray-300">{p.per_user_quota_bytes?fmtBytes(p.per_user_quota_bytes):'not enforced'}</b></span></div><p className="mt-2 truncate text-[11px] text-gray-500" title={(p.allowed_mime_types||[]).join(', ')}>{(p.allowed_mime_types||[]).join(', ')||'No MIME allowlist'}</p></div>)}</div></Section>

  <Section title="Growth, quota & cost assumptions" description="These values are operational assumptions, not provider billing promises. Leave prices blank when unknown." icon={Settings2}>{settings?<div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><NumberField label="Included storage (GB)" disabled={!canEdit} value={settings.included_storage_bytes?settings.included_storage_bytes/1024**3:null} onChange={v=>updateSetting('included_storage_bytes',v==null?null:Math.round(v*1024**3))}/><NumberField label="Unusual daily growth %" disabled={!canEdit} value={Number(settings.unusual_daily_growth_percent||0)} onChange={v=>updateSetting('unusual_daily_growth_percent',v??0)}/><NumberField label="Orphan grace days" disabled={!canEdit} value={settings.orphan_grace_days} onChange={v=>updateSetting('orphan_grace_days',Math.max(1,Math.round(v??30)))}/><NumberField label="Storage price / GB" disabled={!canEdit} value={settings.estimated_storage_price_per_gb} step={0.001} onChange={v=>updateSetting('estimated_storage_price_per_gb',v)}/><NumberField label="Cached egress / GB" disabled={!canEdit} value={settings.estimated_cached_egress_price_per_gb} step={0.001} onChange={v=>updateSetting('estimated_cached_egress_price_per_gb',v)}/><NumberField label="Video provider / GB" disabled={!canEdit} value={settings.estimated_video_provider_price_per_gb} step={0.001} onChange={v=>updateSetting('estimated_video_provider_price_per_gb',v)}/><label className="rounded-xl border border-gray-100 p-3 dark:border-gray-700"><span className="text-xs font-semibold">Warning thresholds (%)</span><input disabled={!canEdit} value={(settings.warning_thresholds||[]).join(', ')} onChange={e=>updateSetting('warning_thresholds',e.target.value.split(',').map(x=>Number(x.trim())).filter(x=>x>0&&x<=100).sort((a,b)=>a-b))} className="mt-2 w-full rounded-lg border border-gray-200 bg-transparent px-3 py-2 dark:border-gray-600"/></label>{canEdit&&<button onClick={()=>void saveSettings()} disabled={saving} className="inline-flex min-h-11 items-center justify-center gap-2 self-end rounded-xl bg-primary-600 px-4 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':'Save monitoring settings'}</button>}</div>:<p className="text-sm text-gray-500">Monitoring settings unavailable.</p>}</Section>

  <div className="grid gap-5 xl:grid-cols-2"><Section title="Largest stored objects" description="Useful for spotting oversized media before it dominates capacity." icon={HardDrive}><div className="space-y-2">{(analytics?.largest_assets||[]).slice(0,12).map(a=><div key={`${a.bucket}/${a.path}`} className="flex items-center gap-3 rounded-xl bg-gray-50 p-3 text-sm dark:bg-gray-900"><div className="min-w-0 flex-1"><div className="truncate font-medium">{a.path}</div><div className="text-xs text-gray-500">{a.bucket} · {a.mime_type||'unknown'}</div></div><b>{fmtBytes(a.bytes)}</b></div>)}</div></Section><Section title="Orphan review queue" description={`${analytics?.orphan_candidates||0} detected/review candidates. Protected evidence is never auto-deleted.`} icon={AlertTriangle}><div className="space-y-2">{orphans.length===0?<p className="text-sm text-gray-500">No current orphan candidates.</p>:orphans.slice(0,12).map(o=><div key={`${o.bucket_id}/${o.object_path}`} className="rounded-xl border border-gray-100 p-3 text-sm dark:border-gray-700"><div className="flex justify-between gap-3"><span className="min-w-0 truncate font-medium">{o.object_path}</span><b>{fmtBytes(o.bytes)}</b></div><div className="mt-1 text-xs text-gray-500">{o.bucket_id} · {o.state}{o.protected?' · protected evidence':''}</div></div>)}</div></Section></div>
  {analytics?.estimated_monthly_storage_cost!=null&&<div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-sm"><b>Configured storage-cost estimate:</b> {Number(analytics.estimated_monthly_storage_cost).toFixed(2)}. This is based only on the owner-configured assumption and is not a provider invoice.</div>}
 </div>;
}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="rounded-2xl border border-gray-200 bg-white p-4 dark:border-gray-700 dark:bg-gray-800"><div className="text-xs text-gray-500">{label}</div><div className="mt-1 text-xl font-bold">{value}</div><div className="mt-1 text-xs text-gray-500">{sub}</div></div>}
function Section({title,description,icon:Icon,children}:{title:string;description:string;icon:typeof HardDrive;children:React.ReactNode}){return <section className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-800"><div className="mb-4 flex items-start gap-3"><Icon className="mt-0.5 h-5 w-5 text-primary-500"/><div><h2 className="font-bold">{title}</h2><p className="text-xs text-gray-500">{description}</p></div></div>{children}</section>}
function NumberField({label,value,onChange,disabled,step=1}:{label:string;value:number|null;onChange:(value:number|null)=>void;disabled:boolean;step?:number}){return <label className="rounded-xl border border-gray-100 p-3 dark:border-gray-700"><span className="text-xs font-semibold">{label}</span><input type="number" step={step} disabled={disabled} value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))} className="mt-2 w-full rounded-lg border border-gray-200 bg-transparent px-3 py-2 disabled:opacity-60 dark:border-gray-600"/></label>}
