import { useCallback,useEffect,useMemo,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { ArrowLeft,User,ShieldCheck,ClipboardList,FileText,Scale,Activity,History,BriefcaseBusiness,Award,Trophy,CheckCircle2,AlertTriangle,XCircle,Eye,RefreshCw,BadgeCheck,LockKeyhole,Mail,Phone,MapPin,CalendarDays,Hash,ExternalLink } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { createKycDocumentSignedUrl,reviewKycDocument } from '../../lib/kycHooks';
import type { KycDocument,KycProfile,KycSubmission } from '../../lib/kycTypes';
import { KYC_DOC_TYPE_LABELS,KYC_STATUS_LABELS } from '../../lib/kycTypes';
import SecureDocumentViewer from '../../components/admin/SecureDocumentViewer';

const TABS=[
  ['overview','Overview',User],['profiles','Profiles & Roles',ShieldCheck],['questionnaires','Questionnaire / Applications',ClipboardList],
  ['kyc','KYC & Verification',ShieldCheck],['documents','Documents',FileText],['professional','Professional Information',BriefcaseBusiness],
  ['achievements','Achievements & Growth',Award],['eligibility','Eligibility',Scale],['restrictions','Restrictions / Moderation',LockKeyhole],
  ['activity','Activity',Activity],['audit','Audit History',History],
] as const;
type TabKey=(typeof TABS)[number][0];
type PermissionMap=Record<string,boolean>;

type IdentityBundle={
  user:{id:string;email:string;phone:string|null;full_name:string|null;username:string|null;avatar_url:string|null;location:string|null;created_at:string;updated_at:string;account_status:string;is_admin:boolean;admin_status:string|null;admin_role:string|null;rbac_role_id:string|null;total_sales_count:number;average_rating:number|string};
  private_profile:null|{country_iso2:string|null;country_calling_code:string|null;date_of_birth:string|null;intended_profiles:string[];interests:string[];onboarding_status:string;onboarding_completed_at:string|null};
  auth:null|{email_verified:boolean;phone_verified:boolean;last_sign_in_at:string|null;auth_created_at:string|null};
};
type QuestionnaireSubmission={id:string;profile_type:string;questionnaire_id:string;questionnaire_version:number;status:string;submitted_at:string|null;reviewed_at:string|null;reviewer_id:string|null;user_visible_reason:string|null;internal_notes:string|null;created_at:string};
type QuestionnaireAnswer={id:string;submission_id:string;question_key:string;answer_value:unknown;question_snapshot:{label?:string;description?:string;answer_type?:string;required?:boolean}};
type ProfessionalDocument={id:string;user_id:string;profile_type:string|null;document_type:string;title:string|null;storage_bucket:string;storage_path:string;original_file_name:string|null;mime_type:string|null;size_bytes:number|null;version:number;status:string;user_visible_reason:string|null;reviewer_id:string|null;reviewed_at:string|null;expires_at:string|null;created_at:string};
type Evidence={id:string;user_id:string;user_achievement_id:string|null;achievement_id:string|null;title:string;description:string|null;evidence_type:string;external_url:string|null;storage_bucket:string|null;storage_path:string|null;original_file_name:string|null;mime_type:string|null;status:string;reviewer_id:string|null;reviewed_at:string|null;user_visible_reason:string|null;created_at:string};
type BadgeAssignment={id:string;badge_id:string;user_id:string;reason:string|null;expires_at:string|null;is_active:boolean;created_at:string;badge?:{id:string;name:string;description:string|null;image_url:string|null;slug:string}|null};
type BadgeRow={id:string;name:string;slug:string;description:string|null;image_url:string|null};
type GrowthScore={score:number|string;growth_level:string;components:Record<string,unknown>;rank_position:number|null;calculated_at:string};
type TrustScore={score:number;level:string;components:Record<string,unknown>;last_calculated:string};
type Eligibility={id:string;profile_type:string;action_key:string;status:string;reasons:Array<{key:string;ok:boolean;message:string;status?:string}>;calculated_at:string};
type Achievement={id:string;user_id:string;achievement_type:string;achievement_name:string;metadata:Record<string,unknown>;earned_at:string|null;verification_status:string;verified_by:string|null;verified_at:string|null;verification_source:string;verification_note:string|null};
type AuditEvent={id:string;action:string;created_at:string;entity_type?:string|null;entity_id?:string|null;metadata?:Record<string,unknown>;details?:Record<string,unknown>;admin_id?:string|null};

type ViewerState={title:string;mimeType:string|null;url:string;expiresAt:Date;metadata:Array<{label:string;value:string|null|undefined}>;refresh:()=>Promise<string>}|null;

export default function AdminUserDetailPage(){
  const {userId}=useParams<{userId:string}>();const [tab,setTab]=useState<TabKey>('overview');const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [permissions,setPermissions]=useState<PermissionMap>({});
  const [identity,setIdentity]=useState<IdentityBundle|null>(null);const [questionnaires,setQuestionnaires]=useState<QuestionnaireSubmission[]>([]);const [answers,setAnswers]=useState<QuestionnaireAnswer[]>([]);
  const [kycProfile,setKycProfile]=useState<KycProfile|null>(null);const [kycSubmissions,setKycSubmissions]=useState<KycSubmission[]>([]);const [kycDocs,setKycDocs]=useState<KycDocument[]>([]);const [professionalDocs,setProfessionalDocs]=useState<ProfessionalDocument[]>([]);
  const [eligibility,setEligibility]=useState<Eligibility[]>([]);const [achievements,setAchievements]=useState<Achievement[]>([]);const [evidence,setEvidence]=useState<Evidence[]>([]);const [assignments,setAssignments]=useState<BadgeAssignment[]>([]);const [badges,setBadges]=useState<BadgeRow[]>([]);const [growth,setGrowth]=useState<GrowthScore|null>(null);const [trust,setTrust]=useState<TrustScore|null>(null);const [audits,setAudits]=useState<AuditEvent[]>([]);const [viewer,setViewer]=useState<ViewerState>(null);const [busy,setBusy]=useState<string|null>(null);

  const can=(key:string)=>permissions[key]===true;
  const loadPermissions=useCallback(async()=>{const checks=['users.view','users.view_sensitive','questionnaires.view','questionnaires.review','kyc.view','kyc.review','kyc.verify','kyc.reject','kyc.request_resubmission','kyc.view_documents','kyc.download_documents','kyc.audit_view','professional_documents.view','professional_documents.review','eligibility.view','eligibility.recalculate','badges.view','badges.assign','badges.view_evidence','badges.review_evidence','badges.manage_ranking'];const pairs=await Promise.all(checks.map(async(key)=>{const [module,action]=key.split('.');const {data}=await supabase.rpc('has_dright_permission',{p_module:module,p_action:action});return [key,data===true] as const;}));setPermissions(Object.fromEntries(pairs));},[]);

  const load=useCallback(async()=>{if(!userId)return;setLoading(true);setError(null);try{
    await loadPermissions();
    const {data:identityData,error:identityError}=await supabase.rpc('get_admin_user_identity_summary',{p_user_id:userId});if(identityError)throw identityError;setIdentity(identityData as IdentityBundle);
    const queries=await Promise.allSettled([
      supabase.from('questionnaire_submissions').select('*').eq('user_id',userId).order('created_at',{ascending:false}),
      supabase.from('kyc_profiles').select('*').eq('user_id',userId).eq('is_deleted',false).maybeSingle(),
      supabase.from('professional_documents').select('*').eq('user_id',userId).eq('is_deleted',false).order('created_at',{ascending:false}),
      supabase.from('user_eligibility').select('*').eq('user_id',userId).order('calculated_at',{ascending:false}),
      supabase.from('user_achievements').select('*').eq('user_id',userId).order('earned_at',{ascending:false}),
      supabase.from('achievement_evidence').select('*').eq('user_id',userId).eq('is_deleted',false).order('created_at',{ascending:false}),
      supabase.from('badge_assignments').select('*,badge:badges(id,name,slug,description,image_url)').eq('user_id',userId).eq('is_deleted',false).order('created_at',{ascending:false}),
      supabase.from('badges').select('id,name,slug,description,image_url').eq('is_active',true).eq('is_deleted',false).order('display_priority',{ascending:false}),
      supabase.from('user_growth_scores').select('*').eq('user_id',userId).maybeSingle(),
      supabase.from('trust_scores').select('*').eq('user_id',userId).maybeSingle(),
      supabase.from('admin_activity_logs').select('id,admin_id,action,target_type,target_id,resource_type,resource_id,details,created_at').or(`target_id.eq.${userId},resource_id.eq.${userId}`).order('created_at',{ascending:false}).limit(100),
      supabase.from('kyc_audit_logs').select('*').eq('user_id',userId).order('created_at',{ascending:false}).limit(100),
    ]);
    const val=<T,>(index:number):T|null=>{const r=queries[index];return r.status==='fulfilled'&&!r.value.error?(r.value.data as T):null;};
    const qs=val<QuestionnaireSubmission[]>(0)??[];setQuestionnaires(qs);
    if(qs.length){const {data}=await supabase.from('questionnaire_answers').select('*').in('submission_id',qs.map((s)=>s.id)).order('created_at');setAnswers((data??[]) as QuestionnaireAnswer[]);}else setAnswers([]);
    const kp=val<KycProfile>(1);setKycProfile(kp);
    if(kp){const {data:subs}=await supabase.from('kyc_submissions').select('*').eq('profile_id',kp.id).eq('is_deleted',false).order('created_at',{ascending:false});setKycSubmissions((subs??[]) as KycSubmission[]);const ids=(subs??[]).map((s)=>s.id);if(ids.length){const {data:docs}=await supabase.from('kyc_documents').select('*').in('submission_id',ids).eq('is_deleted',false).order('created_at',{ascending:false});setKycDocs((docs??[]) as KycDocument[]);}else setKycDocs([]);}else{setKycSubmissions([]);setKycDocs([]);}
    setProfessionalDocs(val<ProfessionalDocument[]>(2)??[]);setEligibility(val<Eligibility[]>(3)??[]);setAchievements(val<Achievement[]>(4)??[]);setEvidence(val<Evidence[]>(5)??[]);setAssignments(val<BadgeAssignment[]>(6)??[]);setBadges(val<BadgeRow[]>(7)??[]);setGrowth(val<GrowthScore>(8));setTrust(val<TrustScore>(9));
    const activity=val<AuditEvent[]>(10)??[];const kycAudit=val<AuditEvent[]>(11)??[];setAudits([...activity,...kycAudit].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()));
  }catch(e){setError(e instanceof Error?e.message:'Could not load user review data');}finally{setLoading(false);}},[userId,loadPermissions]);
  useEffect(()=>{void load();},[load]);

  const currentDocs=useMemo(()=>{const seen=new Set<string>();return kycDocs.filter((d)=>{if(d.status==='replaced'||seen.has(d.doc_type))return false;seen.add(d.doc_type);return true;});},[kycDocs]);
  const questionnaireSummary=questionnaires[0]?.status??'not_started';const eligibleSummary=eligibility.find((e)=>e.action_key==='general')?.status??eligibility[0]?.status??'not_calculated';

  const openKyc=async(doc:KycDocument)=>{if(!can('kyc.view_documents'))return;setBusy(`view-${doc.id}`);try{const url=await createKycDocumentSignedUrl(doc,300);const refresh=()=>createKycDocumentSignedUrl(doc,300);setViewer({title:doc.doc_name||KYC_DOC_TYPE_LABELS[doc.doc_type]||doc.doc_type,mimeType:doc.doc_mime_type,url,expiresAt:new Date(Date.now()+300000),refresh,metadata:[{label:'Document type',value:KYC_DOC_TYPE_LABELS[doc.doc_type]||doc.doc_type},{label:'Status',value:doc.status},{label:'Issuing country',value:doc.issuing_country},{label:'Document number',value:doc.document_number_last4?`••••${doc.document_number_last4}`:'Not recorded'},{label:'Expiry',value:doc.expires_at?formatDate(doc.expires_at):'Not recorded'},{label:'Version',value:String(doc.version)}]});}catch(e){setError(e instanceof Error?e.message:'Could not open document');}finally{setBusy(null);}};
  const openStored=async(input:{id:string;bucket:string|null;path:string|null;title:string;mime:string|null;status:string;kind:string})=>{if(!input.bucket||!input.path)return setError('This record has no private storage object to preview.');setBusy(`view-${input.id}`);try{const make=async()=>{const {data,error}=await supabase.storage.from(input.bucket!).createSignedUrl(input.path!,300);if(error)throw error;return data.signedUrl;};const url=await make();setViewer({title:input.title,mimeType:input.mime,url,expiresAt:new Date(Date.now()+300000),refresh:make,metadata:[{label:'Category',value:input.kind},{label:'Status',value:input.status},{label:'Storage',value:'Private DRIGHT storage'}]});}catch(e){setError(e instanceof Error?e.message:'Could not open secure preview');}finally{setBusy(null);}};

  const confirmKyc=async(doc:KycDocument)=>{if(!can('kyc.verify'))return;if(!window.confirm('Confirm that you have reviewed this document and believe it satisfies the required verification check.'))return;setBusy(`review-${doc.id}`);try{await reviewKycDocument(doc.id,'verified',undefined,'Confirmed after manual authenticity/readability review.',{readable:true,identity_consistent:true,not_expired:true});await load();}catch(e){setError(e instanceof Error?e.message:'Verification failed');}finally{setBusy(null);}};
  const reviewProblem=async(doc:KycDocument,decision:'rejected'|'needs_resubmission'|'unreadable'|'expired'|'suspected_fraud')=>{const presets=['unreadable','blurry','cropped','incomplete','wrong document type','expired','information mismatch','suspected alteration','selfie mismatch','unsupported document','duplicate document','unable to verify authenticity','other'];const chosen=window.prompt(`Reason (${presets.join(', ')}):`,'unreadable');if(!chosen)return;let reason=chosen;if(chosen.trim().toLowerCase()==='other'){const detail=window.prompt('Enter the user-visible reason:');if(!detail)return;reason=detail;}const internal=window.prompt('Optional internal reviewer note (never shown to the user):','')||undefined;setBusy(`review-${doc.id}`);try{await reviewKycDocument(doc.id,decision,reason,internal,{manual_review:true});await load();}catch(e){setError(e instanceof Error?e.message:'Review failed');}finally{setBusy(null);}};
  const reviewQuestionnaire=async(sub:QuestionnaireSubmission,action:string)=>{let reason:string|null=null;if(['rejected','returned_for_changes','more_information_required'].includes(action)){reason=window.prompt('Enter the user-visible reason:');if(!reason)return;}const internal=window.prompt('Optional internal Admin note (never shown to the user):','')||null;setBusy(`q-${sub.id}`);try{const {error}=await supabase.rpc('review_questionnaire_submission',{p_submission_id:sub.id,p_action:action,p_user_visible_reason:reason,p_internal_note:internal});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Questionnaire review failed');}finally{setBusy(null);}};
  const reviewProfessional=async(doc:ProfessionalDocument,decision:'verified'|'rejected'|'needs_resubmission')=>{const reason=decision==='verified'?null:window.prompt('User-visible reason:');if(decision!=='verified'&&!reason)return;const internal=window.prompt('Optional internal Admin note:','')||null;setBusy(`pro-${doc.id}`);try{const {error}=await supabase.rpc('review_professional_document',{p_document_id:doc.id,p_decision:decision,p_user_visible_reason:reason,p_internal_note:internal,p_checklist:{reviewed:true}});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Document review failed');}finally{setBusy(null);}};
  const reviewEvidence=async(item:Evidence,decision:'verified'|'rejected'|'needs_more_evidence')=>{const reason=decision==='verified'?null:window.prompt('User-visible reason:');if(decision!=='verified'&&!reason)return;const internal=window.prompt('Optional authenticity note:','')||null;setBusy(`evidence-${item.id}`);try{const {error}=await supabase.rpc('review_achievement_evidence',{p_evidence_id:item.id,p_decision:decision,p_user_visible_reason:reason,p_internal_note:internal,p_authenticity_checks:{reviewed_source:true,consistent_with_account:true}});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Evidence review failed');}finally{setBusy(null);}};
  const recalcGrowth=async()=>{if(!userId)return;setBusy('growth');try{const {error}=await supabase.rpc('recalculate_user_growth_score',{p_user_id:userId});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Growth score calculation failed');}finally{setBusy(null);}};
  const recalcEligibility=async(profileType:string)=>{if(!userId)return;setBusy(`eligibility-${profileType}`);try{const {error}=await supabase.rpc('recalculate_user_eligibility',{p_user_id:userId,p_profile_type:profileType,p_action_key:'general'});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Eligibility calculation failed');}finally{setBusy(null);}};
  const assignBadge=async()=>{if(!userId)return;const badgeId=window.prompt(`Badge ID to assign:\n${badges.map((b)=>`${b.name}: ${b.id}`).join('\n')}`);if(!badgeId)return;const reason=window.prompt('Reason for badge assignment:','Verified achievement / platform performance')||null;setBusy('badge');try{const {error}=await supabase.rpc('assign_badge_to_user',{p_user_id:userId,p_badge_id:badgeId,p_reason:reason,p_expires_at:null});if(error)throw error;await load();}catch(e){setError(e instanceof Error?e.message:'Badge assignment failed');}finally{setBusy(null);}};

  if(loading)return <div className="p-4 md:p-8"><div className="h-1 bg-primary-600 rounded-full animate-pulse"/><div className="py-24 text-center text-gray-500">Loading complete user review profile…</div></div>;
  if(!identity)return <div className="p-4 md:p-8"><Link to="/admin/users" className="text-primary-600">← Back to users</Link><div className="mt-6 bg-white rounded-2xl border p-8">{error||'User not found.'}</div></div>;
  const u=identity.user;
  return <div className="p-4 md:p-8 max-w-[1500px] mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-center gap-4 mb-5"><Link to="/admin/users" className="inline-flex items-center gap-2 text-sm text-gray-500 hover:text-primary-600"><ArrowLeft className="w-4 h-4"/> Users</Link><div className="flex-1"><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">{u.full_name||u.username||'User'}</h1><p className="text-sm text-gray-500">@{u.username} • {u.id}</p></div><StatusPill value={u.account_status}/></div>
    {error&&<div className="mb-4 p-3 rounded-xl bg-red-50 border border-red-200 text-red-700 text-sm flex items-start gap-2"><AlertTriangle className="w-4 h-4 mt-0.5"/><span className="flex-1">{error}</span><button onClick={()=>setError(null)}>×</button></div>}

    <div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-6 gap-3 mb-5">
      <SummaryCard label="KYC" value={kycProfile?KYC_STATUS_LABELS[kycProfile.status]||kycProfile.status:'Not started'} good={kycProfile?.status==='approved'}/>
      <SummaryCard label="Documents" value={`${currentDocs.filter((d)=>['verified','approved'].includes(d.status)).length}/${currentDocs.length} verified`} good={currentDocs.length>0&&currentDocs.every((d)=>['verified','approved'].includes(d.status))}/>
      <SummaryCard label="Questionnaire" value={pretty(questionnaireSummary)} good={questionnaireSummary==='approved'}/>
      <SummaryCard label="Eligibility" value={pretty(eligibleSummary)} good={eligibleSummary==='eligible'}/>
      <SummaryCard label="Growth" value={growth?`${growth.growth_level} • ${Number(growth.score).toFixed(0)}`:'Not calculated'} good={!!growth}/>
      <SummaryCard label="Badges" value={`${assignments.filter((a)=>a.is_active).length} active`} good={assignments.some((a)=>a.is_active)}/>
    </div>

    <div className="sticky top-0 z-20 bg-surface-muted/95 backdrop-blur -mx-4 px-4 md:-mx-8 md:px-8 mb-5 border-y border-gray-200 dark:border-gray-800 overflow-x-auto"><div className="flex min-w-max">{TABS.map(([key,label,Icon])=><button key={key} onClick={()=>setTab(key)} className={`px-3 py-3 text-sm font-medium inline-flex items-center gap-1.5 border-b-2 ${tab===key?'border-primary-600 text-primary-700':'border-transparent text-gray-500 hover:text-gray-800'}`}><Icon className="w-4 h-4"/>{label}</button>)}</div></div>

    {tab==='overview'&&<Section title="User overview" subtitle="Account, contact, onboarding and verification summary"><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4"><Info icon={<Mail/>} label="Email" value={u.email} secondary={identity.auth?identity.auth.email_verified?'Verified':'Not verified':'Sensitive auth status unavailable'}/><Info icon={<Phone/>} label="Phone" value={u.phone||'Not set'} secondary={identity.auth?identity.auth.phone_verified?'Verified':'Not verified':'—'}/><Info icon={<MapPin/>} label="Country / Location" value={identity.private_profile?.country_iso2||u.location||'Not set'} secondary={identity.private_profile?.country_calling_code||u.location||undefined}/><Info icon={<CalendarDays/>} label="Registered" value={formatDate(u.created_at)} secondary={identity.auth?.last_sign_in_at?`Last sign-in ${formatDate(identity.auth.last_sign_in_at)}`:undefined}/><Info icon={<Hash/>} label="DRIGHT User ID" value={u.id}/><Info icon={<ShieldCheck/>} label="Active profiles" value={(identity.private_profile?.intended_profiles??[]).map(pretty).join(', ')||'Legacy profile data'}/></div>{can('users.view_sensitive')&&identity.private_profile&&<div className="mt-5 grid md:grid-cols-3 gap-3"><Mini label="Date of birth" value={identity.private_profile.date_of_birth?formatDate(identity.private_profile.date_of_birth):'Not set'}/><Mini label="Onboarding" value={pretty(identity.private_profile.onboarding_status)}/><Mini label="Interests" value={(identity.private_profile.interests??[]).join(', ')||'None selected'}/></div>}</Section>}

    {tab==='profiles'&&<Section title="Profiles & Roles" subtitle="One identity with multiple DRIGHT capabilities"><div className="flex flex-wrap gap-2 mb-5">{(identity.private_profile?.intended_profiles??[]).map((p)=><span key={p} className="px-3 py-1.5 rounded-full bg-primary-50 text-primary-700 border border-primary-200 text-sm">{pretty(p)}</span>)}</div><div className="grid md:grid-cols-2 gap-4"><Mini label="Admin account" value={u.is_admin?`Yes • ${u.admin_role||'role pending'}`:'No'}/><Mini label="Admin status" value={u.is_admin?pretty(u.admin_status||'unknown'):'Not applicable'}/><Mini label="Account status" value={u.account_status}/><Mini label="Onboarding state" value={identity.private_profile?pretty(identity.private_profile.onboarding_status):'Legacy / not recorded'}/></div></Section>}

    {tab==='questionnaires'&&<Section title="Questionnaire / Applications" subtitle="Historical question snapshots remain tied to the version originally submitted">{!can('questionnaires.view')?<Denied/>:questionnaires.length===0?<Empty text="No questionnaire submissions."/>:<div className="space-y-4">{questionnaires.map((sub)=><div key={sub.id} className="rounded-2xl border border-gray-200 dark:border-gray-700 p-4"><div className="flex flex-wrap gap-3 items-start"><div className="flex-1"><h3 className="font-semibold text-gray-900 dark:text-gray-100">{pretty(sub.profile_type)} application • v{sub.questionnaire_version}</h3><p className="text-xs text-gray-500 mt-1">Submitted {sub.submitted_at?formatDate(sub.submitted_at):'draft'} • <StatusPill value={sub.status}/></p>{sub.user_visible_reason&&<p className="mt-2 text-sm text-amber-700 bg-amber-50 rounded-lg p-2">User-visible reason: {sub.user_visible_reason}</p>}</div>{can('questionnaires.review')&&<div className="flex flex-wrap gap-2"><Action onClick={()=>void reviewQuestionnaire(sub,'approved')}>Approve</Action><Action onClick={()=>void reviewQuestionnaire(sub,'more_information_required')}>More info</Action><Action onClick={()=>void reviewQuestionnaire(sub,'returned_for_changes')}>Return</Action><Action danger onClick={()=>void reviewQuestionnaire(sub,'rejected')}>Reject</Action></div>}</div><div className="mt-4 grid lg:grid-cols-2 gap-3">{answers.filter((a)=>a.submission_id===sub.id).sort((a,b)=>String(a.question_snapshot?.label||a.question_key).localeCompare(String(b.question_snapshot?.label||b.question_key))).map((a)=><div key={a.id} className="bg-gray-50 dark:bg-gray-900/60 rounded-xl p-3"><p className="text-xs font-semibold text-gray-500">{a.question_snapshot?.label||a.question_key}{a.question_snapshot?.required?' *':''}</p><p className="mt-1 text-sm text-gray-900 dark:text-gray-100 whitespace-pre-wrap break-words">{displayAnswer(a.answer_value)}</p></div>)}</div></div>)}</div>}</Section>}

    {tab==='kyc'&&<div className="space-y-5"><Section title="Verification Summary" subtitle="Overall KYC is reconciled from applicable rules and document-level results">{!can('kyc.view')?<Denied/>:<><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3"><Mini label="Identity / KYC overall" value={kycProfile?KYC_STATUS_LABELS[kycProfile.status]||pretty(kycProfile.status):'Not started'}/><Mini label="Government ID" value={docState(currentDocs,['government_id','passport','drivers_license','national_id','residence_permit'])}/><Mini label="Address" value={docState(currentDocs,['proof_of_address','utility_bill'])}/><Mini label="Face verification" value={docState(currentDocs,['selfie'])}/><Mini label="Business verification" value={docState(currentDocs,['business_registration','tax_document'])}/><Mini label="Questionnaire" value={pretty(questionnaireSummary)}/></div><p className="text-xs text-gray-400 mt-3">The summary does not treat one document as complete KYC unless configured rules make that document sufficient.</p></>}</Section><Section title="KYC documents" subtitle="Private originals; secure previews use short-lived signed URLs">{!can('kyc.view_documents')?<Denied/>:currentDocs.length===0?<Empty text="No KYC documents submitted."/>:<div className="grid xl:grid-cols-2 gap-4">{currentDocs.map((doc)=><DocumentCard key={doc.id} title={KYC_DOC_TYPE_LABELS[doc.doc_type]||pretty(doc.doc_type)} status={doc.status} meta={[doc.issuing_country||'Issuing country not recorded',doc.expires_at?`Expires ${formatDate(doc.expires_at)}`:'No expiry recorded',`Version ${doc.version}`]} reason={doc.user_visible_reason} actions={<><Action onClick={()=>void openKyc(doc)} disabled={busy===`view-${doc.id}`}><Eye className="w-3.5 h-3.5"/> View</Action>{can('kyc.verify')&&<Action onClick={()=>void confirmKyc(doc)}><CheckCircle2 className="w-3.5 h-3.5"/> Confirm</Action>}{can('kyc.request_resubmission')&&<Action onClick={()=>void reviewProblem(doc,'needs_resubmission')}>Request new</Action>}{can('kyc.review')&&<Action onClick={()=>void reviewProblem(doc,'unreadable')}>Unclear</Action>}{can('kyc.reject')&&<Action danger onClick={()=>void reviewProblem(doc,'rejected')}>Reject</Action>}</>}/>)}</div>}</Section></div>}

    {tab==='documents'&&<Section title="All private review documents" subtitle="KYC, professional documents and achievement evidence remain separated by storage/privacy policy"><div className="space-y-6"><DocGroup title="KYC / identity" count={currentDocs.length}>{currentDocs.map((doc)=><DocumentCard key={doc.id} title={KYC_DOC_TYPE_LABELS[doc.doc_type]||doc.doc_type} status={doc.status} meta={[doc.doc_name||'Original',doc.doc_mime_type||'Unknown type']} actions={can('kyc.view_documents')?<Action onClick={()=>void openKyc(doc)}><Eye className="w-3.5 h-3.5"/> View securely</Action>:undefined}/>)}</DocGroup><DocGroup title="Professional" count={professionalDocs.length}>{professionalDocs.map((doc)=><DocumentCard key={doc.id} title={doc.title||pretty(doc.document_type)} status={doc.status} meta={[pretty(doc.document_type),doc.original_file_name||'File']} actions={can('professional_documents.view')?<Action onClick={()=>void openStored({id:doc.id,bucket:doc.storage_bucket,path:doc.storage_path,title:doc.original_file_name||doc.title||'Professional document',mime:doc.mime_type,status:doc.status,kind:'Professional document'})}><Eye className="w-3.5 h-3.5"/> View securely</Action>:undefined}/>)}</DocGroup><DocGroup title="Achievement evidence" count={evidence.length}>{evidence.map((item)=><DocumentCard key={item.id} title={item.title} status={item.status} meta={[pretty(item.evidence_type),item.original_file_name||item.external_url||'Evidence']} actions={<>{item.storage_path&&can('badges.view_evidence')&&<Action onClick={()=>void openStored({id:item.id,bucket:item.storage_bucket,path:item.storage_path,title:item.original_file_name||item.title,mime:item.mime_type,status:item.status,kind:'Achievement evidence'})}><Eye className="w-3.5 h-3.5"/> View</Action>}{item.external_url&&<a href={item.external_url} target="_blank" rel="noreferrer" className="action-btn"><ExternalLink className="w-3.5 h-3.5"/> External source</a>}</>}/>)}</DocGroup></div></Section>}

    {tab==='professional'&&<Section title="Professional Information" subtitle="Optional CVs, certificates, portfolios and business documents are separate from KYC identity storage">{professionalDocs.length===0?<Empty text="No professional documents submitted."/>:<div className="grid xl:grid-cols-2 gap-4">{professionalDocs.map((doc)=><DocumentCard key={doc.id} title={doc.title||pretty(doc.document_type)} status={doc.status} reason={doc.user_visible_reason} meta={[pretty(doc.document_type),doc.profile_type?`For ${pretty(doc.profile_type)}`:'General',doc.expires_at?`Expires ${formatDate(doc.expires_at)}`:'No expiry']} actions={<>{can('professional_documents.view')&&<Action onClick={()=>void openStored({id:doc.id,bucket:doc.storage_bucket,path:doc.storage_path,title:doc.original_file_name||doc.title||'Professional document',mime:doc.mime_type,status:doc.status,kind:'Professional document'})}><Eye className="w-3.5 h-3.5"/> View</Action>}{can('professional_documents.review')&&<><Action onClick={()=>void reviewProfessional(doc,'verified')}>Verify</Action><Action onClick={()=>void reviewProfessional(doc,'needs_resubmission')}>Replace</Action><Action danger onClick={()=>void reviewProfessional(doc,'rejected')}>Reject</Action></>}</>}/>)}</div>}</Section>}

    {tab==='achievements'&&<div className="space-y-5"><Section title="Achievements, badges & growth" subtitle="Ranking uses DRIGHT platform facts and verified evidence; unverified user claims do not count as verified achievements"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Mini label="Verified achievements" value={String(achievements.filter((a)=>['verified','system_verified'].includes(a.verification_status)).length)}/><Mini label="Active badges" value={String(assignments.filter((a)=>a.is_active).length)}/><Mini label="Trust score" value={trust?`${trust.score} • ${pretty(trust.level)}`:'Not calculated'}/><Mini label="Growth score / rank" value={growth?`${Number(growth.score).toFixed(0)} • ${pretty(growth.growth_level)}${growth.rank_position?` • #${growth.rank_position}`:''}`:'Not calculated'}/></div><div className="mt-4 flex flex-wrap gap-2">{can('badges.assign')&&<Action onClick={()=>void assignBadge()}><BadgeCheck className="w-4 h-4"/> Assign badge</Action>}{can('badges.manage_ranking')&&<Action onClick={()=>void recalcGrowth()} disabled={busy==='growth'}><RefreshCw className="w-4 h-4"/> Recalculate growth</Action>}</div>{growth&&<pre className="mt-4 text-xs bg-gray-50 dark:bg-gray-900 rounded-xl p-3 whitespace-pre-wrap break-words">{JSON.stringify(growth.components,null,2)}</pre>}</Section><Section title="Active / historical badges">{assignments.length===0?<Empty text="No badges assigned."/>:<div className="grid md:grid-cols-2 lg:grid-cols-3 gap-3">{assignments.map((a)=><div key={a.id} className="p-4 rounded-xl border border-gray-200 dark:border-gray-700"><div className="flex items-center gap-2"><Trophy className="w-5 h-5 text-amber-500"/><p className="font-semibold">{a.badge?.name||a.badge_id}</p></div><p className="text-xs text-gray-500 mt-1">{a.reason||'No assignment reason recorded'}</p><div className="mt-2"><StatusPill value={a.is_active?'active':'inactive'}/></div></div>)}</div>}</Section><Section title="Achievement evidence review">{evidence.length===0?<Empty text="No user-submitted achievement evidence."/>:<div className="grid xl:grid-cols-2 gap-4">{evidence.map((item)=><DocumentCard key={item.id} title={item.title} status={item.status} reason={item.user_visible_reason} meta={[pretty(item.evidence_type),item.description||'No description']} actions={<>{item.storage_path&&can('badges.view_evidence')&&<Action onClick={()=>void openStored({id:item.id,bucket:item.storage_bucket,path:item.storage_path,title:item.original_file_name||item.title,mime:item.mime_type,status:item.status,kind:'Achievement evidence'})}><Eye className="w-3.5 h-3.5"/> Inspect</Action>}{can('badges.review_evidence')&&<><Action onClick={()=>void reviewEvidence(item,'verified')}>Verify</Action><Action onClick={()=>void reviewEvidence(item,'needs_more_evidence')}>More evidence</Action><Action danger onClick={()=>void reviewEvidence(item,'rejected')}>Reject</Action></>}</>}/>)}</div>}</Section></div>}

    {tab==='eligibility'&&<Section title="Explainable Eligibility" subtitle="Rules show why the account is eligible, limited or needs more information; AI alone does not reject users"><div className="flex flex-wrap gap-2 mb-4">{(identity.private_profile?.intended_profiles??['buyer']).map((profile)=><Action key={profile} onClick={()=>void recalcEligibility(profile)} disabled={!can('eligibility.recalculate')||busy===`eligibility-${profile}`}><RefreshCw className="w-3.5 h-3.5"/> Recalculate {pretty(profile)}</Action>)}</div>{!can('eligibility.view')?<Denied/>:eligibility.length===0?<Empty text="No eligibility snapshot calculated yet."/>:<div className="space-y-4">{eligibility.map((e)=><div key={e.id} className="border border-gray-200 dark:border-gray-700 rounded-xl p-4"><div className="flex items-center justify-between"><p className="font-semibold">{pretty(e.profile_type)} • {pretty(e.action_key)}</p><StatusPill value={e.status}/></div><div className="mt-3 space-y-2">{(e.reasons??[]).map((reason,i)=><div key={`${reason.key}-${i}`} className="flex items-start gap-2 text-sm">{reason.ok?<CheckCircle2 className="w-4 h-4 text-green-500 mt-0.5"/>:<XCircle className="w-4 h-4 text-red-500 mt-0.5"/>}<span>{reason.message}{reason.status?` (${pretty(reason.status)})`:''}</span></div>)}</div><p className="text-xs text-gray-400 mt-3">Calculated {formatDate(e.calculated_at)}</p></div>)}</div>}</Section>}

    {tab==='restrictions'&&<Section title="Account Restrictions / Moderation" subtitle="Current account-level restriction state; moderation systems remain authoritative"><div className="grid md:grid-cols-2 gap-4"><Mini label="Account status" value={u.account_status}/><Mini label="Admin status" value={u.is_admin?pretty(u.admin_status||'unknown'):'Not an admin'}/></div><div className="mt-4 p-3 rounded-xl bg-gray-50 dark:bg-gray-900 text-sm text-gray-600 dark:text-gray-300">This page does not bypass DRIGHT’s existing moderation, lock, ban, appeal or fraud systems. Eligibility treats a non-ACTIVE account as blocked.</div></Section>}

    {tab==='activity'&&<Section title="Activity" subtitle="Account success/growth facts used by existing platform systems"><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Mini label="Completed sales" value={String(u.total_sales_count||0)}/><Mini label="Average rating" value={Number(u.average_rating||0).toFixed(2)}/><Mini label="Trust" value={trust?`${trust.score} / ${pretty(trust.level)}`:'Not calculated'}/><Mini label="Growth" value={growth?`${Number(growth.score).toFixed(0)} / ${pretty(growth.growth_level)}`:'Not calculated'}/></div></Section>}

    {tab==='audit'&&<Section title="Audit History" subtitle="Immutable KYC/review/admin actions are preserved; replacement does not erase prior evidence">{audits.length===0?<Empty text="No review/audit events visible to this Admin."/>:<div className="space-y-2">{audits.map((event)=><div key={`${event.id}-${event.created_at}`} className="flex items-start gap-3 p-3 rounded-xl border border-gray-100 dark:border-gray-800"><div className="w-2 h-2 mt-2 rounded-full bg-primary-500"/><div className="flex-1 min-w-0"><p className="text-sm font-medium text-gray-900 dark:text-gray-100">{pretty(event.action)}</p><p className="text-xs text-gray-500">{event.entity_type?`${pretty(event.entity_type)} • `:''}{formatDate(event.created_at)}</p>{(event.metadata||event.details)&&<p className="text-xs text-gray-400 mt-1 break-words">{compactJson(event.metadata||event.details||{})}</p>}</div></div>)}</div>}</Section>}

    {viewer&&<SecureDocumentViewer open={true} onClose={()=>setViewer(null)} title={viewer.title} mimeType={viewer.mimeType} signedUrl={viewer.url} expiresAt={viewer.expiresAt} metadata={viewer.metadata} onRefreshUrl={viewer.refresh} watermark={`DRIGHT VERIFICATION REVIEW • ${u.username||u.id.slice(0,8)}`}/>}  
  </div>;
}

function Section({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 shadow-sm p-4 sm:p-6"><h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">{title}</h2>{subtitle&&<p className="text-sm text-gray-500 mt-1 mb-5">{subtitle}</p>} {!subtitle&&<div className="mb-5"/>}{children}</section>}
function SummaryCard({label,value,good}:{label:string;value:string;good?:boolean}){return <div className="bg-white dark:bg-gray-900 rounded-xl border border-gray-100 dark:border-gray-800 p-3"><p className="text-xs text-gray-400">{label}</p><p className={`mt-1 text-sm font-semibold ${good?'text-green-600':'text-gray-900 dark:text-gray-100'}`}>{value}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="p-3 rounded-xl bg-gray-50 dark:bg-gray-950 border border-gray-100 dark:border-gray-800"><p className="text-xs text-gray-400">{label}</p><p className="mt-1 text-sm font-medium text-gray-900 dark:text-gray-100 break-words">{value}</p></div>}
function Info({icon,label,value,secondary}:{icon:React.ReactNode;label:string;value:string;secondary?:string}){return <div className="flex gap-3 p-3 rounded-xl border border-gray-100 dark:border-gray-800"><span className="w-5 h-5 text-gray-400 [&>svg]:w-5 [&>svg]:h-5">{icon}</span><div className="min-w-0"><p className="text-xs text-gray-400">{label}</p><p className="text-sm font-medium text-gray-900 dark:text-gray-100 break-words">{value}</p>{secondary&&<p className="text-xs text-gray-500 mt-0.5">{secondary}</p>}</div></div>}
function Action({children,onClick,danger,disabled}:{children:React.ReactNode;onClick:()=>void;danger?:boolean;disabled?:boolean}){return <button onClick={onClick} disabled={disabled} className={`action-btn ${danger?'!text-red-600 !border-red-200 hover:!bg-red-50':''}`}><span className="inline-flex items-center gap-1.5">{children}</span><style>{`.action-btn{display:inline-flex;align-items:center;gap:.375rem;padding:.45rem .7rem;border:1px solid #e5e7eb;border-radius:.6rem;font-size:.75rem;font-weight:600;color:#4b5563;background:white}.action-btn:hover{background:#f9fafb}.action-btn:disabled{opacity:.45;cursor:not-allowed}`}</style></button>}
function DocumentCard({title,status,meta,reason,actions}:{title:string;status:string;meta:string[];reason?:string|null;actions?:React.ReactNode}){return <div className="rounded-xl border border-gray-200 dark:border-gray-700 p-4"><div className="flex items-start gap-3"><FileText className="w-5 h-5 text-primary-500 mt-0.5"/><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-gray-900 dark:text-gray-100">{title}</p><StatusPill value={status}/></div><p className="text-xs text-gray-500 mt-1">{meta.filter(Boolean).join(' • ')}</p>{reason&&<p className="text-xs text-amber-700 mt-2 bg-amber-50 p-2 rounded-lg">User-visible reason: {reason}</p>} {actions&&<div className="flex flex-wrap gap-2 mt-3">{actions}</div>}</div></div></div>}
function DocGroup({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <div><h3 className="font-semibold text-sm text-gray-700 dark:text-gray-300 mb-2">{title} <span className="text-gray-400">({count})</span></h3>{count===0?<Empty text={`No ${title.toLowerCase()} documents.`}/>:<div className="grid xl:grid-cols-2 gap-3">{children}</div>}</div>}
function StatusPill({value}:{value:string}){const v=(value||'unknown').toLowerCase();const good=['approved','verified','eligible','active','completed','system_verified'].includes(v);const bad=['rejected','expired','suspended','ineligible','suspected_fraud'].includes(v);return <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium border ${good?'bg-green-50 text-green-700 border-green-200':bad?'bg-red-50 text-red-700 border-red-200':'bg-amber-50 text-amber-700 border-amber-200'}`}>{pretty(value)}</span>}
function Empty({text}:{text:string}){return <div className="py-8 text-center text-sm text-gray-400">{text}</div>}
function Denied(){return <div className="py-8 text-center text-sm text-gray-500"><LockKeyhole className="w-6 h-6 mx-auto mb-2 text-gray-300"/>This Admin does not have permission to view this section.</div>}
function pretty(value:string){return String(value||'unknown').replace(/_/g,' ').replace(/\b\w/g,(c)=>c.toUpperCase())}
function formatDate(value:string){return new Date(value).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'})}
function displayAnswer(value:unknown){if(Array.isArray(value))return value.join(', ');if(value&&typeof value==='object')return JSON.stringify(value);if(typeof value==='boolean')return value?'Yes':'No';return String(value??'—')}
function docState(docs:KycDocument[],types:string[]){const matches=docs.filter((d)=>types.includes(d.doc_type));if(!matches.length)return 'Not required / not submitted';const verified=matches.find((d)=>['verified','approved'].includes(d.status));return verified?'Verified':pretty(matches[0].status)}
function compactJson(value:Record<string,unknown>){const text=JSON.stringify(value);return text.length>240?`${text.slice(0,240)}…`:text}
