import { useCallback,useEffect,useMemo,useState } from 'react';
import { AlertTriangle,CheckCircle,ChevronDown,ChevronUp,ExternalLink,Flag,Microscope,RefreshCw,Search,ShieldAlert,Trophy,XCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Tab='pending'|'active'|'flagged'|'restricted'|'suspended'|'all';
type Analysis={profile_url:string;platform:string;username?:string|null;status:string;followers?:number|null;following?:number|null;likes?:number|null;content_count?:number|null;authenticity_score?:number|null;risk_level?:string;confidence_score?:number|null;signals?:string[];data_source?:string};
type Snapshot={id:string;profile_url:string;platform:string;analysis:Analysis;analysis_status:string;verification_type:string;analyzed_at:string};
type Signal={id:string;profile_url:string;platform?:string;signal_type:string;severity:string;confidence?:number|null;description:string;previous_value:any;current_value:any;status:string;created_at:string};
type Profile={profile_url:string;platform:string;username?:string|null;health:string;analysis:Analysis|null;latest_research:any;signals:Signal[];history:Snapshot[];comparison:any};
type Marketer={id:string;email:string;full_name:string|null;username:string|null;created_at:string;marketer_status:string;marketer_monitoring_status:string;marketer_last_verified_at:string|null;marketer_next_verification_due_at:string|null;social_media_links:string[]|null;marketer_social_analysis:Analysis[];profiles:Profile[];verification_history:Snapshot[];deep_research_history:any[];monitoring_signals:Signal[];performance:any;scores:any;performance_score:number|null;trust_score:number|null;overall_status:string;current_rank:number;weekly_rank_label:string;reward_eligibility:any};

const safe=(v:any,suffix='')=>v===null||v===undefined?'UNKNOWN':`${v}${suffix}`;
const number=(v:any)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString():'UNKNOWN';
const money=(v:any)=>typeof v==='number'&&Number.isFinite(v)?`$${v.toLocaleString(undefined,{maximumFractionDigits:2})}`:'UNKNOWN';
const date=(v:any)=>v?new Date(v).toLocaleString():'UNKNOWN';
const call=async(method:'GET'|'POST',body?:any)=>{const{data,error}=await supabase.functions.invoke('sales-team-review',{method,body});if(error||data?.error)throw new Error(data?.error||error?.message||'Sales Team request failed');return data};

export default function SalesTeamMarketerApplicationsPage(){
  const[data,setData]=useState<any>({pendingApplications:[],approvedApplications:[],flaggedApplications:[],restrictedApplications:[],suspendedApplications:[],allApplications:[],leaderboard:[],reviewHistory:[]});
  const[selected,setSelected]=useState<Marketer|null>(null);const[tab,setTab]=useState<Tab>('pending');const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[note,setNote]=useState('');const[error,setError]=useState('');const[health,setHealth]=useState<any>(null);const[healthOpen,setHealthOpen]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await call('GET');setData(d);setSelected(s=>s?(d.allApplications||[]).find((x:Marketer)=>x.id===s.id)||null:null)}catch(e){setError(e instanceof Error?e.message:'Failed to load marketer intelligence')}finally{setLoading(false)}},[]);
  const loadHealth=useCallback(async()=>{try{const{data,error}=await supabase.functions.invoke('ai-health',{method:'GET'});if(error||data?.error)throw new Error(data?.error||error?.message);setHealth(data)}catch(e){setHealth({error:e instanceof Error?e.message:'Provider diagnostics unavailable'})}},[]);
  useEffect(()=>{load();loadHealth()},[load,loadHealth]);
  const lists:any={pending:data.pendingApplications||[],active:data.approvedApplications||[],flagged:data.flaggedApplications||[],restricted:data.restrictedApplications||[],suspended:data.suspendedApplications||[],all:data.allApplications||[]};
  const list=useMemo(()=>{const q=query.trim().toLowerCase();return(lists[tab]||[]).filter((m:Marketer)=>!q||[m.full_name,m.email,m.username,m.marketer_status,m.overall_status].some(v=>String(v||'').toLowerCase().includes(q)))},[data,tab,query]);
  const action=async(action:string,extra:any={})=>{if(!selected)return;setBusy(action);setError('');try{await call('POST',{action,applicant_id:selected.id,note,...extra});setNote('');await load()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy('')}};
  const deep=async(profile_url:string)=>{if(!selected)return;setBusy(`deep:${profile_url}`);setError('');try{const{data,error}=await supabase.functions.invoke('marketer-profile-deep-research',{method:'POST',body:{applicant_id:selected.id,profile_url}});if(error||!data?.success)throw new Error(data?.error?.message||'Deep Re-Research did not produce a completed or partial report');await load();await loadHealth()}catch(e){setError(e instanceof Error?e.message:'Deep Re-Research failed')}finally{setBusy('')}};
  const review=async(decision:'approved'|'rejected'|'needs_changes')=>{if(!selected)return;setBusy(decision);try{await call('POST',{action:'review_marketer_application',applicant_id:selected.id,decision,note});setNote('');setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Review failed')}finally{setBusy('')}};
  const counts={pending:lists.pending.length,active:lists.active.length,flagged:lists.flagged.length,restricted:lists.restricted.length,suspended:lists.suspended.length,all:lists.all.length};
  return <div className="p-4 md:p-8 max-w-7xl mx-auto space-y-5">
    <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><h1 className="text-2xl font-bold text-gray-900">Marketer Applications & Intelligence</h1><p className="text-sm text-gray-500 mt-1">Approval does not end verification. Profile evidence, performance, rankings and monitoring remain persistent.</p></div><button onClick={()=>{load();loadHealth()}} disabled={loading} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-200 text-sm"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/>Refresh</button></header>
    {error&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section className="bg-white border border-gray-100 rounded-2xl overflow-hidden"><button onClick={()=>setHealthOpen(v=>!v)} className="w-full p-4 flex items-center justify-between text-left"><div><div className="font-bold">AI Provider Diagnostics</div><div className="text-xs text-gray-500">Configuration and recent connection status. API keys are never displayed.</div></div>{healthOpen?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button>{healthOpen&&<div className="border-t p-4">{health?.error?<div className="text-sm text-amber-700">{health.error}</div>:<div className="grid md:grid-cols-3 gap-3">{['groq','gemini','openai'].map(k=><ProviderCard key={k} p={health?.providers?.[k]}/>)}</div>}</div>}</section>
    <div className="flex flex-wrap gap-2">{(['pending','active','flagged','restricted','suspended','all'] as Tab[]).map(t=><button key={t} onClick={()=>{setTab(t);setSelected(null)}} className={`px-3 py-2 rounded-xl text-sm font-semibold ${tab===t?'bg-gray-900 text-white':'bg-white border border-gray-200'}`}>{t==='pending'?'Pending Review':t==='active'?'Approved / Active':t[0].toUpperCase()+t.slice(1)} ({counts[t]})</button>)}</div>
    <div className="grid lg:grid-cols-[360px_1fr] gap-5"><aside className="bg-white border border-gray-100 rounded-2xl overflow-hidden"><div className="p-4 border-b"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input className="input pl-9" placeholder="Search marketers" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="max-h-[760px] overflow-y-auto">{loading?<div className="p-8 text-center text-gray-400">Loading…</div>:list.length===0?<div className="p-8 text-center text-gray-400">No marketers in this view.</div>:list.map((m:Marketer)=><button key={m.id} onClick={()=>setSelected(m)} className={`w-full text-left p-4 border-b border-gray-100 hover:bg-gray-50 ${selected?.id===m.id?'bg-gray-50 border-l-4 border-l-gray-900':''}`}><div className="font-semibold">{m.full_name||m.username||m.email}</div><div className="text-xs text-gray-500 mt-1">{m.email}</div><div className="flex flex-wrap gap-1 mt-2"><Badge>{m.marketer_status}</Badge><HealthBadge value={m.overall_status||m.marketer_monitoring_status}/>{m.performance_score!==null&&m.performance_score!==undefined?<Badge>Score {m.performance_score}</Badge>:null}</div></button>)}</div></aside>
      <main className="bg-white border border-gray-100 rounded-2xl p-5 min-h-[600px]">{!selected?<Empty/>:<MarketerView marketer={selected} busy={busy} note={note} setNote={setNote} action={action} deep={deep} review={review}/>}</main></div>
    <Leaderboard rows={data.leaderboard||[]}/>
    <ReviewHistory rows={data.reviewHistory||[]}/>
  </div>
}

function MarketerView({marketer:m,busy,note,setNote,action,deep,review}:{marketer:Marketer;busy:string;note:string;setNote:(v:string)=>void;action:(a:string,e?:any)=>Promise<void>;deep:(p:string)=>Promise<void>;review:(d:'approved'|'rejected'|'needs_changes')=>Promise<void>}){return <div className="space-y-6"><section className="border-b pb-5"><div className="flex flex-col md:flex-row md:justify-between gap-4"><div><div className="text-xs uppercase tracking-wide text-gray-400">Marketer Overview</div><h2 className="text-xl font-bold mt-1">{m.full_name||m.username||'Marketer'}</h2><div className="text-sm text-gray-500">{m.email} · {m.id}</div><div className="flex flex-wrap gap-2 mt-3"><HealthBadge value={m.overall_status}/><Badge>{m.marketer_status}</Badge><Badge>Rank #{m.current_rank||'UNKNOWN'}</Badge><Badge>{m.weekly_rank_label||'NEW'}</Badge></div></div><div className="grid grid-cols-2 gap-2 min-w-[260px]"><Metric label="Performance" value={safe(m.performance_score)}/><Metric label="Trust" value={m.trust_score==null?'UNKNOWN':`${m.trust_score}/100`}/><Metric label="Last verified" value={m.marketer_last_verified_at?new Date(m.marketer_last_verified_at).toLocaleDateString():'UNKNOWN'}/><Metric label="Next review" value={m.marketer_next_verification_due_at?new Date(m.marketer_next_verification_due_at).toLocaleDateString():'MANUAL'}/></div></div></section>
    {m.marketer_status!=='pending'&&<><section><h3 className="font-bold mb-3">Performance & Ranking</h3><div className="grid grid-cols-2 md:grid-cols-5 gap-2"><Metric label="Successful Sales" value={number(m.performance?.successful_sales)}/><Metric label="Weekly Sales" value={number(m.performance?.weekly_successful_sales)}/><Metric label="Revenue" value={money(m.performance?.total_sales_value)}/><Metric label="Commission" value={money(m.performance?.commission_earned)}/><Metric label="Reward" value={m.reward_eligibility?.eligible?'ELIGIBLE':'NOT ELIGIBLE'}/></div><div className="grid grid-cols-2 md:grid-cols-5 gap-2 mt-2"><Metric label="Sales Score" value={safe(m.scores?.sales)}/><Metric label="Trust Score" value={safe(m.scores?.trust)}/><Metric label="Growth Quality" value={safe(m.scores?.growth)}/><Metric label="Customer Quality" value={safe(m.scores?.customer_quality)}/><Metric label="Reliability" value={safe(m.scores?.reliability)}/></div>{!m.reward_eligibility?.eligible&&<p className="mt-2 text-xs text-amber-700">{m.reward_eligibility?.reasons?.join(' ')}</p>}</section>
    <section><h3 className="font-bold mb-3">Social Profile Intelligence</h3><div className="space-y-4">{m.profiles?.length?m.profiles.map(p=><ProfileCard key={p.profile_url} p={p} busy={busy} reverify={()=>action('reverify_marketer_profile',{profile_url:p.profile_url})} deep={()=>deep(p.profile_url)} signalAction={(a,id)=>action(a,{signal_id:id})}/>):<p className="text-sm text-gray-400">No submitted profiles.</p>}</div></section>
    <ResearchHistory runs={m.deep_research_history||[]}/>
    <section><h3 className="font-bold mb-3">Administrative Actions</h3><textarea className="input min-h-20" value={note} onChange={e=>setNote(e.target.value)} placeholder="Admin note or action reason…"/><div className="flex flex-wrap gap-2 mt-3"><ActionButton onClick={()=>action('flag_for_review')} label="Flag for Review"/><ActionButton onClick={()=>action('clear_flag')} label="Clear Flag"/><ActionButton onClick={()=>action('restrict_marketer')} label="Restrict Marketer"/><ActionButton onClick={()=>action('suspend_marketer')} label="Suspend Marketer" danger/><ActionButton onClick={()=>action('restore_marketer')} label="Restore Marketer"/><ActionButton onClick={()=>action('add_admin_note')} label="Add Admin Note"/></div></section></>}
    {m.marketer_status==='pending'&&<section><h3 className="font-bold mb-3">Application Review</h3><textarea className="input min-h-20" value={note} onChange={e=>setNote(e.target.value)} placeholder="Review note…"/><div className="flex flex-wrap gap-2 mt-3"><button onClick={()=>review('approved')} disabled={!!busy} className="px-4 py-2.5 rounded-xl bg-gray-900 text-white text-sm font-semibold"><CheckCircle className="inline w-4 h-4 mr-1"/>Approve Marketer</button><button onClick={()=>review('needs_changes')} disabled={!!busy} className="px-4 py-2.5 rounded-xl bg-amber-50 text-amber-800 text-sm font-semibold">Request Changes</button><button onClick={()=>review('rejected')} disabled={!!busy} className="px-4 py-2.5 rounded-xl bg-red-50 text-red-700 text-sm font-semibold"><XCircle className="inline w-4 h-4 mr-1"/>Reject</button></div></section>}
  </div>}

function ProfileCard({p,busy,reverify,deep,signalAction}:{p:Profile;busy:string;reverify:()=>void;deep:()=>void;signalAction:(a:string,id:string)=>void}){const c=p.comparison?.changes;return <article className="border border-gray-200 rounded-2xl p-4"><div className="flex flex-col md:flex-row md:justify-between gap-3"><div><div className="flex gap-2 items-center"><b>{p.platform}</b><HealthBadge value={p.health}/>{p.latest_research?.status&&<Badge>{p.latest_research.status}</Badge>}</div><div className="text-sm text-gray-600 mt-1">{p.username?`@${p.username} · `:''}{p.profile_url}</div></div><div className="flex flex-wrap gap-2"><a href={p.profile_url} target="_blank" rel="noreferrer" className="px-3 py-2 rounded-xl border text-sm inline-flex gap-1 items-center">Open <ExternalLink className="w-4 h-4"/></a><button onClick={reverify} disabled={!!busy} className="px-3 py-2 rounded-xl border text-sm font-semibold"><RefreshCw className={`inline w-4 h-4 mr-1 ${busy==='reverify_marketer_profile'?'animate-spin':''}`}/>Re-Verify</button><button onClick={deep} disabled={!!busy} className="px-3 py-2 rounded-xl bg-gray-900 text-white text-sm font-semibold"><Microscope className="inline w-4 h-4 mr-1"/>Deep Re-Research</button></div></div>
<div className="grid grid-cols-2 md:grid-cols-6 gap-2 mt-4"><Metric label="Followers" value={number(p.analysis?.followers)}/><Metric label="Following" value={number(p.analysis?.following)}/><Metric label="Likes" value={number(p.analysis?.likes)}/><Metric label="Content" value={number(p.analysis?.content_count)}/><Metric label="Authenticity" value={p.analysis?.authenticity_score==null?'UNKNOWN':`${p.analysis.authenticity_score}/100`}/><Metric label="Confidence" value={p.analysis?.confidence_score==null?'UNKNOWN':`${p.analysis.confidence_score}%`}/></div>
<div className="mt-4 rounded-xl bg-gray-50 p-3"><div className="font-semibold text-sm mb-2">Profile Trend</div>{!c?<div className="text-xs text-gray-500">Insufficient historical data.</div>:<div className="grid grid-cols-2 md:grid-cols-4 gap-2"><Trend label="Followers" x={c.followers}/><Trend label="Likes" x={c.likes}/><Trend label="Authenticity" x={c.authenticity}/><Trend label="Confidence" x={c.confidence}/></div>}</div>
<div className="mt-4"><div className="font-semibold text-sm mb-2">Monitoring Signals</div>{!p.signals?.length?<div className="text-xs text-gray-500">No profile monitoring signals.</div>:p.signals.slice(0,10).map(s=><div key={s.id} className="border rounded-xl p-3 mb-2"><div className="flex flex-col md:flex-row md:justify-between gap-2"><div><div className="text-sm font-bold"><AlertTriangle className="inline w-4 h-4 mr-1"/>{s.signal_type} · {s.severity.toUpperCase()}</div><div className="text-xs text-gray-600 mt-1">{s.description}</div><div className="text-[11px] text-gray-400 mt-1">{date(s.created_at)} · {s.status}</div></div>{['open','escalated'].includes(s.status)&&<div className="flex gap-1"><button onClick={()=>signalAction('resolve_signal',s.id)} className="text-xs px-2 py-1 rounded border">Resolve</button><button onClick={()=>signalAction('dismiss_signal',s.id)} className="text-xs px-2 py-1 rounded border">Dismiss</button>{s.status!=='escalated'&&<button onClick={()=>signalAction('escalate_signal',s.id)} className="text-xs px-2 py-1 rounded bg-amber-50 text-amber-800">Escalate</button>}</div>}</div></div>)}</div></article>}

function ResearchHistory({runs}:{runs:any[]}){const[open,setOpen]=useState<string|null>(null);const sorted=[...runs].sort((a,b)=>+new Date(b.created_at)-+new Date(a.created_at));return <section><h3 className="font-bold mb-3">Deep Research History</h3>{!sorted.length?<p className="text-sm text-gray-400">No research history.</p>:<div className="space-y-2">{sorted.map((r:any)=>{const report=r.research?.research||r.research||{};const expanded=open===r.id;return <div key={r.id} className={`border rounded-xl ${r.status==='failed'?'opacity-70':''}`}><button className="w-full p-3 text-left flex justify-between gap-3" onClick={()=>setOpen(expanded?null:r.id)}><div><b>{r.platform} · {String(r.status).toUpperCase()}</b><div className="text-xs text-gray-500 mt-1">{date(r.created_at)} · Evidence {r.evidence_count??0} · AI {r.providers_used?.join?.(', ')||'UNAVAILABLE'}</div>{r.failure_category&&<div className="text-xs text-red-600 mt-1">{r.failure_category}</div>}</div>{expanded?<ChevronUp className="w-4 h-4"/>:<ChevronDown className="w-4 h-4"/>}</button>{expanded&&<div className="border-t p-3 text-sm space-y-2"><p>{r.summary||report.summary||'UNKNOWN'}</p><div><b>Confidence:</b> {r.confidence==null?'UNKNOWN':`${r.confidence}%`}</div><div><b>Recommendation:</b> {r.recommendation||report.recommendation||'MANUAL_REVIEW'}</div><div><b>Limitations:</b> {Array.isArray(r.limitations)&&r.limitations.length?r.limitations.join(' • '):'UNKNOWN'}</div></div>}</div>})}</div>}</section>}
function Leaderboard({rows}:{rows:any[]}){return <section className="bg-white border border-gray-100 rounded-2xl p-5"><div className="flex items-center gap-2 mb-3"><Trophy className="w-5 h-5"/><h2 className="font-bold">Weekly Marketer Leaderboard</h2></div>{!rows.length?<p className="text-sm text-gray-400">No ranked marketers yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-gray-500 border-b"><th className="py-2">Rank</th><th>Marketer</th><th>Score</th><th>Sales</th><th>Revenue</th><th>Growth</th><th>Trust</th><th>Change</th></tr></thead><tbody>{rows.map(r=><tr key={r.marketer_id} className="border-b last:border-0"><td className="py-3 font-bold">#{r.rank}</td><td>{r.name}</td><td>{safe(r.overall_score)}</td><td>{number(r.successful_sales)}</td><td>{money(r.revenue_generated)}</td><td>{safe(r.growth_score)}</td><td>{safe(r.trust_score)}</td><td>{r.weekly_change}</td></tr>)}</tbody></table></div>}</section>}
function ReviewHistory({rows}:{rows:any[]}){return <section className="bg-white border border-gray-100 rounded-2xl p-5"><h2 className="font-bold mb-3">Recent Review & Intelligence History</h2>{!rows.length?<p className="text-sm text-gray-400">No history.</p>:rows.slice(0,50).map(h=><div key={h.id} className="grid md:grid-cols-[180px_120px_160px_1fr] gap-2 border-t py-2 text-sm"><span>{date(h.created_at)}</span><span>{String(h.applicant_id).slice(0,8)}…</span><b>{String(h.decision).replaceAll('_',' ')}</b><span className="text-gray-500">{h.note||'—'}</span></div>)}</section>}
function ProviderCard({p}:{p:any}){if(!p)return <div className="border rounded-xl p-3 text-sm text-gray-400">UNKNOWN</div>;return <div className="border rounded-xl p-3"><div className="font-bold">{p.provider}</div><div className="text-xs text-gray-500 mt-1">{p.model}</div><div className="flex gap-2 mt-2"><Badge>{p.configured?'CONFIGURED':'NOT CONFIGURED'}</Badge><HealthBadge value={p.connectionStatus}/></div><div className="text-xs text-gray-500 mt-2">Last success: {date(p.lastSuccessfulRequest)}</div><div className="text-xs text-gray-500">Last failure: {date(p.lastFailedRequest)}</div>{p.lastFailureReason&&<div className="text-xs text-red-600 mt-1 break-words">{p.lastFailureReason}</div>}</div>}
function Trend({label,x}:{label:string;x:any}){const percent=x?.percent;const change=x?.change??x?.absolute;return <div><div className="text-[10px] text-gray-400">{label}</div><div className="text-xs">{safe(x?.previous)} → {safe(x?.current)}</div><div className="font-semibold text-xs">{change==null?'Insufficient data':`${change>0?'+':''}${Number(change).toFixed(1)}${percent==null?'':` (${percent>0?'+':''}${Number(percent).toFixed(1)}%)`}`}</div></div>}
function Metric({label,value}:{label:string;value:any}){return <div className="rounded-xl bg-gray-50 p-2"><div className="text-[10px] uppercase tracking-wide text-gray-400">{label}</div><div className="font-bold text-sm mt-1 break-words">{value}</div></div>}
function Badge({children}:{children:any}){return <span className="text-[11px] px-2 py-1 rounded-full bg-gray-100 text-gray-700">{children}</span>}
function HealthBadge({value}:{value:any}){const v=String(value||'UNKNOWN').toUpperCase();const cls=v.includes('HEALTH')||v==='HEALTHY'?'bg-green-50 text-green-700':v.includes('WATCH')||v==='FAILING'?'bg-amber-50 text-amber-700':v.includes('FLAG')||v.includes('RISK')||v.includes('SUSPEND')?'bg-red-50 text-red-700':'bg-gray-100 text-gray-600';return <span className={`text-[11px] px-2 py-1 rounded-full font-semibold ${cls}`}>{v.replaceAll('_',' ')}</span>}
function ActionButton({label,onClick,danger}:{label:string;onClick:()=>void;danger?:boolean}){return <button onClick={onClick} className={`px-3 py-2 rounded-xl text-sm font-semibold ${danger?'bg-red-50 text-red-700':'border border-gray-200'}`}>{label}</button>}
function Empty(){return <div className="min-h-[500px] flex flex-col items-center justify-center text-center text-gray-400"><ShieldAlert className="w-10 h-10 mb-3"/><h2 className="font-semibold text-gray-600">Select a marketer</h2><p className="text-sm max-w-md mt-1">Inspect application evidence, profile intelligence, historical changes, monitoring signals and performance.</p></div>}
