import { useCallback, useEffect, useState } from 'react';
import { CheckCircle, ExternalLink, RefreshCw, Search, ShieldAlert, XCircle } from 'lucide-react';
import { supabase } from '../../lib/supabase';

type Application={id:string;email:string;full_name:string|null;username:string|null;avatar_url:string|null;created_at:string;joined_at:string|null;location:string|null;profession:string|null;marketer_level:number;marketer_status:string;social_media_links:unknown;verification_status:string|null;is_verified:boolean;last_active_at:string|null};
type Review={id:string;applicant_id:string;reviewer_id:string;decision:string;note:string|null;social_links_snapshot:unknown;created_at:string};

const linksOf=(value:unknown):string[]=>Array.isArray(value)?value.map(v=>String(v)).filter(Boolean):[];
const reviewCall=async(method:'GET'|'POST',body?:Record<string,unknown>)=>{const {data,error}=await supabase.functions.invoke('sales-team-review',{method,body});if(error)throw error;if(data?.error)throw new Error(data.error);return data};

export default function SalesTeamMarketerApplicationsPage(){
 const[apps,setApps]=useState<Application[]>([]); const[history,setHistory]=useState<Review[]>([]); const[selected,setSelected]=useState<Application|null>(null); const[loading,setLoading]=useState(true); const[busy,setBusy]=useState(''); const[query,setQuery]=useState(''); const[note,setNote]=useState(''); const[error,setError]=useState('');
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await reviewCall('GET');setApps(d.pendingApplications||[]);setHistory(d.reviewHistory||[]);setSelected(s=>s&& (d.pendingApplications||[]).some((a:Application)=>a.id===s.id)?s:null)}catch(e){setError(e instanceof Error?e.message:'Failed to load marketer applications')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const review=async(decision:'approved'|'rejected'|'needs_changes')=>{if(!selected)return;setBusy(decision);setError('');try{await reviewCall('POST',{action:'review_marketer_application',applicant_id:selected.id,decision,note});setNote('');setSelected(null);await load()}catch(e){setError(e instanceof Error?e.message:'Review failed')}finally{setBusy('')}};
 const filtered=apps.filter(a=>{const q=query.trim().toLowerCase();return !q||[a.full_name,a.email,a.username,a.profession,a.location].filter(Boolean).some(v=>String(v).toLowerCase().includes(q))});
 return <div className="p-4 md:p-8 max-w-7xl mx-auto"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6"><div><h1 className="text-2xl font-bold text-gray-900">Marketer Applications</h1><p className="text-sm text-gray-500">Review users who submitted social or professional profile links to join the Marketer program.</p></div><button onClick={load} disabled={loading} className="inline-flex items-center gap-2 px-3 py-2 rounded-xl border border-gray-200 text-sm disabled:opacity-50"><RefreshCw className="w-4 h-4"/>Refresh</button></div>
 {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
 <div className="grid lg:grid-cols-[380px_1fr] gap-5"><section className="bg-white border border-gray-100 rounded-2xl overflow-hidden"><div className="p-4 border-b border-gray-100"><div className="flex items-center justify-between mb-3"><h2 className="font-bold">Pending review <span className="text-xs font-semibold px-2 py-1 rounded-full bg-amber-50 text-amber-700">{apps.length}</span></h2></div><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"/><input className="input pl-9" placeholder="Search applicant" value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="max-h-[650px] overflow-y-auto">{loading?<div className="p-8 text-center text-gray-400">Loading…</div>:filtered.length===0?<div className="p-10 text-center text-gray-400">No pending marketer applications.</div>:filtered.map(a=><button key={a.id} onClick={()=>{setSelected(a);setNote('')}} className={`w-full text-left p-4 border-b border-gray-100 hover:bg-gray-50 ${selected?.id===a.id?'bg-gray-50 border-l-4 border-l-gray-900':''}`}><div className="font-semibold">{a.full_name||a.username||a.email}</div><div className="text-xs text-gray-500 mt-1">{a.email}</div><div className="text-xs text-gray-400 mt-2">Submitted {new Date(a.created_at).toLocaleString()}</div><div className="mt-2 flex flex-wrap gap-1">{linksOf(a.social_media_links).map((l,i)=><span key={i} className="text-[11px] px-2 py-1 rounded-full bg-gray-100">{(()=>{try{return new URL(l).hostname.replace('www.','')}catch{return 'profile'}})()}</span>)}</div></button>)}</div></section>
 <section className="bg-white border border-gray-100 rounded-2xl p-5">{!selected?<div className="h-full min-h-[500px] flex flex-col items-center justify-center text-center text-gray-400"><ShieldAlert className="w-10 h-10 mb-3"/><h2 className="font-semibold text-gray-600">Select an application</h2><p className="text-sm max-w-md mt-1">Choose a pending applicant to inspect their submitted profile links before approving or rejecting the Marketer application.</p></div>:<div><div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4 border-b border-gray-100 pb-5"><div><h2 className="text-xl font-bold">{selected.full_name||selected.username||'Applicant'}</h2><p className="text-sm text-gray-500">{selected.email}</p><div className="flex flex-wrap gap-2 mt-3"><span className="text-xs px-2.5 py-1 rounded-full bg-amber-50 text-amber-700">Pending review</span><span className="text-xs px-2.5 py-1 rounded-full bg-gray-100">Marketer {selected.marketer_level}</span>{selected.is_verified&&<span className="text-xs px-2.5 py-1 rounded-full bg-green-50 text-green-700">DRIGHT verified</span>}</div></div><div className="text-xs text-gray-400">Account created {new Date(selected.created_at).toLocaleDateString()}</div></div>
 <div className="grid sm:grid-cols-2 gap-3 py-5">{selected.profession&&<Info label="Profession" value={selected.profession}/>} {selected.location&&<Info label="Location" value={selected.location}/>} {selected.verification_status&&<Info label="Verification status" value={selected.verification_status}/>} {selected.last_active_at&&<Info label="Last active" value={new Date(selected.last_active_at).toLocaleString()}/>}</div>
 <div><h3 className="font-bold mb-3">Submitted profiles</h3><div className="space-y-3">{linksOf(selected.social_media_links).map((link,i)=><div key={`${link}-${i}`} className="flex items-center justify-between gap-3 border border-gray-100 rounded-xl p-3"><div className="min-w-0"><div className="text-xs font-semibold text-gray-500">Profile {i+1}</div><div className="text-sm truncate mt-1">{link}</div></div><a href={link} target="_blank" rel="noreferrer" className="shrink-0 inline-flex items-center gap-1 px-3 py-2 rounded-lg bg-gray-100 text-sm font-medium">Open <ExternalLink className="w-4 h-4"/></a></div>)}</div></div>
 <div className="mt-6"><label className="block text-xs font-medium text-gray-500 mb-1.5">Review note (optional)</label><textarea className="input min-h-24" placeholder="Record why the application was approved, rejected, or returned for changes…" value={note} onChange={e=>setNote(e.target.value)}/></div>
 <div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>review('approved')} disabled={!!busy} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gray-900 text-white text-sm font-semibold disabled:opacity-50"><CheckCircle className="w-4 h-4"/>{busy==='approved'?'Approving…':'Approve Marketer'}</button><button onClick={()=>review('needs_changes')} disabled={!!busy} className="px-4 py-2.5 rounded-xl border border-amber-300 bg-amber-50 text-amber-800 text-sm font-semibold disabled:opacity-50">Request Changes</button><button onClick={()=>review('rejected')} disabled={!!busy} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl border border-red-200 bg-red-50 text-red-700 text-sm font-semibold disabled:opacity-50"><XCircle className="w-4 h-4"/>{busy==='rejected'?'Rejecting…':'Reject'}</button></div></div>}</section></div>
 <section className="mt-5 bg-white border border-gray-100 rounded-2xl p-5"><h2 className="font-bold mb-3">Recent review history</h2>{history.length===0?<p className="text-sm text-gray-400">No reviews recorded yet.</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b border-gray-100 text-left text-gray-500"><th className="py-2 pr-4">Date</th><th className="py-2 pr-4">Applicant</th><th className="py-2 pr-4">Decision</th><th className="py-2">Note</th></tr></thead><tbody className="divide-y divide-gray-100">{history.slice(0,50).map(h=><tr key={h.id}><td className="py-3 pr-4">{new Date(h.created_at).toLocaleString()}</td><td className="py-3 pr-4">{h.applicant_id.slice(0,8)}…</td><td className="py-3 pr-4 capitalize font-semibold">{h.decision.replace('_',' ')}</td><td className="py-3 text-gray-500">{h.note||'—'}</td></tr>)}</tbody></table></div>}</section></div>;
}
function Info({label,value}:{label:string;value:string}){return <div className="border border-gray-100 rounded-xl p-3"><div className="text-xs text-gray-400">{label}</div><div className="text-sm font-medium mt-1">{value}</div></div>}
